////////////////////////////////////////////
///QUASIT                                ///
////////////////////////////////////////////

/////////////////
///Summoned   ///
/////////////////

IF
  Global("WTPFAMCE","GLOBAL",2)
  Global("#GSUMMON","LOCALS",1)
THEN
  RESPONSE #100
    Wait(3)
    DisplayStringHead(Myself,@536)
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon2",Myself))
    SetGlobal("SPRITE_IS_DEADWTPQUASI","GLOBAL",0)
    SetGlobal("#GSUMMON","LOCALS",2)
END

IF
  Global("#GSUMMON","LOCALS",2)
  Delay(2)
THEN
  RESPONSE #20
    SetGlobal("#GSUMMON","LOCALS",3)
    ActionOverride(%famsummoner%,FaceObject("WTPQuasi"))
    Wait(1)
    DisplayStringHead(%famsummoner%,@539)
  RESPONSE #20
    SetGlobal("#GSUMMON","LOCALS",3)
    ActionOverride(%famsummoner%,FaceObject("WTPQuasi"))
    Wait(1)
    DisplayStringHead(%famsummoner%,@540)
  RESPONSE #20
    SetGlobal("#GSUMMON","LOCALS",3)
    ActionOverride(%famsummoner%,FaceObject("WTPQuasi"))
    Wait(1)
    DisplayStringHead(%famsummoner%,@541)
  RESPONSE #20
    SetGlobal("#GSUMMON","LOCALS",3)
    ActionOverride(%famsummoner%,FaceObject("WTPQuasi"))
    Wait(1)
    DisplayStringHead(%famsummoner%,@542)
  RESPONSE #20
    SetGlobal("#GSUMMON","LOCALS",3)
    ActionOverride(%famsummoner%,FaceObject("WTPQuasi"))
    Wait(1)
    DisplayStringHead(%famsummoner%,@543)
END

///////////////
///Status   ///
///////////////

IF
  Global("WTPSTAT","LOCALS",0)
  OR(2)
    StateCheck(Myself,WTP_STATE_INVALID_OR_STONE)
    StateCheck(%famsummoner%,WTP_STATE_INVALID_ALIVE)
THEN
  RESPONSE #100
    SetGlobal("WTPSTAT","LOCALS",1)
END

IF
  Global("WTPSTAT","LOCALS",1)
  !StateCheck(Myself,WTP_STATE_INVALID_OR_STONE)
  !StateCheck(%famsummoner%,WTP_STATE_INVALID_ALIVE)
THEN
  RESPONSE #100
    SetGlobal("WTPSTAT","LOCALS",0)
END

///////////////////////
///Mage Class       ///
///////////////////////

IF
  Global("#GMAGECLASS","LOCALS",0)
  !FallenRanger(%famsummoner%)
  OR(4)
    Class(%famsummoner%,MAGE_ALL)
    Class(%famsummoner%,BARD)
    Kit(%famsummoner%,BEASTMASTER)
    CheckStat(%famsummoner%,1,USE_ANY_ITEM)
THEN
  RESPONSE #100
    SetGlobal("#GMAGECLASS","LOCALS",1)
END

IF
  Global("#GMAGECLASS","LOCALS",1)
  OR(6)
    Class(%famsummoner%,CLERIC_MAGE)  // first 4 ORs cover multiclasses and dual classes M->F and M->C
    Class(%famsummoner%,FIGHTER_MAGE)
    Class(%famsummoner%,CLERIC_THIEF)
    Class(%famsummoner%,FIGHTER_THIEF)
    Class(%famsummoner%,FIGHTER_MAGE_THIEF)
    Class(%famsummoner%,FIGHTER_MAGE_CLERIC)
  OriginalClass(%famsummoner%,FIGHTER) // this covers dual class F->M and F->T
  OriginalClass(%famsummoner%,CLERIC) // this covers dual class C->M and C->T
THEN
  RESPONSE #100
    SetGlobal("#GMAGECLASS","LOCALS",2)
END

IF
  Global("#GMAGECLASS","LOCALS",1)
  TriggerOverride(%famsummoner%,Global("#GSCRFAI","LOCALS",1))	// this covers the unique case where a dual M/T with UAI uses the Find Familiar scroll
  CheckStat(%famsummoner%,1,USE_ANY_ITEM)
THEN
  RESPONSE #100
    SetGlobal("#GMAGECLASS","LOCALS",2)
    ActionOverride(%famsummoner%,SetGlobal("#GSCRFAI","LOCALS",0))
END

//////////////////////
///Acquire mage Lv ///
//////////////////////

IF
  Global("#GMAGECLASS","LOCALS",1)
  CheckStat(%famsummoner%,2,LEVEL)
  GlobalLT("#GPLALVL","GLOBAL",1)
THEN
  RESPONSE #100
    SetGlobal("#GPLALVL","GLOBAL",1)
END

IF
  Global("#GMAGECLASS","LOCALS",2)
  CheckStat(%famsummoner%,2,LEVEL2)
  GlobalLT("#GPLALVL","GLOBAL",1)
THEN
  RESPONSE #100
    SetGlobal("#GPLALVL","GLOBAL",1)
END

IF
  Global("#GMAGECLASS","LOCALS",1)
  CheckStat(%famsummoner%,3,LEVEL)
  GlobalLT("#GPLALVL","GLOBAL",2)
THEN
  RESPONSE #100
    SetGlobal("#GPLALVL","GLOBAL",2)
END

IF
  Global("#GMAGECLASS","LOCALS",2)
  CheckStat(%famsummoner%,3,LEVEL2)
  GlobalLT("#GPLALVL","GLOBAL",2)
THEN
  RESPONSE #100
    SetGlobal("#GPLALVL","GLOBAL",2)
END

IF
  Global("#GMAGECLASS","LOCALS",1)
  CheckStat(%famsummoner%,4,LEVEL)
  GlobalLT("#GPLALVL","GLOBAL",3)
THEN
  RESPONSE #100
    SetGlobal("#GPLALVL","GLOBAL",3)
END

IF
  Global("#GMAGECLASS","LOCALS",2)
  CheckStat(%famsummoner%,4,LEVEL2)
  GlobalLT("#GPLALVL","GLOBAL",3)
THEN
  RESPONSE #100
    SetGlobal("#GPLALVL","GLOBAL",3)
END

IF
  Global("#GMAGECLASS","LOCALS",1)
  CheckStat(%famsummoner%,5,LEVEL)
  GlobalLT("#GPLALVL","GLOBAL",4)
THEN
  RESPONSE #100
    SetGlobal("#GPLALVL","GLOBAL",4)
END

IF
  Global("#GMAGECLASS","LOCALS",2)
  CheckStat(%famsummoner%,5,LEVEL2)
  GlobalLT("#GPLALVL","GLOBAL",4)
THEN
  RESPONSE #100
    SetGlobal("#GPLALVL","GLOBAL",4)
END

IF
  Global("#GMAGECLASS","LOCALS",1)
  CheckStat(%famsummoner%,6,LEVEL)
  GlobalLT("#GPLALVL","GLOBAL",5)
THEN
  RESPONSE #100
    SetGlobal("#GPLALVL","GLOBAL",5)
END

IF
  Global("#GMAGECLASS","LOCALS",2)
  CheckStat(%famsummoner%,6,LEVEL2)
  GlobalLT("#GPLALVL","GLOBAL",5)
THEN
  RESPONSE #100
    SetGlobal("#GPLALVL","GLOBAL",5)
END

IF
  Global("#GMAGECLASS","LOCALS",1)
  CheckStat(%famsummoner%,7,LEVEL)
  GlobalLT("#GPLALVL","GLOBAL",6)
THEN
  RESPONSE #100
    SetGlobal("#GPLALVL","GLOBAL",6)
END

IF
  Global("#GMAGECLASS","LOCALS",2)
  CheckStat(%famsummoner%,7,LEVEL2)
  GlobalLT("#GPLALVL","GLOBAL",6)
THEN
  RESPONSE #100
    SetGlobal("#GPLALVL","GLOBAL",6)
END

IF
  Global("#GMAGECLASS","LOCALS",1)
  CheckStat(%famsummoner%,8,LEVEL)
  GlobalLT("#GPLALVL","GLOBAL",7)
THEN
  RESPONSE #100
    SetGlobal("#GPLALVL","GLOBAL",7)
END

IF
  Global("#GMAGECLASS","LOCALS",2)
  CheckStat(%famsummoner%,8,LEVEL2)
  GlobalLT("#GPLALVL","GLOBAL",7)
THEN
  RESPONSE #100
    SetGlobal("#GPLALVL","GLOBAL",7)
END

IF
  Global("#GMAGECLASS","LOCALS",1)
  CheckStat(%famsummoner%,9,LEVEL)
  GlobalLT("#GPLALVL","GLOBAL",8)
THEN
  RESPONSE #100
    SetGlobal("#GPLALVL","GLOBAL",8)
END

IF
  Global("#GMAGECLASS","LOCALS",2)
  CheckStat(%famsummoner%,9,LEVEL2)
  GlobalLT("#GPLALVL","GLOBAL",8)
THEN
  RESPONSE #100
    SetGlobal("#GPLALVL","GLOBAL",8)
END

IF
  Global("#GMAGECLASS","LOCALS",1)
  CheckStat(%famsummoner%,10,LEVEL)
  GlobalLT("#GPLALVL","GLOBAL",9)
THEN
  RESPONSE #100
    SetGlobal("#GPLALVL","GLOBAL",9)
END

IF
  Global("#GMAGECLASS","LOCALS",2)
  CheckStat(%famsummoner%,10,LEVEL2)
  GlobalLT("#GPLALVL","GLOBAL",9)
THEN
  RESPONSE #100
    SetGlobal("#GPLALVL","GLOBAL",9)
END

IF
  Global("#GMAGECLASS","LOCALS",1)
  CheckStat(%famsummoner%,11,LEVEL)
  GlobalLT("#GPLALVL","GLOBAL",10)
THEN
  RESPONSE #100
    SetGlobal("#GPLALVL","GLOBAL",10)
END

IF
  Global("#GMAGECLASS","LOCALS",2)
  CheckStat(%famsummoner%,11,LEVEL2)
  GlobalLT("#GPLALVL","GLOBAL",10)
THEN
  RESPONSE #100
    SetGlobal("#GPLALVL","GLOBAL",10)
END

IF
  Global("#GMAGECLASS","LOCALS",1)
  CheckStat(%famsummoner%,12,LEVEL)
  GlobalLT("#GPLALVL","GLOBAL",11)
THEN
  RESPONSE #100
    SetGlobal("#GPLALVL","GLOBAL",11)
END

IF
  Global("#GMAGECLASS","LOCALS",2)
  CheckStat(%famsummoner%,12,LEVEL2)
  GlobalLT("#GPLALVL","GLOBAL",11)
THEN
  RESPONSE #100
    SetGlobal("#GPLALVL","GLOBAL",11)
END

IF
  Global("#GMAGECLASS","LOCALS",1)
  CheckStat(%famsummoner%,13,LEVEL)
  GlobalLT("#GPLALVL","GLOBAL",12)
THEN
  RESPONSE #100
    SetGlobal("#GPLALVL","GLOBAL",12)
END

IF
  Global("#GMAGECLASS","LOCALS",2)
  CheckStat(%famsummoner%,13,LEVEL2)
  GlobalLT("#GPLALVL","GLOBAL",12)
THEN
  RESPONSE #100
    SetGlobal("#GPLALVL","GLOBAL",12)
END

IF
  Global("#GMAGECLASS","LOCALS",1)
  CheckStat(%famsummoner%,14,LEVEL)
  GlobalLT("#GPLALVL","GLOBAL",13)
THEN
  RESPONSE #100
    SetGlobal("#GPLALVL","GLOBAL",13)
END

IF
  Global("#GMAGECLASS","LOCALS",2)
  CheckStat(%famsummoner%,14,LEVEL2)
  GlobalLT("#GPLALVL","GLOBAL",13)
THEN
  RESPONSE #100
    SetGlobal("#GPLALVL","GLOBAL",13)
END

IF
  Global("#GMAGECLASS","LOCALS",1)
  CheckStat(%famsummoner%,15,LEVEL)
  GlobalLT("#GPLALVL","GLOBAL",14)
THEN
  RESPONSE #100
    SetGlobal("#GPLALVL","GLOBAL",14)
END

IF
  Global("#GMAGECLASS","LOCALS",2)
  CheckStat(%famsummoner%,15,LEVEL2)
  GlobalLT("#GPLALVL","GLOBAL",14)
THEN
  RESPONSE #100
    SetGlobal("#GPLALVL","GLOBAL",14)
END

IF
  Global("#GMAGECLASS","LOCALS",1)
  CheckStat(%famsummoner%,16,LEVEL)
  GlobalLT("#GPLALVL","GLOBAL",15)
THEN
  RESPONSE #100
    SetGlobal("#GPLALVL","GLOBAL",15)
END

IF
  Global("#GMAGECLASS","LOCALS",2)
  CheckStat(%famsummoner%,16,LEVEL2)
  GlobalLT("#GPLALVL","GLOBAL",15)
THEN
  RESPONSE #100
    SetGlobal("#GPLALVL","GLOBAL",15)
END

IF
  Global("#GMAGECLASS","LOCALS",1)
  CheckStat(%famsummoner%,17,LEVEL)
  GlobalLT("#GPLALVL","GLOBAL",16)
THEN
  RESPONSE #100
    SetGlobal("#GPLALVL","GLOBAL",16)
END

IF
  Global("#GMAGECLASS","LOCALS",2)
  CheckStat(%famsummoner%,17,LEVEL2)
  GlobalLT("#GPLALVL","GLOBAL",16)
THEN
  RESPONSE #100
    SetGlobal("#GPLALVL","GLOBAL",16)
END

IF
  Global("#GMAGECLASS","LOCALS",1)
  CheckStat(%famsummoner%,18,LEVEL)
  GlobalLT("#GPLALVL","GLOBAL",17)
THEN
  RESPONSE #100
    SetGlobal("#GPLALVL","GLOBAL",17)
END

IF
  Global("#GMAGECLASS","LOCALS",2)
  CheckStat(%famsummoner%,18,LEVEL2)
  GlobalLT("#GPLALVL","GLOBAL",17)
THEN
  RESPONSE #100
    SetGlobal("#GPLALVL","GLOBAL",17)
END

IF
  Global("#GMAGECLASS","LOCALS",1)
  CheckStat(%famsummoner%,19,LEVEL)
  GlobalLT("#GPLALVL","GLOBAL",18)
THEN
  RESPONSE #100
    SetGlobal("#GPLALVL","GLOBAL",18)
END

IF
  Global("#GMAGECLASS","LOCALS",2)
  CheckStat(%famsummoner%,19,LEVEL2)
  GlobalLT("#GPLALVL","GLOBAL",18)
THEN
  RESPONSE #100
    SetGlobal("#GPLALVL","GLOBAL",18)
END

IF
  Global("#GMAGECLASS","LOCALS",1)
  CheckStat(%famsummoner%,20,LEVEL)
  GlobalLT("#GPLALVL","GLOBAL",19)
THEN
  RESPONSE #100
    SetGlobal("#GPLALVL","GLOBAL",19)
END

IF
  Global("#GMAGECLASS","LOCALS",2)
  CheckStat(%famsummoner%,20,LEVEL2)
  GlobalLT("#GPLALVL","GLOBAL",19)
THEN
  RESPONSE #100
    SetGlobal("#GPLALVL","GLOBAL",19)
END

IF
  Global("#GMAGECLASS","LOCALS",1)
  CheckStat(%famsummoner%,21,LEVEL)
  GlobalLT("#GPLALVL","GLOBAL",20)
THEN
  RESPONSE #100
    SetGlobal("#GPLALVL","GLOBAL",20)
END

IF
  Global("#GMAGECLASS","LOCALS",2)
  CheckStat(%famsummoner%,21,LEVEL2)
  GlobalLT("#GPLALVL","GLOBAL",20)
THEN
  RESPONSE #100
    SetGlobal("#GPLALVL","GLOBAL",20)
END

IF
  Global("#GMAGECLASS","LOCALS",1)
  CheckStat(%famsummoner%,22,LEVEL)
  GlobalLT("#GPLALVL","GLOBAL",21)
THEN
  RESPONSE #100
    SetGlobal("#GPLALVL","GLOBAL",21)
END

IF
  Global("#GMAGECLASS","LOCALS",2)
  CheckStat(%famsummoner%,22,LEVEL2)
  GlobalLT("#GPLALVL","GLOBAL",21)
THEN
  RESPONSE #100
    SetGlobal("#GPLALVL","GLOBAL",21)
END

IF
  Global("#GMAGECLASS","LOCALS",1)
  CheckStat(%famsummoner%,23,LEVEL)
  GlobalLT("#GPLALVL","GLOBAL",22)
THEN
  RESPONSE #100
    SetGlobal("#GPLALVL","GLOBAL",22)
END

IF
  Global("#GMAGECLASS","LOCALS",2)
  CheckStat(%famsummoner%,23,LEVEL2)
  GlobalLT("#GPLALVL","GLOBAL",22)
THEN
  RESPONSE #100
    SetGlobal("#GPLALVL","GLOBAL",22)
END

IF
  Global("#GMAGECLASS","LOCALS",1)
  CheckStat(%famsummoner%,24,LEVEL)
  GlobalLT("#GPLALVL","GLOBAL",23)
THEN
  RESPONSE #100
    SetGlobal("#GPLALVL","GLOBAL",23)
END

IF
  Global("#GMAGECLASS","LOCALS",2)
  CheckStat(%famsummoner%,24,LEVEL2)
  GlobalLT("#GPLALVL","GLOBAL",23)
THEN
  RESPONSE #100
    SetGlobal("#GPLALVL","GLOBAL",23)
END

IF
  Global("#GMAGECLASS","LOCALS",1)
  CheckStat(%famsummoner%,25,LEVEL)
  GlobalLT("#GPLALVL","GLOBAL",24)
THEN
  RESPONSE #100
    SetGlobal("#GPLALVL","GLOBAL",24)
END

IF
  Global("#GMAGECLASS","LOCALS",2)
  CheckStat(%famsummoner%,25,LEVEL2)
  GlobalLT("#GPLALVL","GLOBAL",24)
THEN
  RESPONSE #100
    SetGlobal("#GPLALVL","GLOBAL",24)
END

IF
  Global("#GMAGECLASS","LOCALS",1)
  CheckStat(%famsummoner%,26,LEVEL)
  GlobalLT("#GPLALVL","GLOBAL",25)
THEN
  RESPONSE #100
    SetGlobal("#GPLALVL","GLOBAL",25)
END

IF
  Global("#GMAGECLASS","LOCALS",2)
  CheckStat(%famsummoner%,26,LEVEL2)
  GlobalLT("#GPLALVL","GLOBAL",25)
THEN
  RESPONSE #100
    SetGlobal("#GPLALVL","GLOBAL",25)
END

IF
  Global("#GMAGECLASS","LOCALS",1)
  CheckStat(%famsummoner%,27,LEVEL)
  GlobalLT("#GPLALVL","GLOBAL",26)
THEN
  RESPONSE #100
    SetGlobal("#GPLALVL","GLOBAL",26)
END

IF
  Global("#GMAGECLASS","LOCALS",2)
  CheckStat(%famsummoner%,27,LEVEL2)
  GlobalLT("#GPLALVL","GLOBAL",26)
THEN
  RESPONSE #100
    SetGlobal("#GPLALVL","GLOBAL",26)
END

IF
  Global("#GMAGECLASS","LOCALS",1)
  CheckStat(%famsummoner%,28,LEVEL)
  GlobalLT("#GPLALVL","GLOBAL",27)
THEN
  RESPONSE #100
    SetGlobal("#GPLALVL","GLOBAL",27)
END

IF
  Global("#GMAGECLASS","LOCALS",2)
  CheckStat(%famsummoner%,28,LEVEL2)
  GlobalLT("#GPLALVL","GLOBAL",27)
THEN
  RESPONSE #100
    SetGlobal("#GPLALVL","GLOBAL",27)
END

IF
  Global("#GMAGECLASS","LOCALS",1)
  CheckStat(%famsummoner%,29,LEVEL)
  GlobalLT("#GPLALVL","GLOBAL",28)
THEN
  RESPONSE #100
    SetGlobal("#GPLALVL","GLOBAL",28)
END

IF
  Global("#GMAGECLASS","LOCALS",2)
  CheckStat(%famsummoner%,29,LEVEL2)
  GlobalLT("#GPLALVL","GLOBAL",28)
THEN
  RESPONSE #100
    SetGlobal("#GPLALVL","GLOBAL",28)
END

IF
  Global("#GMAGECLASS","LOCALS",1)
  CheckStat(%famsummoner%,30,LEVEL)
  GlobalLT("#GPLALVL","GLOBAL",29)
THEN
  RESPONSE #100
    SetGlobal("#GPLALVL","GLOBAL",29)
END

IF
  Global("#GMAGECLASS","LOCALS",2)
  CheckStat(%famsummoner%,30,LEVEL2)
  GlobalLT("#GPLALVL","GLOBAL",29)
THEN
  RESPONSE #100
    SetGlobal("#GPLALVL","GLOBAL",29)
END

IF
  Global("#GMAGECLASS","LOCALS",1)
  CheckStat(%famsummoner%,31,LEVEL)
  GlobalLT("#GPLALVL","GLOBAL",30)
THEN
  RESPONSE #100
    SetGlobal("#GPLALVL","GLOBAL",30)
END

IF
  Global("#GMAGECLASS","LOCALS",2)
  CheckStat(%famsummoner%,31,LEVEL2)
  GlobalLT("#GPLALVL","GLOBAL",30)
THEN
  RESPONSE #100
    SetGlobal("#GPLALVL","GLOBAL",30)
END

IF
  Global("#GMAGECLASS","LOCALS",1)
  CheckStat(%famsummoner%,32,LEVEL)
  GlobalLT("#GPLALVL","GLOBAL",31)
THEN
  RESPONSE #100
    SetGlobal("#GPLALVL","GLOBAL",31)
END

IF
  Global("#GMAGECLASS","LOCALS",2)
  CheckStat(%famsummoner%,32,LEVEL2)
  GlobalLT("#GPLALVL","GLOBAL",31)
THEN
  RESPONSE #100
    SetGlobal("#GPLALVL","GLOBAL",31)
END

IF
  Global("#GMAGECLASS","LOCALS",1)
  CheckStat(%famsummoner%,33,LEVEL)
  GlobalLT("#GPLALVL","GLOBAL",32)
THEN
  RESPONSE #100
    SetGlobal("#GPLALVL","GLOBAL",32)
END

IF
  Global("#GMAGECLASS","LOCALS",2)
  CheckStat(%famsummoner%,33,LEVEL2)
  GlobalLT("#GPLALVL","GLOBAL",32)
THEN
  RESPONSE #100
    SetGlobal("#GPLALVL","GLOBAL",32)
END

IF
  Global("#GMAGECLASS","LOCALS",1)
  CheckStat(%famsummoner%,34,LEVEL)
  GlobalLT("#GPLALVL","GLOBAL",33)
THEN
  RESPONSE #100
    SetGlobal("#GPLALVL","GLOBAL",33)
END

IF
  Global("#GMAGECLASS","LOCALS",2)
  CheckStat(%famsummoner%,34,LEVEL2)
  GlobalLT("#GPLALVL","GLOBAL",33)
THEN
  RESPONSE #100
    SetGlobal("#GPLALVL","GLOBAL",33)
END

IF
  Global("#GMAGECLASS","LOCALS",1)
  CheckStat(%famsummoner%,35,LEVEL)
  GlobalLT("#GPLALVL","GLOBAL",34)
THEN
  RESPONSE #100
    SetGlobal("#GPLALVL","GLOBAL",34)
END

IF
  Global("#GMAGECLASS","LOCALS",2)
  CheckStat(%famsummoner%,35,LEVEL2)
  GlobalLT("#GPLALVL","GLOBAL",34)
THEN
  RESPONSE #100
    SetGlobal("#GPLALVL","GLOBAL",34)
END

IF
  Global("#GMAGECLASS","LOCALS",1)
  CheckStat(%famsummoner%,36,LEVEL)
  GlobalLT("#GPLALVL","GLOBAL",35)
THEN
  RESPONSE #100
    SetGlobal("#GPLALVL","GLOBAL",35)
END

IF
  Global("#GMAGECLASS","LOCALS",2)
  CheckStat(%famsummoner%,36,LEVEL2)
  GlobalLT("#GPLALVL","GLOBAL",35)
THEN
  RESPONSE #100
    SetGlobal("#GPLALVL","GLOBAL",35)
END

IF
  Global("#GMAGECLASS","LOCALS",1)
  CheckStat(%famsummoner%,37,LEVEL)
  GlobalLT("#GPLALVL","GLOBAL",36)
THEN
  RESPONSE #100
    SetGlobal("#GPLALVL","GLOBAL",36)
END

IF
  Global("#GMAGECLASS","LOCALS",2)
  CheckStat(%famsummoner%,37,LEVEL2)
  GlobalLT("#GPLALVL","GLOBAL",36)
THEN
  RESPONSE #100
    SetGlobal("#GPLALVL","GLOBAL",36)
END

IF
  Global("#GMAGECLASS","LOCALS",1)
  CheckStat(%famsummoner%,38,LEVEL)
  GlobalLT("#GPLALVL","GLOBAL",37)
THEN
  RESPONSE #100
    SetGlobal("#GPLALVL","GLOBAL",37)
END

IF
  Global("#GMAGECLASS","LOCALS",2)
  CheckStat(%famsummoner%,38,LEVEL2)
  GlobalLT("#GPLALVL","GLOBAL",37)
THEN
  RESPONSE #100
    SetGlobal("#GPLALVL","GLOBAL",37)
END

IF
  Global("#GMAGECLASS","LOCALS",1)
  CheckStat(%famsummoner%,39,LEVEL)
  GlobalLT("#GPLALVL","GLOBAL",38)
THEN
  RESPONSE #100
    SetGlobal("#GPLALVL","GLOBAL",38)
END

IF
  Global("#GMAGECLASS","LOCALS",2)
  CheckStat(%famsummoner%,39,LEVEL2)
  GlobalLT("#GPLALVL","GLOBAL",38)
THEN
  RESPONSE #100
    SetGlobal("#GPLALVL","GLOBAL",38)
END

IF
  Global("#GMAGECLASS","LOCALS",1)
  CheckStat(%famsummoner%,40,LEVEL)
  GlobalLT("#GPLALVL","GLOBAL",39)
THEN
  RESPONSE #100
    SetGlobal("#GPLALVL","GLOBAL",39)
END

IF
  Global("#GMAGECLASS","LOCALS",2)
  CheckStat(%famsummoner%,40,LEVEL2)
  GlobalLT("#GPLALVL","GLOBAL",39)
THEN
  RESPONSE #100
    SetGlobal("#GPLALVL","GLOBAL",39)
END

IF
  Global("#GMAGECLASS","LOCALS",1)
  CheckStat(%famsummoner%,41,LEVEL)
  GlobalLT("#GPLALVL","GLOBAL",40)
THEN
  RESPONSE #100
    SetGlobal("#GPLALVL","GLOBAL",40)
END

IF
  Global("#GMAGECLASS","LOCALS",2)
  CheckStat(%famsummoner%,41,LEVEL2)
  GlobalLT("#GPLALVL","GLOBAL",40)
THEN
  RESPONSE #100
    SetGlobal("#GPLALVL","GLOBAL",40)
END

IF
  Global("#GMAGECLASS","LOCALS",1)
  CheckStat(%famsummoner%,42,LEVEL)
  GlobalLT("#GPLALVL","GLOBAL",41)
THEN
  RESPONSE #100
    SetGlobal("#GPLALVL","GLOBAL",41)
END

IF
  Global("#GMAGECLASS","LOCALS",2)
  CheckStat(%famsummoner%,42,LEVEL2)
  GlobalLT("#GPLALVL","GLOBAL",41)
THEN
  RESPONSE #100
    SetGlobal("#GPLALVL","GLOBAL",41)
END

IF
  Global("#GMAGECLASS","LOCALS",1)
  CheckStat(%famsummoner%,43,LEVEL)
  GlobalLT("#GPLALVL","GLOBAL",42)
THEN
  RESPONSE #100
    SetGlobal("#GPLALVL","GLOBAL",42)
END

IF
  Global("#GMAGECLASS","LOCALS",2)
  CheckStat(%famsummoner%,43,LEVEL2)
  GlobalLT("#GPLALVL","GLOBAL",42)
THEN
  RESPONSE #100
    SetGlobal("#GPLALVL","GLOBAL",42)
END

IF
  Global("#GMAGECLASS","LOCALS",1)
  CheckStat(%famsummoner%,44,LEVEL)
  GlobalLT("#GPLALVL","GLOBAL",43)
THEN
  RESPONSE #100
    SetGlobal("#GPLALVL","GLOBAL",43)
END

IF
  Global("#GMAGECLASS","LOCALS",2)
  CheckStat(%famsummoner%,44,LEVEL2)
  GlobalLT("#GPLALVL","GLOBAL",43)
THEN
  RESPONSE #100
    SetGlobal("#GPLALVL","GLOBAL",43)
END

IF
  Global("#GMAGECLASS","LOCALS",1)
  CheckStat(%famsummoner%,45,LEVEL)
  GlobalLT("#GPLALVL","GLOBAL",44)
THEN
  RESPONSE #100
    SetGlobal("#GPLALVL","GLOBAL",44)
END

IF
  Global("#GMAGECLASS","LOCALS",2)
  CheckStat(%famsummoner%,45,LEVEL2)
  GlobalLT("#GPLALVL","GLOBAL",44)
THEN
  RESPONSE #100
    SetGlobal("#GPLALVL","GLOBAL",44)
END

IF
  Global("#GMAGECLASS","LOCALS",1)
  CheckStat(%famsummoner%,46,LEVEL)
  GlobalLT("#GPLALVL","GLOBAL",45)
THEN
  RESPONSE #100
    SetGlobal("#GPLALVL","GLOBAL",45)
END

IF
  Global("#GMAGECLASS","LOCALS",2)
  CheckStat(%famsummoner%,46,LEVEL2)
  GlobalLT("#GPLALVL","GLOBAL",45)
THEN
  RESPONSE #100
    SetGlobal("#GPLALVL","GLOBAL",45)
END

IF
  Global("#GMAGECLASS","LOCALS",1)
  CheckStat(%famsummoner%,47,LEVEL)
  GlobalLT("#GPLALVL","GLOBAL",46)
THEN
  RESPONSE #100
    SetGlobal("#GPLALVL","GLOBAL",46)
END

IF
  Global("#GMAGECLASS","LOCALS",2)
  CheckStat(%famsummoner%,47,LEVEL2)
  GlobalLT("#GPLALVL","GLOBAL",46)
THEN
  RESPONSE #100
    SetGlobal("#GPLALVL","GLOBAL",46)
END

IF
  Global("#GMAGECLASS","LOCALS",1)
  CheckStat(%famsummoner%,48,LEVEL)
  GlobalLT("#GPLALVL","GLOBAL",47)
THEN
  RESPONSE #100
    SetGlobal("#GPLALVL","GLOBAL",47)
END

IF
  Global("#GMAGECLASS","LOCALS",2)
  CheckStat(%famsummoner%,48,LEVEL2)
  GlobalLT("#GPLALVL","GLOBAL",47)
THEN
  RESPONSE #100
    SetGlobal("#GPLALVL","GLOBAL",47)
END

IF
  Global("#GMAGECLASS","LOCALS",1)
  CheckStat(%famsummoner%,49,LEVEL)
  GlobalLT("#GPLALVL","GLOBAL",48)
THEN
  RESPONSE #100
    SetGlobal("#GPLALVL","GLOBAL",48)
END

IF
  Global("#GMAGECLASS","LOCALS",2)
  CheckStat(%famsummoner%,49,LEVEL2)
  GlobalLT("#GPLALVL","GLOBAL",48)
THEN
  RESPONSE #100
    SetGlobal("#GPLALVL","GLOBAL",48)
END

IF
  Global("#GMAGECLASS","LOCALS",1)
  CheckStat(%famsummoner%,50,LEVEL)
  GlobalLT("#GPLALVL","GLOBAL",49)
THEN
  RESPONSE #100
    SetGlobal("#GPLALVL","GLOBAL",49)
END

IF
  Global("#GMAGECLASS","LOCALS",2)
  CheckStat(%famsummoner%,50,LEVEL2)
  GlobalLT("#GPLALVL","GLOBAL",49)
THEN
  RESPONSE #100
    SetGlobal("#GPLALVL","GLOBAL",49)
END

//////////////////////
///Summon resets   ///
//////////////////////

IF
  Global("#GSUMMON","LOCALS",3)
  GlobalsEqual("#GFAMLVL","#GPLALVL")
THEN
  RESPONSE #100
    Wait(4)
    MakeGlobal()
    AddFamiliar()
    ChangeEnemyAlly(Myself,FAMILIAR)
    EquipMostDamagingMelee()
    SetGlobal("#GSUMMON","LOCALS",0)
END

///////////////////////
///Breaking point   ///
///////////////////////

IF
  Global("#GMIRPEN","GLOBAL",2)
  GlobalTimerExpired("#GFAMHAR","GLOBAL")
THEN
  RESPONSE #100
    IncrementGlobal("#GMIRPEN","GLOBAL",-1)
    SetGlobalTimer("#GFAMHAR","GLOBAL",ONE_DAY)
END

IF
  Global("#GMIRPEN","GLOBAL",1)
  GlobalTimerExpired("#GFAMHAR","GLOBAL")
THEN
  RESPONSE #100
    IncrementGlobal("#GMIRPEN","GLOBAL",-1)
END

IF
  Global("#GHARAS","GLOBAL",1)
  Global("#GINPACK","GLOBAL",0)
  Global("#GEMPOW","LOCALS",0)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    IncrementGlobal("#GHARAS","GLOBAL",1)
    Wait(2)
    Dialogue(%famsummoner%)
    SetInterrupt(TRUE)
END

IF
  Global("#GHARAS","GLOBAL",4)
  Global("#GINPACK","GLOBAL",0)
  Global("#GEMPOW","LOCALS",0)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    IncrementGlobal("#GHARAS","GLOBAL",1)
    Wait(2)
    Dialogue(%famsummoner%)
    SetInterrupt(TRUE)
END

IF
  Global("#GHARAS","GLOBAL",7)
  Global("#GINPACK","GLOBAL",0)
  Global("#GEMPOW","LOCALS",0)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    IncrementGlobal("#GHARAS","GLOBAL",1)
    Wait(2)
    Dialogue(%famsummoner%)
    SetInterrupt(TRUE)
END

////////////////////////////////////////////
///LEVEL DRAIN				 ///
////////////////////////////////////////////

IF
  Die()
  Global("#GMAGECLASS","LOCALS",1)
  CheckStatGT(%famsummoner%,4,LEVEL)
THEN
  RESPONSE #100
    SetGlobal("#GIMP","GLOBAL",1)
    Continue()
END

IF
  Die()
  Global("#GMAGECLASS","LOCALS",2)
  CheckStatGT(%famsummoner%,4,LEVEL2)
THEN
  RESPONSE #100
    SetGlobal("#GIMP","GLOBAL",1)
    Continue()
END

IF
  Die()
  Global("#GMAGECLASS","LOCALS",1)
  CheckStat(%famsummoner%,4,LEVEL)
THEN
  RESPONSE #100
    SetGlobal("#GIMP","GLOBAL",2)
    Continue()
END

IF
  Die()
  Global("#GMAGECLASS","LOCALS",2)
  CheckStat(%famsummoner%,4,LEVEL2)
THEN
  RESPONSE #100
    SetGlobal("#GIMP","GLOBAL",2)
    Continue()
END

IF
  Die()
  Global("#GMAGECLASS","LOCALS",1)
  CheckStat(%famsummoner%,3,LEVEL)
THEN
  RESPONSE #100
    SetGlobal("#GIMP","GLOBAL",3)
    Continue()
END

IF
  Die()
  Global("#GMAGECLASS","LOCALS",2)
  CheckStat(%famsummoner%,3,LEVEL2)
THEN
  RESPONSE #100
    SetGlobal("#GIMP","GLOBAL",3)
    Continue()
END

IF
  Die()
  Global("#GMAGECLASS","LOCALS",1)
  CheckStat(%famsummoner%,2,LEVEL)
THEN
  RESPONSE #100
    SetGlobal("#GIMP","GLOBAL",4)
    Continue()
END

IF
  Die()
  Global("#GMAGECLASS","LOCALS",2)
  CheckStat(%famsummoner%,2,LEVEL2)
THEN
  RESPONSE #100
    SetGlobal("#GIMP","GLOBAL",4)
    Continue()
END

///////////////////////
///Death Script     ///
///////////////////////

IF
  OR(2)
    Global("#GStartSpl","GLOBAL",0)
    HPGT(%famsummoner%,3)
  Die()
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    ActionOverride(%famsummoner%,Recoil())
    ActionOverride(%famsummoner%,VerbalConstant(Myself,DAMAGE))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon4",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,MakeUnselectable(4))
    DisplayString(%famsummoner%,8536)
    DisplayString(%famsummoner%,21004)
    CreateCreatureObjectOffScreen("wtpnag9",Myself,0,0,0)
    SetGlobalTimer("#Gmourn","GLOBAL",THREE_DAYS)
    SetGlobal("WTPFAMCE","GLOBAL",0)
    SetGlobal("#GAFTER","GLOBAL",0)
    SetGlobal("#GFLVUP","GLOBAL",0)
    SetGlobal("#GHARAS","GLOBAL",0)
    SetGlobal("#GPLALVL","GLOBAL",0)
    SetGlobal("#GSHOCK","GLOBAL",1)
    SetGlobal("#GHPOFF","GLOBAL",1)
    SetGlobal("#GMIRPEN","GLOBAL",0)
    SetInterrupt(TRUE)
END

IF
  OR(2)
    Global("#GStartSpl","GLOBAL",0)
    HPGT(%famsummoner%,3)
  Global("#GFAMGO","GLOBAL",1)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    ActionOverride(%famsummoner%,Recoil())
    ActionOverride(%famsummoner%,VerbalConstant(Myself,DAMAGE))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ApplySpellRES("WTPDESP1",Myself))
    ActionOverride(%famsummoner%,MakeUnselectable(4))
    DisplayString(%famsummoner%,@522)
    SetGlobalTimer("#Gmourn","GLOBAL",THREE_DAYS)
    SetGlobal("WTPFAMCE","GLOBAL",0)
    SetGlobal("#GAFTER","GLOBAL",0)
    SetGlobal("#GFLVUP","GLOBAL",0)
    SetGlobal("#GHARAS","GLOBAL",0)
    SetGlobal("#GPLALVL","GLOBAL",0)
    SetGlobal("#GFAMGO","GLOBAL",2)
    SetGlobal("#GMIRPEN","GLOBAL",0)
    SetInterrupt(TRUE)
END

IF
  Global("#GStartSpl","GLOBAL",1)
  OR(2)
    HP(%famsummoner%,2)
    HP(%famsummoner%,3)
  Die()
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    ActionOverride(%famsummoner%,Recoil())
    ActionOverride(%famsummoner%,VerbalConstant(Myself,DAMAGE))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFConA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCOND",Myself))
    ActionOverride(%famsummoner%,MakeUnselectable(4))
    DisplayString(%famsummoner%,8536)
    DisplayString(%famsummoner%,21004)
    CreateCreatureObjectOffScreen("wtpnag9",Myself,0,0,0)
    SetGlobalTimer("#Gmourn","GLOBAL",THREE_DAYS)
    SetGlobal("WTPFAMCE","GLOBAL",0)
    SetGlobal("#GAFTER","GLOBAL",0)
    SetGlobal("#GFLVUP","GLOBAL",0)
    SetGlobal("#GHARAS","GLOBAL",0)
    SetGlobal("#GPLALVL","GLOBAL",0)
    SetGlobal("#GSHOCK","GLOBAL",1)
    SetGlobal("#GHPOFF","GLOBAL",1)
    SetGlobal("#GMIRPEN","GLOBAL",0)
    SetInterrupt(TRUE)
END

IF
  Global("#GStartSpl","GLOBAL",1)
  OR(2)
    HP(%famsummoner%,2)
    HP(%famsummoner%,3)
  Global("#GFAMGO","GLOBAL",1)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    ActionOverride(%famsummoner%,Recoil())
    ActionOverride(%famsummoner%,VerbalConstant(Myself,DAMAGE))
    ActionOverride(%famsummoner%,ApplySpellRES("WTPDESP1",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFConA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCOND",Myself))
    ActionOverride(%famsummoner%,MakeUnselectable(4))
    DisplayString(%famsummoner%,@522)
    SetGlobalTimer("#Gmourn","GLOBAL",THREE_DAYS)
    SetGlobal("WTPFAMCE","GLOBAL",0)
    SetGlobal("#GAFTER","GLOBAL",0)
    SetGlobal("#GFLVUP","GLOBAL",0)
    SetGlobal("#GHARAS","GLOBAL",0)
    SetGlobal("#GPLALVL","GLOBAL",0)
    SetGlobal("#GFAMGO","GLOBAL",2)
    SetGlobal("#GMIRPEN","GLOBAL",0)
    SetInterrupt(TRUE)
END

IF
  Global("#GBhaalHP1","GLOBAL",2)
  Die()
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFConA",Myself))
    DisplayString(%famsummoner%,8536)
    DisplayString(%famsummoner%,21004)
    CreateCreatureObjectOffScreen("wtpnag9",Myself,0,0,0)
    SetGlobalTimer("#Gmourn","GLOBAL",THREE_DAYS)
    SetGlobal("WTPFAMCE","GLOBAL",0)
    SetGlobal("#GAFTER","GLOBAL",0)
    SetGlobal("#GFLVUP","GLOBAL",0)
    SetGlobal("#GHARAS","GLOBAL",0)
    SetGlobal("#GPLALVL","GLOBAL",0)
    SetGlobal("#GSHOCK","GLOBAL",1)
    SetGlobal("#GHPOFF","GLOBAL",1)
    SetGlobal("#GMIRPEN","GLOBAL",0)
    SetInterrupt(TRUE)
END

//////////////////////////////////////
///Keep the Familiar close         ///
//////////////////////////////////////

IF
  Exists(Myself)
  ActionListEmpty()
  !Detect([ENEMY])
  CombatCounterLT(1)
  !TriggerOverride(%famsummoner%,Detect([ENEMY]))
  Global("#GAFTER","GLOBAL",1)
THEN
  RESPONSE #80
    MoveToObjectFollow(%famsummoner%)
    Continue()
  RESPONSE #20
    NoAction()
    Continue()
END

////////////////////////////
///To backpack if damaged///
////////////////////////////

IF
  Global("#GBhaalHP1","GLOBAL",0) // GOooPD compatibility check
  Allegiance(Myself,FAMILIAR)
  !Dead("WTPQuasi")
  Global("WTPSTAT","LOCALS",0)
  !StateCheck(Myself,STATE_BLIND)
  HPPercentLT(Myself,25)
  See(LastAttackerOf(Myself))
  !InventoryFull(%famsummoner%)
  Range(%famsummoner%,25)
THEN
  RESPONSE #100
    MoveToObject(%famsummoner%)
    GiveItemCreate("wtpfmqua",%famsummoner%,0,0,0)
    DisplayStringHead(Myself,@524)
    SetGlobalTimer("#GWANOUT","GLOBAL",ONE_HOUR)
    SetGlobalTimer("#GSTAOUT","GLOBAL",FOUR_HOURS)
    DestroySelf()
END

////////////////////////////////////////////////////////////
///Leaves if attacked/wrong alignment/reputation too high///
////////////////////////////////////////////////////////////

IF
  !Alignment(%famsummoner%,CHAOTIC_EVIL)
  !Alignment(%famsummoner%,CHAOTIC_NEUTRAL)
  !Alignment(%famsummoner%,NEUTRAL_EVIL)
  CombatCounterLT(1)
  !Detect([ENEMY])
  !TriggerOverride(%famsummoner%,Detect([ENEMY]))
  Allegiance(Myself,FAMILIAR)
THEN
  RESPONSE #100
    DisplayStringHead(%famsummoner%,@527)
    ApplySpellRES("WTPFCon3",Myself)
    ChangeEnemyAlly(Myself,NEUTRAL)
    RemoveFamiliar()
    CreateCreatureObjectOffScreen("wtpnag9",Myself,0,0,0)
    SetGlobal("#GFAMGO","GLOBAL",1)
END

IF
  ReputationGT(%famsummoner%,18)
  CombatCounterLT(1)
  !Detect([ENEMY])
  !TriggerOverride(%famsummoner%,Detect([ENEMY]))
  Allegiance(Myself,FAMILIAR)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    Wait(2)
    Dialogue(%famsummoner%)
    SetInterrupt(TRUE)
END

IF
  AttackedBy(%famsummoner%,DEFAULT)
  !StateCheck(%famsummoner%,WTP_STATE_SUMMONER_CRAZY)
  !TriggerOverride(%famsummoner%,Detect([ENEMY]))
  Allegiance(Myself,FAMILIAR)
THEN
  RESPONSE #100
    ApplySpellRES("WTPFCon3",Myself)
    ChangeEnemyAlly(Myself,NEUTRAL)
    RemoveFamiliar()
    CreateCreatureObjectOffScreen("wtpnag9",Myself,0,0,0)
    SetGlobal("#GFAMGO","GLOBAL",1)
END

IF
  Global("#GSUMMON","LOCALS",0)
  !Dead("wtpquasi")
  Allegiance(Myself,NEUTRAL)
  !Global("#GFAMGO","GLOBAL",1)
THEN
  RESPONSE #100
    DisplayStringNoName(Myself,@521)
    SetGlobal("#GFAMGO","GLOBAL",3)
    EscapeArea()
END

IF
  Global("#GFAMGO","GLOBAL",0)
  Exists("wtpnag9")
THEN
  RESPONSE #100
    ActionOverride("wtpnag9",DestroySelf())
END

///////////////////////
///Reputation Check ///
///////////////////////

IF
  GlobalGT("#GEMPOW","LOCALS",0)
  OR(3)
    Global("#GREPCHK","LOCALS",1)
    Global("#GREPCHK","LOCALS",3)
    Global("#GREPCHK","LOCALS",6)
  ReputationGT(%famsummoner%,7)
THEN
  RESPONSE #100
    SetGlobal("#GEMPCHA","GLOBAL",1)
    SetGlobal("#GREPCHK","LOCALS",0)
END

IF
  GlobalGT("#GEMPOW","LOCALS",0)
  OR(3)
    Global("#GREPCHK","LOCALS",2)
    Global("#GREPCHK","LOCALS",5)
    Global("#GREPCHK","LOCALS",8)
  OR(2)
    ReputationLT(%famsummoner%,8)
    ReputationGT(%famsummoner%,14)
THEN
  RESPONSE #100
    SetGlobal("#GEMPCHA","GLOBAL",1)
    SetGlobal("#GREPCHK","LOCALS",0)
END

IF
  GlobalGT("#GEMPOW","LOCALS",0)
  OR(3)
    Global("#GREPCHK","LOCALS",4)
    Global("#GREPCHK","LOCALS",7)
    Global("#GREPCHK","LOCALS",9)
  ReputationLT(%famsummoner%,15)
THEN
  RESPONSE #100
    SetGlobal("#GEMPCHA","GLOBAL",1)
    SetGlobal("#GREPCHK","LOCALS",0)
END

//////////////////////////
///Empowerment ON/OFF  ///
//////////////////////////

IF
  OR(2)
    ActionListEmpty()
    Detect([ENEMY])
  Global("#GEMPCHK","LOCALS",0)
  OR(6)
    !Range(%famsummoner%,15)
    Global("WTPSTAT","LOCALS",1)
    StateCheck(Myself,STATE_DISEASED)
    StateCheck(%famsummoner%,STATE_DISEASED)
    Global("#GEMPCHA","GLOBAL",1)
    Global("#GBhaalHP1","GLOBAL",2)					// GOooPD compatibility check
THEN
  RESPONSE #100
    SetGlobal("#GEMPCHK","LOCALS",1)
END

IF
  Global("#GSUMMON","LOCALS",0)
  OR(2)
    ActionListEmpty()
    Detect([ENEMY])
  Global("#GEMPCHK","LOCALS",1)
  Global("#GEMPLUP","LOCALS",0)
  Range(%famsummoner%,15)
  Global("WTPSTAT","LOCALS",0)
  Global("#GEMPCHA","GLOBAL",0)
  !StateCheck(Myself,STATE_DISEASED)
  !StateCheck(%famsummoner%,STATE_DISEASED)
  Global("#GBhaalHP1","GLOBAL",0)						// GOooPD compatibility check
THEN
  RESPONSE #100
    SetGlobal("#GEMPCHK","LOCALS",0)
END

///////////////
/// EMP OFF ///
///////////////

IF
  Global("#GEMPOW","LOCALS",1)
  Global("#GEMPCHK","LOCALS",1)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GEMPOW","LOCALS",0)
    SetGlobal("#GEMPLUP","LOCALS",0)
    SetGlobal("#GEMPCHA","GLOBAL",0)
    ReallyForceSpellRES("WTPFLVQ1",Myself)
    SetInterrupt(TRUE)
END

IF
  Global("#GEMPOW","LOCALS",2)
  Global("#GEMPCHK","LOCALS",1)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GEMPOW","LOCALS",0)
    SetGlobal("#GEMPLUP","LOCALS",0)
    SetGlobal("#GEMPCHA","GLOBAL",0)
    ReallyForceSpellRES("WTPFLVQ2",Myself)
    SetInterrupt(TRUE)
END

IF
  Global("#GEMPOW","LOCALS",3)
  Global("#GEMPCHK","LOCALS",1)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GEMPOW","LOCALS",0)
    SetGlobal("#GEMPLUP","LOCALS",0)
    SetGlobal("#GEMPCHA","GLOBAL",0)
    ReallyForceSpellRES("WTPFLVQ3",Myself)
    SetInterrupt(TRUE)
END

IF
  Global("#GEMPOW","LOCALS",4)
  Global("#GEMPCHK","LOCALS",1)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GEMPOW","LOCALS",0)
    SetGlobal("#GEMPLUP","LOCALS",0)
    SetGlobal("#GEMPCHA","GLOBAL",0)
    ReallyForceSpellRES("WTPFLVQ4",Myself)
    SetInterrupt(TRUE)
END

IF
  Global("#GEMPOW","LOCALS",5)
  Global("#GEMPCHK","LOCALS",1)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GEMPOW","LOCALS",0)
    SetGlobal("#GEMPLUP","LOCALS",0)
    SetGlobal("#GEMPCHA","GLOBAL",0)
    ReallyForceSpellRES("WTPFLVQ6",Myself)
    SetInterrupt(TRUE)
END

IF
  Global("#GEMPOW","LOCALS",6)
  Global("#GEMPCHK","LOCALS",1)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GEMPOW","LOCALS",0)
    SetGlobal("#GEMPLUP","LOCALS",0)
    SetGlobal("#GEMPCHA","GLOBAL",0)
    ReallyForceSpellRES("WTPFLVQ1",Myself)
    ReallyForceSpellRES("WTPFLVQ3",Myself)
    ReallyForceSpellRES("WTPFLVQ7",Myself)
    SetInterrupt(TRUE)
END

IF
  Global("#GEMPOW","LOCALS",7)
  Global("#GEMPCHK","LOCALS",1)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GEMPOW","LOCALS",0)
    SetGlobal("#GEMPLUP","LOCALS",0)
    SetGlobal("#GEMPCHA","GLOBAL",0)
    ReallyForceSpellRES("WTPFLVQ2",Myself)
    ReallyForceSpellRES("WTPFLVQ3",Myself)
    ReallyForceSpellRES("WTPFLVQ6",Myself)
    SetInterrupt(TRUE)
END

IF
  Global("#GEMPOW","LOCALS",8)
  Global("#GEMPCHK","LOCALS",1)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GEMPOW","LOCALS",0)
    SetGlobal("#GEMPLUP","LOCALS",0)
    SetGlobal("#GEMPCHA","GLOBAL",0)
    ReallyForceSpellRES("WTPFLVQ1",Myself)
    SetInterrupt(TRUE)
END

IF
  Global("#GEMPOW","LOCALS",9)
  Global("#GEMPCHK","LOCALS",1)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GEMPOW","LOCALS",0)
    SetGlobal("#GEMPLUP","LOCALS",0)
    SetGlobal("#GEMPCHA","GLOBAL",0)
    ReallyForceSpellRES("WTPFLVQ5",Myself)
    ReallyForceSpellRES("WTPFLVQ6",Myself)
    SetInterrupt(TRUE)
END

IF
  Global("#GEMPOW","LOCALS",10)
  Global("#GEMPCHK","LOCALS",1)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GEMPOW","LOCALS",0)
    SetGlobal("#GEMPLUP","LOCALS",0)
    SetGlobal("#GEMPCHA","GLOBAL",0)
    ReallyForceSpellRES("WTPFLVQ3",Myself)
    SetInterrupt(TRUE)
END

IF
  Global("#GEMPOW","LOCALS",11)
  Global("#GEMPCHK","LOCALS",1)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GEMPOW","LOCALS",0)
    SetGlobal("#GEMPLUP","LOCALS",0)
    SetGlobal("#GEMPCHA","GLOBAL",0)
    ReallyForceSpellRES("WTPFLVQ1",Myself)
    ReallyForceSpellRES("WTPFLVQ1",Myself)
    ReallyForceSpellRES("WTPFLVQ8",Myself)
    ReallyForceSpellRES("WTPFLVQ6",Myself)
    SetInterrupt(TRUE)
END

IF
  Global("#GEMPOW","LOCALS",12)
  Global("#GEMPCHK","LOCALS",1)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GEMPOW","LOCALS",0)
    SetGlobal("#GEMPLUP","LOCALS",0)
    SetGlobal("#GEMPCHA","GLOBAL",0)
    ReallyForceSpellRES("WTPFLVQ1",Myself)
    ReallyForceSpellRES("WTPFLVQ2",Myself)
    ReallyForceSpellRES("WTPFLVQ7",Myself)
    ReallyForceSpellRES("WTPFLVQ6",Myself)
    SetInterrupt(TRUE)
END

IF
  Global("#GEMPOW","LOCALS",13)
  Global("#GEMPCHK","LOCALS",1)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GEMPOW","LOCALS",0)
    SetGlobal("#GEMPLUP","LOCALS",0)
    SetGlobal("#GEMPCHA","GLOBAL",0)
    ReallyForceSpellRES("WTPFLVQ1",Myself)
    ReallyForceSpellRES("WTPFLVQ3",Myself)
    SetInterrupt(TRUE)
END

IF
  Global("#GEMPOW","LOCALS",14)
  Global("#GEMPCHK","LOCALS",1)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GEMPOW","LOCALS",0)
    SetGlobal("#GEMPLUP","LOCALS",0)
    SetGlobal("#GEMPCHA","GLOBAL",0)
    ReallyForceSpellRES("WTPFLVQ1",Myself)
    ReallyForceSpellRES("WTPFLVQ4",Myself)
    SetInterrupt(TRUE)
END

IF
  Global("#GEMPOW","LOCALS",15)
  Global("#GEMPCHK","LOCALS",1)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GEMPOW","LOCALS",0)
    SetGlobal("#GEMPLUP","LOCALS",0)
    SetGlobal("#GEMPCHA","GLOBAL",0)
    ReallyForceSpellRES("WTPFLVQ1",Myself)
    ReallyForceSpellRES("WTPFLVQ6",Myself)
    SetInterrupt(TRUE)
END

IF
  Global("#GEMPOW","LOCALS",16)
  Global("#GEMPCHK","LOCALS",1)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GEMPOW","LOCALS",0)
    SetGlobal("#GEMPLUP","LOCALS",0)
    SetGlobal("#GEMPCHA","GLOBAL",0)
    ReallyForceSpellRES("WTPFLVQE",Myself)
    ReallyForceSpellRES("WTPFLVQ7",Myself)
    ReallyForceSpellRES("WTPFLVQ6",Myself)
    SetInterrupt(TRUE)
END

IF
  Global("#GEMPOW","LOCALS",17)
  Global("#GEMPCHK","LOCALS",1)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GEMPOW","LOCALS",0)
    SetGlobal("#GEMPLUP","LOCALS",0)
    SetGlobal("#GEMPCHA","GLOBAL",0)
    ReallyForceSpellRES("WTPFLVQ1",Myself)
    ReallyForceSpellRES("WTPFLVQ2",Myself)
    ReallyForceSpellRES("WTPFLVQ3",Myself)
    ReallyForceSpellRES("WTPFLVQ8",Myself)
    ReallyForceSpellRES("WTPFLVQ6",Myself)
    SetInterrupt(TRUE)
END

IF
  Global("#GEMPOW","LOCALS",18)
  Global("#GEMPCHK","LOCALS",1)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GEMPOW","LOCALS",0)
    SetGlobal("#GEMPLUP","LOCALS",0)
    SetGlobal("#GEMPCHA","GLOBAL",0)
    ReallyForceSpellRES("WTPFLVQ1",Myself)
    ReallyForceSpellRES("WTPFLVQ1",Myself)
    ReallyForceSpellRES("WTPFLVQ7",Myself)
    SetInterrupt(TRUE)
END

IF
  Global("#GEMPOW","LOCALS",19)
  Global("#GEMPCHK","LOCALS",1)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GEMPOW","LOCALS",0)
    SetGlobal("#GEMPLUP","LOCALS",0)
    SetGlobal("#GEMPCHA","GLOBAL",0)
    ReallyForceSpellRES("WTPFLVQ1",Myself)
    ReallyForceSpellRES("WTPFLVQ5",Myself)
    ReallyForceSpellRES("WTPFLVQ7",Myself)
    ReallyForceSpellRES("WTPFLVQ6",Myself)
    SetInterrupt(TRUE)
END

IF
  Global("#GEMPOW","LOCALS",20)
  Global("#GEMPCHK","LOCALS",1)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GEMPOW","LOCALS",0)
    SetGlobal("#GEMPLUP","LOCALS",0)
    SetGlobal("#GEMPCHA","GLOBAL",0)
    ReallyForceSpellRES("WTPFLVQ1",Myself)
    ReallyForceSpellRES("WTPFLVQ3",Myself)
    ReallyForceSpellRES("WTPFLVQ7",Myself)
    SetInterrupt(TRUE)
END

IF
  Global("#GEMPOW","LOCALS",21)
  Global("#GEMPCHK","LOCALS",1)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GEMPOW","LOCALS",0)
    SetGlobal("#GEMPLUP","LOCALS",0)
    SetGlobal("#GEMPCHA","GLOBAL",0)
    ReallyForceSpellRES("WTPFLVQE",Myself)
    ReallyForceSpellRES("WTPFLVQ3",Myself)
    ReallyForceSpellRES("WTPFLVQ9",Myself)
    SetInterrupt(TRUE)
END

IF
  Global("#GEMPOW","LOCALS",22)
  Global("#GEMPCHK","LOCALS",1)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GEMPOW","LOCALS",0)
    SetGlobal("#GEMPLUP","LOCALS",0)
    SetGlobal("#GEMPCHA","GLOBAL",0)
    ReallyForceSpellRES("WTPFLVQ1",Myself)
    ReallyForceSpellRES("WTPFLVQ1",Myself)
    ReallyForceSpellRES("WTPFLVQ2",Myself)
    ReallyForceSpellRES("WTPFLVQ9",Myself)
    ReallyForceSpellRES("WTPFLVQ7",Myself)
    SetInterrupt(TRUE)
END

IF
  Global("#GEMPOW","LOCALS",23)
  Global("#GEMPCHK","LOCALS",1)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GEMPOW","LOCALS",0)
    SetGlobal("#GEMPLUP","LOCALS",0)
    SetGlobal("#GEMPCHA","GLOBAL",0)
    ReallyForceSpellRES("WTPFLVQ1",Myself)
    ReallyForceSpellRES("WTPFLVQ1",Myself)
    ReallyForceSpellRES("WTPFLVQ3",Myself)
    ReallyForceSpellRES("WTPFLVQ8",Myself)
    SetInterrupt(TRUE)
END

IF
  Global("#GEMPOW","LOCALS",24)
  Global("#GEMPCHK","LOCALS",1)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GEMPOW","LOCALS",0)
    SetGlobal("#GEMPLUP","LOCALS",0)
    SetGlobal("#GEMPCHA","GLOBAL",0)
    ReallyForceSpellRES("WTPFLVQ2",Myself)
    ReallyForceSpellRES("WTPFLVQ5",Myself)
    ReallyForceSpellRES("WTPFLVQ5",Myself)
    ReallyForceSpellRES("WTPFLVQ9",Myself)
    SetInterrupt(TRUE)
END

IF
  Global("#GEMPOW","LOCALS",25)
  Global("#GEMPCHK","LOCALS",1)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GEMPOW","LOCALS",0)
    SetGlobal("#GEMPLUP","LOCALS",0)
    SetGlobal("#GEMPCHA","GLOBAL",0)
    ReallyForceSpellRES("WTPFLVQ1",Myself)
    ReallyForceSpellRES("WTPFLVQ1",Myself)
    ReallyForceSpellRES("WTPFLVQ8",Myself)
    ReallyForceSpellRES("WTPFLVQ6",Myself)
    SetInterrupt(TRUE)
END

IF
  Global("#GEMPOW","LOCALS",26)
  Global("#GEMPCHK","LOCALS",1)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GEMPOW","LOCALS",0)
    SetGlobal("#GEMPLUP","LOCALS",0)
    SetGlobal("#GEMPCHA","GLOBAL",0)
    ReallyForceSpellRES("WTPFLVQE",Myself)
    ReallyForceSpellRES("WTPFLVQ1",Myself)
    ReallyForceSpellRES("WTPFLVQA",Myself)
    ReallyForceSpellRES("WTPFLVQ7",Myself)
    SetInterrupt(TRUE)
END

IF
  Global("#GEMPOW","LOCALS",27)
  Global("#GEMPCHK","LOCALS",1)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GEMPOW","LOCALS",0)
    SetGlobal("#GEMPLUP","LOCALS",0)
    SetGlobal("#GEMPCHA","GLOBAL",0)
    ReallyForceSpellRES("WTPFLVQE",Myself)
    ReallyForceSpellRES("WTPFLVQ2",Myself)
    ReallyForceSpellRES("WTPFLVQ9",Myself)
    ReallyForceSpellRES("WTPFLVQ6",Myself)
    SetInterrupt(TRUE)
END

IF
  Global("#GEMPOW","LOCALS",28)
  Global("#GEMPCHK","LOCALS",1)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GEMPOW","LOCALS",0)
    SetGlobal("#GEMPLUP","LOCALS",0)
    SetGlobal("#GEMPCHA","GLOBAL",0)
    ReallyForceSpellRES("WTPFLVQE",Myself)
    ReallyForceSpellRES("WTPFLVQ3",Myself)
    ReallyForceSpellRES("WTPFLVQ7",Myself)
    SetInterrupt(TRUE)
END

IF
  Global("#GEMPOW","LOCALS",29)
  Global("#GEMPCHK","LOCALS",1)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GEMPOW","LOCALS",0)
    SetGlobal("#GEMPLUP","LOCALS",0)
    SetGlobal("#GEMPCHA","GLOBAL",0)
    ReallyForceSpellRES("WTPFLVQE",Myself)
    ReallyForceSpellRES("WTPFLVQ4",Myself)
    ReallyForceSpellRES("WTPFLVQ7",Myself)
    SetInterrupt(TRUE)
END

IF
  Global("#GEMPOW","LOCALS",30)
  Global("#GEMPCHK","LOCALS",1)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GEMPOW","LOCALS",0)
    SetGlobal("#GEMPLUP","LOCALS",0)
    SetGlobal("#GEMPCHA","GLOBAL",0)
    ReallyForceSpellRES("WTPFLVQE",Myself)
    ReallyForceSpellRES("WTPFLVQ7",Myself)
    ReallyForceSpellRES("WTPFLVQ6",Myself)
    SetInterrupt(TRUE)
END

IF
  Global("#GEMPOW","LOCALS",31)
  Global("#GEMPCHK","LOCALS",1)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GEMPOW","LOCALS",0)
    SetGlobal("#GEMPLUP","LOCALS",0)
    SetGlobal("#GEMPCHA","GLOBAL",0)
    ReallyForceSpellRES("WTPFLVQE",Myself)
    ReallyForceSpellRES("WTPFLVQ1",Myself)
    ReallyForceSpellRES("WTPFLVQ3",Myself)
    ReallyForceSpellRES("WTPFLVQB",Myself)
    ReallyForceSpellRES("WTPFLVQ7",Myself)
    ReallyForceSpellRES("WTPFLVQ6",Myself)
    SetInterrupt(TRUE)
END

IF
  Global("#GEMPOW","LOCALS",32)
  Global("#GEMPCHK","LOCALS",1)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GEMPOW","LOCALS",0)
    SetGlobal("#GEMPLUP","LOCALS",0)
    SetGlobal("#GEMPCHA","GLOBAL",0)
    ReallyForceSpellRES("WTPFLVQE",Myself)
    ReallyForceSpellRES("WTPFLVQ2",Myself)
    ReallyForceSpellRES("WTPFLVQ3",Myself)
    ReallyForceSpellRES("WTPFLVQA",Myself)
    ReallyForceSpellRES("WTPFLVQ7",Myself)
    SetInterrupt(TRUE)
END

IF
  Global("#GEMPOW","LOCALS",33)
  Global("#GEMPCHK","LOCALS",1)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GEMPOW","LOCALS",0)
    SetGlobal("#GEMPLUP","LOCALS",0)
    SetGlobal("#GEMPCHA","GLOBAL",0)
    ReallyForceSpellRES("WTPFLVQE",Myself)
    ReallyForceSpellRES("WTPFLVQ1",Myself)
    ReallyForceSpellRES("WTPFLVQ9",Myself)
    SetInterrupt(TRUE)
END

IF
  Global("#GEMPOW","LOCALS",34)
  Global("#GEMPCHK","LOCALS",1)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GEMPOW","LOCALS",0)
    SetGlobal("#GEMPLUP","LOCALS",0)
    SetGlobal("#GEMPCHA","GLOBAL",0)
    ReallyForceSpellRES("WTPFLVQE",Myself)
    ReallyForceSpellRES("WTPFLVQ5",Myself)
    ReallyForceSpellRES("WTPFLVQ9",Myself)
    ReallyForceSpellRES("WTPFLVQ6",Myself)
    SetInterrupt(TRUE)
END

IF
  Global("#GEMPOW","LOCALS",35)
  Global("#GEMPCHK","LOCALS",1)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GEMPOW","LOCALS",0)
    SetGlobal("#GEMPLUP","LOCALS",0)
    SetGlobal("#GEMPCHA","GLOBAL",0)
    ReallyForceSpellRES("WTPFLVQE",Myself)
    ReallyForceSpellRES("WTPFLVQ3",Myself)
    ReallyForceSpellRES("WTPFLVQ9",Myself)
    SetInterrupt(TRUE)
END

IF
  Global("#GEMPOW","LOCALS",36)
  Global("#GEMPCHK","LOCALS",1)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GEMPOW","LOCALS",0)
    SetGlobal("#GEMPLUP","LOCALS",0)
    SetGlobal("#GEMPCHA","GLOBAL",0)
    ReallyForceSpellRES("WTPFLVQE",Myself)
    ReallyForceSpellRES("WTPFLVQ1",Myself)
    ReallyForceSpellRES("WTPFLVQ1",Myself)
    ReallyForceSpellRES("WTPFLVQA",Myself)
    ReallyForceSpellRES("WTPFLVQB",Myself)
    SetInterrupt(TRUE)
END

IF
  Global("#GEMPOW","LOCALS",37)
  Global("#GEMPCHK","LOCALS",1)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GEMPOW","LOCALS",0)
    SetGlobal("#GEMPLUP","LOCALS",0)
    SetGlobal("#GEMPCHA","GLOBAL",0)
    ReallyForceSpellRES("WTPFLVQE",Myself)
    ReallyForceSpellRES("WTPFLVQ1",Myself)
    ReallyForceSpellRES("WTPFLVQ2",Myself)
    ReallyForceSpellRES("WTPFLVQB",Myself)
    ReallyForceSpellRES("WTPFLVQ8",Myself)
    SetInterrupt(TRUE)
END

IF
  Global("#GEMPOW","LOCALS",38)
  Global("#GEMPCHK","LOCALS",1)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GEMPOW","LOCALS",0)
    SetGlobal("#GEMPLUP","LOCALS",0)
    SetGlobal("#GEMPCHA","GLOBAL",0)
    ReallyForceSpellRES("WTPFLVQE",Myself)
    ReallyForceSpellRES("WTPFLVQ1",Myself)
    ReallyForceSpellRES("WTPFLVQ3",Myself)
    ReallyForceSpellRES("WTPFLVQA",Myself)
    ReallyForceSpellRES("WTPFLVQ6",Myself)
    SetInterrupt(TRUE)
END

IF
  Global("#GEMPOW","LOCALS",39)
  Global("#GEMPCHK","LOCALS",1)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GEMPOW","LOCALS",0)
    SetGlobal("#GEMPLUP","LOCALS",0)
    SetGlobal("#GEMPCHA","GLOBAL",0)
    ReallyForceSpellRES("WTPFLVQE",Myself)
    ReallyForceSpellRES("WTPFLVQ3",Myself)
    ReallyForceSpellRES("WTPFLVQ5",Myself)
    ReallyForceSpellRES("WTPFLVQA",Myself)
    ReallyForceSpellRES("WTPFLVQ7",Myself)
    SetInterrupt(TRUE)
END

IF
  Global("#GEMPOW","LOCALS",40)
  Global("#GEMPCHK","LOCALS",1)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GEMPOW","LOCALS",0)
    SetGlobal("#GEMPLUP","LOCALS",0)
    SetGlobal("#GEMPCHA","GLOBAL",0)
    ReallyForceSpellRES("WTPFLVQE",Myself)
    ReallyForceSpellRES("WTPFLVQ1",Myself)
    ReallyForceSpellRES("WTPFLVQA",Myself)
    ReallyForceSpellRES("WTPFLVQ7",Myself)
    SetInterrupt(TRUE)
END

IF
  Global("#GEMPOW","LOCALS",41)
  Global("#GEMPCHK","LOCALS",1)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GEMPOW","LOCALS",0)
    SetGlobal("#GEMPLUP","LOCALS",0)
    SetGlobal("#GEMPCHA","GLOBAL",0)
    ReallyForceSpellRES("WTPFLVQE",Myself)
    ReallyForceSpellRES("WTPFLVQE",Myself)
    ReallyForceSpellRES("WTPFLVQD",Myself)
    ReallyForceSpellRES("WTPFLVQ6",Myself)
    SetInterrupt(TRUE)
END

IF
  Global("#GEMPOW","LOCALS",42)
  Global("#GEMPCHK","LOCALS",1)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GEMPOW","LOCALS",0)
    SetGlobal("#GEMPLUP","LOCALS",0)
    SetGlobal("#GEMPCHA","GLOBAL",0)
    ReallyForceSpellRES("WTPFLVQE",Myself)
    ReallyForceSpellRES("WTPFLVQ1",Myself)
    ReallyForceSpellRES("WTPFLVQ2",Myself)
    ReallyForceSpellRES("WTPFLVQ3",Myself)
    ReallyForceSpellRES("WTPFLVQB",Myself)
    ReallyForceSpellRES("WTPFLVQA",Myself)
    SetInterrupt(TRUE)
END

IF
  Global("#GEMPOW","LOCALS",43)
  Global("#GEMPCHK","LOCALS",1)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GEMPOW","LOCALS",0)
    SetGlobal("#GEMPLUP","LOCALS",0)
    SetGlobal("#GEMPCHA","GLOBAL",0)
    ReallyForceSpellRES("WTPFLVQE",Myself)
    ReallyForceSpellRES("WTPFLVQ1",Myself)
    ReallyForceSpellRES("WTPFLVQ1",Myself)
    ReallyForceSpellRES("WTPFLVQB",Myself)
    ReallyForceSpellRES("WTPFLVQ7",Myself)
    ReallyForceSpellRES("WTPFLVQ6",Myself)
    SetInterrupt(TRUE)
END

IF
  Global("#GEMPOW","LOCALS",44)
  Global("#GEMPCHK","LOCALS",1)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GEMPOW","LOCALS",0)
    SetGlobal("#GEMPLUP","LOCALS",0)
    SetGlobal("#GEMPCHA","GLOBAL",0)
    ReallyForceSpellRES("WTPFLVQE",Myself)
    ReallyForceSpellRES("WTPFLVQ1",Myself)
    ReallyForceSpellRES("WTPFLVQ5",Myself)
    ReallyForceSpellRES("WTPFLVQB",Myself)
    ReallyForceSpellRES("WTPFLVQ8",Myself)
    SetInterrupt(TRUE)
END

IF
  Global("#GEMPOW","LOCALS",45)
  Global("#GEMPCHK","LOCALS",1)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GEMPOW","LOCALS",0)
    SetGlobal("#GEMPLUP","LOCALS",0)
    SetGlobal("#GEMPCHA","GLOBAL",0)
    ReallyForceSpellRES("WTPFLVQE",Myself)
    ReallyForceSpellRES("WTPFLVQ1",Myself)
    ReallyForceSpellRES("WTPFLVQ3",Myself)
    ReallyForceSpellRES("WTPFLVQB",Myself)
    ReallyForceSpellRES("WTPFLVQ7",Myself)
    ReallyForceSpellRES("WTPFLVQ6",Myself)
    SetInterrupt(TRUE)
END

//////////////////////////////
/// No negative HP allowed ///
//////////////////////////////

IF
  HPLT(Myself,1)
THEN
  RESPONSE #100
    Kill(Myself)
END

/* EVIL FAMILIARS
BLOCK1:
MIRPEN 0 REP 1-7
BLOCK2:
MIRPEN 0 REP 8-14 OR MIRPEN 1 REP 1-7
BLOCK3:
MIRPEN 0 REP 15-20 OR MIRPEN 1 REP 8-14 OR MIRPEN 2 REP 1-7
BLOCK4:
MIRPEN 1 REP 15-20 OR MIRPEN 2 REP 8-14
BLOCK5:
MIRPEN 2 REP 15-20
*/

/* GOOD FAMILIARS
BLOCK1:
MIRPEN 0 REP 16-20
BLOCK2:
MIRPEN 0 REP 9-15 OR MIRPEN 1 REP 16-20
BLOCK3:
MIRPEN 0 REP 1-8 OR MIRPEN 1 REP 10-14 OR MIRPEN 2 REP 16-20
BLOCK4:
MIRPEN 1 REP 1-8 OR MIRPEN 2 REP 10-14
BLOCK5
MIRPEN 2 REP 1-8
*/

/* NEUTRAL FAMILIARS
BLOCK1:
MIRPEN 0 REP 8-13
BLOCK2:
MIRPEN 0 REP 5-7/14-16 OR MIRPEN 1 REP 8-13
BLOCK3:
MIRPEN 0 REP 1-4/17-20 OR MIRPEN 1 REP 5-7/14-16 OR MIRPEN 2 REP 8-13
BLOCK4:
MIRPEN 1 REP 1-4/17-20 OR MIRPEN 2 REP 5-7/14-16
BLOCK5:
MIRPEN 2 REP 1-4/17-20
*/

///////////////
/// EMP ON  ///
///////////////

// LV 1-5

IF										// BLOCK1
  Global("#GEMPCHK","LOCALS",0)
  ReputationLT(%famsummoner%,8)							// MIRPEN 0 REP 1-7
  Global("#GMIRPEN","GLOBAL",0)
  Global("#GEMPOW","LOCALS",0)
  GlobalLT("#GPLALVL","GLOBAL",6)
  Global("#GFLVUP","GLOBAL",0)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GREPCHK","LOCALS",1)
    SetGlobal("#GEMPOW","LOCALS",1)
    ReallyForceSpellRES("WTPFLVP1",Myself)
    SetInterrupt(TRUE)
END

IF										// BLOCK2A
  Global("#GEMPCHK","LOCALS",0)
  ReputationLT(%famsummoner%,15)						// MIRPEN 0 REP 8-14
  ReputationGT(%famsummoner%,7)
  Global("#GMIRPEN","GLOBAL",0)
  Global("#GEMPOW","LOCALS",0)
  GlobalLT("#GPLALVL","GLOBAL",6)
  Global("#GFLVUP","GLOBAL",0)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GREPCHK","LOCALS",2)
    SetGlobal("#GEMPOW","LOCALS",2)
    ReallyForceSpellRES("WTPFLVP2",Myself)
    SetInterrupt(TRUE)
END

IF										// BLOCK2B
  Global("#GEMPCHK","LOCALS",0)
  ReputationLT(%famsummoner%,8)							// MIRPEN 1 REP 1-7
  Global("#GMIRPEN","GLOBAL",1)
  Global("#GEMPOW","LOCALS",0)
  GlobalLT("#GPLALVL","GLOBAL",6)
  Global("#GFLVUP","GLOBAL",0)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GREPCHK","LOCALS",3)
    SetGlobal("#GEMPOW","LOCALS",2)
    ReallyForceSpellRES("WTPFLVP2",Myself)
    SetInterrupt(TRUE)
END

IF										// BLOCK3A
  Global("#GEMPCHK","LOCALS",0)
  ReputationGT(%famsummoner%,14)						// MIRPEN 0 REP 15-20
  Global("#GMIRPEN","GLOBAL",0)
  Global("#GEMPOW","LOCALS",0)
  GlobalLT("#GPLALVL","GLOBAL",6)
  Global("#GFLVUP","GLOBAL",0)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GREPCHK","LOCALS",4)
    SetGlobal("#GEMPOW","LOCALS",3)
    ReallyForceSpellRES("WTPFLVP3",Myself)
    SetInterrupt(TRUE)
END

IF										// BLOCK3B
  Global("#GEMPCHK","LOCALS",0)
  ReputationLT(%famsummoner%,15)						// MIRPEN 1 REP 8-14
  ReputationGT(%famsummoner%,7)
  Global("#GMIRPEN","GLOBAL",1)
  Global("#GEMPOW","LOCALS",0)
  GlobalLT("#GPLALVL","GLOBAL",6)
  Global("#GFLVUP","GLOBAL",0)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GREPCHK","LOCALS",5)
    SetGlobal("#GEMPOW","LOCALS",3)
    ReallyForceSpellRES("WTPFLVP3",Myself)
    SetInterrupt(TRUE)
END

IF										// BLOCK3C
  Global("#GEMPCHK","LOCALS",0)
  ReputationLT(%famsummoner%,8)							// MIRPEN 2 REP 1-7
  Global("#GMIRPEN","GLOBAL",2)
  Global("#GEMPOW","LOCALS",0)
  GlobalLT("#GPLALVL","GLOBAL",6)
  Global("#GFLVUP","GLOBAL",0)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GREPCHK","LOCALS",6)
    SetGlobal("#GEMPOW","LOCALS",3)
    ReallyForceSpellRES("WTPFLVP3",Myself)
    SetInterrupt(TRUE)
END

IF										// BLOCK4A
  Global("#GEMPCHK","LOCALS",0)
  ReputationGT(%famsummoner%,14)						// MIRPEN 1 REP 15-20
  Global("#GMIRPEN","GLOBAL",1)
  Global("#GEMPOW","LOCALS",0)
  GlobalLT("#GPLALVL","GLOBAL",6)
  Global("#GFLVUP","GLOBAL",0)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GREPCHK","LOCALS",7)
    SetGlobal("#GEMPOW","LOCALS",4)
    ReallyForceSpellRES("WTPFLVP4",Myself)
    SetInterrupt(TRUE)
END

IF										// BLOCK4B
  Global("#GEMPCHK","LOCALS",0)
  ReputationLT(%famsummoner%,15)						// MIRPEN 2 REP 8-14
  ReputationGT(%famsummoner%,7)
  Global("#GMIRPEN","GLOBAL",2)
  Global("#GEMPOW","LOCALS",0)
  GlobalLT("#GPLALVL","GLOBAL",6)
  Global("#GFLVUP","GLOBAL",0)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GREPCHK","LOCALS",8)
    SetGlobal("#GEMPOW","LOCALS",4)
    ReallyForceSpellRES("WTPFLVP4",Myself)
    SetInterrupt(TRUE)
END

IF										// BLOCK5
  Global("#GEMPCHK","LOCALS",0)
  ReputationGT(%famsummoner%,14)						// MIRPEN 2 REP 15-20
  Global("#GMIRPEN","GLOBAL",2)
  Global("#GEMPOW","LOCALS",0)
  GlobalLT("#GPLALVL","GLOBAL",6)
  Global("#GFLVUP","GLOBAL",0)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GREPCHK","LOCALS",9)
    SetGlobal("#GEMPOW","LOCALS",5)
    ReallyForceSpellRES("WTPFLVP6",Myself)
    SetInterrupt(TRUE)
END

// LV 6-11

IF										// BLOCK1
  Global("#GEMPCHK","LOCALS",0)
  ReputationLT(%famsummoner%,8)							// MIRPEN 0 REP 1-7
  Global("#GMIRPEN","GLOBAL",0)
  Global("#GEMPOW","LOCALS",0)
  GlobalLT("#GPLALVL","GLOBAL",12)
  GlobalGT("#GPLALVL","GLOBAL",5)
  Global("#GFLVUP","GLOBAL",0)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GREPCHK","LOCALS",1)
    SetGlobal("#GEMPOW","LOCALS",6)
    ReallyForceSpellRES("WTPFLVP1",Myself)
    ReallyForceSpellRES("WTPFLVP3",Myself)
    ReallyForceSpellRES("WTPFLVP7",Myself)
    SetInterrupt(TRUE)
END

IF										// BLOCK2A
  Global("#GEMPCHK","LOCALS",0)
  ReputationLT(%famsummoner%,15)						// MIRPEN 0 REP 8-14
  ReputationGT(%famsummoner%,7)
  Global("#GMIRPEN","GLOBAL",0)
  Global("#GEMPOW","LOCALS",0)
  GlobalLT("#GPLALVL","GLOBAL",12)
  GlobalGT("#GPLALVL","GLOBAL",5)
  Global("#GFLVUP","GLOBAL",0)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GREPCHK","LOCALS",2)
    SetGlobal("#GEMPOW","LOCALS",7)
    ReallyForceSpellRES("WTPFLVP2",Myself)
    ReallyForceSpellRES("WTPFLVP3",Myself)
    ReallyForceSpellRES("WTPFLVP6",Myself)
    SetInterrupt(TRUE)
END

IF										// BLOCK2B
  Global("#GEMPCHK","LOCALS",0)
  ReputationLT(%famsummoner%,8)							// MIRPEN 1 REP 1-7
  Global("#GMIRPEN","GLOBAL",1)
  Global("#GEMPOW","LOCALS",0)
  GlobalLT("#GPLALVL","GLOBAL",12)
  GlobalGT("#GPLALVL","GLOBAL",5)
  Global("#GFLVUP","GLOBAL",0)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GREPCHK","LOCALS",3)
    SetGlobal("#GEMPOW","LOCALS",7)
    ReallyForceSpellRES("WTPFLVP2",Myself)
    ReallyForceSpellRES("WTPFLVP3",Myself)
    ReallyForceSpellRES("WTPFLVP6",Myself)
    SetInterrupt(TRUE)
END

IF										// BLOCK3A
  Global("#GEMPCHK","LOCALS",0)
  ReputationGT(%famsummoner%,14)						// MIRPEN 0 REP 15-20
  Global("#GMIRPEN","GLOBAL",0)
  Global("#GEMPOW","LOCALS",0)
  GlobalLT("#GPLALVL","GLOBAL",12)
  GlobalGT("#GPLALVL","GLOBAL",5)
  Global("#GFLVUP","GLOBAL",0)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GREPCHK","LOCALS",4)
    SetGlobal("#GEMPOW","LOCALS",8)
    ReallyForceSpellRES("WTPFLVP1",Myself)
    SetInterrupt(TRUE)
END

IF										// BLOCK3B
  Global("#GEMPCHK","LOCALS",0)
  ReputationLT(%famsummoner%,15)						// MIRPEN 1 REP 8-14
  ReputationGT(%famsummoner%,7)
  Global("#GMIRPEN","GLOBAL",1)
  Global("#GEMPOW","LOCALS",0)
  GlobalLT("#GPLALVL","GLOBAL",12)
  GlobalGT("#GPLALVL","GLOBAL",5)
  Global("#GFLVUP","GLOBAL",0)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GREPCHK","LOCALS",5)
    SetGlobal("#GEMPOW","LOCALS",8)
    ReallyForceSpellRES("WTPFLVP1",Myself)
    SetInterrupt(TRUE)
END

IF										// BLOCK3C
  Global("#GEMPCHK","LOCALS",0)
  ReputationLT(%famsummoner%,8)							// MIRPEN 2 REP 1-7
  Global("#GMIRPEN","GLOBAL",2)
  Global("#GEMPOW","LOCALS",0)
  GlobalLT("#GPLALVL","GLOBAL",12)
  GlobalGT("#GPLALVL","GLOBAL",5)
  Global("#GFLVUP","GLOBAL",0)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GREPCHK","LOCALS",6)
    SetGlobal("#GEMPOW","LOCALS",8)
    ReallyForceSpellRES("WTPFLVP1",Myself)
    SetInterrupt(TRUE)
END

IF										// BLOCK4A
  Global("#GEMPCHK","LOCALS",0)
  ReputationGT(%famsummoner%,14)						// MIRPEN 1 REP 15-20
  Global("#GMIRPEN","GLOBAL",1)
  Global("#GEMPOW","LOCALS",0)
  GlobalLT("#GPLALVL","GLOBAL",12)
  GlobalGT("#GPLALVL","GLOBAL",5)
  Global("#GFLVUP","GLOBAL",0)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GREPCHK","LOCALS",7)
    SetGlobal("#GEMPOW","LOCALS",9)
    ReallyForceSpellRES("WTPFLVP5",Myself)
    ReallyForceSpellRES("WTPFLVP6",Myself)
    SetInterrupt(TRUE)
END

IF										// BLOCK4B
  Global("#GEMPCHK","LOCALS",0)
  ReputationLT(%famsummoner%,15)						// MIRPEN 2 REP 8-14
  ReputationGT(%famsummoner%,7)
  Global("#GMIRPEN","GLOBAL",2)
  Global("#GEMPOW","LOCALS",0)
  GlobalLT("#GPLALVL","GLOBAL",12)
  GlobalGT("#GPLALVL","GLOBAL",5)
  Global("#GFLVUP","GLOBAL",0)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GREPCHK","LOCALS",8)
    SetGlobal("#GEMPOW","LOCALS",9)
    ReallyForceSpellRES("WTPFLVP5",Myself)
    ReallyForceSpellRES("WTPFLVP6",Myself)
    SetInterrupt(TRUE)
END

IF										// BLOCK5
  Global("#GEMPCHK","LOCALS",0)
  ReputationGT(%famsummoner%,14)						// MIRPEN 2 REP 15-20
  Global("#GMIRPEN","GLOBAL",2)
  Global("#GEMPOW","LOCALS",0)
  GlobalLT("#GPLALVL","GLOBAL",12)
  GlobalGT("#GPLALVL","GLOBAL",5)
  Global("#GFLVUP","GLOBAL",0)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GREPCHK","LOCALS",9)
    SetGlobal("#GEMPOW","LOCALS",10)
    ReallyForceSpellRES("WTPFLVP3",Myself)
    SetInterrupt(TRUE)
END

// LV 12-17

IF										// BLOCK1
  Global("#GEMPCHK","LOCALS",0)
  ReputationLT(%famsummoner%,8)							// MIRPEN 0 REP 1-7
  Global("#GMIRPEN","GLOBAL",0)
  Global("#GEMPOW","LOCALS",0)
  GlobalLT("#GPLALVL","GLOBAL",18)
  GlobalGT("#GPLALVL","GLOBAL",11)
  Global("#GFLVUP","GLOBAL",0)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GREPCHK","LOCALS",1)
    SetGlobal("#GEMPOW","LOCALS",11)
    ReallyForceSpellRES("WTPFLVP1",Myself)
    ReallyForceSpellRES("WTPFLVP1",Myself)
    ReallyForceSpellRES("WTPFLVP8",Myself)
    ReallyForceSpellRES("WTPFLVP6",Myself)
    SetInterrupt(TRUE)
END

IF										// BLOCK2A
  Global("#GEMPCHK","LOCALS",0)
  ReputationLT(%famsummoner%,15)						// MIRPEN 0 REP 8-14
  ReputationGT(%famsummoner%,7)
  Global("#GMIRPEN","GLOBAL",0)
  Global("#GEMPOW","LOCALS",0)
  GlobalLT("#GPLALVL","GLOBAL",18)
  GlobalGT("#GPLALVL","GLOBAL",11)
  Global("#GFLVUP","GLOBAL",0)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GREPCHK","LOCALS",2)
    SetGlobal("#GEMPOW","LOCALS",12)
    ReallyForceSpellRES("WTPFLVP1",Myself)
    ReallyForceSpellRES("WTPFLVP2",Myself)
    ReallyForceSpellRES("WTPFLVP7",Myself)
    ReallyForceSpellRES("WTPFLVP6",Myself)
    SetInterrupt(TRUE)
END

IF										// BLOCK2B
  Global("#GEMPCHK","LOCALS",0)
  ReputationLT(%famsummoner%,8)							// MIRPEN 1 REP 1-7
  Global("#GMIRPEN","GLOBAL",1)
  Global("#GEMPOW","LOCALS",0)
  GlobalLT("#GPLALVL","GLOBAL",18)
  GlobalGT("#GPLALVL","GLOBAL",11)
  Global("#GFLVUP","GLOBAL",0)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GREPCHK","LOCALS",3)
    SetGlobal("#GEMPOW","LOCALS",12)
    ReallyForceSpellRES("WTPFLVP1",Myself)
    ReallyForceSpellRES("WTPFLVP2",Myself)
    ReallyForceSpellRES("WTPFLVP7",Myself)
    ReallyForceSpellRES("WTPFLVP6",Myself)
    SetInterrupt(TRUE)
END

IF										// BLOCK3A
  Global("#GEMPCHK","LOCALS",0)
  ReputationGT(%famsummoner%,14)						// MIRPEN 0 REP 15-20
  Global("#GMIRPEN","GLOBAL",0)
  Global("#GEMPOW","LOCALS",0)
  GlobalLT("#GPLALVL","GLOBAL",18)
  GlobalGT("#GPLALVL","GLOBAL",11)
  Global("#GFLVUP","GLOBAL",0)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GREPCHK","LOCALS",4)
    SetGlobal("#GEMPOW","LOCALS",13)
    ReallyForceSpellRES("WTPFLVP1",Myself)
    ReallyForceSpellRES("WTPFLVP3",Myself)
    SetInterrupt(TRUE)
END

IF										// BLOCK3B
  Global("#GEMPCHK","LOCALS",0)
  ReputationLT(%famsummoner%,15)						// MIRPEN 1 REP 8-14
  ReputationGT(%famsummoner%,7)
  Global("#GMIRPEN","GLOBAL",1)
  Global("#GEMPOW","LOCALS",0)
  GlobalLT("#GPLALVL","GLOBAL",18)
  GlobalGT("#GPLALVL","GLOBAL",11)
  Global("#GFLVUP","GLOBAL",0)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GREPCHK","LOCALS",5)
    SetGlobal("#GEMPOW","LOCALS",13)
    ReallyForceSpellRES("WTPFLVP1",Myself)
    ReallyForceSpellRES("WTPFLVP3",Myself)
    SetInterrupt(TRUE)
END

IF										// BLOCK3C
  Global("#GEMPCHK","LOCALS",0)
  ReputationLT(%famsummoner%,8)							// MIRPEN 2 REP 1-7
  Global("#GMIRPEN","GLOBAL",2)
  Global("#GEMPOW","LOCALS",0)
  GlobalLT("#GPLALVL","GLOBAL",18)
  GlobalGT("#GPLALVL","GLOBAL",11)
  Global("#GFLVUP","GLOBAL",0)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GREPCHK","LOCALS",6)
    SetGlobal("#GEMPOW","LOCALS",13)
    ReallyForceSpellRES("WTPFLVP1",Myself)
    ReallyForceSpellRES("WTPFLVP3",Myself)
    SetInterrupt(TRUE)
END

IF										// BLOCK4A
  Global("#GEMPCHK","LOCALS",0)
  ReputationGT(%famsummoner%,14)						// MIRPEN 1 REP 15-20
  Global("#GMIRPEN","GLOBAL",1)
  Global("#GEMPOW","LOCALS",0)
  GlobalLT("#GPLALVL","GLOBAL",18)
  GlobalGT("#GPLALVL","GLOBAL",11)
  Global("#GFLVUP","GLOBAL",0)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GREPCHK","LOCALS",7)
    SetGlobal("#GEMPOW","LOCALS",14)
    ReallyForceSpellRES("WTPFLVP1",Myself)
    ReallyForceSpellRES("WTPFLVP4",Myself)
    SetInterrupt(TRUE)
END

IF										// BLOCK4B
  Global("#GEMPCHK","LOCALS",0)
  ReputationLT(%famsummoner%,15)						// MIRPEN 2 REP 8-14
  ReputationGT(%famsummoner%,7)
  Global("#GMIRPEN","GLOBAL",2)
  Global("#GEMPOW","LOCALS",0)
  GlobalLT("#GPLALVL","GLOBAL",18)
  GlobalGT("#GPLALVL","GLOBAL",11)
  Global("#GFLVUP","GLOBAL",0)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GREPCHK","LOCALS",8)
    SetGlobal("#GEMPOW","LOCALS",14)
    ReallyForceSpellRES("WTPFLVP1",Myself)
    ReallyForceSpellRES("WTPFLVP4",Myself)
    SetInterrupt(TRUE)
END

IF										// BLOCK5
  Global("#GEMPCHK","LOCALS",0)
  ReputationGT(%famsummoner%,14)						// MIRPEN 2 REP 15-20
  Global("#GMIRPEN","GLOBAL",2)
  Global("#GEMPOW","LOCALS",0)
  GlobalLT("#GPLALVL","GLOBAL",18)
  GlobalGT("#GPLALVL","GLOBAL",11)
  Global("#GFLVUP","GLOBAL",0)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GREPCHK","LOCALS",9)
    SetGlobal("#GEMPOW","LOCALS",15)
    ReallyForceSpellRES("WTPFLVP1",Myself)
    ReallyForceSpellRES("WTPFLVP6",Myself)
    SetInterrupt(TRUE)
END

// LV 18-23

IF										// BLOCK1
  Global("#GEMPCHK","LOCALS",0)
  ReputationLT(%famsummoner%,8)							// MIRPEN 0 REP 1-7
  Global("#GMIRPEN","GLOBAL",0)
  Global("#GEMPOW","LOCALS",0)
  GlobalLT("#GPLALVL","GLOBAL",24)
  GlobalGT("#GPLALVL","GLOBAL",17)
  Global("#GFLVUP","GLOBAL",0)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GREPCHK","LOCALS",1)
    SetGlobal("#GEMPOW","LOCALS",16)
    ReallyForceSpellRES("WTPFLVPE",Myself)
    ReallyForceSpellRES("WTPFLVP7",Myself)
    ReallyForceSpellRES("WTPFLVP6",Myself)
    SetInterrupt(TRUE)
END

IF										// BLOCK2A
  Global("#GEMPCHK","LOCALS",0)
  ReputationLT(%famsummoner%,15)						// MIRPEN 0 REP 8-14
  ReputationGT(%famsummoner%,7)
  Global("#GMIRPEN","GLOBAL",0)
  Global("#GEMPOW","LOCALS",0)
  GlobalLT("#GPLALVL","GLOBAL",24)
  GlobalGT("#GPLALVL","GLOBAL",17)
  Global("#GFLVUP","GLOBAL",0)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GREPCHK","LOCALS",2)
    SetGlobal("#GEMPOW","LOCALS",17)
    ReallyForceSpellRES("WTPFLVP1",Myself)
    ReallyForceSpellRES("WTPFLVP2",Myself)
    ReallyForceSpellRES("WTPFLVP3",Myself)
    ReallyForceSpellRES("WTPFLVP8",Myself)
    ReallyForceSpellRES("WTPFLVP6",Myself)
    SetInterrupt(TRUE)
END

IF										// BLOCK2B
  Global("#GEMPCHK","LOCALS",0)
  ReputationLT(%famsummoner%,8)							// MIRPEN 1 REP 1-7
  Global("#GMIRPEN","GLOBAL",1)
  Global("#GEMPOW","LOCALS",0)
  GlobalLT("#GPLALVL","GLOBAL",24)
  GlobalGT("#GPLALVL","GLOBAL",17)
  Global("#GFLVUP","GLOBAL",0)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GREPCHK","LOCALS",3)
    SetGlobal("#GEMPOW","LOCALS",17)
    ReallyForceSpellRES("WTPFLVP1",Myself)
    ReallyForceSpellRES("WTPFLVP2",Myself)
    ReallyForceSpellRES("WTPFLVP3",Myself)
    ReallyForceSpellRES("WTPFLVP8",Myself)
    ReallyForceSpellRES("WTPFLVP6",Myself)
    SetInterrupt(TRUE)
END

IF										// BLOCK3A
  Global("#GEMPCHK","LOCALS",0)
  ReputationGT(%famsummoner%,14)						// MIRPEN 0 REP 15-20
  Global("#GMIRPEN","GLOBAL",0)
  Global("#GEMPOW","LOCALS",0)
  GlobalLT("#GPLALVL","GLOBAL",24)
  GlobalGT("#GPLALVL","GLOBAL",17)
  Global("#GFLVUP","GLOBAL",0)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GREPCHK","LOCALS",4)
    SetGlobal("#GEMPOW","LOCALS",18)
    ReallyForceSpellRES("WTPFLVP1",Myself)
    ReallyForceSpellRES("WTPFLVP1",Myself)
    ReallyForceSpellRES("WTPFLVP7",Myself)
    SetInterrupt(TRUE)
END

IF										// BLOCK3B
  Global("#GEMPCHK","LOCALS",0)
  ReputationLT(%famsummoner%,15)						// MIRPEN 1 REP 8-14
  ReputationGT(%famsummoner%,7)
  Global("#GMIRPEN","GLOBAL",1)
  Global("#GEMPOW","LOCALS",0)
  GlobalLT("#GPLALVL","GLOBAL",24)
  GlobalGT("#GPLALVL","GLOBAL",17)
  Global("#GFLVUP","GLOBAL",0)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GREPCHK","LOCALS",5)
    SetGlobal("#GEMPOW","LOCALS",18)
    ReallyForceSpellRES("WTPFLVP1",Myself)
    ReallyForceSpellRES("WTPFLVP1",Myself)
    ReallyForceSpellRES("WTPFLVP7",Myself)
    SetInterrupt(TRUE)
END

IF										// BLOCK3C
  Global("#GEMPCHK","LOCALS",0)
  ReputationLT(%famsummoner%,8)							// MIRPEN 2 REP 1-7
  Global("#GMIRPEN","GLOBAL",2)
  Global("#GEMPOW","LOCALS",0)
  GlobalLT("#GPLALVL","GLOBAL",24)
  GlobalGT("#GPLALVL","GLOBAL",17)
  Global("#GFLVUP","GLOBAL",0)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GREPCHK","LOCALS",6)
    SetGlobal("#GEMPOW","LOCALS",18)
    ReallyForceSpellRES("WTPFLVP1",Myself)
    ReallyForceSpellRES("WTPFLVP1",Myself)
    ReallyForceSpellRES("WTPFLVP7",Myself)
    SetInterrupt(TRUE)
END

IF										// BLOCK4A
  Global("#GEMPCHK","LOCALS",0)
  ReputationGT(%famsummoner%,14)						// MIRPEN 1 REP 15-20
  Global("#GMIRPEN","GLOBAL",1)
  Global("#GEMPOW","LOCALS",0)
  GlobalLT("#GPLALVL","GLOBAL",24)
  GlobalGT("#GPLALVL","GLOBAL",17)
  Global("#GFLVUP","GLOBAL",0)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GREPCHK","LOCALS",7)
    SetGlobal("#GEMPOW","LOCALS",19)
    ReallyForceSpellRES("WTPFLVP1",Myself)
    ReallyForceSpellRES("WTPFLVP5",Myself)
    ReallyForceSpellRES("WTPFLVP7",Myself)
    ReallyForceSpellRES("WTPFLVP6",Myself)
    SetInterrupt(TRUE)
END

IF										// BLOCK4B
  Global("#GEMPCHK","LOCALS",0)
  ReputationLT(%famsummoner%,15)						// MIRPEN 2 REP 8-14
  ReputationGT(%famsummoner%,7)
  Global("#GMIRPEN","GLOBAL",2)
  Global("#GEMPOW","LOCALS",0)
  GlobalLT("#GPLALVL","GLOBAL",24)
  GlobalGT("#GPLALVL","GLOBAL",17)
  Global("#GFLVUP","GLOBAL",0)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GREPCHK","LOCALS",8)
    SetGlobal("#GEMPOW","LOCALS",19)
    ReallyForceSpellRES("WTPFLVP1",Myself)
    ReallyForceSpellRES("WTPFLVP5",Myself)
    ReallyForceSpellRES("WTPFLVP7",Myself)
    ReallyForceSpellRES("WTPFLVP6",Myself)
    SetInterrupt(TRUE)
END

IF										// BLOCK5
  Global("#GEMPCHK","LOCALS",0)
  ReputationGT(%famsummoner%,14)						// MIRPEN 2 REP 15-20
  Global("#GMIRPEN","GLOBAL",2)
  Global("#GEMPOW","LOCALS",0)
  GlobalLT("#GPLALVL","GLOBAL",24)
  GlobalGT("#GPLALVL","GLOBAL",17)
  Global("#GFLVUP","GLOBAL",0)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GREPCHK","LOCALS",9)
    SetGlobal("#GEMPOW","LOCALS",20)
    ReallyForceSpellRES("WTPFLVP1",Myself)
    ReallyForceSpellRES("WTPFLVP3",Myself)
    ReallyForceSpellRES("WTPFLVP7",Myself)
    SetInterrupt(TRUE)
END

// LV 24-29

IF										// BLOCK1
  Global("#GEMPCHK","LOCALS",0)
  ReputationLT(%famsummoner%,8)							// MIRPEN 0 REP 1-7
  Global("#GMIRPEN","GLOBAL",0)
  Global("#GEMPOW","LOCALS",0)
  GlobalLT("#GPLALVL","GLOBAL",30)
  GlobalGT("#GPLALVL","GLOBAL",23)
  Global("#GFLVUP","GLOBAL",0)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GREPCHK","LOCALS",1)
    SetGlobal("#GEMPOW","LOCALS",21)
    ReallyForceSpellRES("WTPFLVPE",Myself)
    ReallyForceSpellRES("WTPFLVP3",Myself)
    ReallyForceSpellRES("WTPFLVP9",Myself)
    SetInterrupt(TRUE)
END

IF										// BLOCK2A
  Global("#GEMPCHK","LOCALS",0)
  ReputationLT(%famsummoner%,15)						// MIRPEN 0 REP 8-14
  ReputationGT(%famsummoner%,7)
  Global("#GMIRPEN","GLOBAL",0)
  Global("#GEMPOW","LOCALS",0)
  GlobalLT("#GPLALVL","GLOBAL",30)
  GlobalGT("#GPLALVL","GLOBAL",23)
  Global("#GFLVUP","GLOBAL",0)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GREPCHK","LOCALS",2)
    SetGlobal("#GEMPOW","LOCALS",22)
    ReallyForceSpellRES("WTPFLVP1",Myself)
    ReallyForceSpellRES("WTPFLVP1",Myself)
    ReallyForceSpellRES("WTPFLVP2",Myself)
    ReallyForceSpellRES("WTPFLVP9",Myself)
    ReallyForceSpellRES("WTPFLVP7",Myself)
    SetInterrupt(TRUE)
END

IF										// BLOCK2B
  Global("#GEMPCHK","LOCALS",0)
  ReputationLT(%famsummoner%,8)							// MIRPEN 1 REP 1-7
  Global("#GMIRPEN","GLOBAL",1)
  Global("#GEMPOW","LOCALS",0)
  GlobalLT("#GPLALVL","GLOBAL",30)
  GlobalGT("#GPLALVL","GLOBAL",23)
  Global("#GFLVUP","GLOBAL",0)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GREPCHK","LOCALS",3)
    SetGlobal("#GEMPOW","LOCALS",22)
    ReallyForceSpellRES("WTPFLVP1",Myself)
    ReallyForceSpellRES("WTPFLVP1",Myself)
    ReallyForceSpellRES("WTPFLVP2",Myself)
    ReallyForceSpellRES("WTPFLVP9",Myself)
    ReallyForceSpellRES("WTPFLVP7",Myself)
    SetInterrupt(TRUE)
END

IF										// BLOCK3A
  Global("#GEMPCHK","LOCALS",0)
  ReputationGT(%famsummoner%,14)						// MIRPEN 0 REP 15-20
  Global("#GMIRPEN","GLOBAL",0)
  Global("#GEMPOW","LOCALS",0)
  GlobalLT("#GPLALVL","GLOBAL",30)
  GlobalGT("#GPLALVL","GLOBAL",23)
  Global("#GFLVUP","GLOBAL",0)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GREPCHK","LOCALS",4)
    SetGlobal("#GEMPOW","LOCALS",23)
    ReallyForceSpellRES("WTPFLVP1",Myself)
    ReallyForceSpellRES("WTPFLVP1",Myself)
    ReallyForceSpellRES("WTPFLVP3",Myself)
    ReallyForceSpellRES("WTPFLVP8",Myself)
    SetInterrupt(TRUE)
END

IF										// BLOCK3B
  Global("#GEMPCHK","LOCALS",0)
  ReputationLT(%famsummoner%,15)						// MIRPEN 1 REP 8-14
  ReputationGT(%famsummoner%,7)
  Global("#GMIRPEN","GLOBAL",1)
  Global("#GEMPOW","LOCALS",0)
  GlobalLT("#GPLALVL","GLOBAL",30)
  GlobalGT("#GPLALVL","GLOBAL",23)
  Global("#GFLVUP","GLOBAL",0)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GREPCHK","LOCALS",5)
    SetGlobal("#GEMPOW","LOCALS",23)
    ReallyForceSpellRES("WTPFLVP1",Myself)
    ReallyForceSpellRES("WTPFLVP1",Myself)
    ReallyForceSpellRES("WTPFLVP3",Myself)
    ReallyForceSpellRES("WTPFLVP8",Myself)
    SetInterrupt(TRUE)
END

IF										// BLOCK3C
  Global("#GEMPCHK","LOCALS",0)
  ReputationLT(%famsummoner%,8)							// MIRPEN 2 REP 1-7
  Global("#GMIRPEN","GLOBAL",2)
  Global("#GEMPOW","LOCALS",0)
  GlobalLT("#GPLALVL","GLOBAL",30)
  GlobalGT("#GPLALVL","GLOBAL",23)
  Global("#GFLVUP","GLOBAL",0)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GREPCHK","LOCALS",6)
    SetGlobal("#GEMPOW","LOCALS",23)
    ReallyForceSpellRES("WTPFLVP1",Myself)
    ReallyForceSpellRES("WTPFLVP1",Myself)
    ReallyForceSpellRES("WTPFLVP3",Myself)
    ReallyForceSpellRES("WTPFLVP8",Myself)
    SetInterrupt(TRUE)
END

IF										// BLOCK4A
  Global("#GEMPCHK","LOCALS",0)
  ReputationGT(%famsummoner%,14)						// MIRPEN 1 REP 15-20
  Global("#GMIRPEN","GLOBAL",1)
  Global("#GEMPOW","LOCALS",0)
  GlobalLT("#GPLALVL","GLOBAL",30)
  GlobalGT("#GPLALVL","GLOBAL",23)
  Global("#GFLVUP","GLOBAL",0)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GREPCHK","LOCALS",7)
    SetGlobal("#GEMPOW","LOCALS",24)
    ReallyForceSpellRES("WTPFLVP2",Myself)
    ReallyForceSpellRES("WTPFLVP5",Myself)
    ReallyForceSpellRES("WTPFLVP5",Myself)
    ReallyForceSpellRES("WTPFLVP9",Myself)
    SetInterrupt(TRUE)
END

IF										// BLOCK4B
  Global("#GEMPCHK","LOCALS",0)
  ReputationLT(%famsummoner%,15)						// MIRPEN 2 REP 8-14
  ReputationGT(%famsummoner%,7)
  Global("#GMIRPEN","GLOBAL",2)
  Global("#GEMPOW","LOCALS",0)
  GlobalLT("#GPLALVL","GLOBAL",30)
  GlobalGT("#GPLALVL","GLOBAL",23)
  Global("#GFLVUP","GLOBAL",0)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GREPCHK","LOCALS",8)
    SetGlobal("#GEMPOW","LOCALS",24)
    ReallyForceSpellRES("WTPFLVP2",Myself)
    ReallyForceSpellRES("WTPFLVP5",Myself)
    ReallyForceSpellRES("WTPFLVP5",Myself)
    ReallyForceSpellRES("WTPFLVP9",Myself)
    SetInterrupt(TRUE)
END

IF										// BLOCK5
  Global("#GEMPCHK","LOCALS",0)
  ReputationGT(%famsummoner%,14)						// MIRPEN 2 REP 15-20
  Global("#GMIRPEN","GLOBAL",2)
  Global("#GEMPOW","LOCALS",0)
  GlobalLT("#GPLALVL","GLOBAL",30)
  GlobalGT("#GPLALVL","GLOBAL",23)
  Global("#GFLVUP","GLOBAL",0)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GREPCHK","LOCALS",9)
    SetGlobal("#GEMPOW","LOCALS",25)
    ReallyForceSpellRES("WTPFLVP1",Myself)
    ReallyForceSpellRES("WTPFLVP1",Myself)
    ReallyForceSpellRES("WTPFLVP8",Myself)
    ReallyForceSpellRES("WTPFLVP6",Myself)
    SetInterrupt(TRUE)
END

// LV 30-35

IF										// BLOCK1
  Global("#GEMPCHK","LOCALS",0)
  ReputationLT(%famsummoner%,8)							// MIRPEN 0 REP 1-7
  Global("#GMIRPEN","GLOBAL",0)
  Global("#GEMPOW","LOCALS",0)
  GlobalLT("#GPLALVL","GLOBAL",36)
  GlobalGT("#GPLALVL","GLOBAL",29)
  Global("#GFLVUP","GLOBAL",0)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GREPCHK","LOCALS",1)
    SetGlobal("#GEMPOW","LOCALS",26)
    ReallyForceSpellRES("WTPFLVPE",Myself)
    ReallyForceSpellRES("WTPFLVP1",Myself)
    ReallyForceSpellRES("WTPFLVPA",Myself)
    ReallyForceSpellRES("WTPFLVP7",Myself)
    SetInterrupt(TRUE)
END

IF										// BLOCK2A
  Global("#GEMPCHK","LOCALS",0)
  ReputationLT(%famsummoner%,15)						// MIRPEN 0 REP 8-14
  ReputationGT(%famsummoner%,7)
  Global("#GMIRPEN","GLOBAL",0)
  Global("#GEMPOW","LOCALS",0)
  GlobalLT("#GPLALVL","GLOBAL",36)
  GlobalGT("#GPLALVL","GLOBAL",29)
  Global("#GFLVUP","GLOBAL",0)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GREPCHK","LOCALS",2)
    SetGlobal("#GEMPOW","LOCALS",27)
    ReallyForceSpellRES("WTPFLVPE",Myself)
    ReallyForceSpellRES("WTPFLVP2",Myself)
    ReallyForceSpellRES("WTPFLVP9",Myself)
    ReallyForceSpellRES("WTPFLVP6",Myself)
    SetInterrupt(TRUE)
END

IF										// BLOCK2B
  Global("#GEMPCHK","LOCALS",0)
  ReputationLT(%famsummoner%,8)							// MIRPEN 1 REP 1-7
  Global("#GMIRPEN","GLOBAL",1)
  Global("#GEMPOW","LOCALS",0)
  GlobalLT("#GPLALVL","GLOBAL",36)
  GlobalGT("#GPLALVL","GLOBAL",29)
  Global("#GFLVUP","GLOBAL",0)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GREPCHK","LOCALS",3)
    SetGlobal("#GEMPOW","LOCALS",27)
    ReallyForceSpellRES("WTPFLVPE",Myself)
    ReallyForceSpellRES("WTPFLVP2",Myself)
    ReallyForceSpellRES("WTPFLVP9",Myself)
    ReallyForceSpellRES("WTPFLVP6",Myself)
    SetInterrupt(TRUE)
END

IF										// BLOCK3A
  Global("#GEMPCHK","LOCALS",0)
  ReputationGT(%famsummoner%,14)						// MIRPEN 0 REP 15-20
  Global("#GMIRPEN","GLOBAL",0)
  Global("#GEMPOW","LOCALS",0)
  GlobalLT("#GPLALVL","GLOBAL",36)
  GlobalGT("#GPLALVL","GLOBAL",29)
  Global("#GFLVUP","GLOBAL",0)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GREPCHK","LOCALS",4)
    SetGlobal("#GEMPOW","LOCALS",28)
    ReallyForceSpellRES("WTPFLVPE",Myself)
    ReallyForceSpellRES("WTPFLVP3",Myself)
    ReallyForceSpellRES("WTPFLVP7",Myself)
    SetInterrupt(TRUE)
END

IF										// BLOCK3B
  Global("#GEMPCHK","LOCALS",0)
  ReputationLT(%famsummoner%,15)						// MIRPEN 1 REP 8-14
  ReputationGT(%famsummoner%,7)
  Global("#GMIRPEN","GLOBAL",1)
  Global("#GEMPOW","LOCALS",0)
  GlobalLT("#GPLALVL","GLOBAL",36)
  GlobalGT("#GPLALVL","GLOBAL",29)
  Global("#GFLVUP","GLOBAL",0)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GREPCHK","LOCALS",5)
    SetGlobal("#GEMPOW","LOCALS",28)
    ReallyForceSpellRES("WTPFLVPE",Myself)
    ReallyForceSpellRES("WTPFLVP3",Myself)
    ReallyForceSpellRES("WTPFLVP7",Myself)
    SetInterrupt(TRUE)
END

IF										// BLOCK3C
  Global("#GEMPCHK","LOCALS",0)
  ReputationLT(%famsummoner%,8)							// MIRPEN 2 REP 1-7
  Global("#GMIRPEN","GLOBAL",2)
  Global("#GEMPOW","LOCALS",0)
  GlobalLT("#GPLALVL","GLOBAL",36)
  GlobalGT("#GPLALVL","GLOBAL",29)
  Global("#GFLVUP","GLOBAL",0)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GREPCHK","LOCALS",6)
    SetGlobal("#GEMPOW","LOCALS",28)
    ReallyForceSpellRES("WTPFLVPE",Myself)
    ReallyForceSpellRES("WTPFLVP3",Myself)
    ReallyForceSpellRES("WTPFLVP7",Myself)
    SetInterrupt(TRUE)
END

IF										// BLOCK4A
  Global("#GEMPCHK","LOCALS",0)
  ReputationGT(%famsummoner%,14)						// MIRPEN 1 REP 15-20
  Global("#GMIRPEN","GLOBAL",1)
  Global("#GEMPOW","LOCALS",0)
  GlobalLT("#GPLALVL","GLOBAL",36)
  GlobalGT("#GPLALVL","GLOBAL",29)
  Global("#GFLVUP","GLOBAL",0)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GREPCHK","LOCALS",7)
    SetGlobal("#GEMPOW","LOCALS",29)
    ReallyForceSpellRES("WTPFLVPE",Myself)
    ReallyForceSpellRES("WTPFLVP4",Myself)
    ReallyForceSpellRES("WTPFLVP7",Myself)
    SetInterrupt(TRUE)
END

IF										// BLOCK4B
  Global("#GEMPCHK","LOCALS",0)
  ReputationLT(%famsummoner%,15)						// MIRPEN 2 REP 8-14
  ReputationGT(%famsummoner%,7)
  Global("#GMIRPEN","GLOBAL",2)
  Global("#GEMPOW","LOCALS",0)
  GlobalLT("#GPLALVL","GLOBAL",36)
  GlobalGT("#GPLALVL","GLOBAL",29)
  Global("#GFLVUP","GLOBAL",0)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GREPCHK","LOCALS",8)
    SetGlobal("#GEMPOW","LOCALS",29)
    ReallyForceSpellRES("WTPFLVPE",Myself)
    ReallyForceSpellRES("WTPFLVP4",Myself)
    ReallyForceSpellRES("WTPFLVP7",Myself)
    SetInterrupt(TRUE)
END

IF										// BLOCK5
  Global("#GEMPCHK","LOCALS",0)
  ReputationGT(%famsummoner%,14)						// MIRPEN 2 REP 15-20
  Global("#GMIRPEN","GLOBAL",2)
  Global("#GEMPOW","LOCALS",0)
  GlobalLT("#GPLALVL","GLOBAL",36)
  GlobalGT("#GPLALVL","GLOBAL",29)
  Global("#GFLVUP","GLOBAL",0)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GREPCHK","LOCALS",9)
    SetGlobal("#GEMPOW","LOCALS",30)
    ReallyForceSpellRES("WTPFLVPE",Myself)
    ReallyForceSpellRES("WTPFLVP7",Myself)
    ReallyForceSpellRES("WTPFLVP6",Myself)
    SetInterrupt(TRUE)
END

// LV 36-41

IF										// BLOCK1
  Global("#GEMPCHK","LOCALS",0)
  ReputationLT(%famsummoner%,8)							// MIRPEN 0 REP 1-7
  Global("#GMIRPEN","GLOBAL",0)
  Global("#GEMPOW","LOCALS",0)
  GlobalLT("#GPLALVL","GLOBAL",42)
  GlobalGT("#GPLALVL","GLOBAL",35)
  Global("#GFLVUP","GLOBAL",0)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GREPCHK","LOCALS",1)
    SetGlobal("#GEMPOW","LOCALS",31)
    ReallyForceSpellRES("WTPFLVPE",Myself)
    ReallyForceSpellRES("WTPFLVP1",Myself)
    ReallyForceSpellRES("WTPFLVP3",Myself)
    ReallyForceSpellRES("WTPFLVPB",Myself)
    ReallyForceSpellRES("WTPFLVP7",Myself)
    ReallyForceSpellRES("WTPFLVP6",Myself)
    SetInterrupt(TRUE)
END

IF										// BLOCK2A
  Global("#GEMPCHK","LOCALS",0)
  ReputationLT(%famsummoner%,15)						// MIRPEN 0 REP 8-14
  ReputationGT(%famsummoner%,7)
  Global("#GMIRPEN","GLOBAL",0)
  Global("#GEMPOW","LOCALS",0)
  GlobalLT("#GPLALVL","GLOBAL",42)
  GlobalGT("#GPLALVL","GLOBAL",35)
  Global("#GFLVUP","GLOBAL",0)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GREPCHK","LOCALS",2)
    SetGlobal("#GEMPOW","LOCALS",32)
    ReallyForceSpellRES("WTPFLVPE",Myself)
    ReallyForceSpellRES("WTPFLVP2",Myself)
    ReallyForceSpellRES("WTPFLVP3",Myself)
    ReallyForceSpellRES("WTPFLVPA",Myself)
    ReallyForceSpellRES("WTPFLVP7",Myself)
    SetInterrupt(TRUE)
END

IF										// BLOCK2B
  Global("#GEMPCHK","LOCALS",0)
  ReputationLT(%famsummoner%,8)							// MIRPEN 1 REP 1-7
  Global("#GMIRPEN","GLOBAL",1)
  Global("#GEMPOW","LOCALS",0)
  GlobalLT("#GPLALVL","GLOBAL",42)
  GlobalGT("#GPLALVL","GLOBAL",35)
  Global("#GFLVUP","GLOBAL",0)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GREPCHK","LOCALS",3)
    SetGlobal("#GEMPOW","LOCALS",32)
    ReallyForceSpellRES("WTPFLVPE",Myself)
    ReallyForceSpellRES("WTPFLVP2",Myself)
    ReallyForceSpellRES("WTPFLVP3",Myself)
    ReallyForceSpellRES("WTPFLVPA",Myself)
    ReallyForceSpellRES("WTPFLVP7",Myself)
    SetInterrupt(TRUE)
END

IF										// BLOCK3A
  Global("#GEMPCHK","LOCALS",0)
  ReputationGT(%famsummoner%,14)						// MIRPEN 0 REP 15-20
  Global("#GMIRPEN","GLOBAL",0)
  Global("#GEMPOW","LOCALS",0)
  GlobalLT("#GPLALVL","GLOBAL",42)
  GlobalGT("#GPLALVL","GLOBAL",35)
  Global("#GFLVUP","GLOBAL",0)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GREPCHK","LOCALS",4)
    SetGlobal("#GEMPOW","LOCALS",33)
    ReallyForceSpellRES("WTPFLVPE",Myself)
    ReallyForceSpellRES("WTPFLVP1",Myself)
    ReallyForceSpellRES("WTPFLVP9",Myself)
    SetInterrupt(TRUE)
END

IF										// BLOCK3B
  Global("#GEMPCHK","LOCALS",0)
  ReputationLT(%famsummoner%,15)						// MIRPEN 1 REP 8-14
  ReputationGT(%famsummoner%,7)
  Global("#GMIRPEN","GLOBAL",1)
  Global("#GEMPOW","LOCALS",0)
  GlobalLT("#GPLALVL","GLOBAL",42)
  GlobalGT("#GPLALVL","GLOBAL",35)
  Global("#GFLVUP","GLOBAL",0)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GREPCHK","LOCALS",5)
    SetGlobal("#GEMPOW","LOCALS",33)
    ReallyForceSpellRES("WTPFLVPE",Myself)
    ReallyForceSpellRES("WTPFLVP1",Myself)
    ReallyForceSpellRES("WTPFLVP9",Myself)
    SetInterrupt(TRUE)
END

IF										// BLOCK3C
  Global("#GEMPCHK","LOCALS",0)
  ReputationLT(%famsummoner%,8)							// MIRPEN 2 REP 1-7
  Global("#GMIRPEN","GLOBAL",2)
  Global("#GEMPOW","LOCALS",0)
  GlobalLT("#GPLALVL","GLOBAL",42)
  GlobalGT("#GPLALVL","GLOBAL",35)
  Global("#GFLVUP","GLOBAL",0)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GREPCHK","LOCALS",6)
    SetGlobal("#GEMPOW","LOCALS",33)
    ReallyForceSpellRES("WTPFLVPE",Myself)
    ReallyForceSpellRES("WTPFLVP1",Myself)
    ReallyForceSpellRES("WTPFLVP9",Myself)
    SetInterrupt(TRUE)
END

IF										// BLOCK4A
  Global("#GEMPCHK","LOCALS",0)
  ReputationGT(%famsummoner%,14)						// MIRPEN 1 REP 15-20
  Global("#GMIRPEN","GLOBAL",1)
  Global("#GEMPOW","LOCALS",0)
  GlobalLT("#GPLALVL","GLOBAL",42)
  GlobalGT("#GPLALVL","GLOBAL",35)
  Global("#GFLVUP","GLOBAL",0)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GREPCHK","LOCALS",7)
    SetGlobal("#GEMPOW","LOCALS",34)
    ReallyForceSpellRES("WTPFLVPE",Myself)
    ReallyForceSpellRES("WTPFLVP5",Myself)
    ReallyForceSpellRES("WTPFLVP9",Myself)
    ReallyForceSpellRES("WTPFLVP6",Myself)
    SetInterrupt(TRUE)
END

IF										// BLOCK4B
  Global("#GEMPCHK","LOCALS",0)
  ReputationLT(%famsummoner%,15)						// MIRPEN 2 REP 8-14
  ReputationGT(%famsummoner%,7)
  Global("#GMIRPEN","GLOBAL",2)
  Global("#GEMPOW","LOCALS",0)
  GlobalLT("#GPLALVL","GLOBAL",42)
  GlobalGT("#GPLALVL","GLOBAL",35)
  Global("#GFLVUP","GLOBAL",0)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GREPCHK","LOCALS",8)
    SetGlobal("#GEMPOW","LOCALS",34)
    ReallyForceSpellRES("WTPFLVPE",Myself)
    ReallyForceSpellRES("WTPFLVP5",Myself)
    ReallyForceSpellRES("WTPFLVP9",Myself)
    ReallyForceSpellRES("WTPFLVP6",Myself)
    SetInterrupt(TRUE)
END

IF										// BLOCK5
  Global("#GEMPCHK","LOCALS",0)
  ReputationGT(%famsummoner%,14)						// MIRPEN 2 REP 15-20
  Global("#GMIRPEN","GLOBAL",2)
  Global("#GEMPOW","LOCALS",0)
  GlobalLT("#GPLALVL","GLOBAL",42)
  GlobalGT("#GPLALVL","GLOBAL",35)
  Global("#GFLVUP","GLOBAL",0)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GREPCHK","LOCALS",9)
    SetGlobal("#GEMPOW","LOCALS",35)
    ReallyForceSpellRES("WTPFLVPE",Myself)
    ReallyForceSpellRES("WTPFLVP3",Myself)
    ReallyForceSpellRES("WTPFLVP9",Myself)
    SetInterrupt(TRUE)
END

// LV 42-47

IF										// BLOCK1
  Global("#GEMPCHK","LOCALS",0)
  ReputationLT(%famsummoner%,8)							// MIRPEN 0 REP 1-7
  Global("#GMIRPEN","GLOBAL",0)
  Global("#GEMPOW","LOCALS",0)
  GlobalLT("#GPLALVL","GLOBAL",48)
  GlobalGT("#GPLALVL","GLOBAL",41)
  Global("#GFLVUP","GLOBAL",0)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GREPCHK","LOCALS",1)
    SetGlobal("#GEMPOW","LOCALS",36)
    ReallyForceSpellRES("WTPFLVPE",Myself)
    ReallyForceSpellRES("WTPFLVP1",Myself)
    ReallyForceSpellRES("WTPFLVP1",Myself)
    ReallyForceSpellRES("WTPFLVPA",Myself)
    ReallyForceSpellRES("WTPFLVPB",Myself)
    SetInterrupt(TRUE)
END

IF										// BLOCK2A
  Global("#GEMPCHK","LOCALS",0)
  ReputationLT(%famsummoner%,15)						// MIRPEN 0 REP 8-14
  ReputationGT(%famsummoner%,7)
  Global("#GMIRPEN","GLOBAL",0)
  Global("#GEMPOW","LOCALS",0)
  GlobalLT("#GPLALVL","GLOBAL",48)
  GlobalGT("#GPLALVL","GLOBAL",41)
  Global("#GFLVUP","GLOBAL",0)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GREPCHK","LOCALS",2)
    SetGlobal("#GEMPOW","LOCALS",37)
    ReallyForceSpellRES("WTPFLVPE",Myself)
    ReallyForceSpellRES("WTPFLVP1",Myself)
    ReallyForceSpellRES("WTPFLVP2",Myself)
    ReallyForceSpellRES("WTPFLVPB",Myself)
    ReallyForceSpellRES("WTPFLVP8",Myself)
    SetInterrupt(TRUE)
END

IF										// BLOCK2B
  Global("#GEMPCHK","LOCALS",0)
  ReputationLT(%famsummoner%,8)							// MIRPEN 1 REP 1-7
  Global("#GMIRPEN","GLOBAL",1)
  Global("#GEMPOW","LOCALS",0)
  GlobalLT("#GPLALVL","GLOBAL",48)
  GlobalGT("#GPLALVL","GLOBAL",41)
  Global("#GFLVUP","GLOBAL",0)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GREPCHK","LOCALS",3)
    SetGlobal("#GEMPOW","LOCALS",37)
    ReallyForceSpellRES("WTPFLVPE",Myself)
    ReallyForceSpellRES("WTPFLVP1",Myself)
    ReallyForceSpellRES("WTPFLVP2",Myself)
    ReallyForceSpellRES("WTPFLVPB",Myself)
    ReallyForceSpellRES("WTPFLVP8",Myself)
    SetInterrupt(TRUE)
END

IF										// BLOCK3A
  Global("#GEMPCHK","LOCALS",0)
  ReputationGT(%famsummoner%,14)						// MIRPEN 0 REP 15-20
  Global("#GMIRPEN","GLOBAL",0)
  Global("#GEMPOW","LOCALS",0)
  GlobalLT("#GPLALVL","GLOBAL",48)
  GlobalGT("#GPLALVL","GLOBAL",41)
  Global("#GFLVUP","GLOBAL",0)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GREPCHK","LOCALS",4)
    SetGlobal("#GEMPOW","LOCALS",38)
    ReallyForceSpellRES("WTPFLVPE",Myself)
    ReallyForceSpellRES("WTPFLVP1",Myself)
    ReallyForceSpellRES("WTPFLVP3",Myself)
    ReallyForceSpellRES("WTPFLVPA",Myself)
    ReallyForceSpellRES("WTPFLVP6",Myself)
    SetInterrupt(TRUE)
END

IF										// BLOCK3B
  Global("#GEMPCHK","LOCALS",0)
  ReputationLT(%famsummoner%,15)						// MIRPEN 1 REP 8-14
  ReputationGT(%famsummoner%,7)
  Global("#GMIRPEN","GLOBAL",1)
  Global("#GEMPOW","LOCALS",0)
  GlobalLT("#GPLALVL","GLOBAL",48)
  GlobalGT("#GPLALVL","GLOBAL",41)
  Global("#GFLVUP","GLOBAL",0)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GREPCHK","LOCALS",5)
    SetGlobal("#GEMPOW","LOCALS",38)
    ReallyForceSpellRES("WTPFLVPE",Myself)
    ReallyForceSpellRES("WTPFLVP1",Myself)
    ReallyForceSpellRES("WTPFLVP3",Myself)
    ReallyForceSpellRES("WTPFLVPA",Myself)
    ReallyForceSpellRES("WTPFLVP6",Myself)
    SetInterrupt(TRUE)
END

IF										// BLOCK3C
  Global("#GEMPCHK","LOCALS",0)
  ReputationLT(%famsummoner%,8)							// MIRPEN 2 REP 1-7
  Global("#GMIRPEN","GLOBAL",2)
  Global("#GEMPOW","LOCALS",0)
  GlobalLT("#GPLALVL","GLOBAL",48)
  GlobalGT("#GPLALVL","GLOBAL",41)
  Global("#GFLVUP","GLOBAL",0)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GREPCHK","LOCALS",6)
    SetGlobal("#GEMPOW","LOCALS",38)
    ReallyForceSpellRES("WTPFLVPE",Myself)
    ReallyForceSpellRES("WTPFLVP1",Myself)
    ReallyForceSpellRES("WTPFLVP3",Myself)
    ReallyForceSpellRES("WTPFLVPA",Myself)
    ReallyForceSpellRES("WTPFLVP6",Myself)
    SetInterrupt(TRUE)
END

IF										// BLOCK4A
  Global("#GEMPCHK","LOCALS",0)
  ReputationGT(%famsummoner%,14)						// MIRPEN 1 REP 15-20
  Global("#GMIRPEN","GLOBAL",1)
  Global("#GEMPOW","LOCALS",0)
  GlobalLT("#GPLALVL","GLOBAL",48)
  GlobalGT("#GPLALVL","GLOBAL",41)
  Global("#GFLVUP","GLOBAL",0)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GREPCHK","LOCALS",7)
    SetGlobal("#GEMPOW","LOCALS",39)
    ReallyForceSpellRES("WTPFLVPE",Myself)
    ReallyForceSpellRES("WTPFLVP3",Myself)
    ReallyForceSpellRES("WTPFLVP5",Myself)
    ReallyForceSpellRES("WTPFLVPA",Myself)
    ReallyForceSpellRES("WTPFLVP7",Myself)
    SetInterrupt(TRUE)
END

IF										// BLOCK4B
  Global("#GEMPCHK","LOCALS",0)
  ReputationLT(%famsummoner%,15)						// MIRPEN 2 REP 8-14
  ReputationGT(%famsummoner%,7)
  Global("#GMIRPEN","GLOBAL",2)
  Global("#GEMPOW","LOCALS",0)
  GlobalLT("#GPLALVL","GLOBAL",48)
  GlobalGT("#GPLALVL","GLOBAL",41)
  Global("#GFLVUP","GLOBAL",0)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GREPCHK","LOCALS",8)
    SetGlobal("#GEMPOW","LOCALS",39)
    ReallyForceSpellRES("WTPFLVPE",Myself)
    ReallyForceSpellRES("WTPFLVP3",Myself)
    ReallyForceSpellRES("WTPFLVP5",Myself)
    ReallyForceSpellRES("WTPFLVPA",Myself)
    ReallyForceSpellRES("WTPFLVP7",Myself)
    SetInterrupt(TRUE)
END

IF										// BLOCK5
  Global("#GEMPCHK","LOCALS",0)
  ReputationGT(%famsummoner%,14)						// MIRPEN 2 REP 15-20
  Global("#GMIRPEN","GLOBAL",2)
  Global("#GEMPOW","LOCALS",0)
  GlobalLT("#GPLALVL","GLOBAL",48)
  GlobalGT("#GPLALVL","GLOBAL",41)
  Global("#GFLVUP","GLOBAL",0)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GREPCHK","LOCALS",9)
    SetGlobal("#GEMPOW","LOCALS",40)
    ReallyForceSpellRES("WTPFLVPE",Myself)
    ReallyForceSpellRES("WTPFLVP1",Myself)
    ReallyForceSpellRES("WTPFLVPA",Myself)
    ReallyForceSpellRES("WTPFLVP7",Myself)
    SetInterrupt(TRUE)
END

// LV 48+

IF										// BLOCK1
  Global("#GEMPCHK","LOCALS",0)
  ReputationLT(%famsummoner%,8)							// MIRPEN 0 REP 1-7
  Global("#GMIRPEN","GLOBAL",0)
  Global("#GEMPOW","LOCALS",0)
  GlobalGT("#GPLALVL","GLOBAL",47)
  Global("#GFLVUP","GLOBAL",0)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GREPCHK","LOCALS",1)
    SetGlobal("#GEMPOW","LOCALS",41)
    ReallyForceSpellRES("WTPFLVPE",Myself)
    ReallyForceSpellRES("WTPFLVPE",Myself)
    ReallyForceSpellRES("WTPFLVPD",Myself)
    ReallyForceSpellRES("WTPFLVP6",Myself)
    SetInterrupt(TRUE)
END

IF										// BLOCK2A
  Global("#GEMPCHK","LOCALS",0)
  ReputationLT(%famsummoner%,15)						// MIRPEN 0 REP 8-14
  ReputationGT(%famsummoner%,7)
  Global("#GMIRPEN","GLOBAL",0)
  Global("#GEMPOW","LOCALS",0)
  GlobalGT("#GPLALVL","GLOBAL",47)
  Global("#GFLVUP","GLOBAL",0)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GREPCHK","LOCALS",2)
    SetGlobal("#GEMPOW","LOCALS",42)
    ReallyForceSpellRES("WTPFLVPE",Myself)
    ReallyForceSpellRES("WTPFLVP1",Myself)
    ReallyForceSpellRES("WTPFLVP2",Myself)
    ReallyForceSpellRES("WTPFLVP3",Myself)
    ReallyForceSpellRES("WTPFLVPB",Myself)
    ReallyForceSpellRES("WTPFLVPA",Myself)
    SetInterrupt(TRUE)
END

IF										// BLOCK2B
  Global("#GEMPCHK","LOCALS",0)
  ReputationLT(%famsummoner%,8)							// MIRPEN 1 REP 1-7
  Global("#GMIRPEN","GLOBAL",1)
  Global("#GEMPOW","LOCALS",0)
  GlobalGT("#GPLALVL","GLOBAL",47)
  Global("#GFLVUP","GLOBAL",0)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GREPCHK","LOCALS",3)
    SetGlobal("#GEMPOW","LOCALS",42)
    ReallyForceSpellRES("WTPFLVPE",Myself)
    ReallyForceSpellRES("WTPFLVP1",Myself)
    ReallyForceSpellRES("WTPFLVP2",Myself)
    ReallyForceSpellRES("WTPFLVP3",Myself)
    ReallyForceSpellRES("WTPFLVPB",Myself)
    ReallyForceSpellRES("WTPFLVPA",Myself)
    SetInterrupt(TRUE)
END

IF										// BLOCK3A
  Global("#GEMPCHK","LOCALS",0)
  ReputationGT(%famsummoner%,14)						// MIRPEN 0 REP 15-20
  Global("#GMIRPEN","GLOBAL",0)
  Global("#GEMPOW","LOCALS",0)
  GlobalGT("#GPLALVL","GLOBAL",47)
  Global("#GFLVUP","GLOBAL",0)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GREPCHK","LOCALS",4)
    SetGlobal("#GEMPOW","LOCALS",43)
    ReallyForceSpellRES("WTPFLVPE",Myself)
    ReallyForceSpellRES("WTPFLVP1",Myself)
    ReallyForceSpellRES("WTPFLVP1",Myself)
    ReallyForceSpellRES("WTPFLVPB",Myself)
    ReallyForceSpellRES("WTPFLVP7",Myself)
    ReallyForceSpellRES("WTPFLVP6",Myself)
    SetInterrupt(TRUE)
END

IF										// BLOCK3B
  Global("#GEMPCHK","LOCALS",0)
  ReputationLT(%famsummoner%,15)						// MIRPEN 1 REP 8-14
  ReputationGT(%famsummoner%,7)
  Global("#GMIRPEN","GLOBAL",1)
  Global("#GEMPOW","LOCALS",0)
  GlobalGT("#GPLALVL","GLOBAL",47)
  Global("#GFLVUP","GLOBAL",0)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GREPCHK","LOCALS",5)
    SetGlobal("#GEMPOW","LOCALS",43)
    ReallyForceSpellRES("WTPFLVPE",Myself)
    ReallyForceSpellRES("WTPFLVP1",Myself)
    ReallyForceSpellRES("WTPFLVP1",Myself)
    ReallyForceSpellRES("WTPFLVPB",Myself)
    ReallyForceSpellRES("WTPFLVP7",Myself)
    ReallyForceSpellRES("WTPFLVP6",Myself)
    SetInterrupt(TRUE)
END

IF										// BLOCK3C
  Global("#GEMPCHK","LOCALS",0)
  ReputationLT(%famsummoner%,8)							// MIRPEN 2 REP 1-7
  Global("#GMIRPEN","GLOBAL",2)
  Global("#GEMPOW","LOCALS",0)
  GlobalGT("#GPLALVL","GLOBAL",47)
  Global("#GFLVUP","GLOBAL",0)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GREPCHK","LOCALS",6)
    SetGlobal("#GEMPOW","LOCALS",43)
    ReallyForceSpellRES("WTPFLVPE",Myself)
    ReallyForceSpellRES("WTPFLVP1",Myself)
    ReallyForceSpellRES("WTPFLVP1",Myself)
    ReallyForceSpellRES("WTPFLVPB",Myself)
    ReallyForceSpellRES("WTPFLVP7",Myself)
    ReallyForceSpellRES("WTPFLVP6",Myself)
    SetInterrupt(TRUE)
END

IF										// BLOCK4A
  Global("#GEMPCHK","LOCALS",0)
  ReputationGT(%famsummoner%,14)						// MIRPEN 1 REP 15-20
  Global("#GMIRPEN","GLOBAL",1)
  Global("#GEMPOW","LOCALS",0)
  GlobalGT("#GPLALVL","GLOBAL",47)
  Global("#GFLVUP","GLOBAL",0)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GREPCHK","LOCALS",7)
    SetGlobal("#GEMPOW","LOCALS",44)
    ReallyForceSpellRES("WTPFLVPE",Myself)
    ReallyForceSpellRES("WTPFLVP1",Myself)
    ReallyForceSpellRES("WTPFLVP5",Myself)
    ReallyForceSpellRES("WTPFLVPB",Myself)
    ReallyForceSpellRES("WTPFLVP8",Myself)
    SetInterrupt(TRUE)
END

IF										// BLOCK4B
  Global("#GEMPCHK","LOCALS",0)
  ReputationLT(%famsummoner%,15)						// MIRPEN 2 REP 8-14
  ReputationGT(%famsummoner%,7)
  Global("#GMIRPEN","GLOBAL",2)
  Global("#GEMPOW","LOCALS",0)
  GlobalGT("#GPLALVL","GLOBAL",47)
  Global("#GFLVUP","GLOBAL",0)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GREPCHK","LOCALS",8)
    SetGlobal("#GEMPOW","LOCALS",44)
    ReallyForceSpellRES("WTPFLVPE",Myself)
    ReallyForceSpellRES("WTPFLVP1",Myself)
    ReallyForceSpellRES("WTPFLVP5",Myself)
    ReallyForceSpellRES("WTPFLVPB",Myself)
    ReallyForceSpellRES("WTPFLVP8",Myself)
    SetInterrupt(TRUE)
END

IF										// BLOCK5
  Global("#GEMPCHK","LOCALS",0)
  ReputationGT(%famsummoner%,14)						// MIRPEN 2 REP 15-20
  Global("#GMIRPEN","GLOBAL",2)
  Global("#GEMPOW","LOCALS",0)
  GlobalGT("#GPLALVL","GLOBAL",47)
  Global("#GFLVUP","GLOBAL",0)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GREPCHK","LOCALS",9)
    SetGlobal("#GEMPOW","LOCALS",45)
    ReallyForceSpellRES("WTPFLVPE",Myself)
    ReallyForceSpellRES("WTPFLVP1",Myself)
    ReallyForceSpellRES("WTPFLVP3",Myself)
    ReallyForceSpellRES("WTPFLVPB",Myself)
    ReallyForceSpellRES("WTPFLVP7",Myself)
    ReallyForceSpellRES("WTPFLVP6",Myself)
    SetInterrupt(TRUE)
END

///////////////////////
///Level up with PC ///
///////////////////////

IF
  !GlobalsEqual("#GFAMLVL","#GPLALVL")
  Global("#GFLVUP","GLOBAL",1)
  Global("WTPFAMCE","GLOBAL",2)
THEN
  RESPONSE #100
    MoveViewObject(Myself,INSTANT)
    LockScroll()
    SetGlobal("#GFLVUP","GLOBAL",2)
    AddGlobals("#GFLVUP","#GFAMLVL")
END

IF
  GlobalsEqual("#GFAMLVL","#GPLALVL")
  GlobalGT("#GFLVUP","GLOBAL",2)
THEN
  RESPONSE #100
    UnlockScroll()
    SetGlobal("#GFLVUP","GLOBAL",0)
    SetGlobal("#GEMPCHK","LOCALS",1)
    SetGlobal("#GEMPLUP","LOCALS",1)
    SetGlobal("#GNAMCHG","LOCALS",0)
END

IF
  GlobalsEqual("#GFAMLVL","#GPLALVL")
  Global("#GFLVUP","GLOBAL",1)
THEN
  RESPONSE #100
    SetGlobal("#GFLVUP","GLOBAL",0)
END

//////////////////////
///Level up script ///
//////////////////////

IF
  !GlobalsEqual("#GFAMLVL","#GPLALVL")
  GlobalLT("#GFAMLVL","GLOBAL",1)
  Global("#GFLVUP","GLOBAL",2)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetName(@119)
    AddXPObject(Myself,2000)
    ApplySpellRES("WTPFMLV0",Myself)
    ApplySpellRES("WTPFMLVL",Myself)
    ApplySpellRES("WTPFMLVE",Myself)
    Wait(1)
    DisplayStringNoName(Myself,@40)
    DisplayStringNoName(Myself,@47)
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon2",Myself))
    SetGlobal("#GFAMLVL","GLOBAL",1)
    SetGlobal("#GFLVUP","GLOBAL",3)
    SetInterrupt(TRUE)
    Continue()
END

IF
  !GlobalsEqual("#GFAMLVL","#GPLALVL")
  GlobalLT("#GFAMLVL","GLOBAL",2)
  Global("#GFLVUP","GLOBAL",3)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetName(@120)
    AddXPObject(Myself,2000)
    ApplySpellRES("WTPFMLV0",Myself)
    ApplySpellRES("WTPFMLVL",Myself)
    ApplySpellRES("WTPFMLV9",Myself)
    ApplySpellRES("WTPFMLVA",Myself)
    ApplySpellRES("WTPFMLVB",Myself)
    ApplySpellRES("WTPFMLVC",Myself)
    ApplySpellRES("WTPFMLVD",Myself)
    ApplySpellRES("WTPFMLVE",Myself)
    AddSpecialAbility("WTPIN03")  // Horror
    Wait(1)
    DisplayStringNoName(Myself,@40)
    DisplayStringNoName(Myself,@36) // ST UP
    DisplayStringNoName(Myself,@47)
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon2",Myself))
    SetGlobal("#GFAMLVL","GLOBAL",2)
    SetGlobal("#GFLVUP","GLOBAL",4)
    SetInterrupt(TRUE)
    Continue()
END

IF
  !GlobalsEqual("#GFAMLVL","#GPLALVL")
  GlobalLT("#GFAMLVL","GLOBAL",3)
  Global("#GFLVUP","GLOBAL",4)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetName(@121)
    AddXPObject(Myself,4000)
    ApplySpellRES("WTPFMLV0",Myself)
    ApplySpellRES("WTPFMLVL",Myself)
    ApplySpellRES("WTPFMLVE",Myself)
    ApplySpellRES("WTPFMLV1",Myself)  // AC +1
    Wait(1)
    DisplayStringNoName(Myself,@40)
    DisplayStringNoName(Myself,@33)
    DisplayStringNoName(Myself,@47)
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon2",Myself))
    SetGlobal("#GFAMLVL","GLOBAL",3)
    SetGlobal("#GFLVUP","GLOBAL",5)
    SetInterrupt(TRUE)
    Continue()
END

IF
  !GlobalsEqual("#GFAMLVL","#GPLALVL")
  GlobalLT("#GFAMLVL","GLOBAL",4)
  Global("#GFLVUP","GLOBAL",5)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetName(@122)
    AddXPObject(Myself,8000)
    ApplySpellRES("WTPFMLV0",Myself)
    ApplySpellRES("WTPFMLV4",Myself)
    ApplySpellRES("WTPFMLVL",Myself)
    ApplySpellRES("WTPFMLV9",Myself)
    ApplySpellRES("WTPFMLV9",Myself)
    ApplySpellRES("WTPFMLVA",Myself)
    ApplySpellRES("WTPFMLVA",Myself)
    ApplySpellRES("WTPFMLVB",Myself)
    ApplySpellRES("WTPFMLVB",Myself)
    ApplySpellRES("WTPFMLVC",Myself)
    ApplySpellRES("WTPFMLVC",Myself)
    ApplySpellRES("WTPFMLVC",Myself)
    ApplySpellRES("WTPFMLVD",Myself)
    ApplySpellRES("WTPFMLVD",Myself)
    ApplySpellRES("WTPFMLVE",Myself)
    ApplySpellRES("WTPFQUAA",Myself) // +1
    Wait(1)
    DisplayStringNoName(Myself,@40)
    DisplayStringNoName(Myself,@25)
    DisplayStringNoName(Myself,@35)
    DisplayStringNoName(Myself,@36) // ST UP
    DisplayStringNoName(Myself,@47)
    EquipMostDamagingMelee()
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon2",Myself))
    SetGlobal("#GFAMLVL","GLOBAL",4)
    SetGlobal("#GFLVUP","GLOBAL",6)
    SetInterrupt(TRUE)
    Continue()
END

IF
  !GlobalsEqual("#GFAMLVL","#GPLALVL")
  GlobalLT("#GFAMLVL","GLOBAL",5)
  Global("#GFLVUP","GLOBAL",6)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetName(@123)
    AddXPObject(Myself,16000)
    ApplySpellRES("WTPFMLV0",Myself)
    ApplySpellRES("WTPFMLV4",Myself)
    ApplySpellRES("WTPFMLVL",Myself)
    ApplySpellRES("WTPFMLVE",Myself)
    AddSpecialAbility("WTPIN16")  // Invisibility
    Wait(1)
    DisplayStringNoName(Myself,@40)
    DisplayStringNoName(Myself,@35)
    DisplayStringNoName(Myself,@47)
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon2",Myself))
    SetGlobal("#GFAMLVL","GLOBAL",5)
    SetGlobal("#GFLVUP","GLOBAL",7)
    SetInterrupt(TRUE)
    Continue()
END

IF
  !GlobalsEqual("#GFAMLVL","#GPLALVL")
  GlobalLT("#GFAMLVL","GLOBAL",6)
  Global("#GFLVUP","GLOBAL",7)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetName(@124)
    AddXPObject(Myself,32000)
    ApplySpellRES("WTPFMLV0",Myself)
    ApplySpellRES("WTPFMLV4",Myself)
    ApplySpellRES("WTPFMLVL",Myself)
    ApplySpellRES("WTPFMLV9",Myself)
    ApplySpellRES("WTPFMLVA",Myself)
    ApplySpellRES("WTPFMLVB",Myself)
    ApplySpellRES("WTPFMLVC",Myself)
    ApplySpellRES("WTPFMLVD",Myself)
    ApplySpellRES("WTPFMLVE",Myself)
    Wait(1)
    DisplayStringNoName(Myself,@40)
    DisplayStringNoName(Myself,@35)
    DisplayStringNoName(Myself,@36) // ST UP
    DisplayStringNoName(Myself,@47)
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon2",Myself))
    SetGlobal("#GFAMLVL","GLOBAL",6)
    SetGlobal("#GFLVUP","GLOBAL",8)
    SetInterrupt(TRUE)
    Continue()
END

IF
  !GlobalsEqual("#GFAMLVL","#GPLALVL")
  GlobalLT("#GFAMLVL","GLOBAL",7)
  Global("#GFLVUP","GLOBAL",8)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetName(@125)
    AddXPObject(Myself,61000)
    ApplySpellRES("WTPFMLV0",Myself)
    ApplySpellRES("WTPFMLV4",Myself)
    ApplySpellRES("WTPFMLVL",Myself)
    ApplySpellRES("WTPFMLVE",Myself)
    Wait(1)
    DisplayStringNoName(Myself,@40)
    DisplayStringNoName(Myself,@35)
    DisplayStringNoName(Myself,@47)
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon2",Myself))
    SetGlobal("#GFAMLVL","GLOBAL",7)
    SetGlobal("#GFLVUP","GLOBAL",9)
    SetInterrupt(TRUE)
    Continue()
END

IF
  !GlobalsEqual("#GFAMLVL","#GPLALVL")
  GlobalLT("#GFAMLVL","GLOBAL",8)
  Global("#GFLVUP","GLOBAL",9)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetName(@126)
    AddXPObject(Myself,125000)
    ApplySpellRES("WTPFMLV0",Myself)
    ApplySpellRES("WTPFMLV4",Myself)
    ApplySpellRES("WTPFMLVL",Myself)
    ApplySpellRES("WTPFMLV9",Myself)
    ApplySpellRES("WTPFMLV9",Myself)
    ApplySpellRES("WTPFMLVA",Myself)
    ApplySpellRES("WTPFMLVA",Myself)
    ApplySpellRES("WTPFMLVB",Myself)
    ApplySpellRES("WTPFMLVB",Myself)
    ApplySpellRES("WTPFMLVC",Myself)
    ApplySpellRES("WTPFMLVC",Myself)
    ApplySpellRES("WTPFMLVC",Myself)
    ApplySpellRES("WTPFMLVD",Myself)
    ApplySpellRES("WTPFMLVD",Myself)
    ApplySpellRES("WTPFMLVE",Myself)
    ApplySpellRES("WTPFMLV8",Myself) // Also immune to non magical weapons
    AddSpecialAbility("WTPIN06")  // Polymorph Wolf
    Wait(1)
    DisplayStringNoName(Myself,@40)
    DisplayStringNoName(Myself,@36) // ST UP
    DisplayStringNoName(Myself,@28)
    DisplayStringNoName(Myself,@35)
    DisplayStringNoName(Myself,@47)
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon2",Myself))
    SetGlobal("#GFAMLVL","GLOBAL",8)
    SetGlobal("#GFLVUP","GLOBAL",10)
    SetInterrupt(TRUE)
    Continue()
END

IF
  !GlobalsEqual("#GFAMLVL","#GPLALVL")
  GlobalLT("#GFAMLVL","GLOBAL",9)
  Global("#GFLVUP","GLOBAL",10)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetName(@127)
    AddXPObject(Myself,250000)
    ApplySpellRES("WTPFMLV0",Myself)
    ApplySpellRES("WTPFMLV4",Myself)
    ApplySpellRES("WTPFMLV2",Myself)
    ApplySpellRES("WTPFMLVE",Myself)
    Wait(1)
    DisplayStringNoName(Myself,@41)
    DisplayStringNoName(Myself,@35)
    DisplayStringNoName(Myself,@47)
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon5",Myself))
    SetGlobal("#GFAMLVL","GLOBAL",9)
    SetGlobal("#GFLVUP","GLOBAL",11)
    SetInterrupt(TRUE)
    Continue()
END

IF
  !GlobalsEqual("#GFAMLVL","#GPLALVL")
  GlobalLT("#GFAMLVL","GLOBAL",10)
  Global("#GFLVUP","GLOBAL",11)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetName(@128)
    AddXPObject(Myself,250000)
    ApplySpellRES("WTPFMLV0",Myself)
    ApplySpellRES("WTPFMLV4",Myself)
    ApplySpellRES("WTPFMLV2",Myself)
    ApplySpellRES("WTPFMLV9",Myself)
    ApplySpellRES("WTPFMLVA",Myself)
    ApplySpellRES("WTPFMLVB",Myself)
    ApplySpellRES("WTPFMLVC",Myself)
    ApplySpellRES("WTPFMLVD",Myself)
    ApplySpellRES("WTPFMLVE",Myself)
    ApplySpellRES("WTPFMLV1",Myself)  // AC +1
    Wait(1)
    DisplayStringNoName(Myself,@41)
    DisplayStringNoName(Myself,@33)
    DisplayStringNoName(Myself,@35)
    DisplayStringNoName(Myself,@36) // ST UP
    DisplayStringNoName(Myself,@47)
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon5",Myself))
    SetGlobal("#GFAMLVL","GLOBAL",10)
    SetGlobal("#GFLVUP","GLOBAL",12)
    SetInterrupt(TRUE)
    Continue()
END

IF
  !GlobalsEqual("#GFAMLVL","#GPLALVL")
  GlobalLT("#GFAMLVL","GLOBAL",11)
  Global("#GFLVUP","GLOBAL",12)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetName(@129)
    AddXPObject(Myself,250000)
    ApplySpellRES("WTPFMLV0",Myself)
    ApplySpellRES("WTPFMLV4",Myself)
    ApplySpellRES("WTPFMLV2",Myself)
    ApplySpellRES("WTPFQUAB",Myself) // +2
    Wait(1)
    DisplayStringNoName(Myself,@41)
    DisplayStringNoName(Myself,@26)
    DisplayStringNoName(Myself,@35)
    EquipMostDamagingMelee()
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon5",Myself))
    SetGlobal("#GFAMLVL","GLOBAL",11)
    SetGlobal("#GFLVUP","GLOBAL",13)
    SetInterrupt(TRUE)
    Continue()
END

IF
  !GlobalsEqual("#GFAMLVL","#GPLALVL")
  GlobalLT("#GFAMLVL","GLOBAL",12)
  Global("#GFLVUP","GLOBAL",13)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetName(@130)
    AddXPObject(Myself,250000)
    ApplySpellRES("WTPFMLV0",Myself)
    ApplySpellRES("WTPFMLV4",Myself)
    ApplySpellRES("WTPFMLV2",Myself)
    ApplySpellRES("WTPFMLV9",Myself)
    ApplySpellRES("WTPFMLV9",Myself)
    ApplySpellRES("WTPFMLVA",Myself)
    ApplySpellRES("WTPFMLVA",Myself)
    ApplySpellRES("WTPFMLVB",Myself)
    ApplySpellRES("WTPFMLVB",Myself)
    ApplySpellRES("WTPFMLVC",Myself)
    ApplySpellRES("WTPFMLVC",Myself)
    ApplySpellRES("WTPFMLVC",Myself)
    ApplySpellRES("WTPFMLVD",Myself)
    ApplySpellRES("WTPFMLVD",Myself)
    AddSpecialAbility("WTPIN11")  // Detect Magic
    Wait(1)
    DisplayStringNoName(Myself,@41)
    DisplayStringNoName(Myself,@35)
    DisplayStringNoName(Myself,@36) // ST UP
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon5",Myself))
    SetGlobal("#GFAMLVL","GLOBAL",12)
    SetGlobal("#GFLVUP","GLOBAL",14)
    SetInterrupt(TRUE)
    Continue()
END

IF
  !GlobalsEqual("#GFAMLVL","#GPLALVL")
  GlobalLT("#GFAMLVL","GLOBAL",13)
  Global("#GFLVUP","GLOBAL",14)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetName(@131)
    AddXPObject(Myself,250000)
    ApplySpellRES("WTPFMLV0",Myself)
    ApplySpellRES("WTPFMLV4",Myself)
    ApplySpellRES("WTPFMLV2",Myself)
    Wait(1)
    DisplayStringNoName(Myself,@41)
    DisplayStringNoName(Myself,@35)
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon5",Myself))
    SetGlobal("#GFAMLVL","GLOBAL",13)
    SetGlobal("#GFLVUP","GLOBAL",15)
    SetInterrupt(TRUE)
    Continue()
END

IF
  !GlobalsEqual("#GFAMLVL","#GPLALVL")
  GlobalLT("#GFAMLVL","GLOBAL",14)
  Global("#GFLVUP","GLOBAL",15)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetName(@132)
    AddXPObject(Myself,250000)
    ApplySpellRES("WTPFMLV0",Myself)
    ApplySpellRES("WTPFMLV4",Myself)
    ApplySpellRES("WTPFMLV2",Myself)
    ApplySpellRES("WTPFMLV9",Myself)
    ApplySpellRES("WTPFMLVA",Myself)
    ApplySpellRES("WTPFMLVB",Myself)
    ApplySpellRES("WTPFMLVC",Myself)
    ApplySpellRES("WTPFMLVD",Myself)
    Wait(1)
    DisplayStringNoName(Myself,@41)
    DisplayStringNoName(Myself,@35)
    DisplayStringNoName(Myself,@36) // ST UP
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon5",Myself))
    SetGlobal("#GFAMLVL","GLOBAL",14)
    SetGlobal("#GFLVUP","GLOBAL",16)
    SetInterrupt(TRUE)
    Continue()
END

IF
  !GlobalsEqual("#GFAMLVL","#GPLALVL")
  GlobalLT("#GFAMLVL","GLOBAL",15)
  Global("#GFLVUP","GLOBAL",16)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetName(@133)
    AddXPObject(Myself,250000)
    ApplySpellRES("WTPFMLV0",Myself)
    ApplySpellRES("WTPFMLV4",Myself)
    ApplySpellRES("WTPFMLV2",Myself)
    Wait(1)
    DisplayStringNoName(Myself,@41)
    DisplayStringNoName(Myself,@35)
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon5",Myself))
    SetGlobal("#GFAMLVL","GLOBAL",15)
    SetGlobal("#GFLVUP","GLOBAL",17)
    SetInterrupt(TRUE)
    Continue()
END

IF
  !GlobalsEqual("#GFAMLVL","#GPLALVL")
  GlobalLT("#GFAMLVL","GLOBAL",16)
  Global("#GFLVUP","GLOBAL",17)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetName(@134)
    AddXPObject(Myself,250000)
    ApplySpellRES("WTPFMLV0",Myself)
    ApplySpellRES("WTPFMLV4",Myself)
    ApplySpellRES("WTPFMLV2",Myself)
    ApplySpellRES("WTPFMLV9",Myself)
    ApplySpellRES("WTPFMLVA",Myself)
    ApplySpellRES("WTPFMLVB",Myself)
    ApplySpellRES("WTPFMLVD",Myself)
    Wait(1)
    DisplayStringNoName(Myself,@41)
    DisplayStringNoName(Myself,@35)
    DisplayStringNoName(Myself,@36) // ST UP
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon5",Myself))
    SetGlobal("#GFAMLVL","GLOBAL",16)
    SetGlobal("#GFLVUP","GLOBAL",18)
    SetInterrupt(TRUE)
    Continue()
END

IF
  !GlobalsEqual("#GFAMLVL","#GPLALVL")
  GlobalLT("#GFAMLVL","GLOBAL",17)
  Global("#GFLVUP","GLOBAL",18)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetName(@135)
    AddXPObject(Myself,250000)
    ApplySpellRES("WTPFMLV0",Myself)
    ApplySpellRES("WTPFMLV4",Myself)
    ApplySpellRES("WTPFMLV2",Myself)
    Wait(1)
    DisplayStringNoName(Myself,@41)
    DisplayStringNoName(Myself,@35)
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon5",Myself))
    SetGlobal("#GFAMLVL","GLOBAL",17)
    SetGlobal("#GFLVUP","GLOBAL",19)
    SetInterrupt(TRUE)
    Continue()
END

IF
  !GlobalsEqual("#GFAMLVL","#GPLALVL")
  GlobalLT("#GFAMLVL","GLOBAL",18)
  Global("#GFLVUP","GLOBAL",19)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetName(@136)
    AddXPObject(Myself,250000)
    ApplySpellRES("WTPFMLV0",Myself)
    ApplySpellRES("WTPFMLV4",Myself)
    ApplySpellRES("WTPFMLV2",Myself)
    ApplySpellRES("WTPFMLV1",Myself)  // AC +1
    Wait(1)
    DisplayStringNoName(Myself,@41)
    DisplayStringNoName(Myself,@33)
    DisplayStringNoName(Myself,@35)
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon5",Myself))
    SetGlobal("#GFAMLVL","GLOBAL",18)
    SetGlobal("#GFLVUP","GLOBAL",20)
    SetInterrupt(TRUE)
    Continue()
END

IF
  !GlobalsEqual("#GFAMLVL","#GPLALVL")
  GlobalLT("#GFAMLVL","GLOBAL",19)
  Global("#GFLVUP","GLOBAL",20)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetName(@137)
    AddXPObject(Myself,250000)
    ApplySpellRES("WTPFMLV0",Myself)
    ApplySpellRES("WTPFMLV4",Myself)
    ApplySpellRES("WTPFMLV3",Myself)
    ApplySpellRES("WTPFQUAC",Myself) // +3
    Wait(1)
    DisplayStringNoName(Myself,@42)
    DisplayStringNoName(Myself,@27)
    DisplayStringNoName(Myself,@35)
    EquipMostDamagingMelee()
    SetGlobal("#GFAMLVL","GLOBAL",19)
    SetGlobal("#GFLVUP","GLOBAL",21)
    SetInterrupt(TRUE)
    Continue()
END

IF
  !GlobalsEqual("#GFAMLVL","#GPLALVL")
  GlobalLT("#GFAMLVL","GLOBAL",20)
  Global("#GFLVUP","GLOBAL",21)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetName(@138)
    AddXPObject(Myself,250000)
    ApplySpellRES("WTPFMLV0",Myself)
    ApplySpellRES("WTPFMLV4",Myself)
    ApplySpellRES("WTPFMLV3",Myself)
    Wait(1)
    DisplayStringNoName(Myself,@42)
    DisplayStringNoName(Myself,@35)
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon5",Myself))
    SetGlobal("#GFAMLVL","GLOBAL",20)
    SetGlobal("#GFLVUP","GLOBAL",22)
    SetInterrupt(TRUE)
    Continue()
END

IF
  !GlobalsEqual("#GFAMLVL","#GPLALVL")
  GlobalLT("#GFAMLVL","GLOBAL",21)
  Global("#GFLVUP","GLOBAL",22)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetName(@139)
    AddXPObject(Myself,250000)
    ApplySpellRES("WTPFMLV0",Myself)
    ApplySpellRES("WTPFMLV3",Myself)
    Wait(1)
    DisplayStringNoName(Myself,@42)
    SetGlobal("#GFAMLVL","GLOBAL",21)
    SetGlobal("#GFLVUP","GLOBAL",23)
    SetInterrupt(TRUE)
    Continue()
END

IF
  !GlobalsEqual("#GFAMLVL","#GPLALVL")
  GlobalLT("#GFAMLVL","GLOBAL",22)
  Global("#GFLVUP","GLOBAL",23)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetName(@140)
    AddXPObject(Myself,250000)
    ApplySpellRES("WTPFMLV0",Myself)
    ApplySpellRES("WTPFMLV3",Myself)
    Wait(1)
    DisplayStringNoName(Myself,@42)
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon5",Myself))
    SetGlobal("#GFAMLVL","GLOBAL",22)
    SetGlobal("#GFLVUP","GLOBAL",24)
    SetInterrupt(TRUE)
    Continue()
END

IF
  !GlobalsEqual("#GFAMLVL","#GPLALVL")
  GlobalLT("#GFAMLVL","GLOBAL",23)
  Global("#GFLVUP","GLOBAL",24)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetName(@141)
    AddXPObject(Myself,250000)
    ApplySpellRES("WTPFMLV0",Myself)
    ApplySpellRES("WTPFMLV3",Myself)
    Wait(1)
    DisplayStringNoName(Myself,@42)
    SetGlobal("#GFAMLVL","GLOBAL",23)
    SetGlobal("#GFLVUP","GLOBAL",25)
    SetInterrupt(TRUE)
    Continue()
END

IF
  !GlobalsEqual("#GFAMLVL","#GPLALVL")
  GlobalLT("#GFAMLVL","GLOBAL",24)
  Global("#GFLVUP","GLOBAL",25)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetName(@142)
    AddXPObject(Myself,250000)
    ApplySpellRES("WTPFMLV0",Myself)
    ApplySpellRES("WTPFMLV3",Myself)
    Wait(1)
    DisplayStringNoName(Myself,@42)
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon5",Myself))
    SetGlobal("#GFAMLVL","GLOBAL",24)
    SetGlobal("#GFLVUP","GLOBAL",26)
    SetInterrupt(TRUE)
    Continue()
END

IF
  !GlobalsEqual("#GFAMLVL","#GPLALVL")
  GlobalLT("#GFAMLVL","GLOBAL",25)
  Global("#GFLVUP","GLOBAL",26)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetName(@143)
    AddXPObject(Myself,250000)
    ApplySpellRES("WTPFMLV0",Myself)
    ApplySpellRES("WTPFMLV3",Myself)
    Wait(1)
    DisplayStringNoName(Myself,@42)
    SetGlobal("#GFAMLVL","GLOBAL",25)
    SetGlobal("#GFLVUP","GLOBAL",27)
    SetInterrupt(TRUE)
    Continue()
END

IF
  !GlobalsEqual("#GFAMLVL","#GPLALVL")
  GlobalLT("#GFAMLVL","GLOBAL",26)
  Global("#GFLVUP","GLOBAL",27)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetName(@144)
    AddXPObject(Myself,250000)
    ApplySpellRES("WTPFMLV0",Myself)
    ApplySpellRES("WTPFMLV3",Myself)
    Wait(1)
    DisplayStringNoName(Myself,@42)
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon5",Myself))
    SetGlobal("#GFAMLVL","GLOBAL",26)
    SetGlobal("#GFLVUP","GLOBAL",28)
    SetInterrupt(TRUE)
    Continue()
END

IF
  !GlobalsEqual("#GFAMLVL","#GPLALVL")
  GlobalLT("#GFAMLVL","GLOBAL",27)
  Global("#GFLVUP","GLOBAL",28)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetName(@145)
    AddXPObject(Myself,250000)
    ApplySpellRES("WTPFMLV0",Myself)
    ApplySpellRES("WTPFMLV3",Myself)
    Wait(1)
    DisplayStringNoName(Myself,@42)
    SetGlobal("#GFAMLVL","GLOBAL",27)
    SetGlobal("#GFLVUP","GLOBAL",29)
    SetInterrupt(TRUE)
    Continue()
END

IF
  !GlobalsEqual("#GFAMLVL","#GPLALVL")
  GlobalLT("#GFAMLVL","GLOBAL",28)
  Global("#GFLVUP","GLOBAL",29)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetName(@146)
    AddXPObject(Myself,250000)
    ApplySpellRES("WTPFMLV0",Myself)
    ApplySpellRES("WTPFMLV3",Myself)
    Wait(1)
    DisplayStringNoName(Myself,@42)
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon5",Myself))
    SetGlobal("#GFAMLVL","GLOBAL",28)
    SetGlobal("#GFLVUP","GLOBAL",30)
    SetInterrupt(TRUE)
    Continue()
END

IF
  !GlobalsEqual("#GFAMLVL","#GPLALVL")
  GlobalLT("#GFAMLVL","GLOBAL",29)
  Global("#GFLVUP","GLOBAL",30)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetName(@147)
    AddXPObject(Myself,250000)
    ApplySpellRES("WTPFMLV0",Myself)
    ApplySpellRES("WTPFMLV3",Myself)
    Wait(1)
    DisplayStringNoName(Myself,@42)
    SetGlobal("#GFAMLVL","GLOBAL",29)
    SetGlobal("#GFLVUP","GLOBAL",31)
    SetInterrupt(TRUE)
    Continue()
END

IF
  !GlobalsEqual("#GFAMLVL","#GPLALVL")
  GlobalLT("#GFAMLVL","GLOBAL",30)
  Global("#GFLVUP","GLOBAL",31)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetName(@148)
    AddXPObject(Myself,250000)
    ApplySpellRES("WTPFMLV0",Myself)
    ApplySpellRES("WTPFMLV3",Myself)
    Wait(1)
    DisplayStringNoName(Myself,@42)
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon5",Myself))
    SetGlobal("#GFAMLVL","GLOBAL",30)
    SetGlobal("#GFLVUP","GLOBAL",32)
    SetInterrupt(TRUE)
    Continue()
END

IF
  !GlobalsEqual("#GFAMLVL","#GPLALVL")
  GlobalLT("#GFAMLVL","GLOBAL",31)
  Global("#GFLVUP","GLOBAL",32)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetName(@149)
    AddXPObject(Myself,250000)
    ApplySpellRES("WTPFMLV0",Myself)
    ApplySpellRES("WTPFMLV3",Myself)
    ApplySpellRES("WTPFMLV1",Myself)  // AC +1
    Wait(1)
    DisplayStringNoName(Myself,@42)
    DisplayStringNoName(Myself,@33)
    SetGlobal("#GFAMLVL","GLOBAL",31)
    SetGlobal("#GFLVUP","GLOBAL",33)
    SetInterrupt(TRUE)
    Continue()
END

IF
  !GlobalsEqual("#GFAMLVL","#GPLALVL")
  GlobalLT("#GFAMLVL","GLOBAL",32)
  Global("#GFLVUP","GLOBAL",33)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetName(@150)
    AddXPObject(Myself,250000)
    ApplySpellRES("WTPFMLV0",Myself)
    ApplySpellRES("WTPFMLV3",Myself)
    Wait(1)
    DisplayStringNoName(Myself,@42)
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon5",Myself))
    SetGlobal("#GFAMLVL","GLOBAL",32)
    SetGlobal("#GFLVUP","GLOBAL",34)
    SetInterrupt(TRUE)
    Continue()
END

IF
  !GlobalsEqual("#GFAMLVL","#GPLALVL")
  GlobalLT("#GFAMLVL","GLOBAL",33)
  Global("#GFLVUP","GLOBAL",34)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetName(@151)
    AddXPObject(Myself,250000)
    ApplySpellRES("WTPFMLV0",Myself)
    ApplySpellRES("WTPFMLV3",Myself)
    Wait(1)
    DisplayStringNoName(Myself,@42)
    SetGlobal("#GFAMLVL","GLOBAL",33)
    SetGlobal("#GFLVUP","GLOBAL",35)
    SetInterrupt(TRUE)
    Continue()
END

IF
  !GlobalsEqual("#GFAMLVL","#GPLALVL")
  GlobalLT("#GFAMLVL","GLOBAL",34)
  Global("#GFLVUP","GLOBAL",35)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetName(@152)
    AddXPObject(Myself,250000)
    ApplySpellRES("WTPFMLV0",Myself)
    ApplySpellRES("WTPFMLV3",Myself)
    Wait(1)
    DisplayStringNoName(Myself,@42)
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon5",Myself))
    SetGlobal("#GFAMLVL","GLOBAL",34)
    SetGlobal("#GFLVUP","GLOBAL",36)
    SetInterrupt(TRUE)
    Continue()
END

IF
  !GlobalsEqual("#GFAMLVL","#GPLALVL")
  GlobalLT("#GFAMLVL","GLOBAL",35)
  Global("#GFLVUP","GLOBAL",36)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetName(@153)
    AddXPObject(Myself,250000)
    ApplySpellRES("WTPFMLV0",Myself)
    ApplySpellRES("WTPFMLV3",Myself)
    Wait(1)
    DisplayStringNoName(Myself,@42)
    SetGlobal("#GFAMLVL","GLOBAL",35)
    SetGlobal("#GFLVUP","GLOBAL",37)
    SetInterrupt(TRUE)
    Continue()
END

IF
  !GlobalsEqual("#GFAMLVL","#GPLALVL")
  GlobalLT("#GFAMLVL","GLOBAL",36)
  Global("#GFLVUP","GLOBAL",37)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetName(@154)
    AddXPObject(Myself,250000)
    ApplySpellRES("WTPFMLV0",Myself)
    ApplySpellRES("WTPFMLV3",Myself)
    Wait(1)
    DisplayStringNoName(Myself,@42)
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon5",Myself))
    SetGlobal("#GFAMLVL","GLOBAL",36)
    SetGlobal("#GFLVUP","GLOBAL",38)
    SetInterrupt(TRUE)
    Continue()
END

IF
  !GlobalsEqual("#GFAMLVL","#GPLALVL")
  GlobalLT("#GFAMLVL","GLOBAL",37)
  Global("#GFLVUP","GLOBAL",38)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetName(@155)
    AddXPObject(Myself,250000)
    ApplySpellRES("WTPFMLV0",Myself)
    ApplySpellRES("WTPFMLV3",Myself)
    Wait(1)
    DisplayStringNoName(Myself,@42)
    SetGlobal("#GFAMLVL","GLOBAL",37)
    SetGlobal("#GFLVUP","GLOBAL",39)
    SetInterrupt(TRUE)
    Continue()
END

IF
  !GlobalsEqual("#GFAMLVL","#GPLALVL")
  GlobalLT("#GFAMLVL","GLOBAL",38)
  Global("#GFLVUP","GLOBAL",39)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetName(@156)
    AddXPObject(Myself,250000)
    ApplySpellRES("WTPFMLV0",Myself)
    ApplySpellRES("WTPFMLV3",Myself)
    Wait(1)
    DisplayStringNoName(Myself,@42)
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon5",Myself))
    SetGlobal("#GFAMLVL","GLOBAL",38)
    SetGlobal("#GFLVUP","GLOBAL",40)
    SetInterrupt(TRUE)
    Continue()
END

IF
  !GlobalsEqual("#GFAMLVL","#GPLALVL")
  GlobalLT("#GFAMLVL","GLOBAL",39)
  Global("#GFLVUP","GLOBAL",40)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetName(@157)
    AddXPObject(Myself,250000)
    ApplySpellRES("WTPFMLV0",Myself)
    ApplySpellRES("WTPFMLV3",Myself)
    Wait(1)
    DisplayStringNoName(Myself,@42)
    SetGlobal("#GFAMLVL","GLOBAL",39)
    SetGlobal("#GFLVUP","GLOBAL",41)
    SetInterrupt(TRUE)
    Continue()
END

IF
  !GlobalsEqual("#GFAMLVL","#GPLALVL")
  GlobalLT("#GFAMLVL","GLOBAL",40)
  Global("#GFLVUP","GLOBAL",41)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetName(@158)
    AddXPObject(Myself,250000)
    ApplySpellRES("WTPFMLV0",Myself)
    ApplySpellRES("WTPFMLV3",Myself)
    Wait(1)
    DisplayStringNoName(Myself,@42)
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon5",Myself))
    SetGlobal("#GFAMLVL","GLOBAL",40)
    SetGlobal("#GFLVUP","GLOBAL",42)
    SetInterrupt(TRUE)
    Continue()
END

IF
  !GlobalsEqual("#GFAMLVL","#GPLALVL")
  GlobalLT("#GFAMLVL","GLOBAL",41)
  Global("#GFLVUP","GLOBAL",42)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetName(@159)
    AddXPObject(Myself,250000)
    ApplySpellRES("WTPFMLV0",Myself)
    ApplySpellRES("WTPFMLV3",Myself)
    Wait(1)
    DisplayStringNoName(Myself,@42)
    SetGlobal("#GFAMLVL","GLOBAL",41)
    SetGlobal("#GFLVUP","GLOBAL",43)
    SetInterrupt(TRUE)
    Continue()
END

IF
  !GlobalsEqual("#GFAMLVL","#GPLALVL")
  GlobalLT("#GFAMLVL","GLOBAL",42)
  Global("#GFLVUP","GLOBAL",43)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetName(@160)
    AddXPObject(Myself,250000)
    ApplySpellRES("WTPFMLV0",Myself)
    ApplySpellRES("WTPFMLV3",Myself)
    Wait(1)
    DisplayStringNoName(Myself,@42)
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon5",Myself))
    SetGlobal("#GFAMLVL","GLOBAL",42)
    SetGlobal("#GFLVUP","GLOBAL",44)
    SetInterrupt(TRUE)
    Continue()
END

IF
  !GlobalsEqual("#GFAMLVL","#GPLALVL")
  GlobalLT("#GFAMLVL","GLOBAL",43)
  Global("#GFLVUP","GLOBAL",44)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetName(@161)
    AddXPObject(Myself,250000)
    ApplySpellRES("WTPFMLV0",Myself)
    ApplySpellRES("WTPFMLV3",Myself)
    Wait(1)
    DisplayStringNoName(Myself,@42)
    SetGlobal("#GFAMLVL","GLOBAL",43)
    SetGlobal("#GFLVUP","GLOBAL",45)
    SetInterrupt(TRUE)
    Continue()
END

IF
  !GlobalsEqual("#GFAMLVL","#GPLALVL")
  GlobalLT("#GFAMLVL","GLOBAL",44)
  Global("#GFLVUP","GLOBAL",45)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetName(@162)
    AddXPObject(Myself,250000)
    ApplySpellRES("WTPFMLV0",Myself)
    ApplySpellRES("WTPFMLV3",Myself)
    Wait(1)
    DisplayStringNoName(Myself,@42)
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon5",Myself))
    SetGlobal("#GFAMLVL","GLOBAL",44)
    SetGlobal("#GFLVUP","GLOBAL",46)
    SetInterrupt(TRUE)
    Continue()
END

IF
  !GlobalsEqual("#GFAMLVL","#GPLALVL")
  GlobalLT("#GFAMLVL","GLOBAL",45)
  Global("#GFLVUP","GLOBAL",46)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetName(@163)
    AddXPObject(Myself,250000)
    ApplySpellRES("WTPFMLV0",Myself)
    ApplySpellRES("WTPFMLV3",Myself)
    Wait(1)
    DisplayStringNoName(Myself,@42)
    SetGlobal("#GFAMLVL","GLOBAL",45)
    SetGlobal("#GFLVUP","GLOBAL",47)
    SetInterrupt(TRUE)
    Continue()
END

IF
  !GlobalsEqual("#GFAMLVL","#GPLALVL")
  GlobalLT("#GFAMLVL","GLOBAL",46)
  Global("#GFLVUP","GLOBAL",47)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetName(@164)
    AddXPObject(Myself,250000)
    ApplySpellRES("WTPFMLV0",Myself)
    ApplySpellRES("WTPFMLV3",Myself)
    Wait(1)
    DisplayStringNoName(Myself,@42)
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon5",Myself))
    SetGlobal("#GFAMLVL","GLOBAL",46)
    SetGlobal("#GFLVUP","GLOBAL",48)
    SetInterrupt(TRUE)
    Continue()
END

IF
  !GlobalsEqual("#GFAMLVL","#GPLALVL")
  GlobalLT("#GFAMLVL","GLOBAL",47)
  Global("#GFLVUP","GLOBAL",48)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetName(@165)
    AddXPObject(Myself,250000)
    ApplySpellRES("WTPFMLV0",Myself)
    ApplySpellRES("WTPFMLV3",Myself)
    Wait(1)
    DisplayStringNoName(Myself,@42)
    SetGlobal("#GFAMLVL","GLOBAL",47)
    SetGlobal("#GFLVUP","GLOBAL",49)
    SetInterrupt(TRUE)
    Continue()
END

IF
  !GlobalsEqual("#GFAMLVL","#GPLALVL")
  GlobalLT("#GFAMLVL","GLOBAL",48)
  Global("#GFLVUP","GLOBAL",49)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetName(@166)
    AddXPObject(Myself,250000)
    ApplySpellRES("WTPFMLV0",Myself)
    ApplySpellRES("WTPFMLV3",Myself)
    Wait(1)
    DisplayStringNoName(Myself,@42)
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon5",Myself))
    SetGlobal("#GFAMLVL","GLOBAL",48)
    SetGlobal("#GFLVUP","GLOBAL",50)
    SetInterrupt(TRUE)
    Continue()
END

IF
  !GlobalsEqual("#GFAMLVL","#GPLALVL")
  GlobalLT("#GFAMLVL","GLOBAL",49)
  Global("#GFLVUP","GLOBAL",50)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetName(@167)
    AddXPObject(Myself,250000)
    ApplySpellRES("WTPFMLV0",Myself)
    ApplySpellRES("WTPFMLV3",Myself)
    Wait(1)
    DisplayStringNoName(Myself,@42)
    SetGlobal("#GFAMLVL","GLOBAL",49)
    SetGlobal("#GFLVUP","GLOBAL",100)
    SetInterrupt(TRUE)
    Continue()
END

IF
  !GlobalsEqual("#GFAMLVL","#GPLALVL")
  GlobalGT("#GFLVUP","GLOBAL",1)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    ActionOverride(Player1,MakeUnselectable(6))
    ActionOverride(Player2,MakeUnselectable(6))
    ActionOverride(Player3,MakeUnselectable(6))
    ActionOverride(Player4,MakeUnselectable(6))
    ActionOverride(Player5,MakeUnselectable(6))
    ActionOverride(Player6,MakeUnselectable(6))
    SetInterrupt(TRUE)
END

///////////////////
/// Name change ///
///////////////////

IF
  Global("#GNAMCHG","LOCALS",0)
  Global("#GEMPCHK","LOCALS",0)
  Global("#GFAMLVL","GLOBAL",0)
THEN
  RESPONSE #100
    SetName(@700)
    SetGlobal("#GNAMCHG","LOCALS",1)
END

IF
  Global("#GNAMCHG","LOCALS",0)
  Global("#GEMPCHK","LOCALS",0)
  Global("#GFAMLVL","GLOBAL",1)
THEN
  RESPONSE #100
    SetName(@701)
    SetGlobal("#GNAMCHG","LOCALS",1)
END

IF
  Global("#GNAMCHG","LOCALS",0)
  Global("#GEMPCHK","LOCALS",0)
  Global("#GFAMLVL","GLOBAL",2)
THEN
  RESPONSE #100
    SetName(@702)
    SetGlobal("#GNAMCHG","LOCALS",1)
END

IF
  Global("#GNAMCHG","LOCALS",0)
  Global("#GEMPCHK","LOCALS",0)
  Global("#GFAMLVL","GLOBAL",3)
THEN
  RESPONSE #100
    SetName(@703)
    SetGlobal("#GNAMCHG","LOCALS",1)
END

IF
  Global("#GNAMCHG","LOCALS",0)
  Global("#GEMPCHK","LOCALS",0)
  Global("#GFAMLVL","GLOBAL",4)
THEN
  RESPONSE #100
    SetName(@704)
    SetGlobal("#GNAMCHG","LOCALS",1)
END

IF
  Global("#GNAMCHG","LOCALS",0)
  Global("#GEMPCHK","LOCALS",0)
  Global("#GFAMLVL","GLOBAL",5)
THEN
  RESPONSE #100
    SetName(@705)
    SetGlobal("#GNAMCHG","LOCALS",1)
END

IF
  Global("#GNAMCHG","LOCALS",0)
  Global("#GEMPCHK","LOCALS",0)
  Global("#GFAMLVL","GLOBAL",6)
THEN
  RESPONSE #100
    SetName(@706)
    SetGlobal("#GNAMCHG","LOCALS",1)
END

IF
  Global("#GNAMCHG","LOCALS",0)
  Global("#GEMPCHK","LOCALS",0)
  Global("#GFAMLVL","GLOBAL",7)
THEN
  RESPONSE #100
    SetName(@707)
    SetGlobal("#GNAMCHG","LOCALS",1)
END

IF
  Global("#GNAMCHG","LOCALS",0)
  Global("#GEMPCHK","LOCALS",0)
  Global("#GFAMLVL","GLOBAL",8)
THEN
  RESPONSE #100
    SetName(@708)
    SetGlobal("#GNAMCHG","LOCALS",1)
END

IF
  Global("#GNAMCHG","LOCALS",0)
  Global("#GEMPCHK","LOCALS",0)
  Global("#GFAMLVL","GLOBAL",9)
THEN
  RESPONSE #100
    SetName(@709)
    SetGlobal("#GNAMCHG","LOCALS",1)
END

IF
  Global("#GNAMCHG","LOCALS",0)
  Global("#GEMPCHK","LOCALS",0)
  Global("#GFAMLVL","GLOBAL",10)
THEN
  RESPONSE #100
    SetName(@710)
    SetGlobal("#GNAMCHG","LOCALS",1)
END

IF
  Global("#GNAMCHG","LOCALS",0)
  Global("#GEMPCHK","LOCALS",0)
  Global("#GFAMLVL","GLOBAL",11)
THEN
  RESPONSE #100
    SetName(@711)
    SetGlobal("#GNAMCHG","LOCALS",1)
END

IF
  Global("#GNAMCHG","LOCALS",0)
  Global("#GEMPCHK","LOCALS",0)
  Global("#GFAMLVL","GLOBAL",12)
THEN
  RESPONSE #100
    SetName(@712)
    SetGlobal("#GNAMCHG","LOCALS",1)
END

IF
  Global("#GNAMCHG","LOCALS",0)
  Global("#GEMPCHK","LOCALS",0)
  Global("#GFAMLVL","GLOBAL",13)
THEN
  RESPONSE #100
    SetName(@713)
    SetGlobal("#GNAMCHG","LOCALS",1)
END

IF
  Global("#GNAMCHG","LOCALS",0)
  Global("#GEMPCHK","LOCALS",0)
  Global("#GFAMLVL","GLOBAL",14)
THEN
  RESPONSE #100
    SetName(@714)
    SetGlobal("#GNAMCHG","LOCALS",1)
END

IF
  Global("#GNAMCHG","LOCALS",0)
  Global("#GEMPCHK","LOCALS",0)
  Global("#GFAMLVL","GLOBAL",15)
THEN
  RESPONSE #100
    SetName(@715)
    SetGlobal("#GNAMCHG","LOCALS",1)
END

IF
  Global("#GNAMCHG","LOCALS",0)
  Global("#GEMPCHK","LOCALS",0)
  Global("#GFAMLVL","GLOBAL",16)
THEN
  RESPONSE #100
    SetName(@716)
    SetGlobal("#GNAMCHG","LOCALS",1)
END

IF
  Global("#GNAMCHG","LOCALS",0)
  Global("#GEMPCHK","LOCALS",0)
  Global("#GFAMLVL","GLOBAL",17)
THEN
  RESPONSE #100
    SetName(@717)
    SetGlobal("#GNAMCHG","LOCALS",1)
END

IF
  Global("#GNAMCHG","LOCALS",0)
  Global("#GEMPCHK","LOCALS",0)
  Global("#GFAMLVL","GLOBAL",18)
THEN
  RESPONSE #100
    SetName(@718)
    SetGlobal("#GNAMCHG","LOCALS",1)
END

IF
  Global("#GNAMCHG","LOCALS",0)
  Global("#GEMPCHK","LOCALS",0)
  Global("#GFAMLVL","GLOBAL",19)
THEN
  RESPONSE #100
    SetName(@719)
    SetGlobal("#GNAMCHG","LOCALS",1)
END

IF
  Global("#GNAMCHG","LOCALS",0)
  Global("#GEMPCHK","LOCALS",0)
  Global("#GFAMLVL","GLOBAL",20)
THEN
  RESPONSE #100
    SetName(@720)
    SetGlobal("#GNAMCHG","LOCALS",1)
END

IF
  Global("#GNAMCHG","LOCALS",0)
  Global("#GEMPCHK","LOCALS",0)
  Global("#GFAMLVL","GLOBAL",21)
THEN
  RESPONSE #100
    SetName(@721)
    SetGlobal("#GNAMCHG","LOCALS",1)
END

IF
  Global("#GNAMCHG","LOCALS",0)
  Global("#GEMPCHK","LOCALS",0)
  Global("#GFAMLVL","GLOBAL",22)
THEN
  RESPONSE #100
    SetName(@722)
    SetGlobal("#GNAMCHG","LOCALS",1)
END

IF
  Global("#GNAMCHG","LOCALS",0)
  Global("#GEMPCHK","LOCALS",0)
  Global("#GFAMLVL","GLOBAL",23)
THEN
  RESPONSE #100
    SetName(@723)
    SetGlobal("#GNAMCHG","LOCALS",1)
END

IF
  Global("#GNAMCHG","LOCALS",0)
  Global("#GEMPCHK","LOCALS",0)
  Global("#GFAMLVL","GLOBAL",24)
THEN
  RESPONSE #100
    SetName(@724)
    SetGlobal("#GNAMCHG","LOCALS",1)
END

IF
  Global("#GNAMCHG","LOCALS",0)
  Global("#GEMPCHK","LOCALS",0)
  Global("#GFAMLVL","GLOBAL",25)
THEN
  RESPONSE #100
    SetName(@725)
    SetGlobal("#GNAMCHG","LOCALS",1)
END

IF
  Global("#GNAMCHG","LOCALS",0)
  Global("#GEMPCHK","LOCALS",0)
  Global("#GFAMLVL","GLOBAL",26)
THEN
  RESPONSE #100
    SetName(@726)
    SetGlobal("#GNAMCHG","LOCALS",1)
END

IF
  Global("#GNAMCHG","LOCALS",0)
  Global("#GEMPCHK","LOCALS",0)
  Global("#GFAMLVL","GLOBAL",27)
THEN
  RESPONSE #100
    SetName(@727)
    SetGlobal("#GNAMCHG","LOCALS",1)
END

IF
  Global("#GNAMCHG","LOCALS",0)
  Global("#GEMPCHK","LOCALS",0)
  Global("#GFAMLVL","GLOBAL",28)
THEN
  RESPONSE #100
    SetName(@728)
    SetGlobal("#GNAMCHG","LOCALS",1)
END

IF
  Global("#GNAMCHG","LOCALS",0)
  Global("#GEMPCHK","LOCALS",0)
  Global("#GFAMLVL","GLOBAL",29)
THEN
  RESPONSE #100
    SetName(@729)
    SetGlobal("#GNAMCHG","LOCALS",1)
END

IF
  Global("#GNAMCHG","LOCALS",0)
  Global("#GEMPCHK","LOCALS",0)
  Global("#GFAMLVL","GLOBAL",30)
THEN
  RESPONSE #100
    SetName(@730)
    SetGlobal("#GNAMCHG","LOCALS",1)
END

IF
  Global("#GNAMCHG","LOCALS",0)
  Global("#GEMPCHK","LOCALS",0)
  Global("#GFAMLVL","GLOBAL",31)
THEN
  RESPONSE #100
    SetName(@731)
    SetGlobal("#GNAMCHG","LOCALS",1)
END

IF
  Global("#GNAMCHG","LOCALS",0)
  Global("#GEMPCHK","LOCALS",0)
  Global("#GFAMLVL","GLOBAL",32)
THEN
  RESPONSE #100
    SetName(@732)
    SetGlobal("#GNAMCHG","LOCALS",1)
END

IF
  Global("#GNAMCHG","LOCALS",0)
  Global("#GEMPCHK","LOCALS",0)
  Global("#GFAMLVL","GLOBAL",33)
THEN
  RESPONSE #100
    SetName(@733)
    SetGlobal("#GNAMCHG","LOCALS",1)
END

IF
  Global("#GNAMCHG","LOCALS",0)
  Global("#GEMPCHK","LOCALS",0)
  Global("#GFAMLVL","GLOBAL",34)
THEN
  RESPONSE #100
    SetName(@734)
    SetGlobal("#GNAMCHG","LOCALS",1)
END

IF
  Global("#GNAMCHG","LOCALS",0)
  Global("#GEMPCHK","LOCALS",0)
  Global("#GFAMLVL","GLOBAL",35)
THEN
  RESPONSE #100
    SetName(@735)
    SetGlobal("#GNAMCHG","LOCALS",1)
END

IF
  Global("#GNAMCHG","LOCALS",0)
  Global("#GEMPCHK","LOCALS",0)
  Global("#GFAMLVL","GLOBAL",36)
THEN
  RESPONSE #100
    SetName(@736)
    SetGlobal("#GNAMCHG","LOCALS",1)
END

IF
  Global("#GNAMCHG","LOCALS",0)
  Global("#GEMPCHK","LOCALS",0)
  Global("#GFAMLVL","GLOBAL",37)
THEN
  RESPONSE #100
    SetName(@737)
    SetGlobal("#GNAMCHG","LOCALS",1)
END

IF
  Global("#GNAMCHG","LOCALS",0)
  Global("#GEMPCHK","LOCALS",0)
  Global("#GFAMLVL","GLOBAL",38)
THEN
  RESPONSE #100
    SetName(@738)
    SetGlobal("#GNAMCHG","LOCALS",1)
END

IF
  Global("#GNAMCHG","LOCALS",0)
  Global("#GEMPCHK","LOCALS",0)
  Global("#GFAMLVL","GLOBAL",39)
THEN
  RESPONSE #100
    SetName(@739)
    SetGlobal("#GNAMCHG","LOCALS",1)
END

IF
  Global("#GNAMCHG","LOCALS",0)
  Global("#GEMPCHK","LOCALS",0)
  Global("#GFAMLVL","GLOBAL",40)
THEN
  RESPONSE #100
    SetName(@740)
    SetGlobal("#GNAMCHG","LOCALS",1)
END

IF
  Global("#GNAMCHG","LOCALS",0)
  Global("#GEMPCHK","LOCALS",0)
  Global("#GFAMLVL","GLOBAL",41)
THEN
  RESPONSE #100
    SetName(@741)
    SetGlobal("#GNAMCHG","LOCALS",1)
END

IF
  Global("#GNAMCHG","LOCALS",0)
  Global("#GEMPCHK","LOCALS",0)
  Global("#GFAMLVL","GLOBAL",42)
THEN
  RESPONSE #100
    SetName(@742)
    SetGlobal("#GNAMCHG","LOCALS",1)
END

IF
  Global("#GNAMCHG","LOCALS",0)
  Global("#GEMPCHK","LOCALS",0)
  Global("#GFAMLVL","GLOBAL",43)
THEN
  RESPONSE #100
    SetName(@743)
    SetGlobal("#GNAMCHG","LOCALS",1)
END

IF
  Global("#GNAMCHG","LOCALS",0)
  Global("#GEMPCHK","LOCALS",0)
  Global("#GFAMLVL","GLOBAL",44)
THEN
  RESPONSE #100
    SetName(@744)
    SetGlobal("#GNAMCHG","LOCALS",1)
END

IF
  Global("#GNAMCHG","LOCALS",0)
  Global("#GEMPCHK","LOCALS",0)
  Global("#GFAMLVL","GLOBAL",45)
THEN
  RESPONSE #100
    SetName(@745)
    SetGlobal("#GNAMCHG","LOCALS",1)
END

IF
  Global("#GNAMCHG","LOCALS",0)
  Global("#GEMPCHK","LOCALS",0)
  Global("#GFAMLVL","GLOBAL",46)
THEN
  RESPONSE #100
    SetName(@746)
    SetGlobal("#GNAMCHG","LOCALS",1)
END

IF
  Global("#GNAMCHG","LOCALS",0)
  Global("#GEMPCHK","LOCALS",0)
  Global("#GFAMLVL","GLOBAL",47)
THEN
  RESPONSE #100
    SetName(@747)
    SetGlobal("#GNAMCHG","LOCALS",1)
END

IF
  Global("#GNAMCHG","LOCALS",0)
  Global("#GEMPCHK","LOCALS",0)
  Global("#GFAMLVL","GLOBAL",48)
THEN
  RESPONSE #100
    SetName(@748)
    SetGlobal("#GNAMCHG","LOCALS",1)
END

IF
  Global("#GNAMCHG","LOCALS",0)
  Global("#GEMPCHK","LOCALS",0)
  Global("#GFAMLVL","GLOBAL",49)
THEN
  RESPONSE #100
    SetName(@749)
    SetGlobal("#GNAMCHG","LOCALS",1)
END

IF
  Global("#GNAMCHG","LOCALS",1)
  Global("#GEMPCHK","LOCALS",1)
  Global("#GFAMLVL","GLOBAL",0)
THEN
  RESPONSE #100
    SetName(@4)
    SetGlobal("#GNAMCHG","LOCALS",0)
END

IF
  Global("#GNAMCHG","LOCALS",1)
  Global("#GEMPCHK","LOCALS",1)
  Global("#GFAMLVL","GLOBAL",1)
THEN
  RESPONSE #100
    SetName(@119)
    SetGlobal("#GNAMCHG","LOCALS",0)
END

IF
  Global("#GNAMCHG","LOCALS",1)
  Global("#GEMPCHK","LOCALS",1)
  Global("#GFAMLVL","GLOBAL",2)
THEN
  RESPONSE #100
    SetName(@120)
    SetGlobal("#GNAMCHG","LOCALS",0)
END

IF
  Global("#GNAMCHG","LOCALS",1)
  Global("#GEMPCHK","LOCALS",1)
  Global("#GFAMLVL","GLOBAL",3)
THEN
  RESPONSE #100
    SetName(@121)
    SetGlobal("#GNAMCHG","LOCALS",0)
END

IF
  Global("#GNAMCHG","LOCALS",1)
  Global("#GEMPCHK","LOCALS",1)
  Global("#GFAMLVL","GLOBAL",4)
THEN
  RESPONSE #100
    SetName(@122)
    SetGlobal("#GNAMCHG","LOCALS",0)
END

IF
  Global("#GNAMCHG","LOCALS",1)
  Global("#GEMPCHK","LOCALS",1)
  Global("#GFAMLVL","GLOBAL",5)
THEN
  RESPONSE #100
    SetName(@123)
    SetGlobal("#GNAMCHG","LOCALS",0)
END

IF
  Global("#GNAMCHG","LOCALS",1)
  Global("#GEMPCHK","LOCALS",1)
  Global("#GFAMLVL","GLOBAL",6)
THEN
  RESPONSE #100
    SetName(@124)
    SetGlobal("#GNAMCHG","LOCALS",0)
END

IF
  Global("#GNAMCHG","LOCALS",1)
  Global("#GEMPCHK","LOCALS",1)
  Global("#GFAMLVL","GLOBAL",7)
THEN
  RESPONSE #100
    SetName(@125)
    SetGlobal("#GNAMCHG","LOCALS",0)
END

IF
  Global("#GNAMCHG","LOCALS",1)
  Global("#GEMPCHK","LOCALS",1)
  Global("#GFAMLVL","GLOBAL",8)
THEN
  RESPONSE #100
    SetName(@126)
    SetGlobal("#GNAMCHG","LOCALS",0)
END

IF
  Global("#GNAMCHG","LOCALS",1)
  Global("#GEMPCHK","LOCALS",1)
  Global("#GFAMLVL","GLOBAL",9)
THEN
  RESPONSE #100
    SetName(@127)
    SetGlobal("#GNAMCHG","LOCALS",0)
END

IF
  Global("#GNAMCHG","LOCALS",1)
  Global("#GEMPCHK","LOCALS",1)
  Global("#GFAMLVL","GLOBAL",10)
THEN
  RESPONSE #100
    SetName(@128)
    SetGlobal("#GNAMCHG","LOCALS",0)
END

IF
  Global("#GNAMCHG","LOCALS",1)
  Global("#GEMPCHK","LOCALS",1)
  Global("#GFAMLVL","GLOBAL",11)
THEN
  RESPONSE #100
    SetName(@129)
    SetGlobal("#GNAMCHG","LOCALS",0)
END

IF
  Global("#GNAMCHG","LOCALS",1)
  Global("#GEMPCHK","LOCALS",1)
  Global("#GFAMLVL","GLOBAL",12)
THEN
  RESPONSE #100
    SetName(@130)
    SetGlobal("#GNAMCHG","LOCALS",0)
END

IF
  Global("#GNAMCHG","LOCALS",1)
  Global("#GEMPCHK","LOCALS",1)
  Global("#GFAMLVL","GLOBAL",13)
THEN
  RESPONSE #100
    SetName(@131)
    SetGlobal("#GNAMCHG","LOCALS",0)
END

IF
  Global("#GNAMCHG","LOCALS",1)
  Global("#GEMPCHK","LOCALS",1)
  Global("#GFAMLVL","GLOBAL",14)
THEN
  RESPONSE #100
    SetName(@132)
    SetGlobal("#GNAMCHG","LOCALS",0)
END

IF
  Global("#GNAMCHG","LOCALS",1)
  Global("#GEMPCHK","LOCALS",1)
  Global("#GFAMLVL","GLOBAL",15)
THEN
  RESPONSE #100
    SetName(@133)
    SetGlobal("#GNAMCHG","LOCALS",0)
END

IF
  Global("#GNAMCHG","LOCALS",1)
  Global("#GEMPCHK","LOCALS",1)
  Global("#GFAMLVL","GLOBAL",16)
THEN
  RESPONSE #100
    SetName(@134)
    SetGlobal("#GNAMCHG","LOCALS",0)
END

IF
  Global("#GNAMCHG","LOCALS",1)
  Global("#GEMPCHK","LOCALS",1)
  Global("#GFAMLVL","GLOBAL",17)
THEN
  RESPONSE #100
    SetName(@135)
    SetGlobal("#GNAMCHG","LOCALS",0)
END

IF
  Global("#GNAMCHG","LOCALS",1)
  Global("#GEMPCHK","LOCALS",1)
  Global("#GFAMLVL","GLOBAL",18)
THEN
  RESPONSE #100
    SetName(@136)
    SetGlobal("#GNAMCHG","LOCALS",0)
END

IF
  Global("#GNAMCHG","LOCALS",1)
  Global("#GEMPCHK","LOCALS",1)
  Global("#GFAMLVL","GLOBAL",19)
THEN
  RESPONSE #100
    SetName(@137)
    SetGlobal("#GNAMCHG","LOCALS",0)
END

IF
  Global("#GNAMCHG","LOCALS",1)
  Global("#GEMPCHK","LOCALS",1)
  Global("#GFAMLVL","GLOBAL",20)
THEN
  RESPONSE #100
    SetName(@138)
    SetGlobal("#GNAMCHG","LOCALS",0)
END

IF
  Global("#GNAMCHG","LOCALS",1)
  Global("#GEMPCHK","LOCALS",1)
  Global("#GFAMLVL","GLOBAL",21)
THEN
  RESPONSE #100
    SetName(@139)
    SetGlobal("#GNAMCHG","LOCALS",0)
END

IF
  Global("#GNAMCHG","LOCALS",1)
  Global("#GEMPCHK","LOCALS",1)
  Global("#GFAMLVL","GLOBAL",22)
THEN
  RESPONSE #100
    SetName(@140)
    SetGlobal("#GNAMCHG","LOCALS",0)
END

IF
  Global("#GNAMCHG","LOCALS",1)
  Global("#GEMPCHK","LOCALS",1)
  Global("#GFAMLVL","GLOBAL",23)
THEN
  RESPONSE #100
    SetName(@141)
    SetGlobal("#GNAMCHG","LOCALS",0)
END

IF
  Global("#GNAMCHG","LOCALS",1)
  Global("#GEMPCHK","LOCALS",1)
  Global("#GFAMLVL","GLOBAL",24)
THEN
  RESPONSE #100
    SetName(@142)
    SetGlobal("#GNAMCHG","LOCALS",0)
END

IF
  Global("#GNAMCHG","LOCALS",1)
  Global("#GEMPCHK","LOCALS",1)
  Global("#GFAMLVL","GLOBAL",25)
THEN
  RESPONSE #100
    SetName(@143)
    SetGlobal("#GNAMCHG","LOCALS",0)
END

IF
  Global("#GNAMCHG","LOCALS",1)
  Global("#GEMPCHK","LOCALS",1)
  Global("#GFAMLVL","GLOBAL",26)
THEN
  RESPONSE #100
    SetName(@144)
    SetGlobal("#GNAMCHG","LOCALS",0)
END

IF
  Global("#GNAMCHG","LOCALS",1)
  Global("#GEMPCHK","LOCALS",1)
  Global("#GFAMLVL","GLOBAL",27)
THEN
  RESPONSE #100
    SetName(@145)
    SetGlobal("#GNAMCHG","LOCALS",0)
END

IF
  Global("#GNAMCHG","LOCALS",1)
  Global("#GEMPCHK","LOCALS",1)
  Global("#GFAMLVL","GLOBAL",28)
THEN
  RESPONSE #100
    SetName(@146)
    SetGlobal("#GNAMCHG","LOCALS",0)
END

IF
  Global("#GNAMCHG","LOCALS",1)
  Global("#GEMPCHK","LOCALS",1)
  Global("#GFAMLVL","GLOBAL",29)
THEN
  RESPONSE #100
    SetName(@147)
    SetGlobal("#GNAMCHG","LOCALS",0)
END

IF
  Global("#GNAMCHG","LOCALS",1)
  Global("#GEMPCHK","LOCALS",1)
  Global("#GFAMLVL","GLOBAL",30)
THEN
  RESPONSE #100
    SetName(@148)
    SetGlobal("#GNAMCHG","LOCALS",0)
END

IF
  Global("#GNAMCHG","LOCALS",1)
  Global("#GEMPCHK","LOCALS",1)
  Global("#GFAMLVL","GLOBAL",31)
THEN
  RESPONSE #100
    SetName(@149)
    SetGlobal("#GNAMCHG","LOCALS",0)
END

IF
  Global("#GNAMCHG","LOCALS",1)
  Global("#GEMPCHK","LOCALS",1)
  Global("#GFAMLVL","GLOBAL",32)
THEN
  RESPONSE #100
    SetName(@150)
    SetGlobal("#GNAMCHG","LOCALS",0)
END

IF
  Global("#GNAMCHG","LOCALS",1)
  Global("#GEMPCHK","LOCALS",1)
  Global("#GFAMLVL","GLOBAL",33)
THEN
  RESPONSE #100
    SetName(@151)
    SetGlobal("#GNAMCHG","LOCALS",0)
END

IF
  Global("#GNAMCHG","LOCALS",1)
  Global("#GEMPCHK","LOCALS",1)
  Global("#GFAMLVL","GLOBAL",34)
THEN
  RESPONSE #100
    SetName(@152)
    SetGlobal("#GNAMCHG","LOCALS",0)
END

IF
  Global("#GNAMCHG","LOCALS",1)
  Global("#GEMPCHK","LOCALS",1)
  Global("#GFAMLVL","GLOBAL",35)
THEN
  RESPONSE #100
    SetName(@153)
    SetGlobal("#GNAMCHG","LOCALS",0)
END

IF
  Global("#GNAMCHG","LOCALS",1)
  Global("#GEMPCHK","LOCALS",1)
  Global("#GFAMLVL","GLOBAL",36)
THEN
  RESPONSE #100
    SetName(@154)
    SetGlobal("#GNAMCHG","LOCALS",0)
END

IF
  Global("#GNAMCHG","LOCALS",1)
  Global("#GEMPCHK","LOCALS",1)
  Global("#GFAMLVL","GLOBAL",37)
THEN
  RESPONSE #100
    SetName(@155)
    SetGlobal("#GNAMCHG","LOCALS",0)
END

IF
  Global("#GNAMCHG","LOCALS",1)
  Global("#GEMPCHK","LOCALS",1)
  Global("#GFAMLVL","GLOBAL",38)
THEN
  RESPONSE #100
    SetName(@156)
    SetGlobal("#GNAMCHG","LOCALS",0)
END

IF
  Global("#GNAMCHG","LOCALS",1)
  Global("#GEMPCHK","LOCALS",1)
  Global("#GFAMLVL","GLOBAL",39)
THEN
  RESPONSE #100
    SetName(@157)
    SetGlobal("#GNAMCHG","LOCALS",0)
END

IF
  Global("#GNAMCHG","LOCALS",1)
  Global("#GEMPCHK","LOCALS",1)
  Global("#GFAMLVL","GLOBAL",40)
THEN
  RESPONSE #100
    SetName(@158)
    SetGlobal("#GNAMCHG","LOCALS",0)
END

IF
  Global("#GNAMCHG","LOCALS",1)
  Global("#GEMPCHK","LOCALS",1)
  Global("#GFAMLVL","GLOBAL",41)
THEN
  RESPONSE #100
    SetName(@159)
    SetGlobal("#GNAMCHG","LOCALS",0)
END

IF
  Global("#GNAMCHG","LOCALS",1)
  Global("#GEMPCHK","LOCALS",1)
  Global("#GFAMLVL","GLOBAL",42)
THEN
  RESPONSE #100
    SetName(@160)
    SetGlobal("#GNAMCHG","LOCALS",0)
END

IF
  Global("#GNAMCHG","LOCALS",1)
  Global("#GEMPCHK","LOCALS",1)
  Global("#GFAMLVL","GLOBAL",43)
THEN
  RESPONSE #100
    SetName(@161)
    SetGlobal("#GNAMCHG","LOCALS",0)
END

IF
  Global("#GNAMCHG","LOCALS",1)
  Global("#GEMPCHK","LOCALS",1)
  Global("#GFAMLVL","GLOBAL",44)
THEN
  RESPONSE #100
    SetName(@162)
    SetGlobal("#GNAMCHG","LOCALS",0)
END

IF
  Global("#GNAMCHG","LOCALS",1)
  Global("#GEMPCHK","LOCALS",1)
  Global("#GFAMLVL","GLOBAL",45)
THEN
  RESPONSE #100
    SetName(@163)
    SetGlobal("#GNAMCHG","LOCALS",0)
END

IF
  Global("#GNAMCHG","LOCALS",1)
  Global("#GEMPCHK","LOCALS",1)
  Global("#GFAMLVL","GLOBAL",46)
THEN
  RESPONSE #100
    SetName(@164)
    SetGlobal("#GNAMCHG","LOCALS",0)
END

IF
  Global("#GNAMCHG","LOCALS",1)
  Global("#GEMPCHK","LOCALS",1)
  Global("#GFAMLVL","GLOBAL",47)
THEN
  RESPONSE #100
    SetName(@165)
    SetGlobal("#GNAMCHG","LOCALS",0)
END

IF
  Global("#GNAMCHG","LOCALS",1)
  Global("#GEMPCHK","LOCALS",1)
  Global("#GFAMLVL","GLOBAL",48)
THEN
  RESPONSE #100
    SetName(@166)
    SetGlobal("#GNAMCHG","LOCALS",0)
END

IF
  Global("#GNAMCHG","LOCALS",1)
  Global("#GEMPCHK","LOCALS",1)
  Global("#GFAMLVL","GLOBAL",49)
THEN
  RESPONSE #100
    SetName(@167)
    SetGlobal("#GNAMCHG","LOCALS",0)
END
