////////////////////////////////////////////
///FERRET				 ///
////////////////////////////////////////////

/////////////////
///Summoned   ///
/////////////////

IF
  Global("WTPFAMLN","GLOBAL",2)
  Global("#GSUMMON","LOCALS",1)
THEN
  RESPONSE #100
    Wait(3)
    DisplayStringHead(Myself,@535)
    ActionOverride(Player1,ReallyForceSpellRES("WTPFCon2",Myself))
    SetGlobal("SPRITE_IS_DEADWTPFERRE","GLOBAL",0)
    SetGlobal("#GSUMMON","LOCALS",2)
END

IF
  Global("#GSUMMON","LOCALS",2)
  Delay(2)
THEN
  RESPONSE #20
    SetGlobal("#GSUMMON","LOCALS",3)
    ActionOverride(Player1,FaceObject("WTPFerre"))
    Wait(1)
    DisplayStringHead(Player1,@539)
  RESPONSE #20
    SetGlobal("#GSUMMON","LOCALS",3)
    ActionOverride(Player1,FaceObject("WTPFerre"))
    Wait(1)
    DisplayStringHead(Player1,@540)
  RESPONSE #20
    SetGlobal("#GSUMMON","LOCALS",3)
    ActionOverride(Player1,FaceObject("WTPFerre"))
    Wait(1)
    DisplayStringHead(Player1,@541)
  RESPONSE #20
    SetGlobal("#GSUMMON","LOCALS",3)
    ActionOverride(Player1,FaceObject("WTPFerre"))
    Wait(1)
    DisplayStringHead(Player1,@542)
  RESPONSE #20
    SetGlobal("#GSUMMON","LOCALS",3)
    ActionOverride(Player1,FaceObject("WTPFerre"))
    Wait(1)
    DisplayStringHead(Player1,@543)
END

///////////////
///Status   ///
///////////////

IF
  Global("WTPSTAT","LOCALS",0)
  OR(15)
    StateCheck(Myself,STATE_PANIC)
    StateCheck(Myself,STATE_HELPLESS)
    StateCheck(Myself,STATE_SLEEPING)
    StateCheck(Myself,STATE_BERSERK)
    StateCheck(Myself,STATE_CHARMED)
    StateCheck(Myself,STATE_FEEBLEMINDED)
    StateCheck(Myself,STATE_CONFUSED)
    StateCheck(Myself,STATE_STONE_DEATH)
    StateCheck(Player1,STATE_PANIC)
    StateCheck(Player1,STATE_HELPLESS)
    StateCheck(Player1,STATE_SLEEPING)
    StateCheck(Player1,STATE_BERSERK)
    StateCheck(Player1,STATE_CHARMED)
    StateCheck(Player1,STATE_FEEBLEMINDED)
    StateCheck(Player1,STATE_CONFUSED)
THEN
  RESPONSE #100
    SetGlobal("WTPSTAT","LOCALS",1)
END

IF
  Global("WTPSTAT","LOCALS",1)
  !StateCheck(Myself,STATE_PANIC)
  !StateCheck(Myself,STATE_HELPLESS)
  !StateCheck(Myself,STATE_SLEEPING)
  !StateCheck(Myself,STATE_BERSERK)
  !StateCheck(Myself,STATE_CHARMED)
  !StateCheck(Myself,STATE_FEEBLEMINDED)
  !StateCheck(Myself,STATE_CONFUSED)
  !StateCheck(Myself,STATE_STONE_DEATH)
  !StateCheck(Player1,STATE_PANIC)
  !StateCheck(Player1,STATE_HELPLESS)
  !StateCheck(Player1,STATE_SLEEPING)
  !StateCheck(Player1,STATE_BERSERK)
  !StateCheck(Player1,STATE_CHARMED)
  !StateCheck(Player1,STATE_FEEBLEMINDED)
  !StateCheck(Player1,STATE_CONFUSED)
THEN
  RESPONSE #100
    SetGlobal("WTPSTAT","LOCALS",0)
END

///////////////////////
///Mage Class       ///
///////////////////////

IF
  Global("#GMAGECLASS","LOCALS",0)
  !FallenRanger(Player1)
  OR(4)
    Class(Player1,MAGE_ALL)
    Class(Player1,BARD)
    Kit(Player1,BEASTMASTER)
    CheckStat(Player1,1,191)
THEN
  RESPONSE #100
    SetGlobal("#GMAGECLASS","LOCALS",1)
END

IF
  Global("#GMAGECLASS","LOCALS",1)
  OR(6)
    Class(Player1,CLERIC_MAGE)  // first 4 ORs cover multiclasses and dual classes M->F and M->C
    Class(Player1,FIGHTER_MAGE)
    Class(Player1,CLERIC_THIEF)
    Class(Player1,FIGHTER_THIEF)
    Class(Player1,FIGHTER_MAGE_THIEF)
    Class(Player1,FIGHTER_MAGE_CLERIC)
  OriginalClass(Player1,FIGHTER) // this covers dual class F->M and F->T
  OriginalClass(Player1,CLERIC) // this covers dual class C->M and C->T
THEN
  RESPONSE #100
    SetGlobal("#GMAGECLASS","LOCALS",2)
END

IF
  Global("#GMAGECLASS","LOCALS",1)
  TriggerOverride(Player1,Global("#GSCRFAI","LOCALS",1))	// this covers the unique case where a dual M/T with UAI uses the Find Familiar scroll
  CheckStat(Player1,1,191)
THEN
  RESPONSE #100
    SetGlobal("#GMAGECLASS","LOCALS",2)
    ActionOverride(Player1,SetGlobal("#GSCRFAI","LOCALS",0))
END

//////////////////////
///Acquire mage Lv ///
//////////////////////

IF
  Global("#GMAGECLASS","LOCALS",1)
  CheckStat(Player1,2,LEVEL)
  GlobalLT("#GPLALVL","GLOBAL",1)
THEN
  RESPONSE #100
    SetGlobal("#GPLALVL","GLOBAL",1)
END

IF
  Global("#GMAGECLASS","LOCALS",2)
  CheckStat(Player1,2,LEVEL2)
  GlobalLT("#GPLALVL","GLOBAL",1)
THEN
  RESPONSE #100
    SetGlobal("#GPLALVL","GLOBAL",1)
END

IF
  Global("#GMAGECLASS","LOCALS",1)
  CheckStat(Player1,3,LEVEL)
  GlobalLT("#GPLALVL","GLOBAL",2)
THEN
  RESPONSE #100
    SetGlobal("#GPLALVL","GLOBAL",2)
END

IF
  Global("#GMAGECLASS","LOCALS",2)
  CheckStat(Player1,3,LEVEL2)
  GlobalLT("#GPLALVL","GLOBAL",2)
THEN
  RESPONSE #100
    SetGlobal("#GPLALVL","GLOBAL",2)
END

IF
  Global("#GMAGECLASS","LOCALS",1)
  CheckStat(Player1,4,LEVEL)
  GlobalLT("#GPLALVL","GLOBAL",3)
THEN
  RESPONSE #100
    SetGlobal("#GPLALVL","GLOBAL",3)
END

IF
  Global("#GMAGECLASS","LOCALS",2)
  CheckStat(Player1,4,LEVEL2)
  GlobalLT("#GPLALVL","GLOBAL",3)
THEN
  RESPONSE #100
    SetGlobal("#GPLALVL","GLOBAL",3)
END

IF
  Global("#GMAGECLASS","LOCALS",1)
  CheckStat(Player1,5,LEVEL)
  GlobalLT("#GPLALVL","GLOBAL",4)
THEN
  RESPONSE #100
    SetGlobal("#GPLALVL","GLOBAL",4)
END

IF
  Global("#GMAGECLASS","LOCALS",2)
  CheckStat(Player1,5,LEVEL2)
  GlobalLT("#GPLALVL","GLOBAL",4)
THEN
  RESPONSE #100
    SetGlobal("#GPLALVL","GLOBAL",4)
END

IF
  Global("#GMAGECLASS","LOCALS",1)
  CheckStat(Player1,6,LEVEL)
  GlobalLT("#GPLALVL","GLOBAL",5)
THEN
  RESPONSE #100
    SetGlobal("#GPLALVL","GLOBAL",5)
END

IF
  Global("#GMAGECLASS","LOCALS",2)
  CheckStat(Player1,6,LEVEL2)
  GlobalLT("#GPLALVL","GLOBAL",5)
THEN
  RESPONSE #100
    SetGlobal("#GPLALVL","GLOBAL",5)
END

IF
  Global("#GMAGECLASS","LOCALS",1)
  CheckStat(Player1,7,LEVEL)
  GlobalLT("#GPLALVL","GLOBAL",6)
THEN
  RESPONSE #100
    SetGlobal("#GPLALVL","GLOBAL",6)
END

IF
  Global("#GMAGECLASS","LOCALS",2)
  CheckStat(Player1,7,LEVEL2)
  GlobalLT("#GPLALVL","GLOBAL",6)
THEN
  RESPONSE #100
    SetGlobal("#GPLALVL","GLOBAL",6)
END

IF
  Global("#GMAGECLASS","LOCALS",1)
  CheckStat(Player1,8,LEVEL)
  GlobalLT("#GPLALVL","GLOBAL",7)
THEN
  RESPONSE #100
    SetGlobal("#GPLALVL","GLOBAL",7)
END

IF
  Global("#GMAGECLASS","LOCALS",2)
  CheckStat(Player1,8,LEVEL2)
  GlobalLT("#GPLALVL","GLOBAL",7)
THEN
  RESPONSE #100
    SetGlobal("#GPLALVL","GLOBAL",7)
END

IF
  Global("#GMAGECLASS","LOCALS",1)
  CheckStat(Player1,9,LEVEL)
  GlobalLT("#GPLALVL","GLOBAL",8)
THEN
  RESPONSE #100
    SetGlobal("#GPLALVL","GLOBAL",8)
END

IF
  Global("#GMAGECLASS","LOCALS",2)
  CheckStat(Player1,9,LEVEL2)
  GlobalLT("#GPLALVL","GLOBAL",8)
THEN
  RESPONSE #100
    SetGlobal("#GPLALVL","GLOBAL",8)
END

IF
  Global("#GMAGECLASS","LOCALS",1)
  CheckStat(Player1,10,LEVEL)
  GlobalLT("#GPLALVL","GLOBAL",9)
THEN
  RESPONSE #100
    SetGlobal("#GPLALVL","GLOBAL",9)
END

IF
  Global("#GMAGECLASS","LOCALS",2)
  CheckStat(Player1,10,LEVEL2)
  GlobalLT("#GPLALVL","GLOBAL",9)
THEN
  RESPONSE #100
    SetGlobal("#GPLALVL","GLOBAL",9)
END

IF
  Global("#GMAGECLASS","LOCALS",1)
  CheckStat(Player1,11,LEVEL)
  GlobalLT("#GPLALVL","GLOBAL",10)
THEN
  RESPONSE #100
    SetGlobal("#GPLALVL","GLOBAL",10)
END

IF
  Global("#GMAGECLASS","LOCALS",2)
  CheckStat(Player1,11,LEVEL2)
  GlobalLT("#GPLALVL","GLOBAL",10)
THEN
  RESPONSE #100
    SetGlobal("#GPLALVL","GLOBAL",10)
END

IF
  Global("#GMAGECLASS","LOCALS",1)
  CheckStat(Player1,12,LEVEL)
  GlobalLT("#GPLALVL","GLOBAL",11)
THEN
  RESPONSE #100
    SetGlobal("#GPLALVL","GLOBAL",11)
END

IF
  Global("#GMAGECLASS","LOCALS",2)
  CheckStat(Player1,12,LEVEL2)
  GlobalLT("#GPLALVL","GLOBAL",11)
THEN
  RESPONSE #100
    SetGlobal("#GPLALVL","GLOBAL",11)
END

IF
  Global("#GMAGECLASS","LOCALS",1)
  CheckStat(Player1,13,LEVEL)
  GlobalLT("#GPLALVL","GLOBAL",12)
THEN
  RESPONSE #100
    SetGlobal("#GPLALVL","GLOBAL",12)
END

IF
  Global("#GMAGECLASS","LOCALS",2)
  CheckStat(Player1,13,LEVEL2)
  GlobalLT("#GPLALVL","GLOBAL",12)
THEN
  RESPONSE #100
    SetGlobal("#GPLALVL","GLOBAL",12)
END

IF
  Global("#GMAGECLASS","LOCALS",1)
  CheckStat(Player1,14,LEVEL)
  GlobalLT("#GPLALVL","GLOBAL",13)
THEN
  RESPONSE #100
    SetGlobal("#GPLALVL","GLOBAL",13)
END

IF
  Global("#GMAGECLASS","LOCALS",2)
  CheckStat(Player1,14,LEVEL2)
  GlobalLT("#GPLALVL","GLOBAL",13)
THEN
  RESPONSE #100
    SetGlobal("#GPLALVL","GLOBAL",13)
END

IF
  Global("#GMAGECLASS","LOCALS",1)
  CheckStat(Player1,15,LEVEL)
  GlobalLT("#GPLALVL","GLOBAL",14)
THEN
  RESPONSE #100
    SetGlobal("#GPLALVL","GLOBAL",14)
END

IF
  Global("#GMAGECLASS","LOCALS",2)
  CheckStat(Player1,15,LEVEL2)
  GlobalLT("#GPLALVL","GLOBAL",14)
THEN
  RESPONSE #100
    SetGlobal("#GPLALVL","GLOBAL",14)
END

IF
  Global("#GMAGECLASS","LOCALS",1)
  CheckStat(Player1,16,LEVEL)
  GlobalLT("#GPLALVL","GLOBAL",15)
THEN
  RESPONSE #100
    SetGlobal("#GPLALVL","GLOBAL",15)
END

IF
  Global("#GMAGECLASS","LOCALS",2)
  CheckStat(Player1,16,LEVEL2)
  GlobalLT("#GPLALVL","GLOBAL",15)
THEN
  RESPONSE #100
    SetGlobal("#GPLALVL","GLOBAL",15)
END

IF
  Global("#GMAGECLASS","LOCALS",1)
  CheckStat(Player1,17,LEVEL)
  GlobalLT("#GPLALVL","GLOBAL",16)
THEN
  RESPONSE #100
    SetGlobal("#GPLALVL","GLOBAL",16)
END

IF
  Global("#GMAGECLASS","LOCALS",2)
  CheckStat(Player1,17,LEVEL2)
  GlobalLT("#GPLALVL","GLOBAL",16)
THEN
  RESPONSE #100
    SetGlobal("#GPLALVL","GLOBAL",16)
END

IF
  Global("#GMAGECLASS","LOCALS",1)
  CheckStat(Player1,18,LEVEL)
  GlobalLT("#GPLALVL","GLOBAL",17)
THEN
  RESPONSE #100
    SetGlobal("#GPLALVL","GLOBAL",17)
END

IF
  Global("#GMAGECLASS","LOCALS",2)
  CheckStat(Player1,18,LEVEL2)
  GlobalLT("#GPLALVL","GLOBAL",17)
THEN
  RESPONSE #100
    SetGlobal("#GPLALVL","GLOBAL",17)
END

IF
  Global("#GMAGECLASS","LOCALS",1)
  CheckStat(Player1,19,LEVEL)
  GlobalLT("#GPLALVL","GLOBAL",18)
THEN
  RESPONSE #100
    SetGlobal("#GPLALVL","GLOBAL",18)
END

IF
  Global("#GMAGECLASS","LOCALS",2)
  CheckStat(Player1,19,LEVEL2)
  GlobalLT("#GPLALVL","GLOBAL",18)
THEN
  RESPONSE #100
    SetGlobal("#GPLALVL","GLOBAL",18)
END

IF
  Global("#GMAGECLASS","LOCALS",1)
  CheckStat(Player1,20,LEVEL)
  GlobalLT("#GPLALVL","GLOBAL",19)
THEN
  RESPONSE #100
    SetGlobal("#GPLALVL","GLOBAL",19)
END

IF
  Global("#GMAGECLASS","LOCALS",2)
  CheckStat(Player1,20,LEVEL2)
  GlobalLT("#GPLALVL","GLOBAL",19)
THEN
  RESPONSE #100
    SetGlobal("#GPLALVL","GLOBAL",19)
END

IF
  Global("#GMAGECLASS","LOCALS",1)
  CheckStat(Player1,21,LEVEL)
  GlobalLT("#GPLALVL","GLOBAL",20)
THEN
  RESPONSE #100
    SetGlobal("#GPLALVL","GLOBAL",20)
END

IF
  Global("#GMAGECLASS","LOCALS",2)
  CheckStat(Player1,21,LEVEL2)
  GlobalLT("#GPLALVL","GLOBAL",20)
THEN
  RESPONSE #100
    SetGlobal("#GPLALVL","GLOBAL",20)
END

IF
  Global("#GMAGECLASS","LOCALS",1)
  CheckStat(Player1,22,LEVEL)
  GlobalLT("#GPLALVL","GLOBAL",21)
THEN
  RESPONSE #100
    SetGlobal("#GPLALVL","GLOBAL",21)
END

IF
  Global("#GMAGECLASS","LOCALS",2)
  CheckStat(Player1,22,LEVEL2)
  GlobalLT("#GPLALVL","GLOBAL",21)
THEN
  RESPONSE #100
    SetGlobal("#GPLALVL","GLOBAL",21)
END

IF
  Global("#GMAGECLASS","LOCALS",1)
  CheckStat(Player1,23,LEVEL)
  GlobalLT("#GPLALVL","GLOBAL",22)
THEN
  RESPONSE #100
    SetGlobal("#GPLALVL","GLOBAL",22)
END

IF
  Global("#GMAGECLASS","LOCALS",2)
  CheckStat(Player1,23,LEVEL2)
  GlobalLT("#GPLALVL","GLOBAL",22)
THEN
  RESPONSE #100
    SetGlobal("#GPLALVL","GLOBAL",22)
END

IF
  Global("#GMAGECLASS","LOCALS",1)
  CheckStat(Player1,24,LEVEL)
  GlobalLT("#GPLALVL","GLOBAL",23)
THEN
  RESPONSE #100
    SetGlobal("#GPLALVL","GLOBAL",23)
END

IF
  Global("#GMAGECLASS","LOCALS",2)
  CheckStat(Player1,24,LEVEL2)
  GlobalLT("#GPLALVL","GLOBAL",23)
THEN
  RESPONSE #100
    SetGlobal("#GPLALVL","GLOBAL",23)
END

IF
  Global("#GMAGECLASS","LOCALS",1)
  CheckStat(Player1,25,LEVEL)
  GlobalLT("#GPLALVL","GLOBAL",24)
THEN
  RESPONSE #100
    SetGlobal("#GPLALVL","GLOBAL",24)
END

IF
  Global("#GMAGECLASS","LOCALS",2)
  CheckStat(Player1,25,LEVEL2)
  GlobalLT("#GPLALVL","GLOBAL",24)
THEN
  RESPONSE #100
    SetGlobal("#GPLALVL","GLOBAL",24)
END

IF
  Global("#GMAGECLASS","LOCALS",1)
  CheckStat(Player1,26,LEVEL)
  GlobalLT("#GPLALVL","GLOBAL",25)
THEN
  RESPONSE #100
    SetGlobal("#GPLALVL","GLOBAL",25)
END

IF
  Global("#GMAGECLASS","LOCALS",2)
  CheckStat(Player1,26,LEVEL2)
  GlobalLT("#GPLALVL","GLOBAL",25)
THEN
  RESPONSE #100
    SetGlobal("#GPLALVL","GLOBAL",25)
END

IF
  Global("#GMAGECLASS","LOCALS",1)
  CheckStat(Player1,27,LEVEL)
  GlobalLT("#GPLALVL","GLOBAL",26)
THEN
  RESPONSE #100
    SetGlobal("#GPLALVL","GLOBAL",26)
END

IF
  Global("#GMAGECLASS","LOCALS",2)
  CheckStat(Player1,27,LEVEL2)
  GlobalLT("#GPLALVL","GLOBAL",26)
THEN
  RESPONSE #100
    SetGlobal("#GPLALVL","GLOBAL",26)
END

IF
  Global("#GMAGECLASS","LOCALS",1)
  CheckStat(Player1,28,LEVEL)
  GlobalLT("#GPLALVL","GLOBAL",27)
THEN
  RESPONSE #100
    SetGlobal("#GPLALVL","GLOBAL",27)
END

IF
  Global("#GMAGECLASS","LOCALS",2)
  CheckStat(Player1,28,LEVEL2)
  GlobalLT("#GPLALVL","GLOBAL",27)
THEN
  RESPONSE #100
    SetGlobal("#GPLALVL","GLOBAL",27)
END

IF
  Global("#GMAGECLASS","LOCALS",1)
  CheckStat(Player1,29,LEVEL)
  GlobalLT("#GPLALVL","GLOBAL",28)
THEN
  RESPONSE #100
    SetGlobal("#GPLALVL","GLOBAL",28)
END

IF
  Global("#GMAGECLASS","LOCALS",2)
  CheckStat(Player1,29,LEVEL2)
  GlobalLT("#GPLALVL","GLOBAL",28)
THEN
  RESPONSE #100
    SetGlobal("#GPLALVL","GLOBAL",28)
END

IF
  Global("#GMAGECLASS","LOCALS",1)
  CheckStat(Player1,30,LEVEL)
  GlobalLT("#GPLALVL","GLOBAL",29)
THEN
  RESPONSE #100
    SetGlobal("#GPLALVL","GLOBAL",29)
END

IF
  Global("#GMAGECLASS","LOCALS",2)
  CheckStat(Player1,30,LEVEL2)
  GlobalLT("#GPLALVL","GLOBAL",29)
THEN
  RESPONSE #100
    SetGlobal("#GPLALVL","GLOBAL",29)
END

IF
  Global("#GMAGECLASS","LOCALS",1)
  CheckStat(Player1,31,LEVEL)
  GlobalLT("#GPLALVL","GLOBAL",30)
THEN
  RESPONSE #100
    SetGlobal("#GPLALVL","GLOBAL",30)
END

IF
  Global("#GMAGECLASS","LOCALS",2)
  CheckStat(Player1,31,LEVEL2)
  GlobalLT("#GPLALVL","GLOBAL",30)
THEN
  RESPONSE #100
    SetGlobal("#GPLALVL","GLOBAL",30)
END

IF
  Global("#GMAGECLASS","LOCALS",1)
  CheckStat(Player1,32,LEVEL)
  GlobalLT("#GPLALVL","GLOBAL",31)
THEN
  RESPONSE #100
    SetGlobal("#GPLALVL","GLOBAL",31)
END

IF
  Global("#GMAGECLASS","LOCALS",2)
  CheckStat(Player1,32,LEVEL2)
  GlobalLT("#GPLALVL","GLOBAL",31)
THEN
  RESPONSE #100
    SetGlobal("#GPLALVL","GLOBAL",31)
END

IF
  Global("#GMAGECLASS","LOCALS",1)
  CheckStat(Player1,33,LEVEL)
  GlobalLT("#GPLALVL","GLOBAL",32)
THEN
  RESPONSE #100
    SetGlobal("#GPLALVL","GLOBAL",32)
END

IF
  Global("#GMAGECLASS","LOCALS",2)
  CheckStat(Player1,33,LEVEL2)
  GlobalLT("#GPLALVL","GLOBAL",32)
THEN
  RESPONSE #100
    SetGlobal("#GPLALVL","GLOBAL",32)
END

IF
  Global("#GMAGECLASS","LOCALS",1)
  CheckStat(Player1,34,LEVEL)
  GlobalLT("#GPLALVL","GLOBAL",33)
THEN
  RESPONSE #100
    SetGlobal("#GPLALVL","GLOBAL",33)
END

IF
  Global("#GMAGECLASS","LOCALS",2)
  CheckStat(Player1,34,LEVEL2)
  GlobalLT("#GPLALVL","GLOBAL",33)
THEN
  RESPONSE #100
    SetGlobal("#GPLALVL","GLOBAL",33)
END

IF
  Global("#GMAGECLASS","LOCALS",1)
  CheckStat(Player1,35,LEVEL)
  GlobalLT("#GPLALVL","GLOBAL",34)
THEN
  RESPONSE #100
    SetGlobal("#GPLALVL","GLOBAL",34)
END

IF
  Global("#GMAGECLASS","LOCALS",2)
  CheckStat(Player1,35,LEVEL2)
  GlobalLT("#GPLALVL","GLOBAL",34)
THEN
  RESPONSE #100
    SetGlobal("#GPLALVL","GLOBAL",34)
END

IF
  Global("#GMAGECLASS","LOCALS",1)
  CheckStat(Player1,36,LEVEL)
  GlobalLT("#GPLALVL","GLOBAL",35)
THEN
  RESPONSE #100
    SetGlobal("#GPLALVL","GLOBAL",35)
END

IF
  Global("#GMAGECLASS","LOCALS",2)
  CheckStat(Player1,36,LEVEL2)
  GlobalLT("#GPLALVL","GLOBAL",35)
THEN
  RESPONSE #100
    SetGlobal("#GPLALVL","GLOBAL",35)
END

IF
  Global("#GMAGECLASS","LOCALS",1)
  CheckStat(Player1,37,LEVEL)
  GlobalLT("#GPLALVL","GLOBAL",36)
THEN
  RESPONSE #100
    SetGlobal("#GPLALVL","GLOBAL",36)
END

IF
  Global("#GMAGECLASS","LOCALS",2)
  CheckStat(Player1,37,LEVEL2)
  GlobalLT("#GPLALVL","GLOBAL",36)
THEN
  RESPONSE #100
    SetGlobal("#GPLALVL","GLOBAL",36)
END

IF
  Global("#GMAGECLASS","LOCALS",1)
  CheckStat(Player1,38,LEVEL)
  GlobalLT("#GPLALVL","GLOBAL",37)
THEN
  RESPONSE #100
    SetGlobal("#GPLALVL","GLOBAL",37)
END

IF
  Global("#GMAGECLASS","LOCALS",2)
  CheckStat(Player1,38,LEVEL2)
  GlobalLT("#GPLALVL","GLOBAL",37)
THEN
  RESPONSE #100
    SetGlobal("#GPLALVL","GLOBAL",37)
END

IF
  Global("#GMAGECLASS","LOCALS",1)
  CheckStat(Player1,39,LEVEL)
  GlobalLT("#GPLALVL","GLOBAL",38)
THEN
  RESPONSE #100
    SetGlobal("#GPLALVL","GLOBAL",38)
END

IF
  Global("#GMAGECLASS","LOCALS",2)
  CheckStat(Player1,39,LEVEL2)
  GlobalLT("#GPLALVL","GLOBAL",38)
THEN
  RESPONSE #100
    SetGlobal("#GPLALVL","GLOBAL",38)
END

IF
  Global("#GMAGECLASS","LOCALS",1)
  CheckStat(Player1,40,LEVEL)
  GlobalLT("#GPLALVL","GLOBAL",39)
THEN
  RESPONSE #100
    SetGlobal("#GPLALVL","GLOBAL",39)
END

IF
  Global("#GMAGECLASS","LOCALS",2)
  CheckStat(Player1,40,LEVEL2)
  GlobalLT("#GPLALVL","GLOBAL",39)
THEN
  RESPONSE #100
    SetGlobal("#GPLALVL","GLOBAL",39)
END

IF
  Global("#GMAGECLASS","LOCALS",1)
  CheckStat(Player1,41,LEVEL)
  GlobalLT("#GPLALVL","GLOBAL",40)
THEN
  RESPONSE #100
    SetGlobal("#GPLALVL","GLOBAL",40)
END

IF
  Global("#GMAGECLASS","LOCALS",2)
  CheckStat(Player1,41,LEVEL2)
  GlobalLT("#GPLALVL","GLOBAL",40)
THEN
  RESPONSE #100
    SetGlobal("#GPLALVL","GLOBAL",40)
END

IF
  Global("#GMAGECLASS","LOCALS",1)
  CheckStat(Player1,42,LEVEL)
  GlobalLT("#GPLALVL","GLOBAL",41)
THEN
  RESPONSE #100
    SetGlobal("#GPLALVL","GLOBAL",41)
END

IF
  Global("#GMAGECLASS","LOCALS",2)
  CheckStat(Player1,42,LEVEL2)
  GlobalLT("#GPLALVL","GLOBAL",41)
THEN
  RESPONSE #100
    SetGlobal("#GPLALVL","GLOBAL",41)
END

IF
  Global("#GMAGECLASS","LOCALS",1)
  CheckStat(Player1,43,LEVEL)
  GlobalLT("#GPLALVL","GLOBAL",42)
THEN
  RESPONSE #100
    SetGlobal("#GPLALVL","GLOBAL",42)
END

IF
  Global("#GMAGECLASS","LOCALS",2)
  CheckStat(Player1,43,LEVEL2)
  GlobalLT("#GPLALVL","GLOBAL",42)
THEN
  RESPONSE #100
    SetGlobal("#GPLALVL","GLOBAL",42)
END

IF
  Global("#GMAGECLASS","LOCALS",1)
  CheckStat(Player1,44,LEVEL)
  GlobalLT("#GPLALVL","GLOBAL",43)
THEN
  RESPONSE #100
    SetGlobal("#GPLALVL","GLOBAL",43)
END

IF
  Global("#GMAGECLASS","LOCALS",2)
  CheckStat(Player1,44,LEVEL2)
  GlobalLT("#GPLALVL","GLOBAL",43)
THEN
  RESPONSE #100
    SetGlobal("#GPLALVL","GLOBAL",43)
END

IF
  Global("#GMAGECLASS","LOCALS",1)
  CheckStat(Player1,45,LEVEL)
  GlobalLT("#GPLALVL","GLOBAL",44)
THEN
  RESPONSE #100
    SetGlobal("#GPLALVL","GLOBAL",44)
END

IF
  Global("#GMAGECLASS","LOCALS",2)
  CheckStat(Player1,45,LEVEL2)
  GlobalLT("#GPLALVL","GLOBAL",44)
THEN
  RESPONSE #100
    SetGlobal("#GPLALVL","GLOBAL",44)
END

IF
  Global("#GMAGECLASS","LOCALS",1)
  CheckStat(Player1,46,LEVEL)
  GlobalLT("#GPLALVL","GLOBAL",45)
THEN
  RESPONSE #100
    SetGlobal("#GPLALVL","GLOBAL",45)
END

IF
  Global("#GMAGECLASS","LOCALS",2)
  CheckStat(Player1,46,LEVEL2)
  GlobalLT("#GPLALVL","GLOBAL",45)
THEN
  RESPONSE #100
    SetGlobal("#GPLALVL","GLOBAL",45)
END

IF
  Global("#GMAGECLASS","LOCALS",1)
  CheckStat(Player1,47,LEVEL)
  GlobalLT("#GPLALVL","GLOBAL",46)
THEN
  RESPONSE #100
    SetGlobal("#GPLALVL","GLOBAL",46)
END

IF
  Global("#GMAGECLASS","LOCALS",2)
  CheckStat(Player1,47,LEVEL2)
  GlobalLT("#GPLALVL","GLOBAL",46)
THEN
  RESPONSE #100
    SetGlobal("#GPLALVL","GLOBAL",46)
END

IF
  Global("#GMAGECLASS","LOCALS",1)
  CheckStat(Player1,48,LEVEL)
  GlobalLT("#GPLALVL","GLOBAL",47)
THEN
  RESPONSE #100
    SetGlobal("#GPLALVL","GLOBAL",47)
END

IF
  Global("#GMAGECLASS","LOCALS",2)
  CheckStat(Player1,48,LEVEL2)
  GlobalLT("#GPLALVL","GLOBAL",47)
THEN
  RESPONSE #100
    SetGlobal("#GPLALVL","GLOBAL",47)
END

IF
  Global("#GMAGECLASS","LOCALS",1)
  CheckStat(Player1,49,LEVEL)
  GlobalLT("#GPLALVL","GLOBAL",48)
THEN
  RESPONSE #100
    SetGlobal("#GPLALVL","GLOBAL",48)
END

IF
  Global("#GMAGECLASS","LOCALS",2)
  CheckStat(Player1,49,LEVEL2)
  GlobalLT("#GPLALVL","GLOBAL",48)
THEN
  RESPONSE #100
    SetGlobal("#GPLALVL","GLOBAL",48)
END

IF
  Global("#GMAGECLASS","LOCALS",1)
  CheckStat(Player1,50,LEVEL)
  GlobalLT("#GPLALVL","GLOBAL",49)
THEN
  RESPONSE #100
    SetGlobal("#GPLALVL","GLOBAL",49)
END

IF
  Global("#GMAGECLASS","LOCALS",2)
  CheckStat(Player1,50,LEVEL2)
  GlobalLT("#GPLALVL","GLOBAL",49)
THEN
  RESPONSE #100
    SetGlobal("#GPLALVL","GLOBAL",49)
END

//////////////////////
///Summon resets   ///
//////////////////////

IF
  Global("#GSUMMON","LOCALS",3)
  GlobalsEqual("#GFAMLVL","#GPLALVL")
THEN
  RESPONSE #100
    Wait(4)
    MakeGlobal()
    AddFamiliar()
    ChangeEnemyAlly(Myself,FAMILIAR)
    EquipMostDamagingMelee()
    SetGlobal("#GSUMMON","LOCALS",0)
END

///////////////////////
///Breaking point   ///
///////////////////////

IF
  Global("#GMIRPEN","GLOBAL",2)
  GlobalTimerExpired("#GFAMHAR","GLOBAL")
THEN
  RESPONSE #100
    IncrementGlobal("#GMIRPEN","GLOBAL",-1)
    SetGlobalTimer("#GFAMHAR","GLOBAL",7200)
END

IF
  Global("#GMIRPEN","GLOBAL",1)
  GlobalTimerExpired("#GFAMHAR","GLOBAL")
THEN
  RESPONSE #100
    IncrementGlobal("#GMIRPEN","GLOBAL",-1)
END

IF
  Global("#GHARAS","GLOBAL",1)
  Global("#GINPACK", "GLOBAL", 0)
  Global("#GEMPOW","LOCALS",0)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    IncrementGlobal("#GHARAS","GLOBAL",1)
    Wait(2)
    Dialogue(Player1)
    SetInterrupt(TRUE)
END

IF
  Global("#GHARAS","GLOBAL",4)
  Global("#GINPACK", "GLOBAL", 0)
  Global("#GEMPOW","LOCALS",0)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    IncrementGlobal("#GHARAS","GLOBAL",1)
    Wait(2)
    Dialogue(Player1)
    SetInterrupt(TRUE)
END

IF
  Global("#GHARAS","GLOBAL",7)
  Global("#GINPACK", "GLOBAL", 0)
  Global("#GEMPOW","LOCALS",0)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    IncrementGlobal("#GHARAS","GLOBAL",1)
    Wait(2)
    Dialogue(Player1)
    SetInterrupt(TRUE)
END

///////////////////////
///Death Script     ///
///////////////////////

IF
  OR(2)
    Global("#GStartSpl","GLOBAL",0)
    HPGT(Player1,3)
  Die()
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    ActionOverride(Player1,Recoil())
    ActionOverride(Player1,VerbalConstant(Myself,DAMAGE))
    ActionOverride(Player1,ReallyForceSpellRES("WTPFCon4",Myself))
    ActionOverride(Player1,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(Player1,MakeUnselectable(4))
    DisplayString(Player1,8536)
    DisplayString(Player1,21004)
    CreateCreatureObjectOffScreen("wtpnag3",Myself,0,0,0)
    SetGlobalTimer("#Gmourn","GLOBAL", 21600)
    SetGlobal("WTPFAMLN","GLOBAL",0)
    SetGlobal("#GAFTER","GLOBAL",0)
    SetGlobal("#GFLVUP","GLOBAL",0)
    SetGlobal("#GHARAS","GLOBAL",0)
    SetGlobal("#GPLALVL","GLOBAL",0)
    SetGlobal("#GSHOCK","GLOBAL",1)
    SetGlobal("#GHPOFF","GLOBAL",1)
    SetGlobal("#GMIRPEN","GLOBAL",0)
    SetInterrupt(TRUE)
END

IF
  OR(2)
    Global("#GStartSpl","GLOBAL",0)
    HPGT(Player1,3)
  Global("#GFAMGO","GLOBAL",1)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    ActionOverride(Player1,Recoil())
    ActionOverride(Player1,VerbalConstant(Myself,DAMAGE))
    ActionOverride(Player1,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(Player1,ApplySpellRES("WTPDESP1",Myself))
    ActionOverride(Player1,MakeUnselectable(4))
    DisplayString(Player1,@522)
    SetGlobalTimer("#Gmourn","GLOBAL", 21600)
    SetGlobal("WTPFAMLN","GLOBAL",0)
    SetGlobal("#GAFTER","GLOBAL",0)
    SetGlobal("#GFLVUP","GLOBAL",0)
    SetGlobal("#GHARAS","GLOBAL",0)
    SetGlobal("#GPLALVL","GLOBAL",0)
    SetGlobal("#GFAMGO","GLOBAL",2)
    SetGlobal("#GMIRPEN","GLOBAL",0)
    SetInterrupt(TRUE)
END

IF
  Global("#GStartSpl","GLOBAL",1)
  OR(2)
    HP(Player1,2)
    HP(Player1,3)
  Die()
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    ActionOverride(Player1,Recoil())
    ActionOverride(Player1,VerbalConstant(Myself,DAMAGE))
    ActionOverride(Player1,ReallyForceSpellRES("WTPFConA",Myself))
    ActionOverride(Player1,ReallyForceSpellRES("WTPFCOND",Myself))
    ActionOverride(Player1,MakeUnselectable(4))
    DisplayString(Player1,8536)
    DisplayString(Player1,21004)
    CreateCreatureObjectOffScreen("wtpnag3",Myself,0,0,0)
    SetGlobalTimer("#Gmourn","GLOBAL", 21600)
    SetGlobal("WTPFAMLN","GLOBAL",0)
    SetGlobal("#GAFTER","GLOBAL",0)
    SetGlobal("#GFLVUP","GLOBAL",0)
    SetGlobal("#GHARAS","GLOBAL",0)
    SetGlobal("#GPLALVL","GLOBAL",0)
    SetGlobal("#GSHOCK","GLOBAL",1)
    SetGlobal("#GHPOFF","GLOBAL",1)
    SetGlobal("#GMIRPEN","GLOBAL",0)
    SetInterrupt(TRUE)
END

IF
  Global("#GStartSpl","GLOBAL",1)
  OR(2)
    HP(Player1,2)
    HP(Player1,3)
  Global("#GFAMGO","GLOBAL",1)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    ActionOverride(Player1,Recoil())
    ActionOverride(Player1,VerbalConstant(Myself,DAMAGE))
    ActionOverride(Player1,ApplySpellRES("WTPDESP1",Myself))
    ActionOverride(Player1,ReallyForceSpellRES("WTPFConA",Myself))
    ActionOverride(Player1,ReallyForceSpellRES("WTPFCOND",Myself))
    ActionOverride(Player1,MakeUnselectable(4))
    DisplayString(Player1,@522)
    SetGlobalTimer("#Gmourn","GLOBAL", 21600)
    SetGlobal("WTPFAMLN","GLOBAL",0)
    SetGlobal("#GAFTER","GLOBAL",0)
    SetGlobal("#GFLVUP","GLOBAL",0)
    SetGlobal("#GHARAS","GLOBAL",0)
    SetGlobal("#GPLALVL","GLOBAL",0)
    SetGlobal("#GFAMGO","GLOBAL",2)
    SetGlobal("#GMIRPEN","GLOBAL",0)
    SetInterrupt(TRUE)
END

IF
  Global("#GBhaalHP1","GLOBAL",2)
  Die()
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    ActionOverride(Player1,ReallyForceSpellRES("WTPFConA",Myself))
    DisplayString(Player1,8536)
    DisplayString(Player1,21004)
    CreateCreatureObjectOffScreen("wtpnag3",Myself,0,0,0)
    SetGlobalTimer("#Gmourn","GLOBAL", 21600)
    SetGlobal("WTPFAMLN","GLOBAL",0)
    SetGlobal("#GAFTER","GLOBAL",0)
    SetGlobal("#GFLVUP","GLOBAL",0)
    SetGlobal("#GHARAS","GLOBAL",0)
    SetGlobal("#GPLALVL","GLOBAL",0)
    SetGlobal("#GSHOCK","GLOBAL",1)
    SetGlobal("#GHPOFF","GLOBAL",1)
    SetGlobal("#GMIRPEN","GLOBAL",0)
    SetInterrupt(TRUE)
END

//////////////////////////////////////
///Keep the Familiar close         ///
//////////////////////////////////////

IF
  Exists(Myself)
  ActionListEmpty()
  !Detect([ENEMY])
  CombatCounterLT(1)
  !TriggerOverride(Player1,Detect([ENEMY]))
  Global("#GAFTER","GLOBAL",1)
THEN
  RESPONSE #80
    MoveToObjectFollow(Player1)
    Continue()
  RESPONSE #20
    NoAction()
    Continue()
END

////////////////////////////
///To backpack if damaged///
////////////////////////////

IF
  Global("#GBhaalHP1","GLOBAL",0) // GOooPD compatibility check
  Allegiance(Myself,FAMILIAR)
  !Dead("WTPFerre")
  Global("WTPSTAT","LOCALS",0)
  !StateCheck(Myself,STATE_BLIND)
  HPPercentLT(Myself,25)
  See(LastAttackerOf())
  !InventoryFull(Player1)
  Range(Player1,25)
THEN
  RESPONSE #100
    MoveToObject(Player1)
    GiveItemCreate("wtpfmfer",Player1,0,0,0)
    DisplayStringHead(Myself,@523)
    SetGlobalTimer("#GWANOUT","GLOBAL",300)
    SetGlobalTimer("#GSTAOUT","GLOBAL",1200)
    DestroySelf()
END

////////////////////////////////////////
///Leaves if attacked/wrong alignment///
////////////////////////////////////////

IF
  !Alignment(Player1,MASK_LAWFUL)
  CombatCounterLT(1)
  !Detect([ENEMY])
  !TriggerOverride(Player1,Detect([ENEMY]))
  Allegiance(Myself,FAMILIAR)
THEN
  RESPONSE #100
    DisplayStringHead(Player1,@527)
    ApplySpellRES("WTPFCon3",Myself)
    ChangeEnemyAlly(Myself,NEUTRAL)
    RemoveFamiliar()
    CreateCreatureObjectOffScreen("wtpnag3",Myself,0,0,0)
    SetGlobal("#GFAMGO","GLOBAL",1)
END

IF
  AttackedBy(Player1,DEFAULT)
  !StateCheck(Player1,STATE_BERSERK)
  !StateCheck(Player1,STATE_CONFUSED)
  !TriggerOverride(Player1, Detect([ENEMY]))
  Allegiance(Myself,FAMILIAR)
THEN
  RESPONSE #100
    ApplySpellRES("WTPFCon3",Myself)
    ChangeEnemyAlly(Myself,NEUTRAL)
    RemoveFamiliar()
    CreateCreatureObjectOffScreen("wtpnag3",Myself,0,0,0)
    SetGlobal("#GFAMGO","GLOBAL",1)
END

IF
  Global("#GSUMMON","LOCALS",0)
  !Dead("wtpferre")
  Allegiance(Myself,NEUTRAL)
  !Global("#GFAMGO","GLOBAL",1)
THEN
  RESPONSE #100
    DisplayStringNoName(Myself,@521)
    SetGlobal("#GFAMGO","GLOBAL",3)
    EscapeArea()
END

IF
  Global("#GFAMGO","GLOBAL",0)
  Exists("wtpnag3")
THEN
  RESPONSE #100
    ActionOverride("wtpnag3",DestroySelf())
END

///////////////////////
///Reputation Check ///
///////////////////////

IF
  GlobalGT("#GEMPOW","LOCALS", 0)
  OR(3)
    Global("#GREPCHK","LOCALS",1)
    Global("#GREPCHK","LOCALS",3)
    Global("#GREPCHK","LOCALS",6)
  OR(2)
    ReputationLT(Player1,8)
    ReputationGT(Player1,13)
THEN
  RESPONSE #100
    SetGlobal("#GEMPCHA","GLOBAL",1)
    SetGlobal("#GREPCHK","LOCALS",0)
END

IF
  GlobalGT("#GEMPOW","LOCALS", 0)
  OR(3)
    Global("#GREPCHK","LOCALS",2)
    Global("#GREPCHK","LOCALS",5)
    Global("#GREPCHK","LOCALS",8)
  !Reputation(Player1,5)
  !Reputation(Player1,6)
  !Reputation(Player1,7)
  !Reputation(Player1,14)
  !Reputation(Player1,15)
  !Reputation(Player1,16)
THEN
  RESPONSE #100
    SetGlobal("#GEMPCHA","GLOBAL",1)
    SetGlobal("#GREPCHK","LOCALS",0)
END

IF
  GlobalGT("#GEMPOW","LOCALS", 0)
  OR(3)
    Global("#GREPCHK","LOCALS",4)
    Global("#GREPCHK","LOCALS",7)
    Global("#GREPCHK","LOCALS",9)
  ReputationLT(Player1,17)
  ReputationGT(Player1,4)
THEN
  RESPONSE #100
    SetGlobal("#GEMPCHA","GLOBAL",1)
    SetGlobal("#GREPCHK","LOCALS",0)
END

//////////////////////////
///Empowerment ON/OFF  ///
//////////////////////////

IF
  OR(2)
    ActionListEmpty()
    Detect([ENEMY])
  Global("#GEMPCHK","LOCALS",0)
  OR(6)
    !Range(Player1,15)
    Global("WTPSTAT","LOCALS",1)
    StateCheck(Myself,STATE_DISEASED)
    StateCheck(Player1,STATE_DISEASED)
    Global("#GEMPCHA","GLOBAL",1)
    Global("#GBhaalHP1","GLOBAL",2)					// GOooPD compatibility check
THEN
  RESPONSE #100
    SetGlobal("#GEMPCHK","LOCALS",1)
END

IF
  Global("#GSUMMON","LOCALS",0)
  OR(2)
    ActionListEmpty()
    Detect([ENEMY])
  Global("#GEMPCHK","LOCALS",1)
  Range(Player1,15)
  Global("WTPSTAT","LOCALS",0)
  Global("#GEMPCHA","GLOBAL",0)
  !StateCheck(Myself,STATE_DISEASED)
  !StateCheck(Player1,STATE_DISEASED)
  Global("#GBhaalHP1","GLOBAL",0)						// GOooPD compatibility check
THEN
  RESPONSE #100
    SetGlobal("#GEMPCHK","LOCALS",0)
END

///////////////
/// EMP OFF ///
///////////////

IF
  Global("#GEMPOW","LOCALS", 1)
  Global("#GEMPCHK","LOCALS",1)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GEMPOW","LOCALS",0)
    SetGlobal("#GEMPCHA","GLOBAL",0)
    ReallyForceSpellRES("WTPFLVS1",Myself)
    SetInterrupt(TRUE)
END

IF
  Global("#GEMPOW","LOCALS", 2)
  Global("#GEMPCHK","LOCALS",1)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GEMPOW","LOCALS",0)
    SetGlobal("#GEMPCHA","GLOBAL",0)
    ReallyForceSpellRES("WTPFLVS2",Myself)
    SetInterrupt(TRUE)
END

IF
  Global("#GEMPOW","LOCALS", 3)
  Global("#GEMPCHK","LOCALS",1)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GEMPOW","LOCALS",0)
    SetGlobal("#GEMPCHA","GLOBAL",0)
    ReallyForceSpellRES("WTPFLVS3",Myself)
    SetInterrupt(TRUE)
END

IF
  Global("#GEMPOW","LOCALS", 4)
  Global("#GEMPCHK","LOCALS",1)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GEMPOW","LOCALS",0)
    SetGlobal("#GEMPCHA","GLOBAL",0)
    ReallyForceSpellRES("WTPFLVS4",Myself)
    SetInterrupt(TRUE)
END

IF
  Global("#GEMPOW","LOCALS", 5)
  Global("#GEMPCHK","LOCALS",1)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GEMPOW","LOCALS",0)
    SetGlobal("#GEMPCHA","GLOBAL",0)
    ReallyForceSpellRES("WTPFLVS5",Myself)
    SetInterrupt(TRUE)
END

IF
  Global("#GEMPOW","LOCALS", 6)
  Global("#GEMPCHK","LOCALS",1)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GEMPOW","LOCALS",0)
    SetGlobal("#GEMPCHA","GLOBAL",0)
    ReallyForceSpellRES("WTPFLVS6",Myself)
    SetInterrupt(TRUE)
END

IF
  Global("#GEMPOW","LOCALS", 7)
  Global("#GEMPCHK","LOCALS",1)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GEMPOW","LOCALS",0)
    SetGlobal("#GEMPCHA","GLOBAL",0)
    ReallyForceSpellRES("WTPFLVS7",Myself)
    SetInterrupt(TRUE)
END

IF
  Global("#GEMPOW","LOCALS", 8)
  Global("#GEMPCHK","LOCALS",1)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GEMPOW","LOCALS",0)
    SetGlobal("#GEMPCHA","GLOBAL",0)
    ReallyForceSpellRES("WTPFLVS1",Myself)
    SetInterrupt(TRUE)
END

IF
  Global("#GEMPOW","LOCALS", 9)
  Global("#GEMPCHK","LOCALS",1)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GEMPOW","LOCALS",0)
    SetGlobal("#GEMPCHA","GLOBAL",0)
    ReallyForceSpellRES("WTPFLVS2",Myself)
    SetInterrupt(TRUE)
END

IF
  Global("#GEMPOW","LOCALS", 10)
  Global("#GEMPCHK","LOCALS",1)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GEMPOW","LOCALS",0)
    SetGlobal("#GEMPCHA","GLOBAL",0)
    ReallyForceSpellRES("WTPFLVS3",Myself)
    SetInterrupt(TRUE)
END

IF
  Global("#GEMPOW","LOCALS", 11)
  Global("#GEMPCHK","LOCALS",1)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GEMPOW","LOCALS",0)
    SetGlobal("#GEMPCHA","GLOBAL",0)
    ReallyForceSpellRES("WTPFLVS8",Myself)
    SetInterrupt(TRUE)
END

IF
  Global("#GEMPOW","LOCALS", 12)
  Global("#GEMPCHK","LOCALS",1)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GEMPOW","LOCALS",0)
    SetGlobal("#GEMPCHA","GLOBAL",0)
    ReallyForceSpellRES("WTPFLVS9",Myself)
    SetInterrupt(TRUE)
END

IF
  Global("#GEMPOW","LOCALS", 13)
  Global("#GEMPCHK","LOCALS",1)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GEMPOW","LOCALS",0)
    SetGlobal("#GEMPCHA","GLOBAL",0)
    ReallyForceSpellRES("WTPFLVS6",Myself)
    SetInterrupt(TRUE)
END

IF
  Global("#GEMPOW","LOCALS", 14)
  Global("#GEMPCHK","LOCALS",1)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GEMPOW","LOCALS",0)
    SetGlobal("#GEMPCHA","GLOBAL",0)
    ReallyForceSpellRES("WTPFLVS7",Myself)
    SetInterrupt(TRUE)
END

IF
  Global("#GEMPOW","LOCALS", 15)
  Global("#GEMPCHK","LOCALS",1)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GEMPOW","LOCALS",0)
    SetGlobal("#GEMPCHA","GLOBAL",0)
    ReallyForceSpellRES("WTPFLVS1",Myself)
    SetInterrupt(TRUE)
END

IF
  Global("#GEMPOW","LOCALS", 16)
  Global("#GEMPCHK","LOCALS",1)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GEMPOW","LOCALS",0)
    SetGlobal("#GEMPCHA","GLOBAL",0)
    ReallyForceSpellRES("WTPFLVSA",Myself)
    SetInterrupt(TRUE)
END

IF
  Global("#GEMPOW","LOCALS", 17)
  Global("#GEMPCHK","LOCALS",1)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GEMPOW","LOCALS",0)
    SetGlobal("#GEMPCHA","GLOBAL",0)
    ReallyForceSpellRES("WTPFLVSB",Myself)
    SetInterrupt(TRUE)
END

IF
  Global("#GEMPOW","LOCALS", 18)
  Global("#GEMPCHK","LOCALS",1)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GEMPOW","LOCALS",0)
    SetGlobal("#GEMPCHA","GLOBAL",0)
    ReallyForceSpellRES("WTPFLVS8",Myself)
    SetInterrupt(TRUE)
END

IF
  Global("#GEMPOW","LOCALS", 19)
  Global("#GEMPCHK","LOCALS",1)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GEMPOW","LOCALS",0)
    SetGlobal("#GEMPCHA","GLOBAL",0)
    ReallyForceSpellRES("WTPFLVS9",Myself)
    SetInterrupt(TRUE)
END

IF
  Global("#GEMPOW","LOCALS", 20)
  Global("#GEMPCHK","LOCALS",1)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GEMPOW","LOCALS",0)
    SetGlobal("#GEMPCHA","GLOBAL",0)
    ReallyForceSpellRES("WTPFLVS6",Myself)
    SetInterrupt(TRUE)
END

IF
  Global("#GEMPOW","LOCALS", 21)
  Global("#GEMPCHK","LOCALS",1)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GEMPOW","LOCALS",0)
    SetGlobal("#GEMPCHA","GLOBAL",0)
    ReallyForceSpellRES("WTPFLVSC",Myself)
    SetInterrupt(TRUE)
END

IF
  Global("#GEMPOW","LOCALS", 22)
  Global("#GEMPCHK","LOCALS",1)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GEMPOW","LOCALS",0)
    SetGlobal("#GEMPCHA","GLOBAL",0)
    ReallyForceSpellRES("WTPFLVSD",Myself)
    SetInterrupt(TRUE)
END

IF
  Global("#GEMPOW","LOCALS", 23)
  Global("#GEMPCHK","LOCALS",1)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GEMPOW","LOCALS",0)
    SetGlobal("#GEMPCHA","GLOBAL",0)
    ReallyForceSpellRES("WTPFLVSA",Myself)
    SetInterrupt(TRUE)
END

IF
  Global("#GEMPOW","LOCALS", 24)
  Global("#GEMPCHK","LOCALS",1)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GEMPOW","LOCALS",0)
    SetGlobal("#GEMPCHA","GLOBAL",0)
    ReallyForceSpellRES("WTPFLVSB",Myself)
    SetInterrupt(TRUE)
END

IF
  Global("#GEMPOW","LOCALS", 25)
  Global("#GEMPCHK","LOCALS",1)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GEMPOW","LOCALS",0)
    SetGlobal("#GEMPCHA","GLOBAL",0)
    ReallyForceSpellRES("WTPFLVS8",Myself)
    SetInterrupt(TRUE)
END

IF
  Global("#GEMPOW","LOCALS", 26)
  Global("#GEMPCHK","LOCALS",1)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GEMPOW","LOCALS",0)
    SetGlobal("#GEMPCHA","GLOBAL",0)
    ReallyForceSpellRES("WTPFLVSE",Myself)
    SetInterrupt(TRUE)
END

IF
  Global("#GEMPOW","LOCALS", 27)
  Global("#GEMPCHK","LOCALS",1)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GEMPOW","LOCALS",0)
    SetGlobal("#GEMPCHA","GLOBAL",0)
    ReallyForceSpellRES("WTPFLVSF",Myself)
    SetInterrupt(TRUE)
END

IF
  Global("#GEMPOW","LOCALS", 28)
  Global("#GEMPCHK","LOCALS",1)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GEMPOW","LOCALS",0)
    SetGlobal("#GEMPCHA","GLOBAL",0)
    ReallyForceSpellRES("WTPFLVSC",Myself)
    SetInterrupt(TRUE)
END

IF
  Global("#GEMPOW","LOCALS", 29)
  Global("#GEMPCHK","LOCALS",1)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GEMPOW","LOCALS",0)
    SetGlobal("#GEMPCHA","GLOBAL",0)
    ReallyForceSpellRES("WTPFLVSD",Myself)
    SetInterrupt(TRUE)
END

IF
  Global("#GEMPOW","LOCALS", 30)
  Global("#GEMPCHK","LOCALS",1)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GEMPOW","LOCALS",0)
    SetGlobal("#GEMPCHA","GLOBAL",0)
    ReallyForceSpellRES("WTPFLVSA",Myself)
    SetInterrupt(TRUE)
END

IF
  Global("#GEMPOW","LOCALS", 31)
  Global("#GEMPCHK","LOCALS",1)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GEMPOW","LOCALS",0)
    SetGlobal("#GEMPCHA","GLOBAL",0)
    ReallyForceSpellRES("WTPFLVSG",Myself)
    SetInterrupt(TRUE)
END

IF
  Global("#GEMPOW","LOCALS", 32)
  Global("#GEMPCHK","LOCALS",1)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GEMPOW","LOCALS",0)
    SetGlobal("#GEMPCHA","GLOBAL",0)
    ReallyForceSpellRES("WTPFLVSH",Myself)
    SetInterrupt(TRUE)
END

IF
  Global("#GEMPOW","LOCALS", 33)
  Global("#GEMPCHK","LOCALS",1)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GEMPOW","LOCALS",0)
    SetGlobal("#GEMPCHA","GLOBAL",0)
    ReallyForceSpellRES("WTPFLVSE",Myself)
    SetInterrupt(TRUE)
END

IF
  Global("#GEMPOW","LOCALS", 34)
  Global("#GEMPCHK","LOCALS",1)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GEMPOW","LOCALS",0)
    SetGlobal("#GEMPCHA","GLOBAL",0)
    ReallyForceSpellRES("WTPFLVSF",Myself)
    SetInterrupt(TRUE)
END

IF
  Global("#GEMPOW","LOCALS", 35)
  Global("#GEMPCHK","LOCALS",1)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GEMPOW","LOCALS",0)
    SetGlobal("#GEMPCHA","GLOBAL",0)
    ReallyForceSpellRES("WTPFLVSC",Myself)
    SetInterrupt(TRUE)
END

IF
  Global("#GEMPOW","LOCALS", 36)
  Global("#GEMPCHK","LOCALS",1)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GEMPOW","LOCALS",0)
    SetGlobal("#GEMPCHA","GLOBAL",0)
    ReallyForceSpellRES("WTPFLVSI",Myself)
    SetInterrupt(TRUE)
END

IF
  Global("#GEMPOW","LOCALS", 37)
  Global("#GEMPCHK","LOCALS",1)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GEMPOW","LOCALS",0)
    SetGlobal("#GEMPCHA","GLOBAL",0)
    ReallyForceSpellRES("WTPFLVSJ",Myself)
    SetInterrupt(TRUE)
END

IF
  Global("#GEMPOW","LOCALS", 38)
  Global("#GEMPCHK","LOCALS",1)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GEMPOW","LOCALS",0)
    SetGlobal("#GEMPCHA","GLOBAL",0)
    ReallyForceSpellRES("WTPFLVSG",Myself)
    SetInterrupt(TRUE)
END

IF
  Global("#GEMPOW","LOCALS", 39)
  Global("#GEMPCHK","LOCALS",1)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GEMPOW","LOCALS",0)
    SetGlobal("#GEMPCHA","GLOBAL",0)
    ReallyForceSpellRES("WTPFLVSH",Myself)
    SetInterrupt(TRUE)
END

IF
  Global("#GEMPOW","LOCALS", 40)
  Global("#GEMPCHK","LOCALS",1)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GEMPOW","LOCALS",0)
    SetGlobal("#GEMPCHA","GLOBAL",0)
    ReallyForceSpellRES("WTPFLVSE",Myself)
    SetInterrupt(TRUE)
END

IF
  Global("#GEMPOW","LOCALS", 41)
  Global("#GEMPCHK","LOCALS",1)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GEMPOW","LOCALS",0)
    SetGlobal("#GEMPCHA","GLOBAL",0)
    ReallyForceSpellRES("WTPFLVSK",Myself)
    SetInterrupt(TRUE)
END

IF
  Global("#GEMPOW","LOCALS", 42)
  Global("#GEMPCHK","LOCALS",1)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GEMPOW","LOCALS",0)
    SetGlobal("#GEMPCHA","GLOBAL",0)
    ReallyForceSpellRES("WTPFLVSL",Myself)
    SetInterrupt(TRUE)
END

IF
  Global("#GEMPOW","LOCALS", 43)
  Global("#GEMPCHK","LOCALS",1)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GEMPOW","LOCALS",0)
    SetGlobal("#GEMPCHA","GLOBAL",0)
    ReallyForceSpellRES("WTPFLVSI",Myself)
    SetInterrupt(TRUE)
END

IF
  Global("#GEMPOW","LOCALS", 44)
  Global("#GEMPCHK","LOCALS",1)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GEMPOW","LOCALS",0)
    SetGlobal("#GEMPCHA","GLOBAL",0)
    ReallyForceSpellRES("WTPFLVSJ",Myself)
    SetInterrupt(TRUE)
END

IF
  Global("#GEMPOW","LOCALS", 45)
  Global("#GEMPCHK","LOCALS",1)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GEMPOW","LOCALS",0)
    SetGlobal("#GEMPCHA","GLOBAL",0)
    ReallyForceSpellRES("WTPFLVSG",Myself)
    SetInterrupt(TRUE)
END

//////////////////////////////
/// No negative HP allowed ///
//////////////////////////////

IF
  HPLT(Myself,1)
THEN
  RESPONSE #100
    Kill(Myself)
END

/* EVIL FAMILIARS
BLOCK1:
MIRPEN 0 REP 1-7
BLOCK2:
MIRPEN 0 REP 8-14 OR MIRPEN 1 REP 1-7
BLOCK3:
MIRPEN 0 REP 15-20 OR MIRPEN 1 REP 8-14 OR MIRPEN2 REP 1-7
BLOCK4:
MIRPEN 1 REP 15-20 OR MIRPEN 2 REP 8-14
BLOCK5:
MIRPEN 2 REP 15-20
*/

/* GOOD FAMILIARS
BLOCK1:
MIRPEN 0 REP 16-20
BLOCK2:
MIRPEN 0 REP 9-15 OR MIRPEN 1 REP 16-20
BLOCK3:
MIRPEN 0 REP 1-8 OR MIRPEN 1 REP 10-14 OR MIRPEN 2 REP 16-20
BLOCK4:
MIRPEN 1 REP 1-8 OR MIRPEN 2 REP 10-14
BLOCK5
MIRPEN 2 REP 1-8
*/

/* NEUTRAL FAMILIARS
BLOCK1:
MIRPEN 0 REP 8-13
BLOCK2:
MIRPEN 0 REP 5-7/14-16 OR MIRPEN 1 REP 8-13
BLOCK3:
MIRPEN 0 REP 1-4/17-20 OR MIRPEN 1 REP 5-7/14-16 OR MIRPEN 2 REP 8-13
BLOCK4:
MIRPEN 1 REP 1-4/17-20 OR MIRPEN 2 REP 5-7/14-16
BLOCK5:
MIRPEN 2 REP 1-4/17-20
*/

///////////////
/// EMP ON  ///
///////////////

// LV 1-5

IF										// BLOCK1
  Global("#GEMPCHK","LOCALS",0)
  ReputationLT(Player1,14)						// MIRPEN 0 REP 8-13
  ReputationGT(Player1,7)
  Global("#GMIRPEN","GLOBAL",0)
  Global("#GEMPOW","LOCALS", 0)
  GlobalLT("#GPLALVL","GLOBAL",6)
  Global("#GFLVUP","GLOBAL",0)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GREPCHK","LOCALS",1)
    SetGlobal("#GEMPOW","LOCALS",1)
    ReallyForceSpellRES("WTPFLVR1",Myself)
    SetInterrupt(TRUE)
END

IF										// BLOCK2A
  Global("#GEMPCHK","LOCALS",0)
  OR(6)									// MIRPEN 0 REP 5-7/14-16
    Reputation(Player1,5)
    Reputation(Player1,6)
    Reputation(Player1,7)
    Reputation(Player1,14)
    Reputation(Player1,15)
    Reputation(Player1,16)
  Global("#GMIRPEN","GLOBAL",0)
  Global("#GEMPOW","LOCALS", 0)
  GlobalLT("#GPLALVL","GLOBAL",6)
  Global("#GFLVUP","GLOBAL",0)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GREPCHK","LOCALS",2)
    SetGlobal("#GEMPOW","LOCALS",2)
    ReallyForceSpellRES("WTPFLVR2",Myself)
    SetInterrupt(TRUE)
END

IF										// BLOCK2B
  Global("#GEMPCHK","LOCALS",0)
  ReputationGT(Player1,7)							// MIRPEN 1 REP 8-13
  ReputationLT(Player1,14)
  Global("#GMIRPEN","GLOBAL",1)
  Global("#GEMPOW","LOCALS", 0)
  GlobalLT("#GPLALVL","GLOBAL",6)
  Global("#GFLVUP","GLOBAL",0)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GREPCHK","LOCALS",3)
    SetGlobal("#GEMPOW","LOCALS",2)
    ReallyForceSpellRES("WTPFLVR2",Myself)
    SetInterrupt(TRUE)
END

IF										// BLOCK3A
  Global("#GEMPCHK","LOCALS",0)
  OR(2)									// MIRPEN 0 REP 1-4/17-20
    ReputationLT(Player1,5)
    ReputationGT(Player1,16)
  Global("#GMIRPEN","GLOBAL",0)
  Global("#GEMPOW","LOCALS", 0)
  GlobalLT("#GPLALVL","GLOBAL",6)
  Global("#GFLVUP","GLOBAL",0)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GREPCHK","LOCALS",4)
    SetGlobal("#GEMPOW","LOCALS",3)
    ReallyForceSpellRES("WTPFLVR3",Myself)
    SetInterrupt(TRUE)
END

IF										// BLOCK3B
  Global("#GEMPCHK","LOCALS",0)
  OR(6)									// MIRPEN 1 REP 5-7/14-16
    Reputation(Player1,5)
    Reputation(Player1,6)
    Reputation(Player1,7)
    Reputation(Player1,14)
    Reputation(Player1,15)
    Reputation(Player1,16)
  Global("#GMIRPEN","GLOBAL",1)
  Global("#GEMPOW","LOCALS", 0)
  GlobalLT("#GPLALVL","GLOBAL",6)
  Global("#GFLVUP","GLOBAL",0)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GREPCHK","LOCALS",5)
    SetGlobal("#GEMPOW","LOCALS",3)
    ReallyForceSpellRES("WTPFLVR3",Myself)
    SetInterrupt(TRUE)
END

IF										// BLOCK3C
  Global("#GEMPCHK","LOCALS",0)
  ReputationGT(Player1,7)							// MIRPEN 2 REP 8-13
  ReputationLT(Player1,14)
  Global("#GMIRPEN","GLOBAL",2)
  Global("#GEMPOW","LOCALS", 0)
  GlobalLT("#GPLALVL","GLOBAL",6)
  Global("#GFLVUP","GLOBAL",0)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GREPCHK","LOCALS",6)
    SetGlobal("#GEMPOW","LOCALS",3)
    ReallyForceSpellRES("WTPFLVR3",Myself)
    SetInterrupt(TRUE)
END

IF										// BLOCK4A
  Global("#GEMPCHK","LOCALS",0)
  OR(2)									// MIRPEN 1 REP 1-4/17-20
    ReputationLT(Player1,5)
    ReputationGT(Player1,16)
  Global("#GMIRPEN","GLOBAL",1)
  Global("#GEMPOW","LOCALS", 0)
  GlobalLT("#GPLALVL","GLOBAL",6)
  Global("#GFLVUP","GLOBAL",0)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GREPCHK","LOCALS",7)
    SetGlobal("#GEMPOW","LOCALS",4)
    ReallyForceSpellRES("WTPFLVR4",Myself)
    SetInterrupt(TRUE)
END

IF										// BLOCK4B
  Global("#GEMPCHK","LOCALS",0)
  OR(6)									// MIRPEN 2 REP 5-7/14-16
    Reputation(Player1,5)
    Reputation(Player1,6)
    Reputation(Player1,7)
    Reputation(Player1,14)
    Reputation(Player1,15)
    Reputation(Player1,16)
  Global("#GMIRPEN","GLOBAL",2)
  Global("#GEMPOW","LOCALS", 0)
  GlobalLT("#GPLALVL","GLOBAL",6)
  Global("#GFLVUP","GLOBAL",0)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GREPCHK","LOCALS",8)
    SetGlobal("#GEMPOW","LOCALS",4)
    ReallyForceSpellRES("WTPFLVR4",Myself)
    SetInterrupt(TRUE)
END

IF										// BLOCK5
  Global("#GEMPCHK","LOCALS",0)
  OR(2)									// MIRPEN 2 REP 1-4/17-20
    ReputationLT(Player1,5)
    ReputationGT(Player1,16)
  Global("#GMIRPEN","GLOBAL",2)
  Global("#GEMPOW","LOCALS", 0)
  GlobalLT("#GPLALVL","GLOBAL",6)
  Global("#GFLVUP","GLOBAL",0)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GREPCHK","LOCALS",9)
    SetGlobal("#GEMPOW","LOCALS",5)
    ReallyForceSpellRES("WTPFLVR5",Myself)
    SetInterrupt(TRUE)
END

// LV 6-11

IF										// BLOCK1
  Global("#GEMPCHK","LOCALS",0)
  ReputationLT(Player1,14)						// MIRPEN 0 REP 8-13
  ReputationGT(Player1,7)
  Global("#GMIRPEN","GLOBAL",0)
  Global("#GEMPOW","LOCALS", 0)
  GlobalLT("#GPLALVL","GLOBAL",12)
  GlobalGT("#GPLALVL","GLOBAL",5)
  Global("#GFLVUP","GLOBAL",0)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GREPCHK","LOCALS",1)
    SetGlobal("#GEMPOW","LOCALS",6)
    ReallyForceSpellRES("WTPFLVR6",Myself)
    SetInterrupt(TRUE)
END

IF										// BLOCK2A
  Global("#GEMPCHK","LOCALS",0)
  OR(6)									// MIRPEN 0 REP 5-7/14-16
    Reputation(Player1,5)
    Reputation(Player1,6)
    Reputation(Player1,7)
    Reputation(Player1,14)
    Reputation(Player1,15)
    Reputation(Player1,16)
  Global("#GMIRPEN","GLOBAL",0)
  Global("#GEMPOW","LOCALS", 0)
  GlobalLT("#GPLALVL","GLOBAL",12)
  GlobalGT("#GPLALVL","GLOBAL",5)
  Global("#GFLVUP","GLOBAL",0)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GREPCHK","LOCALS",2)
    SetGlobal("#GEMPOW","LOCALS",7)
    ReallyForceSpellRES("WTPFLVR7",Myself)
    SetInterrupt(TRUE)
END

IF										// BLOCK2B
  Global("#GEMPCHK","LOCALS",0)
  ReputationGT(Player1,7)							// MIRPEN 1 REP 8-13
  ReputationLT(Player1,14)
  Global("#GMIRPEN","GLOBAL",1)
  Global("#GEMPOW","LOCALS", 0)
  GlobalLT("#GPLALVL","GLOBAL",12)
  GlobalGT("#GPLALVL","GLOBAL",5)
  Global("#GFLVUP","GLOBAL",0)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GREPCHK","LOCALS",3)
    SetGlobal("#GEMPOW","LOCALS",7)
    ReallyForceSpellRES("WTPFLVR7",Myself)
    SetInterrupt(TRUE)
END

IF										// BLOCK3A
  Global("#GEMPCHK","LOCALS",0)
  OR(2)									// MIRPEN 0 REP 1-4/17-20
    ReputationLT(Player1,5)
    ReputationGT(Player1,16)
  Global("#GMIRPEN","GLOBAL",0)
  Global("#GEMPOW","LOCALS", 0)
  GlobalLT("#GPLALVL","GLOBAL",12)
  GlobalGT("#GPLALVL","GLOBAL",5)
  Global("#GFLVUP","GLOBAL",0)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GREPCHK","LOCALS",4)
    SetGlobal("#GEMPOW","LOCALS",8)
    ReallyForceSpellRES("WTPFLVR1",Myself)
    SetInterrupt(TRUE)
END

IF										// BLOCK3B
  Global("#GEMPCHK","LOCALS",0)
  OR(6)									// MIRPEN 1 REP 5-7/14-16
    Reputation(Player1,5)
    Reputation(Player1,6)
    Reputation(Player1,7)
    Reputation(Player1,14)
    Reputation(Player1,15)
    Reputation(Player1,16)
  Global("#GMIRPEN","GLOBAL",1)
  Global("#GEMPOW","LOCALS", 0)
  GlobalLT("#GPLALVL","GLOBAL",12)
  GlobalGT("#GPLALVL","GLOBAL",5)
  Global("#GFLVUP","GLOBAL",0)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GREPCHK","LOCALS",5)
    SetGlobal("#GEMPOW","LOCALS",8)
    ReallyForceSpellRES("WTPFLVR1",Myself)
    SetInterrupt(TRUE)
END

IF										// BLOCK3C
  Global("#GEMPCHK","LOCALS",0)
  ReputationGT(Player1,7)							// MIRPEN 2 REP 8-13
  ReputationLT(Player1,14)
  Global("#GMIRPEN","GLOBAL",2)
  Global("#GEMPOW","LOCALS", 0)
  GlobalLT("#GPLALVL","GLOBAL",12)
  GlobalGT("#GPLALVL","GLOBAL",5)
  Global("#GFLVUP","GLOBAL",0)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GREPCHK","LOCALS",6)
    SetGlobal("#GEMPOW","LOCALS",8)
    ReallyForceSpellRES("WTPFLVR1",Myself)
    SetInterrupt(TRUE)
END

IF										// BLOCK4A
  Global("#GEMPCHK","LOCALS",0)
  OR(2)									// MIRPEN 1 REP 1-4/17-20
    ReputationLT(Player1,5)
    ReputationGT(Player1,16)
  Global("#GMIRPEN","GLOBAL",1)
  Global("#GEMPOW","LOCALS", 0)
  GlobalLT("#GPLALVL","GLOBAL",12)
  GlobalGT("#GPLALVL","GLOBAL",5)
  Global("#GFLVUP","GLOBAL",0)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GREPCHK","LOCALS",7)
    SetGlobal("#GEMPOW","LOCALS",9)
    ReallyForceSpellRES("WTPFLVR2",Myself)
    SetInterrupt(TRUE)
END

IF										// BLOCK4B
  Global("#GEMPCHK","LOCALS",0)
  OR(6)									// MIRPEN 2 REP 5-7/14-16
    Reputation(Player1,5)
    Reputation(Player1,6)
    Reputation(Player1,7)
    Reputation(Player1,14)
    Reputation(Player1,15)
    Reputation(Player1,16)
  Global("#GMIRPEN","GLOBAL",2)
  Global("#GEMPOW","LOCALS", 0)
  GlobalLT("#GPLALVL","GLOBAL",12)
  GlobalGT("#GPLALVL","GLOBAL",5)
  Global("#GFLVUP","GLOBAL",0)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GREPCHK","LOCALS",8)
    SetGlobal("#GEMPOW","LOCALS",9)
    ReallyForceSpellRES("WTPFLVR2",Myself)
    SetInterrupt(TRUE)
END

IF										// BLOCK5
  Global("#GEMPCHK","LOCALS",0)
  OR(2)									// MIRPEN 2 REP 1-4/17-20
    ReputationLT(Player1,5)
    ReputationGT(Player1,16)
  Global("#GMIRPEN","GLOBAL",2)
  Global("#GEMPOW","LOCALS", 0)
  GlobalLT("#GPLALVL","GLOBAL",12)
  GlobalGT("#GPLALVL","GLOBAL",5)
  Global("#GFLVUP","GLOBAL",0)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GREPCHK","LOCALS",9)
    SetGlobal("#GEMPOW","LOCALS",10)
    ReallyForceSpellRES("WTPFLVR3",Myself)
    SetInterrupt(TRUE)
END

// LV 12-17

IF										// BLOCK1
  Global("#GEMPCHK","LOCALS",0)
  ReputationLT(Player1,14)						// MIRPEN 0 REP 8-13
  ReputationGT(Player1,7)
  Global("#GMIRPEN","GLOBAL",0)
  Global("#GEMPOW","LOCALS", 0)
  GlobalLT("#GPLALVL","GLOBAL",18)
  GlobalGT("#GPLALVL","GLOBAL",11)
  Global("#GFLVUP","GLOBAL",0)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GREPCHK","LOCALS",1)
    SetGlobal("#GEMPOW","LOCALS",11)
    ReallyForceSpellRES("WTPFLVR8",Myself)
    SetInterrupt(TRUE)
END

IF										// BLOCK2A
  Global("#GEMPCHK","LOCALS",0)
  OR(6)									// MIRPEN 0 REP 5-7/14-16
    Reputation(Player1,5)
    Reputation(Player1,6)
    Reputation(Player1,7)
    Reputation(Player1,14)
    Reputation(Player1,15)
    Reputation(Player1,16)
  Global("#GMIRPEN","GLOBAL",0)
  Global("#GEMPOW","LOCALS", 0)
  GlobalLT("#GPLALVL","GLOBAL",18)
  GlobalGT("#GPLALVL","GLOBAL",11)
  Global("#GFLVUP","GLOBAL",0)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GREPCHK","LOCALS",2)
    SetGlobal("#GEMPOW","LOCALS",12)
    ReallyForceSpellRES("WTPFLVR9",Myself)
    SetInterrupt(TRUE)
END

IF										// BLOCK2B
  Global("#GEMPCHK","LOCALS",0)
  ReputationGT(Player1,7)							// MIRPEN 1 REP 8-13
  ReputationLT(Player1,14)
  Global("#GMIRPEN","GLOBAL",1)
  Global("#GEMPOW","LOCALS", 0)
  GlobalLT("#GPLALVL","GLOBAL",18)
  GlobalGT("#GPLALVL","GLOBAL",11)
  Global("#GFLVUP","GLOBAL",0)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GREPCHK","LOCALS",3)
    SetGlobal("#GEMPOW","LOCALS",12)
    ReallyForceSpellRES("WTPFLVR9",Myself)
    SetInterrupt(TRUE)
END

IF										// BLOCK3A
  Global("#GEMPCHK","LOCALS",0)
  OR(2)									// MIRPEN 0 REP 1-4/17-20
    ReputationLT(Player1,5)
    ReputationGT(Player1,16)
  Global("#GMIRPEN","GLOBAL",0)
  Global("#GEMPOW","LOCALS", 0)
  GlobalLT("#GPLALVL","GLOBAL",18)
  GlobalGT("#GPLALVL","GLOBAL",11)
  Global("#GFLVUP","GLOBAL",0)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GREPCHK","LOCALS",4)
    SetGlobal("#GEMPOW","LOCALS",13)
    ReallyForceSpellRES("WTPFLVR6",Myself)
    SetInterrupt(TRUE)
END

IF										// BLOCK3B
  Global("#GEMPCHK","LOCALS",0)
  OR(6)									// MIRPEN 1 REP 5-7/14-16
    Reputation(Player1,5)
    Reputation(Player1,6)
    Reputation(Player1,7)
    Reputation(Player1,14)
    Reputation(Player1,15)
    Reputation(Player1,16)
  Global("#GMIRPEN","GLOBAL",1)
  Global("#GEMPOW","LOCALS", 0)
  GlobalLT("#GPLALVL","GLOBAL",18)
  GlobalGT("#GPLALVL","GLOBAL",11)
  Global("#GFLVUP","GLOBAL",0)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GREPCHK","LOCALS",5)
    SetGlobal("#GEMPOW","LOCALS",13)
    ReallyForceSpellRES("WTPFLVR6",Myself)
    SetInterrupt(TRUE)
END

IF										// BLOCK3C
  Global("#GEMPCHK","LOCALS",0)
  ReputationGT(Player1,7)							// MIRPEN 2 REP 8-13
  ReputationLT(Player1,14)
  Global("#GMIRPEN","GLOBAL",2)
  Global("#GEMPOW","LOCALS", 0)
  GlobalLT("#GPLALVL","GLOBAL",18)
  GlobalGT("#GPLALVL","GLOBAL",11)
  Global("#GFLVUP","GLOBAL",0)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GREPCHK","LOCALS",6)
    SetGlobal("#GEMPOW","LOCALS",13)
    ReallyForceSpellRES("WTPFLVR6",Myself)
    SetInterrupt(TRUE)
END

IF										// BLOCK4A
  Global("#GEMPCHK","LOCALS",0)
  OR(2)									// MIRPEN 1 REP 1-4/17-20
    ReputationLT(Player1,5)
    ReputationGT(Player1,16)
  Global("#GMIRPEN","GLOBAL",1)
  Global("#GEMPOW","LOCALS", 0)
  GlobalLT("#GPLALVL","GLOBAL",18)
  GlobalGT("#GPLALVL","GLOBAL",11)
  Global("#GFLVUP","GLOBAL",0)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GREPCHK","LOCALS",7)
    SetGlobal("#GEMPOW","LOCALS",14)
    ReallyForceSpellRES("WTPFLVR7",Myself)
    SetInterrupt(TRUE)
END

IF										// BLOCK4B
  Global("#GEMPCHK","LOCALS",0)
  OR(6)									// MIRPEN 2 REP 5-7/14-16
    Reputation(Player1,5)
    Reputation(Player1,6)
    Reputation(Player1,7)
    Reputation(Player1,14)
    Reputation(Player1,15)
    Reputation(Player1,16)
  Global("#GMIRPEN","GLOBAL",2)
  Global("#GEMPOW","LOCALS", 0)
  GlobalLT("#GPLALVL","GLOBAL",18)
  GlobalGT("#GPLALVL","GLOBAL",11)
  Global("#GFLVUP","GLOBAL",0)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GREPCHK","LOCALS",8)
    SetGlobal("#GEMPOW","LOCALS",14)
    ReallyForceSpellRES("WTPFLVR7",Myself)
    SetInterrupt(TRUE)
END

IF										// BLOCK5
  Global("#GEMPCHK","LOCALS",0)
  OR(2)									// MIRPEN 2 REP 1-4/17-20
    ReputationLT(Player1,5)
    ReputationGT(Player1,16)
  Global("#GMIRPEN","GLOBAL",2)
  Global("#GEMPOW","LOCALS", 0)
  GlobalLT("#GPLALVL","GLOBAL",18)
  GlobalGT("#GPLALVL","GLOBAL",11)
  Global("#GFLVUP","GLOBAL",0)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GREPCHK","LOCALS",9)
    SetGlobal("#GEMPOW","LOCALS",15)
    ReallyForceSpellRES("WTPFLVR1",Myself)
    SetInterrupt(TRUE)
END

// LV 18-23

IF										// BLOCK1
  Global("#GEMPCHK","LOCALS",0)
  ReputationLT(Player1,14)						// MIRPEN 0 REP 8-13
  ReputationGT(Player1,7)
  Global("#GMIRPEN","GLOBAL",0)
  Global("#GEMPOW","LOCALS", 0)
  GlobalLT("#GPLALVL","GLOBAL",24)
  GlobalGT("#GPLALVL","GLOBAL",17)
  Global("#GFLVUP","GLOBAL",0)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GREPCHK","LOCALS",1)
    SetGlobal("#GEMPOW","LOCALS",16)
    ReallyForceSpellRES("WTPFLVRA",Myself)
    SetInterrupt(TRUE)
END

IF										// BLOCK2A
  Global("#GEMPCHK","LOCALS",0)
  OR(6)									// MIRPEN 0 REP 5-7/14-16
    Reputation(Player1,5)
    Reputation(Player1,6)
    Reputation(Player1,7)
    Reputation(Player1,14)
    Reputation(Player1,15)
    Reputation(Player1,16)
  Global("#GMIRPEN","GLOBAL",0)
  Global("#GEMPOW","LOCALS", 0)
  GlobalLT("#GPLALVL","GLOBAL",24)
  GlobalGT("#GPLALVL","GLOBAL",17)
  Global("#GFLVUP","GLOBAL",0)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GREPCHK","LOCALS",2)
    SetGlobal("#GEMPOW","LOCALS",17)
    ReallyForceSpellRES("WTPFLVRB",Myself)
    SetInterrupt(TRUE)
END

IF										// BLOCK2B
  Global("#GEMPCHK","LOCALS",0)
  ReputationGT(Player1,7)							// MIRPEN 1 REP 8-13
  ReputationLT(Player1,14)
  Global("#GMIRPEN","GLOBAL",1)
  Global("#GEMPOW","LOCALS", 0)
  GlobalLT("#GPLALVL","GLOBAL",24)
  GlobalGT("#GPLALVL","GLOBAL",17)
  Global("#GFLVUP","GLOBAL",0)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GREPCHK","LOCALS",3)
    SetGlobal("#GEMPOW","LOCALS",17)
    ReallyForceSpellRES("WTPFLVRB",Myself)
    SetInterrupt(TRUE)
END

IF										// BLOCK3A
  Global("#GEMPCHK","LOCALS",0)
  OR(2)									// MIRPEN 0 REP 1-4/17-20
    ReputationLT(Player1,5)
    ReputationGT(Player1,16)
  Global("#GMIRPEN","GLOBAL",0)
  Global("#GEMPOW","LOCALS", 0)
  GlobalLT("#GPLALVL","GLOBAL",24)
  GlobalGT("#GPLALVL","GLOBAL",17)
  Global("#GFLVUP","GLOBAL",0)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GREPCHK","LOCALS",4)
    SetGlobal("#GEMPOW","LOCALS",18)
    ReallyForceSpellRES("WTPFLVR8",Myself)
    SetInterrupt(TRUE)
END

IF										// BLOCK3B
  Global("#GEMPCHK","LOCALS",0)
  OR(6)									// MIRPEN 1 REP 5-7/14-16
    Reputation(Player1,5)
    Reputation(Player1,6)
    Reputation(Player1,7)
    Reputation(Player1,14)
    Reputation(Player1,15)
    Reputation(Player1,16)
  Global("#GMIRPEN","GLOBAL",1)
  Global("#GEMPOW","LOCALS", 0)
  GlobalLT("#GPLALVL","GLOBAL",24)
  GlobalGT("#GPLALVL","GLOBAL",17)
  Global("#GFLVUP","GLOBAL",0)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GREPCHK","LOCALS",5)
    SetGlobal("#GEMPOW","LOCALS",18)
    ReallyForceSpellRES("WTPFLVR8",Myself)
    SetInterrupt(TRUE)
END

IF 										// BLOCK3C
  Global("#GEMPCHK","LOCALS",0)
  ReputationGT(Player1,7)							// MIRPEN 2 REP 8-13
  ReputationLT(Player1,14)
  Global("#GMIRPEN","GLOBAL",2)
  Global("#GEMPOW","LOCALS", 0)
  GlobalLT("#GPLALVL","GLOBAL",24)
  GlobalGT("#GPLALVL","GLOBAL",17)
  Global("#GFLVUP","GLOBAL",0)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GREPCHK","LOCALS",6)
    SetGlobal("#GEMPOW","LOCALS",18)
    ReallyForceSpellRES("WTPFLVR8",Myself)
    SetInterrupt(TRUE)
END

IF										// BLOCK4A
  Global("#GEMPCHK","LOCALS",0)
  OR(2)									// MIRPEN 1 REP 1-4/17-20
    ReputationLT(Player1,5)
    ReputationGT(Player1,16)
  Global("#GMIRPEN","GLOBAL",1)
  Global("#GEMPOW","LOCALS", 0)
  GlobalLT("#GPLALVL","GLOBAL",24)
  GlobalGT("#GPLALVL","GLOBAL",17)
  Global("#GFLVUP","GLOBAL",0)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GREPCHK","LOCALS",7)
    SetGlobal("#GEMPOW","LOCALS",19)
    ReallyForceSpellRES("WTPFLVR9",Myself)
    SetInterrupt(TRUE)
END

IF										// BLOCK4B
  Global("#GEMPCHK","LOCALS",0)
  OR(6)									// MIRPEN 2 REP 5-7/14-16
    Reputation(Player1,5)
    Reputation(Player1,6)
    Reputation(Player1,7)
    Reputation(Player1,14)
    Reputation(Player1,15)
    Reputation(Player1,16)
  Global("#GMIRPEN","GLOBAL",2)
  Global("#GEMPOW","LOCALS", 0)
  GlobalLT("#GPLALVL","GLOBAL",24)
  GlobalGT("#GPLALVL","GLOBAL",17)
  Global("#GFLVUP","GLOBAL",0)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GREPCHK","LOCALS",8)
    SetGlobal("#GEMPOW","LOCALS",19)
    ReallyForceSpellRES("WTPFLVR9",Myself)
    SetInterrupt(TRUE)
END

IF										// BLOCK5
  Global("#GEMPCHK","LOCALS",0)
  OR(2)									// MIRPEN 2 REP 1-4/17-20
    ReputationLT(Player1,5)
    ReputationGT(Player1,16)
  Global("#GMIRPEN","GLOBAL",2)
  Global("#GEMPOW","LOCALS", 0)
  GlobalLT("#GPLALVL","GLOBAL",24)
  GlobalGT("#GPLALVL","GLOBAL",17)
  Global("#GFLVUP","GLOBAL",0)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GREPCHK","LOCALS",9)
    SetGlobal("#GEMPOW","LOCALS",20)
    ReallyForceSpellRES("WTPFLVR6",Myself)
    SetInterrupt(TRUE)
END

// LV 24-29

IF										// BLOCK1
  Global("#GEMPCHK","LOCALS",0)
  ReputationLT(Player1,14)						// MIRPEN 0 REP 8-13
  ReputationGT(Player1,7)
  Global("#GMIRPEN","GLOBAL",0)
  Global("#GEMPOW","LOCALS", 0)
  GlobalLT("#GPLALVL","GLOBAL",30)
  GlobalGT("#GPLALVL","GLOBAL",23)
  Global("#GFLVUP","GLOBAL",0)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GREPCHK","LOCALS",1)
    SetGlobal("#GEMPOW","LOCALS",21)
    ReallyForceSpellRES("WTPFLVRC",Myself)
    SetInterrupt(TRUE)
END

IF										// BLOCK2A
  Global("#GEMPCHK","LOCALS",0)
  OR(6)									// MIRPEN 0 REP 5-7/14-16
    Reputation(Player1,5)
    Reputation(Player1,6)
    Reputation(Player1,7)
    Reputation(Player1,14)
    Reputation(Player1,15)
    Reputation(Player1,16)
  Global("#GMIRPEN","GLOBAL",0)
  Global("#GEMPOW","LOCALS", 0)
  GlobalLT("#GPLALVL","GLOBAL",30)
  GlobalGT("#GPLALVL","GLOBAL",23)
  Global("#GFLVUP","GLOBAL",0)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GREPCHK","LOCALS",2)
    SetGlobal("#GEMPOW","LOCALS",22)
    ReallyForceSpellRES("WTPFLVRD",Myself)
    SetInterrupt(TRUE)
END

IF										// BLOCK2B
  Global("#GEMPCHK","LOCALS",0)
  ReputationGT(Player1,7)							// MIRPEN 1 REP 8-13
  ReputationLT(Player1,14)
  Global("#GMIRPEN","GLOBAL",1)
  Global("#GEMPOW","LOCALS", 0)
  GlobalLT("#GPLALVL","GLOBAL",30)
  GlobalGT("#GPLALVL","GLOBAL",23)
  Global("#GFLVUP","GLOBAL",0)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GREPCHK","LOCALS",3)
    SetGlobal("#GEMPOW","LOCALS",22)
    ReallyForceSpellRES("WTPFLVRD",Myself)
    SetInterrupt(TRUE)
END

IF										// BLOCK3A
  Global("#GEMPCHK","LOCALS",0)
  OR(2)									// MIRPEN 0 REP 1-4/17-20
    ReputationLT(Player1,5)
    ReputationGT(Player1,16)
  Global("#GMIRPEN","GLOBAL",0)
  Global("#GEMPOW","LOCALS", 0)
  GlobalLT("#GPLALVL","GLOBAL",30)
  GlobalGT("#GPLALVL","GLOBAL",23)
  Global("#GFLVUP","GLOBAL",0)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GREPCHK","LOCALS",4)
    SetGlobal("#GEMPOW","LOCALS",23)
    ReallyForceSpellRES("WTPFLVRA",Myself)
    SetInterrupt(TRUE)
END

IF										// BLOCK3B
  Global("#GEMPCHK","LOCALS",0)
  OR(6)									// MIRPEN 1 REP 5-7/14-16
    Reputation(Player1,5)
    Reputation(Player1,6)
    Reputation(Player1,7)
    Reputation(Player1,14)
    Reputation(Player1,15)
    Reputation(Player1,16)
  Global("#GMIRPEN","GLOBAL",1)
  Global("#GEMPOW","LOCALS", 0)
  GlobalLT("#GPLALVL","GLOBAL",30)
  GlobalGT("#GPLALVL","GLOBAL",23)
  Global("#GFLVUP","GLOBAL",0)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GREPCHK","LOCALS",5)
    SetGlobal("#GEMPOW","LOCALS",23)
    ReallyForceSpellRES("WTPFLVRA",Myself)
    SetInterrupt(TRUE)
END

IF										// BLOCK3C
  Global("#GEMPCHK","LOCALS",0)
  ReputationGT(Player1,7)							// MIRPEN 2 REP 8-13
  ReputationLT(Player1,14)
  Global("#GMIRPEN","GLOBAL",2)
  Global("#GEMPOW","LOCALS", 0)
  GlobalLT("#GPLALVL","GLOBAL",30)
  GlobalGT("#GPLALVL","GLOBAL",23)
  Global("#GFLVUP","GLOBAL",0)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GREPCHK","LOCALS",6)
    SetGlobal("#GEMPOW","LOCALS",23)
    ReallyForceSpellRES("WTPFLVRA",Myself)
    SetInterrupt(TRUE)
END

IF										// BLOCK4A
  Global("#GEMPCHK","LOCALS",0)
  OR(2)									// MIRPEN 1 REP 1-4/17-20
    ReputationLT(Player1,5)
    ReputationGT(Player1,16)
  Global("#GMIRPEN","GLOBAL",1)
  Global("#GEMPOW","LOCALS", 0)
  GlobalLT("#GPLALVL","GLOBAL",30)
  GlobalGT("#GPLALVL","GLOBAL",23)
  Global("#GFLVUP","GLOBAL",0)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GREPCHK","LOCALS",7)
    SetGlobal("#GEMPOW","LOCALS",24)
    ReallyForceSpellRES("WTPFLVRB",Myself)
    SetInterrupt(TRUE)
END

IF										// BLOCK4B
  Global("#GEMPCHK","LOCALS",0)
  OR(6)									// MIRPEN 2 REP 5-7/14-16
    Reputation(Player1,5)
    Reputation(Player1,6)
    Reputation(Player1,7)
    Reputation(Player1,14)
    Reputation(Player1,15)
    Reputation(Player1,16)
  Global("#GMIRPEN","GLOBAL",2)
  Global("#GEMPOW","LOCALS", 0)
  GlobalLT("#GPLALVL","GLOBAL",30)
  GlobalGT("#GPLALVL","GLOBAL",23)
  Global("#GFLVUP","GLOBAL",0)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GREPCHK","LOCALS",8)
    SetGlobal("#GEMPOW","LOCALS",24)
    ReallyForceSpellRES("WTPFLVRB",Myself)
    SetInterrupt(TRUE)
END

IF										// BLOCK5
  Global("#GEMPCHK","LOCALS",0)
  OR(2)									// MIRPEN 2 REP 1-4/17-20
    ReputationLT(Player1,5)
    ReputationGT(Player1,16)
  Global("#GMIRPEN","GLOBAL",2)
  Global("#GEMPOW","LOCALS", 0)
  GlobalLT("#GPLALVL","GLOBAL",30)
  GlobalGT("#GPLALVL","GLOBAL",23)
  Global("#GFLVUP","GLOBAL",0)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GREPCHK","LOCALS",9)
    SetGlobal("#GEMPOW","LOCALS",25)
    ReallyForceSpellRES("WTPFLVR8",Myself)
    SetInterrupt(TRUE)
END

// LV 30-35

IF										// BLOCK1
  Global("#GEMPCHK","LOCALS",0)
  ReputationLT(Player1,14)						// MIRPEN 0 REP 8-13
  ReputationGT(Player1,7)
  Global("#GMIRPEN","GLOBAL",0)
  Global("#GEMPOW","LOCALS", 0)
  GlobalLT("#GPLALVL","GLOBAL",36)
  GlobalGT("#GPLALVL","GLOBAL",29)
  Global("#GFLVUP","GLOBAL",0)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GREPCHK","LOCALS",1)
    SetGlobal("#GEMPOW","LOCALS",26)
    ReallyForceSpellRES("WTPFLVRE",Myself)
    SetInterrupt(TRUE)
END

IF										// BLOCK2A
  Global("#GEMPCHK","LOCALS",0)
  OR(6)									// MIRPEN 0 REP 5-7/14-16
    Reputation(Player1,5)
    Reputation(Player1,6)
    Reputation(Player1,7)
    Reputation(Player1,14)
    Reputation(Player1,15)
    Reputation(Player1,16)
  Global("#GMIRPEN","GLOBAL",0)
  Global("#GEMPOW","LOCALS", 0)
  GlobalLT("#GPLALVL","GLOBAL",36)
  GlobalGT("#GPLALVL","GLOBAL",29)
  Global("#GFLVUP","GLOBAL",0)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GREPCHK","LOCALS",2)
    SetGlobal("#GEMPOW","LOCALS",27)
    ReallyForceSpellRES("WTPFLVRF",Myself)
    SetInterrupt(TRUE)
END

IF										// BLOCK2B
  Global("#GEMPCHK","LOCALS",0)
  ReputationGT(Player1,7)							// MIRPEN 1 REP 8-13
  ReputationLT(Player1,14)
  Global("#GMIRPEN","GLOBAL",1)
  Global("#GEMPOW","LOCALS", 0)
  GlobalLT("#GPLALVL","GLOBAL",36)
  GlobalGT("#GPLALVL","GLOBAL",29)
  Global("#GFLVUP","GLOBAL",0)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GREPCHK","LOCALS",3)
    SetGlobal("#GEMPOW","LOCALS",27)
    ReallyForceSpellRES("WTPFLVRF",Myself)
    SetInterrupt(TRUE)
END

IF										// BLOCK3A
  Global("#GEMPCHK","LOCALS",0)
  OR(2)									// MIRPEN 0 REP 1-4/17-20
    ReputationLT(Player1,5)
    ReputationGT(Player1,16)
  Global("#GMIRPEN","GLOBAL",0)
  Global("#GEMPOW","LOCALS", 0)
  GlobalLT("#GPLALVL","GLOBAL",36)
  GlobalGT("#GPLALVL","GLOBAL",29)
  Global("#GFLVUP","GLOBAL",0)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GREPCHK","LOCALS",4)
    SetGlobal("#GEMPOW","LOCALS",28)
    ReallyForceSpellRES("WTPFLVRC",Myself)
    SetInterrupt(TRUE)
END

IF										// BLOCK3B
  Global("#GEMPCHK","LOCALS",0)
  OR(6)									// MIRPEN 1 REP 5-7/14-16
    Reputation(Player1,5)
    Reputation(Player1,6)
    Reputation(Player1,7)
    Reputation(Player1,14)
    Reputation(Player1,15)
    Reputation(Player1,16)
  Global("#GMIRPEN","GLOBAL",1)
  Global("#GEMPOW","LOCALS", 0)
  GlobalLT("#GPLALVL","GLOBAL",36)
  GlobalGT("#GPLALVL","GLOBAL",29)
  Global("#GFLVUP","GLOBAL",0)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GREPCHK","LOCALS",5)
    SetGlobal("#GEMPOW","LOCALS",28)
    ReallyForceSpellRES("WTPFLVRC",Myself)
    SetInterrupt(TRUE)
END

IF										// BLOCK3C
  Global("#GEMPCHK","LOCALS",0)
  ReputationGT(Player1,7)							// MIRPEN 2 REP 8-13
  ReputationLT(Player1,14)
  Global("#GMIRPEN","GLOBAL",2)
  Global("#GEMPOW","LOCALS", 0)
  GlobalLT("#GPLALVL","GLOBAL",36)
  GlobalGT("#GPLALVL","GLOBAL",29)
  Global("#GFLVUP","GLOBAL",0)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GREPCHK","LOCALS",6)
    SetGlobal("#GEMPOW","LOCALS",28)
    ReallyForceSpellRES("WTPFLVRC",Myself)
    SetInterrupt(TRUE)
END

IF										// BLOCK4A
  Global("#GEMPCHK","LOCALS",0)
  OR(2)									// MIRPEN 1 REP 1-4/17-20
    ReputationLT(Player1,5)
    ReputationGT(Player1,16)
  Global("#GMIRPEN","GLOBAL",1)
  Global("#GEMPOW","LOCALS", 0)
  GlobalLT("#GPLALVL","GLOBAL",36)
  GlobalGT("#GPLALVL","GLOBAL",29)
  Global("#GFLVUP","GLOBAL",0)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GREPCHK","LOCALS",7)
    SetGlobal("#GEMPOW","LOCALS",29)
    ReallyForceSpellRES("WTPFLVRD",Myself)
    SetInterrupt(TRUE)
END

IF										// BLOCK4B
  Global("#GEMPCHK","LOCALS",0)
  OR(6)									// MIRPEN 2 REP 5-7/14-16
    Reputation(Player1,5)
    Reputation(Player1,6)
    Reputation(Player1,7)
    Reputation(Player1,14)
    Reputation(Player1,15)
    Reputation(Player1,16)
  Global("#GMIRPEN","GLOBAL",2)
  Global("#GEMPOW","LOCALS", 0)
  GlobalLT("#GPLALVL","GLOBAL",36)
  GlobalGT("#GPLALVL","GLOBAL",29)
  Global("#GFLVUP","GLOBAL",0)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GREPCHK","LOCALS",8)
    SetGlobal("#GEMPOW","LOCALS",29)
    ReallyForceSpellRES("WTPFLVRD",Myself)
    SetInterrupt(TRUE)
END

IF										// BLOCK5
  Global("#GEMPCHK","LOCALS",0)
  OR(2)									// MIRPEN 2 REP 1-4/17-20
    ReputationLT(Player1,5)
    ReputationGT(Player1,16)
  Global("#GMIRPEN","GLOBAL",2)
  Global("#GEMPOW","LOCALS", 0)
  GlobalLT("#GPLALVL","GLOBAL",36)
  GlobalGT("#GPLALVL","GLOBAL",29)
  Global("#GFLVUP","GLOBAL",0)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GREPCHK","LOCALS",9)
    SetGlobal("#GEMPOW","LOCALS",30)
    ReallyForceSpellRES("WTPFLVRA",Myself)
    SetInterrupt(TRUE)
END

// LV 36-41

IF										// BLOCK1
  Global("#GEMPCHK","LOCALS",0)
  ReputationLT(Player1,14)						// MIRPEN 0 REP 8-13
  ReputationGT(Player1,7)
  Global("#GMIRPEN","GLOBAL",0)
  Global("#GEMPOW","LOCALS", 0)
  GlobalLT("#GPLALVL","GLOBAL",42)
  GlobalGT("#GPLALVL","GLOBAL",35)
  Global("#GFLVUP","GLOBAL",0)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GREPCHK","LOCALS",1)
    SetGlobal("#GEMPOW","LOCALS",31)
    ReallyForceSpellRES("WTPFLVRG",Myself)
    SetInterrupt(TRUE)
END

IF										// BLOCK2A
  Global("#GEMPCHK","LOCALS",0)
  OR(6)									// MIRPEN 0 REP 5-7/14-16
    Reputation(Player1,5)
    Reputation(Player1,6)
    Reputation(Player1,7)
    Reputation(Player1,14)
    Reputation(Player1,15)
    Reputation(Player1,16)
  Global("#GMIRPEN","GLOBAL",0)
  Global("#GEMPOW","LOCALS", 0)
  GlobalLT("#GPLALVL","GLOBAL",42)
  GlobalGT("#GPLALVL","GLOBAL",35)
  Global("#GFLVUP","GLOBAL",0)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GREPCHK","LOCALS",2)
    SetGlobal("#GEMPOW","LOCALS",32)
    ReallyForceSpellRES("WTPFLVRH",Myself)
    SetInterrupt(TRUE)
END

IF										// BLOCK2B
  Global("#GEMPCHK","LOCALS",0)
  ReputationGT(Player1,7)							// MIRPEN 1 REP 8-13
  ReputationLT(Player1,14)
  Global("#GMIRPEN","GLOBAL",1)
  Global("#GEMPOW","LOCALS", 0)
  GlobalLT("#GPLALVL","GLOBAL",42)
  GlobalGT("#GPLALVL","GLOBAL",35)
  Global("#GFLVUP","GLOBAL",0)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GREPCHK","LOCALS",3)
    SetGlobal("#GEMPOW","LOCALS",32)
    ReallyForceSpellRES("WTPFLVRH",Myself)
    SetInterrupt(TRUE)
END

IF										// BLOCK3A
  Global("#GEMPCHK","LOCALS",0)
  OR(2)									// MIRPEN 0 REP 1-4/17-20
    ReputationLT(Player1,5)
    ReputationGT(Player1,16)
  Global("#GMIRPEN","GLOBAL",0)
  Global("#GEMPOW","LOCALS", 0)
  GlobalLT("#GPLALVL","GLOBAL",42)
  GlobalGT("#GPLALVL","GLOBAL",35)
  Global("#GFLVUP","GLOBAL",0)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GREPCHK","LOCALS",4)
    SetGlobal("#GEMPOW","LOCALS",33)
    ReallyForceSpellRES("WTPFLVRE",Myself)
    SetInterrupt(TRUE)
END

IF										// BLOCK3B
  Global("#GEMPCHK","LOCALS",0)
  OR(6)									// MIRPEN 1 REP 5-7/14-16
    Reputation(Player1,5)
    Reputation(Player1,6)
    Reputation(Player1,7)
    Reputation(Player1,14)
    Reputation(Player1,15)
    Reputation(Player1,16)
  Global("#GMIRPEN","GLOBAL",1)
  Global("#GEMPOW","LOCALS", 0)
  GlobalLT("#GPLALVL","GLOBAL",42)
  GlobalGT("#GPLALVL","GLOBAL",35)
  Global("#GFLVUP","GLOBAL",0)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GREPCHK","LOCALS",5)
    SetGlobal("#GEMPOW","LOCALS",33)
    ReallyForceSpellRES("WTPFLVRE",Myself)
    SetInterrupt(TRUE)
END

IF										// BLOCK3C
  Global("#GEMPCHK","LOCALS",0)
  ReputationGT(Player1,7)							// MIRPEN 2 REP 8-13
  ReputationLT(Player1,14)
  Global("#GMIRPEN","GLOBAL",2)
  Global("#GEMPOW","LOCALS", 0)
  GlobalLT("#GPLALVL","GLOBAL",42)
  GlobalGT("#GPLALVL","GLOBAL",35)
  Global("#GFLVUP","GLOBAL",0)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GREPCHK","LOCALS",6)
    SetGlobal("#GEMPOW","LOCALS",33)
    ReallyForceSpellRES("WTPFLVRE",Myself)
    SetInterrupt(TRUE)
END

IF										// BLOCK4A
  Global("#GEMPCHK","LOCALS",0)
  OR(2)									// MIRPEN 1 REP 1-4/17-20
    ReputationLT(Player1,5)
    ReputationGT(Player1,16)
  Global("#GMIRPEN","GLOBAL",1)
  Global("#GEMPOW","LOCALS", 0)
  GlobalLT("#GPLALVL","GLOBAL",42)
  GlobalGT("#GPLALVL","GLOBAL",35)
  Global("#GFLVUP","GLOBAL",0)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GREPCHK","LOCALS",7)
    SetGlobal("#GEMPOW","LOCALS",34)
    ReallyForceSpellRES("WTPFLVRF",Myself)
    SetInterrupt(TRUE)
END

IF										// BLOCK4B
  Global("#GEMPCHK","LOCALS",0)
  OR(6)									// MIRPEN 2 REP 5-7/14-16
    Reputation(Player1,5)
    Reputation(Player1,6)
    Reputation(Player1,7)
    Reputation(Player1,14)
    Reputation(Player1,15)
    Reputation(Player1,16)
  Global("#GMIRPEN","GLOBAL",2)
  Global("#GEMPOW","LOCALS", 0)
  GlobalLT("#GPLALVL","GLOBAL",42)
  GlobalGT("#GPLALVL","GLOBAL",35)
  Global("#GFLVUP","GLOBAL",0)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GREPCHK","LOCALS",8)
    SetGlobal("#GEMPOW","LOCALS",34)
    ReallyForceSpellRES("WTPFLVRF",Myself)
    SetInterrupt(TRUE)
END

IF										// BLOCK5
  Global("#GEMPCHK","LOCALS",0)
  OR(2)									// MIRPEN 2 REP 1-4/17-20
    ReputationLT(Player1,5)
    ReputationGT(Player1,16)
  Global("#GMIRPEN","GLOBAL",2)
  Global("#GEMPOW","LOCALS", 0)
  GlobalLT("#GPLALVL","GLOBAL",42)
  GlobalGT("#GPLALVL","GLOBAL",35)
  Global("#GFLVUP","GLOBAL",0)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GREPCHK","LOCALS",9)
    SetGlobal("#GEMPOW","LOCALS",35)
    ReallyForceSpellRES("WTPFLVRC",Myself)
    SetInterrupt(TRUE)
END

// LV 42-47

IF										// BLOCK1
  Global("#GEMPCHK","LOCALS",0)
  ReputationLT(Player1,14)						// MIRPEN 0 REP 8-13
  ReputationGT(Player1,7)
  Global("#GMIRPEN","GLOBAL",0)
  Global("#GEMPOW","LOCALS", 0)
  GlobalLT("#GPLALVL","GLOBAL",48)
  GlobalGT("#GPLALVL","GLOBAL",41)
  Global("#GFLVUP","GLOBAL",0)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GREPCHK","LOCALS",1)
    SetGlobal("#GEMPOW","LOCALS",36)
    ReallyForceSpellRES("WTPFLVRI",Myself)
    SetInterrupt(TRUE)
END

IF										// BLOCK2A
  Global("#GEMPCHK","LOCALS",0)
  OR(6)									// MIRPEN 0 REP 5-7/14-16
    Reputation(Player1,5)
    Reputation(Player1,6)
    Reputation(Player1,7)
    Reputation(Player1,14)
    Reputation(Player1,15)
    Reputation(Player1,16)
  Global("#GMIRPEN","GLOBAL",0)
  Global("#GEMPOW","LOCALS", 0)
  GlobalLT("#GPLALVL","GLOBAL",48)
  GlobalGT("#GPLALVL","GLOBAL",41)
  Global("#GFLVUP","GLOBAL",0)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GREPCHK","LOCALS",2)
    SetGlobal("#GEMPOW","LOCALS",37)
    ReallyForceSpellRES("WTPFLVRJ",Myself)
    SetInterrupt(TRUE)
END

IF										// BLOCK2B
  Global("#GEMPCHK","LOCALS",0)
  ReputationGT(Player1,7)							// MIRPEN 1 REP 8-13
  ReputationLT(Player1,14)
  Global("#GMIRPEN","GLOBAL",1)
  Global("#GEMPOW","LOCALS", 0)
  GlobalLT("#GPLALVL","GLOBAL",48)
  GlobalGT("#GPLALVL","GLOBAL",41)
  Global("#GFLVUP","GLOBAL",0)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GREPCHK","LOCALS",3)
    SetGlobal("#GEMPOW","LOCALS",37)
    ReallyForceSpellRES("WTPFLVRJ",Myself)
    SetInterrupt(TRUE)
END

IF										// BLOCK3A
  Global("#GEMPCHK","LOCALS",0)
  OR(2)									// MIRPEN 0 REP 1-4/17-20
    ReputationLT(Player1,5)
    ReputationGT(Player1,16)
  Global("#GMIRPEN","GLOBAL",0)
  Global("#GEMPOW","LOCALS", 0)
  GlobalLT("#GPLALVL","GLOBAL",48)
  GlobalGT("#GPLALVL","GLOBAL",41)
  Global("#GFLVUP","GLOBAL",0)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GREPCHK","LOCALS",4)
    SetGlobal("#GEMPOW","LOCALS",38)
    ReallyForceSpellRES("WTPFLVRG",Myself)
    SetInterrupt(TRUE)
END

IF										// BLOCK3B
  Global("#GEMPCHK","LOCALS",0)
  OR(6)									// MIRPEN 1 REP 5-7/14-16
    Reputation(Player1,5)
    Reputation(Player1,6)
    Reputation(Player1,7)
    Reputation(Player1,14)
    Reputation(Player1,15)
    Reputation(Player1,16)
  Global("#GMIRPEN","GLOBAL",1)
  Global("#GEMPOW","LOCALS", 0)
  GlobalLT("#GPLALVL","GLOBAL",48)
  GlobalGT("#GPLALVL","GLOBAL",41)
  Global("#GFLVUP","GLOBAL",0)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GREPCHK","LOCALS",5)
    SetGlobal("#GEMPOW","LOCALS",38)
    ReallyForceSpellRES("WTPFLVRG",Myself)
    SetInterrupt(TRUE)
END

IF										// BLOCK3C
  Global("#GEMPCHK","LOCALS",0)
  ReputationGT(Player1,7)							// MIRPEN 2 REP 8-13
  ReputationLT(Player1,14)
  Global("#GMIRPEN","GLOBAL",2)
  Global("#GEMPOW","LOCALS", 0)
  GlobalLT("#GPLALVL","GLOBAL",48)
  GlobalGT("#GPLALVL","GLOBAL",41)
  Global("#GFLVUP","GLOBAL",0)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GREPCHK","LOCALS",6)
    SetGlobal("#GEMPOW","LOCALS",38)
    ReallyForceSpellRES("WTPFLVRG",Myself)
    SetInterrupt(TRUE)
END

IF										// BLOCK4A
  Global("#GEMPCHK","LOCALS",0)
  OR(2)									// MIRPEN 1 REP 1-4/17-20
    ReputationLT(Player1,5)
    ReputationGT(Player1,16)
  Global("#GMIRPEN","GLOBAL",1)
  Global("#GEMPOW","LOCALS", 0)
  GlobalLT("#GPLALVL","GLOBAL",48)
  GlobalGT("#GPLALVL","GLOBAL",41)
  Global("#GFLVUP","GLOBAL",0)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GREPCHK","LOCALS",7)
    SetGlobal("#GEMPOW","LOCALS",39)
    ReallyForceSpellRES("WTPFLVRH",Myself)
    SetInterrupt(TRUE)
END

IF										// BLOCK4B
  Global("#GEMPCHK","LOCALS",0)
  OR(6)									// MIRPEN 2 REP 5-7/14-16
    Reputation(Player1,5)
    Reputation(Player1,6)
    Reputation(Player1,7)
    Reputation(Player1,14)
    Reputation(Player1,15)
    Reputation(Player1,16)
  Global("#GMIRPEN","GLOBAL",2)
  Global("#GEMPOW","LOCALS", 0)
  GlobalLT("#GPLALVL","GLOBAL",48)
  GlobalGT("#GPLALVL","GLOBAL",41)
  Global("#GFLVUP","GLOBAL",0)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GREPCHK","LOCALS",8)
    SetGlobal("#GEMPOW","LOCALS",39)
    ReallyForceSpellRES("WTPFLVRH",Myself)
    SetInterrupt(TRUE)
END

IF										// BLOCK5
  Global("#GEMPCHK","LOCALS",0)
  OR(2)									// MIRPEN 2 REP 1-4/17-20
    ReputationLT(Player1,5)
    ReputationGT(Player1,16)
  Global("#GMIRPEN","GLOBAL",2)
  Global("#GEMPOW","LOCALS", 0)
  GlobalLT("#GPLALVL","GLOBAL",48)
  GlobalGT("#GPLALVL","GLOBAL",41)
  Global("#GFLVUP","GLOBAL",0)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GREPCHK","LOCALS",9)
    SetGlobal("#GEMPOW","LOCALS",40)
    ReallyForceSpellRES("WTPFLVRE",Myself)
    SetInterrupt(TRUE)
END

// LV 48+

IF										// BLOCK1
  Global("#GEMPCHK","LOCALS",0)
  ReputationLT(Player1,14)						// MIRPEN 0 REP 8-13
  ReputationGT(Player1,7)
  Global("#GMIRPEN","GLOBAL",0)
  Global("#GEMPOW","LOCALS", 0)
  GlobalGT("#GPLALVL","GLOBAL",47)
  Global("#GFLVUP","GLOBAL",0)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GREPCHK","LOCALS",1)
    SetGlobal("#GEMPOW","LOCALS",41)
    ReallyForceSpellRES("WTPFLVRK",Myself)
    SetInterrupt(TRUE)
END

IF										// BLOCK2A
  Global("#GEMPCHK","LOCALS",0)
  OR(6)									// MIRPEN 0 REP 5-7/14-16
    Reputation(Player1,5)
    Reputation(Player1,6)
    Reputation(Player1,7)
    Reputation(Player1,14)
    Reputation(Player1,15)
    Reputation(Player1,16)
  Global("#GMIRPEN","GLOBAL",0)
  Global("#GEMPOW","LOCALS", 0)
  GlobalGT("#GPLALVL","GLOBAL",47)
  Global("#GFLVUP","GLOBAL",0)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GREPCHK","LOCALS",2)
    SetGlobal("#GEMPOW","LOCALS",42)
    ReallyForceSpellRES("WTPFLVRL",Myself)
    SetInterrupt(TRUE)
END

IF										// BLOCK2B
  Global("#GEMPCHK","LOCALS",0)
  ReputationGT(Player1,7)							// MIRPEN 1 REP 8-13
  ReputationLT(Player1,14)
  Global("#GMIRPEN","GLOBAL",1)
  Global("#GEMPOW","LOCALS", 0)
  GlobalGT("#GPLALVL","GLOBAL",47)
  Global("#GFLVUP","GLOBAL",0)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GREPCHK","LOCALS",3)
    SetGlobal("#GEMPOW","LOCALS",42)
    ReallyForceSpellRES("WTPFLVRL",Myself)
    SetInterrupt(TRUE)
END

IF										// BLOCK3A
  Global("#GEMPCHK","LOCALS",0)
  OR(2)									// MIRPEN 0 REP 1-4/17-20
    ReputationLT(Player1,5)
    ReputationGT(Player1,16)
  Global("#GMIRPEN","GLOBAL",0)
  Global("#GEMPOW","LOCALS", 0)
  GlobalGT("#GPLALVL","GLOBAL",47)
  Global("#GFLVUP","GLOBAL",0)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GREPCHK","LOCALS",4)
    SetGlobal("#GEMPOW","LOCALS",43)
    ReallyForceSpellRES("WTPFLVRI",Myself)
    SetInterrupt(TRUE)
END

IF										// BLOCK3B
  Global("#GEMPCHK","LOCALS",0)
  OR(6)									// MIRPEN 1 REP 5-7/14-16
    Reputation(Player1,5)
    Reputation(Player1,6)
    Reputation(Player1,7)
    Reputation(Player1,14)
    Reputation(Player1,15)
    Reputation(Player1,16)
  Global("#GMIRPEN","GLOBAL",1)
  Global("#GEMPOW","LOCALS", 0)
  GlobalGT("#GPLALVL","GLOBAL",47)
  Global("#GFLVUP","GLOBAL",0)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GREPCHK","LOCALS",5)
    SetGlobal("#GEMPOW","LOCALS",43)
    ReallyForceSpellRES("WTPFLVRI",Myself)
    SetInterrupt(TRUE)
END

IF										// BLOCK3C
  Global("#GEMPCHK","LOCALS",0)
  ReputationGT(Player1,7)							// MIRPEN 2 REP 8-13
  ReputationLT(Player1,14)
  Global("#GMIRPEN","GLOBAL",2)
  Global("#GEMPOW","LOCALS", 0)
  GlobalGT("#GPLALVL","GLOBAL",47)
  Global("#GFLVUP","GLOBAL",0)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GREPCHK","LOCALS",6)
    SetGlobal("#GEMPOW","LOCALS",43)
    ReallyForceSpellRES("WTPFLVRI",Myself)
    SetInterrupt(TRUE)
END

IF										// BLOCK4A
  Global("#GEMPCHK","LOCALS",0)
  OR(2)									// MIRPEN 1 REP 1-4/17-20
    ReputationLT(Player1,5)
    ReputationGT(Player1,16)
  Global("#GMIRPEN","GLOBAL",1)
  Global("#GEMPOW","LOCALS", 0)
  GlobalGT("#GPLALVL","GLOBAL",47)
  Global("#GFLVUP","GLOBAL",0)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GREPCHK","LOCALS",7)
    SetGlobal("#GEMPOW","LOCALS",44)
    ReallyForceSpellRES("WTPFLVRJ",Myself)
    SetInterrupt(TRUE)
END

IF										// BLOCK4B
  Global("#GEMPCHK","LOCALS",0)
  OR(6)									// MIRPEN 2 REP 5-7/14-16
    Reputation(Player1,5)
    Reputation(Player1,6)
    Reputation(Player1,7)
    Reputation(Player1,14)
    Reputation(Player1,15)
    Reputation(Player1,16)
  Global("#GMIRPEN","GLOBAL",2)
  Global("#GEMPOW","LOCALS", 0)
  GlobalGT("#GPLALVL","GLOBAL",47)
  Global("#GFLVUP","GLOBAL",0)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GREPCHK","LOCALS",8)
    SetGlobal("#GEMPOW","LOCALS",44)
    ReallyForceSpellRES("WTPFLVRJ",Myself)
    SetInterrupt(TRUE)
END

IF										// BLOCK5
  Global("#GEMPCHK","LOCALS",0)
  OR(2)									// MIRPEN 2 REP 1-4/17-20
    ReputationLT(Player1,5)
    ReputationGT(Player1,16)
  Global("#GMIRPEN","GLOBAL",2)
  Global("#GEMPOW","LOCALS", 0)
  GlobalGT("#GPLALVL","GLOBAL",47)
  Global("#GFLVUP","GLOBAL",0)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GREPCHK","LOCALS",9)
    SetGlobal("#GEMPOW","LOCALS",45)
    ReallyForceSpellRES("WTPFLVRG",Myself)
    SetInterrupt(TRUE)
END

///////////////////////
///Level up with PC ///
///////////////////////

IF
  !GlobalsEqual("#GFAMLVL","#GPLALVL")
  Global("#GFLVUP","GLOBAL",1)
  Global("WTPFAMLN","GLOBAL",2)
THEN
  RESPONSE #100
    MoveViewObject(Myself,INSTANT)
    LockScroll()
    SetGlobal("#GFLVUP","GLOBAL",2)
END

IF
  GlobalsEqual("#GFAMLVL","#GPLALVL")
  GlobalGT("#GFLVUP","GLOBAL",2)
THEN
  RESPONSE #100
    UnlockScroll()
    SetGlobal("#GFLVUP","GLOBAL",0)
END

IF
  GlobalsEqual("#GFAMLVL","#GPLALVL")
  Global("#GFLVUP","GLOBAL",1)
THEN
  RESPONSE #100
    SetGlobal("#GFLVUP","GLOBAL",0)
END

//////////////////////
///Level up script ///
//////////////////////

IF
  !GlobalsEqual("#GFAMLVL","#GPLALVL")
  GlobalLT("#GFAMLVL","GLOBAL",1)
  Global("#GFLVUP","GLOBAL",2)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetName(@364)
    ApplySpellRES("WTPFMLV0",Myself)
    ApplySpellRES("WTPFMLVL",Myself)
    ApplySpellRES("WTPFMLV5",Myself)
    Wait(1)
    DisplayStringNoName(Myself,@40)
    DisplayStringNoName(Myself,@29)
    DisplayStringNoName(Myself,@45) // Thief points
    ActionOverride(Player1,ReallyForceSpellRES("WTPFCon2",Myself))
    SetGlobal("#GFAMLVL","GLOBAL",1)
    SetGlobal("#GFLVUP","GLOBAL",3)
    SetInterrupt(TRUE)
    Continue()
END

IF
  !GlobalsEqual("#GFAMLVL","#GPLALVL")
  GlobalLT("#GFAMLVL","GLOBAL",2)
  Global("#GFLVUP","GLOBAL",3)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetName(@365)
    ApplySpellRES("WTPFMLV0",Myself)
    ApplySpellRES("WTPFMLVL",Myself)
    ApplySpellRES("WTPFMLV5",Myself)
    ApplySpellRES("WTPFMLV4",Myself)
    Wait(1)
    DisplayStringNoName(Myself,@40)
    DisplayStringNoName(Myself,@35)
    DisplayStringNoName(Myself,@45) // Thief points
    ActionOverride(Player1,ReallyForceSpellRES("WTPFCon2",Myself))
    SetGlobal("#GFAMLVL","GLOBAL",2)
    SetGlobal("#GFLVUP","GLOBAL",4)
    SetInterrupt(TRUE)
    Continue()
END

IF
  !GlobalsEqual("#GFAMLVL","#GPLALVL")
  GlobalLT("#GFAMLVL","GLOBAL",3)
  Global("#GFLVUP","GLOBAL",4)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetName(@366)
    ApplySpellRES("WTPFMLV0",Myself)
    ApplySpellRES("WTPFMLVL",Myself)
    ApplySpellRES("WTPFMLV5",Myself)
    ApplySpellRES("WTPFMLV1",Myself)  // AC +1
    ApplySpellRES("WTPFMLV1",Myself)  // AC +1
    Wait(1)
    DisplayStringNoName(Myself,@40)
    DisplayStringNoName(Myself,@34)
    DisplayStringNoName(Myself,@45) // Thief points
    ActionOverride(Player1,ReallyForceSpellRES("WTPFCon2",Myself))
    SetGlobal("#GFAMLVL","GLOBAL",3)
    SetGlobal("#GFLVUP","GLOBAL",5)
    SetInterrupt(TRUE)
    Continue()
END

IF
  !GlobalsEqual("#GFAMLVL","#GPLALVL")
  GlobalLT("#GFAMLVL","GLOBAL",4)
  Global("#GFLVUP","GLOBAL",5)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetName(@367)
    ApplySpellRES("WTPFMLV0",Myself)
    ApplySpellRES("WTPFMLVL",Myself)
    ApplySpellRES("WTPFMLV5",Myself)
    ApplySpellRES("WTPFMLV4",Myself)
    ApplySpellRES("WTPFMLV9",Myself)
    ApplySpellRES("WTPFMLVA",Myself)
    ApplySpellRES("WTPFMLVA",Myself)
    ApplySpellRES("WTPFMLVB",Myself)
    ApplySpellRES("WTPFMLVC",Myself)
    ApplySpellRES("WTPFMLVD",Myself)
    ApplySpellRES("WTPFMLVD",Myself)
    ApplySpellRES("WTPFFERA",Myself) // +1
    Wait(1)
    DisplayStringNoName(Myself,@40)
    DisplayStringNoName(Myself,@25)
    DisplayStringNoName(Myself,@30)
    DisplayStringNoName(Myself,@35)
    DisplayStringNoName(Myself,@37) // ST UP
    DisplayStringNoName(Myself,@45) // Thief points
    EquipMostDamagingMelee()
    ActionOverride(Player1,ReallyForceSpellRES("WTPFCon2",Myself))
    SetGlobal("#GFAMLVL","GLOBAL",4)
    SetGlobal("#GFLVUP","GLOBAL",6)
    SetInterrupt(TRUE)
    Continue()
END

IF
  !GlobalsEqual("#GFAMLVL","#GPLALVL")
  GlobalLT("#GFAMLVL","GLOBAL",5)
  Global("#GFLVUP","GLOBAL",6)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetName(@368)
    ApplySpellRES("WTPFMLV0",Myself)
    ApplySpellRES("WTPFMLVL",Myself)
    ApplySpellRES("WTPFMLV5",Myself)
    AddSpecialAbility("WTPIN15")  // War Dance
    Wait(1)
    DisplayStringNoName(Myself,@40)
    DisplayStringNoName(Myself,@45) // Thief points
    ActionOverride(Player1,ReallyForceSpellRES("WTPFCon2",Myself))
    SetGlobal("#GFAMLVL","GLOBAL",5)
    SetGlobal("#GFLVUP","GLOBAL",7)
    SetInterrupt(TRUE)
    Continue()
END

IF
  !GlobalsEqual("#GFAMLVL","#GPLALVL")
  GlobalLT("#GFAMLVL","GLOBAL",6)
  Global("#GFLVUP","GLOBAL",7)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetName(@369)
    ApplySpellRES("WTPFMLV0",Myself)
    ApplySpellRES("WTPFMLVL",Myself)
    ApplySpellRES("WTPFMLV5",Myself)
    ApplySpellRES("WTPFMLV4",Myself)
    Wait(1)
    DisplayStringNoName(Myself,@40)
    DisplayStringNoName(Myself,@35)
    DisplayStringNoName(Myself,@45) // Thief points
    ActionOverride(Player1,ReallyForceSpellRES("WTPFCon2",Myself))
    SetGlobal("#GFAMLVL","GLOBAL",6)
    SetGlobal("#GFLVUP","GLOBAL",8)
    SetInterrupt(TRUE)
    Continue()
END

IF
  !GlobalsEqual("#GFAMLVL","#GPLALVL")
  GlobalLT("#GFAMLVL","GLOBAL",7)
  Global("#GFLVUP","GLOBAL",8)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetName(@370)
    ApplySpellRES("WTPFMLV0",Myself)
    ApplySpellRES("WTPFMLVL",Myself)
    ApplySpellRES("WTPFMLV6",Myself)
    Wait(1)
    DisplayStringNoName(Myself,@40)
    DisplayStringNoName(Myself,@520)
    DisplayStringNoName(Myself,@45) // Thief points
    ActionOverride(Player1,ReallyForceSpellRES("WTPFCon2",Myself))
    SetGlobal("#GFAMLVL","GLOBAL",7)
    SetGlobal("#GFLVUP","GLOBAL",9)
    SetInterrupt(TRUE)
    Continue()
END

IF
  !GlobalsEqual("#GFAMLVL","#GPLALVL")
  GlobalLT("#GFAMLVL","GLOBAL",8)
  Global("#GFLVUP","GLOBAL",9)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetName(@371)
    ApplySpellRES("WTPFMLV0",Myself)
    ApplySpellRES("WTPFMLVL",Myself)
    ApplySpellRES("WTPFMLV5",Myself)
    ApplySpellRES("WTPFMLV4",Myself)
    ApplySpellRES("WTPFMLV9",Myself)
    ApplySpellRES("WTPFMLVA",Myself)
    ApplySpellRES("WTPFMLVA",Myself)
    ApplySpellRES("WTPFMLVB",Myself)
    ApplySpellRES("WTPFMLVC",Myself)
    ApplySpellRES("WTPFMLVD",Myself)
    ApplySpellRES("WTPFMLVD",Myself)
    Wait(1)
    DisplayStringNoName(Myself,@40)
    DisplayStringNoName(Myself,@31)
    DisplayStringNoName(Myself,@35)
    DisplayStringNoName(Myself,@37) // ST UP
    DisplayStringNoName(Myself,@45) // Thief points
    ActionOverride(Player1,ReallyForceSpellRES("WTPFCon2",Myself))
    SetGlobal("#GFAMLVL","GLOBAL",8)
    SetGlobal("#GFLVUP","GLOBAL",10)
    SetInterrupt(TRUE)
    Continue()
END

IF
  !GlobalsEqual("#GFAMLVL","#GPLALVL")
  GlobalLT("#GFAMLVL","GLOBAL",9)
  Global("#GFLVUP","GLOBAL",10)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetName(@372)
    ApplySpellRES("WTPFMLV0",Myself)
    ApplySpellRES("WTPFMLV2",Myself)
    ApplySpellRES("WTPFMLV5",Myself)
    Wait(1)
    DisplayStringNoName(Myself,@41)
    DisplayStringNoName(Myself,@45) // Thief points
    ActionOverride(Player1,ReallyForceSpellRES("WTPFCon5",Myself))
    SetGlobal("#GFAMLVL","GLOBAL",9)
    SetGlobal("#GFLVUP","GLOBAL",11)
    SetInterrupt(TRUE)
    Continue()
END

IF
  !GlobalsEqual("#GFAMLVL","#GPLALVL")
  GlobalLT("#GFAMLVL","GLOBAL",10)
  Global("#GFLVUP","GLOBAL",11)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetName(@373)
    ApplySpellRES("WTPFMLV0",Myself)
    ApplySpellRES("WTPFMLV2",Myself)
    ApplySpellRES("WTPFMLV5",Myself)
    ApplySpellRES("WTPFMLV4",Myself)
    ApplySpellRES("WTPFMLV1",Myself)  // AC +1
    ApplySpellRES("WTPFMLV1",Myself)  // AC +1
    Wait(1)
    DisplayStringNoName(Myself,@41)
    DisplayStringNoName(Myself,@34)
    DisplayStringNoName(Myself,@35)
    DisplayStringNoName(Myself,@45) // Thief points
    ActionOverride(Player1,ReallyForceSpellRES("WTPFCon5",Myself))
    SetGlobal("#GFAMLVL","GLOBAL",10)
    SetGlobal("#GFLVUP","GLOBAL",12)
    SetInterrupt(TRUE)
    Continue()
END

IF
  !GlobalsEqual("#GFAMLVL","#GPLALVL")
  GlobalLT("#GFAMLVL","GLOBAL",11)
  Global("#GFLVUP","GLOBAL",12)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetName(@374)
    ApplySpellRES("WTPFMLV0",Myself)
    ApplySpellRES("WTPFMLV2",Myself)
    ApplySpellRES("WTPFMLV5",Myself)
    ApplySpellRES("WTPFFERB",Myself) // +2
    AddSpecialAbility("WTPIN15")  // War Dance
    Wait(1)
    DisplayStringNoName(Myself,@41)
    DisplayStringNoName(Myself,@26)
    DisplayStringNoName(Myself,@45) // Thief points
    EquipMostDamagingMelee()
    ActionOverride(Player1,ReallyForceSpellRES("WTPFCon5",Myself))
    SetGlobal("#GFAMLVL","GLOBAL",11)
    SetGlobal("#GFLVUP","GLOBAL",13)
    SetInterrupt(TRUE)
    Continue()
END

IF
  !GlobalsEqual("#GFAMLVL","#GPLALVL")
  GlobalLT("#GFAMLVL","GLOBAL",12)
  Global("#GFLVUP","GLOBAL",13)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetName(@375)
    ApplySpellRES("WTPFMLV0",Myself)
    ApplySpellRES("WTPFMLV2",Myself)
    ApplySpellRES("WTPFMLV5",Myself)
    ApplySpellRES("WTPFMLV4",Myself)
    ApplySpellRES("WTPFMLV9",Myself)
    ApplySpellRES("WTPFMLVA",Myself)
    ApplySpellRES("WTPFMLVA",Myself)
    ApplySpellRES("WTPFMLVB",Myself)
    ApplySpellRES("WTPFMLVC",Myself)
    ApplySpellRES("WTPFMLVD",Myself)
    ApplySpellRES("WTPFMLVD",Myself)
    Wait(1)
    DisplayStringNoName(Myself,@41)
    DisplayStringNoName(Myself,@35)
    DisplayStringNoName(Myself,@37) // ST UP
    DisplayStringNoName(Myself,@32)
    DisplayStringNoName(Myself,@45) // Thief points
    ActionOverride(Player1,ReallyForceSpellRES("WTPFCon5",Myself))
    SetGlobal("#GFAMLVL","GLOBAL",12)
    SetGlobal("#GFLVUP","GLOBAL",14)
    SetInterrupt(TRUE)
    Continue()
END

IF
  !GlobalsEqual("#GFAMLVL","#GPLALVL")
  GlobalLT("#GFAMLVL","GLOBAL",13)
  Global("#GFLVUP","GLOBAL",14)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetName(@376)
    ApplySpellRES("WTPFMLV0",Myself)
    ApplySpellRES("WTPFMLV2",Myself)
    ApplySpellRES("WTPFMLV5",Myself)
    Wait(1)
    DisplayStringNoName(Myself,@41)
    DisplayStringNoName(Myself,@45) // Thief points
    ActionOverride(Player1,ReallyForceSpellRES("WTPFCon5",Myself))
    SetGlobal("#GFAMLVL","GLOBAL",13)
    SetGlobal("#GFLVUP","GLOBAL",15)
    SetInterrupt(TRUE)
    Continue()
END

IF
  !GlobalsEqual("#GFAMLVL","#GPLALVL")
  GlobalLT("#GFAMLVL","GLOBAL",14)
  Global("#GFLVUP","GLOBAL",15)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetName(@377)
    ApplySpellRES("WTPFMLV0",Myself)
    ApplySpellRES("WTPFMLV2",Myself)
    ApplySpellRES("WTPFMLV6",Myself)
    ApplySpellRES("WTPFMLV4",Myself)
    Wait(1)
    DisplayStringNoName(Myself,@41)
    DisplayStringNoName(Myself,@35)
    DisplayStringNoName(Myself,@45) // Thief points
    ActionOverride(Player1,ReallyForceSpellRES("WTPFCon5",Myself))
    SetGlobal("#GFAMLVL","GLOBAL",14)
    SetGlobal("#GFLVUP","GLOBAL",16)
    SetInterrupt(TRUE)
    Continue()
END

IF
  !GlobalsEqual("#GFAMLVL","#GPLALVL")
  GlobalLT("#GFAMLVL","GLOBAL",15)
  Global("#GFLVUP","GLOBAL",16)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetName(@378)
    ApplySpellRES("WTPFMLV0",Myself)
    ApplySpellRES("WTPFMLV2",Myself)
    ApplySpellRES("WTPFMLV5",Myself)
    Wait(1)
    DisplayStringNoName(Myself,@41)
    DisplayStringNoName(Myself,@520)
    DisplayStringNoName(Myself,@45) // Thief points
    ActionOverride(Player1,ReallyForceSpellRES("WTPFCon5",Myself))
    SetGlobal("#GFAMLVL","GLOBAL",15)
    SetGlobal("#GFLVUP","GLOBAL",17)
    SetInterrupt(TRUE)
    Continue()
END

IF
  !GlobalsEqual("#GFAMLVL","#GPLALVL")
  GlobalLT("#GFAMLVL","GLOBAL",16)
  Global("#GFLVUP","GLOBAL",17)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetName(@379)
    ApplySpellRES("WTPFMLV0",Myself)
    ApplySpellRES("WTPFMLV2",Myself)
    ApplySpellRES("WTPFMLV5",Myself)
    ApplySpellRES("WTPFMLV4",Myself)
    ApplySpellRES("WTPFMLV9",Myself)
    ApplySpellRES("WTPFMLVA",Myself)
    ApplySpellRES("WTPFMLVA",Myself)
    ApplySpellRES("WTPFMLVB",Myself)
    ApplySpellRES("WTPFMLVC",Myself)
    ApplySpellRES("WTPFMLVD",Myself)
    ApplySpellRES("WTPFMLVD",Myself)
    Wait(1)
    DisplayStringNoName(Myself,@41)
    DisplayStringNoName(Myself,@35)
    DisplayStringNoName(Myself,@37) // ST UP
    DisplayStringNoName(Myself,@45) // Thief points
    ActionOverride(Player1,ReallyForceSpellRES("WTPFCon5",Myself))
    SetGlobal("#GFAMLVL","GLOBAL",16)
    SetGlobal("#GFLVUP","GLOBAL",18)
    SetInterrupt(TRUE)
    Continue()
END

IF
  !GlobalsEqual("#GFAMLVL","#GPLALVL")
  GlobalLT("#GFAMLVL","GLOBAL",17)
  Global("#GFLVUP","GLOBAL",18)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetName(@380)
    ApplySpellRES("WTPFMLV0",Myself)
    ApplySpellRES("WTPFMLV2",Myself)
    ApplySpellRES("WTPFMLV5",Myself)
    Wait(1)
    DisplayStringNoName(Myself,@41)
    DisplayStringNoName(Myself,@45) // Thief points
    ActionOverride(Player1,ReallyForceSpellRES("WTPFCon5",Myself))
    SetGlobal("#GFAMLVL","GLOBAL",17)
    SetGlobal("#GFLVUP","GLOBAL",19)
    SetInterrupt(TRUE)
    Continue()
END

IF
  !GlobalsEqual("#GFAMLVL","#GPLALVL")
  GlobalLT("#GFAMLVL","GLOBAL",18)
  Global("#GFLVUP","GLOBAL",19)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetName(@381)
    ApplySpellRES("WTPFMLV0",Myself)
    ApplySpellRES("WTPFMLV2",Myself)
    ApplySpellRES("WTPFMLV5",Myself)
    ApplySpellRES("WTPFMLV4",Myself)
    ApplySpellRES("WTPFMLV1",Myself)  // AC +1
    ApplySpellRES("WTPFMLV1",Myself)  // AC +1
    Wait(1)
    DisplayStringNoName(Myself,@41)
    DisplayStringNoName(Myself,@34)
    DisplayStringNoName(Myself,@35)
    DisplayStringNoName(Myself,@45) // Thief points
    ActionOverride(Player1,ReallyForceSpellRES("WTPFCon5",Myself))
    SetGlobal("#GFAMLVL","GLOBAL",18)
    SetGlobal("#GFLVUP","GLOBAL",20)
    SetInterrupt(TRUE)
    Continue()
END

IF
  !GlobalsEqual("#GFAMLVL","#GPLALVL")
  GlobalLT("#GFAMLVL","GLOBAL",19)
  Global("#GFLVUP","GLOBAL",20)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetName(@382)
    ApplySpellRES("WTPFMLV0",Myself)
    ApplySpellRES("WTPFMLV3",Myself)
    ApplySpellRES("WTPFMLV5",Myself)
    ApplySpellRES("WTPFFERC",Myself) // +3
    AddSpecialAbility("WTPIN15")  // War Dance
    Wait(1)
    DisplayStringNoName(Myself,@42)
    DisplayStringNoName(Myself,@27)
    DisplayStringNoName(Myself,@45) // Thief points
    EquipMostDamagingMelee()
    SetGlobal("#GFAMLVL","GLOBAL",19)
    SetGlobal("#GFLVUP","GLOBAL",21)
    SetInterrupt(TRUE)
    Continue()
END

IF
  !GlobalsEqual("#GFAMLVL","#GPLALVL")
  GlobalLT("#GFAMLVL","GLOBAL",20)
  Global("#GFLVUP","GLOBAL",21)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetName(@383)
    ApplySpellRES("WTPFMLV0",Myself)
    ApplySpellRES("WTPFMLV3",Myself)
    ApplySpellRES("WTPFMLV5",Myself)
    ApplySpellRES("WTPFMLV4",Myself)
    ApplySpellRES("WTPFMLV9",Myself)
    ApplySpellRES("WTPFMLVA",Myself)
    ApplySpellRES("WTPFMLVA",Myself)
    ApplySpellRES("WTPFMLVB",Myself)
    ApplySpellRES("WTPFMLVC",Myself)
    ApplySpellRES("WTPFMLVD",Myself)
    ApplySpellRES("WTPFMLVD",Myself)
    Wait(1)
    DisplayStringNoName(Myself,@42)
    DisplayStringNoName(Myself,@35)
    DisplayStringNoName(Myself,@37) // ST UP
    DisplayStringNoName(Myself,@45) // Thief points
    ActionOverride(Player1,ReallyForceSpellRES("WTPFCon5",Myself))
    SetGlobal("#GFAMLVL","GLOBAL",20)
    SetGlobal("#GFLVUP","GLOBAL",22)
    SetInterrupt(TRUE)
    Continue()
END

IF
  !GlobalsEqual("#GFAMLVL","#GPLALVL")
  GlobalLT("#GFAMLVL","GLOBAL",21)
  Global("#GFLVUP","GLOBAL",22)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetName(@384)
    ApplySpellRES("WTPFMLV0",Myself)
    ApplySpellRES("WTPFMLV3",Myself)
    ApplySpellRES("WTPFMLV6",Myself)
    Wait(1)
    DisplayStringNoName(Myself,@42)
    DisplayStringNoName(Myself,@45) // Thief points
    SetGlobal("#GFAMLVL","GLOBAL",21)
    SetGlobal("#GFLVUP","GLOBAL",23)
    SetInterrupt(TRUE)
    Continue()
END

IF
  !GlobalsEqual("#GFAMLVL","#GPLALVL")
  GlobalLT("#GFAMLVL","GLOBAL",22)
  Global("#GFLVUP","GLOBAL",23)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetName(@385)
    ApplySpellRES("WTPFMLV0",Myself)
    ApplySpellRES("WTPFMLV3",Myself)
    ApplySpellRES("WTPFMLV5",Myself)
    Wait(1)
    DisplayStringNoName(Myself,@42)
    DisplayStringNoName(Myself,@45) // Thief points
    ActionOverride(Player1,ReallyForceSpellRES("WTPFCon5",Myself))
    SetGlobal("#GFAMLVL","GLOBAL",22)
    SetGlobal("#GFLVUP","GLOBAL",24)
    SetInterrupt(TRUE)
    Continue()
END

IF
  !GlobalsEqual("#GFAMLVL","#GPLALVL")
  GlobalLT("#GFAMLVL","GLOBAL",23)
  Global("#GFLVUP","GLOBAL",24)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetName(@386)
    ApplySpellRES("WTPFMLV0",Myself)
    ApplySpellRES("WTPFMLV3",Myself)
    ApplySpellRES("WTPFMLV5",Myself)
    Wait(1)
    DisplayStringNoName(Myself,@42)
    DisplayStringNoName(Myself,@520)
    DisplayStringNoName(Myself,@45) // Thief points
    SetGlobal("#GFAMLVL","GLOBAL",23)
    SetGlobal("#GFLVUP","GLOBAL",25)
    SetInterrupt(TRUE)
    Continue()
END

IF
  !GlobalsEqual("#GFAMLVL","#GPLALVL")
  GlobalLT("#GFAMLVL","GLOBAL",24)
  Global("#GFLVUP","GLOBAL",25)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetName(@387)
    ApplySpellRES("WTPFMLV0",Myself)
    ApplySpellRES("WTPFMLV3",Myself)
    ApplySpellRES("WTPFMLV5",Myself)
    Wait(1)
    DisplayStringNoName(Myself,@42)
    DisplayStringNoName(Myself,@45) // Thief points
    ActionOverride(Player1,ReallyForceSpellRES("WTPFCon5",Myself))
    SetGlobal("#GFAMLVL","GLOBAL",24)
    SetGlobal("#GFLVUP","GLOBAL",26)
    SetInterrupt(TRUE)
    Continue()
END

IF
  !GlobalsEqual("#GFAMLVL","#GPLALVL")
  GlobalLT("#GFAMLVL","GLOBAL",25)
  Global("#GFLVUP","GLOBAL",26)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetName(@388)
    ApplySpellRES("WTPFMLV0",Myself)
    ApplySpellRES("WTPFMLV3",Myself)
    ApplySpellRES("WTPFMLV5",Myself)
    Wait(1)
    DisplayStringNoName(Myself,@42)
    DisplayStringNoName(Myself,@45) // Thief points
    SetGlobal("#GFAMLVL","GLOBAL",25)
    SetGlobal("#GFLVUP","GLOBAL",27)
    SetInterrupt(TRUE)
    Continue()
END

IF
  !GlobalsEqual("#GFAMLVL","#GPLALVL")
  GlobalLT("#GFAMLVL","GLOBAL",26)
  Global("#GFLVUP","GLOBAL",27)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetName(@389)
    ApplySpellRES("WTPFMLV0",Myself)
    ApplySpellRES("WTPFMLV3",Myself)
    ApplySpellRES("WTPFMLV5",Myself)
    Wait(1)
    DisplayStringNoName(Myself,@42)
    DisplayStringNoName(Myself,@45) // Thief points
    ActionOverride(Player1,ReallyForceSpellRES("WTPFCon5",Myself))
    SetGlobal("#GFAMLVL","GLOBAL",26)
    SetGlobal("#GFLVUP","GLOBAL",28)
    SetInterrupt(TRUE)
    Continue()
END

IF
  !GlobalsEqual("#GFAMLVL","#GPLALVL")
  GlobalLT("#GFAMLVL","GLOBAL",27)
  Global("#GFLVUP","GLOBAL",28)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetName(@390)
    ApplySpellRES("WTPFMLV0",Myself)
    ApplySpellRES("WTPFMLV3",Myself)
    ApplySpellRES("WTPFMLV5",Myself)
    Wait(1)
    DisplayStringNoName(Myself,@42)
    DisplayStringNoName(Myself,@45) // Thief points
    SetGlobal("#GFAMLVL","GLOBAL",27)
    SetGlobal("#GFLVUP","GLOBAL",29)
    SetInterrupt(TRUE)
    Continue()
END

IF
  !GlobalsEqual("#GFAMLVL","#GPLALVL")
  GlobalLT("#GFAMLVL","GLOBAL",28)
  Global("#GFLVUP","GLOBAL",29)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetName(@391)
    ApplySpellRES("WTPFMLV0",Myself)
    ApplySpellRES("WTPFMLV3",Myself)
    ApplySpellRES("WTPFMLV6",Myself)
    Wait(1)
    DisplayStringNoName(Myself,@42)
    DisplayStringNoName(Myself,@45) // Thief points
    ActionOverride(Player1,ReallyForceSpellRES("WTPFCon5",Myself))
    SetGlobal("#GFAMLVL","GLOBAL",28)
    SetGlobal("#GFLVUP","GLOBAL",30)
    SetInterrupt(TRUE)
    Continue()
END

IF
  !GlobalsEqual("#GFAMLVL","#GPLALVL")
  GlobalLT("#GFAMLVL","GLOBAL",29)
  Global("#GFLVUP","GLOBAL",30)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetName(@392)
    ApplySpellRES("WTPFMLV0",Myself)
    ApplySpellRES("WTPFMLV3",Myself)
    ApplySpellRES("WTPFMLV5",Myself)
    AddSpecialAbility("WTPIN15")  // War Dance
    Wait(1)
    DisplayStringNoName(Myself,@42)
    DisplayStringNoName(Myself,@45) // Thief points
    SetGlobal("#GFAMLVL","GLOBAL",29)
    SetGlobal("#GFLVUP","GLOBAL",31)
    SetInterrupt(TRUE)
    Continue()
END

IF
  !GlobalsEqual("#GFAMLVL","#GPLALVL")
  GlobalLT("#GFAMLVL","GLOBAL",30)
  Global("#GFLVUP","GLOBAL",31)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetName(@393)
    ApplySpellRES("WTPFMLV0",Myself)
    ApplySpellRES("WTPFMLV3",Myself)
    ApplySpellRES("WTPFMLV5",Myself)
    Wait(1)
    DisplayStringNoName(Myself,@42)
    DisplayStringNoName(Myself,@45) // Thief points
    ActionOverride(Player1,ReallyForceSpellRES("WTPFCon5",Myself))
    SetGlobal("#GFAMLVL","GLOBAL",30)
    SetGlobal("#GFLVUP","GLOBAL",32)
    SetInterrupt(TRUE)
    Continue()
END

IF
  !GlobalsEqual("#GFAMLVL","#GPLALVL")
  GlobalLT("#GFAMLVL","GLOBAL",31)
  Global("#GFLVUP","GLOBAL",32)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetName(@394)
    ApplySpellRES("WTPFMLV0",Myself)
    ApplySpellRES("WTPFMLV3",Myself)
    ApplySpellRES("WTPFMLV5",Myself)
    ApplySpellRES("WTPFMLV1",Myself)  // AC +1
    ApplySpellRES("WTPFMLV1",Myself)  // AC +1
    Wait(1)
    DisplayStringNoName(Myself,@42)
    DisplayStringNoName(Myself,@34)
    DisplayStringNoName(Myself,@520)
    DisplayStringNoName(Myself,@45) // Thief points
    SetGlobal("#GFAMLVL","GLOBAL",31)
    SetGlobal("#GFLVUP","GLOBAL",33)
    SetInterrupt(TRUE)
    Continue()
END

IF
  !GlobalsEqual("#GFAMLVL","#GPLALVL")
  GlobalLT("#GFAMLVL","GLOBAL",32)
  Global("#GFLVUP","GLOBAL",33)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetName(@395)
    ApplySpellRES("WTPFMLV0",Myself)
    ApplySpellRES("WTPFMLV3",Myself)
    ApplySpellRES("WTPFMLV5",Myself)
    Wait(1)
    DisplayStringNoName(Myself,@42)
    DisplayStringNoName(Myself,@45) // Thief points
    ActionOverride(Player1,ReallyForceSpellRES("WTPFCon5",Myself))
    SetGlobal("#GFAMLVL","GLOBAL",32)
    SetGlobal("#GFLVUP","GLOBAL",34)
    SetInterrupt(TRUE)
    Continue()
END

IF
  !GlobalsEqual("#GFAMLVL","#GPLALVL")
  GlobalLT("#GFAMLVL","GLOBAL",33)
  Global("#GFLVUP","GLOBAL",34)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetName(@396)
    ApplySpellRES("WTPFMLV0",Myself)
    ApplySpellRES("WTPFMLV3",Myself)
    ApplySpellRES("WTPFMLV5",Myself)
    Wait(1)
    DisplayStringNoName(Myself,@42)
    DisplayStringNoName(Myself,@45) // Thief points
    SetGlobal("#GFAMLVL","GLOBAL",33)
    SetGlobal("#GFLVUP","GLOBAL",35)
    SetInterrupt(TRUE)
    Continue()
END

IF
  !GlobalsEqual("#GFAMLVL","#GPLALVL")
  GlobalLT("#GFAMLVL","GLOBAL",34)
  Global("#GFLVUP","GLOBAL",35)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetName(@397)
    ApplySpellRES("WTPFMLV0",Myself)
    ApplySpellRES("WTPFMLV3",Myself)
    ApplySpellRES("WTPFMLV5",Myself)
    Wait(1)
    DisplayStringNoName(Myself,@42)
    DisplayStringNoName(Myself,@45) // Thief points
    ActionOverride(Player1,ReallyForceSpellRES("WTPFCon5",Myself))
    SetGlobal("#GFAMLVL","GLOBAL",34)
    SetGlobal("#GFLVUP","GLOBAL",36)
    SetInterrupt(TRUE)
    Continue()
END

IF
  !GlobalsEqual("#GFAMLVL","#GPLALVL")
  GlobalLT("#GFAMLVL","GLOBAL",35)
  Global("#GFLVUP","GLOBAL",36)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetName(@398)
    ApplySpellRES("WTPFMLV0",Myself)
    ApplySpellRES("WTPFMLV3",Myself)
    ApplySpellRES("WTPFMLV6",Myself)
    Wait(1)
    DisplayStringNoName(Myself,@42)
    DisplayStringNoName(Myself,@45) // Thief points
    SetGlobal("#GFAMLVL","GLOBAL",35)
    SetGlobal("#GFLVUP","GLOBAL",37)
    SetInterrupt(TRUE)
    Continue()
END

IF
  !GlobalsEqual("#GFAMLVL","#GPLALVL")
  GlobalLT("#GFAMLVL","GLOBAL",36)
  Global("#GFLVUP","GLOBAL",37)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetName(@399)
    ApplySpellRES("WTPFMLV0",Myself)
    ApplySpellRES("WTPFMLV3",Myself)
    ApplySpellRES("WTPFMLV5",Myself)
    Wait(1)
    DisplayStringNoName(Myself,@42)
    DisplayStringNoName(Myself,@45) // Thief points
    ActionOverride(Player1,ReallyForceSpellRES("WTPFCon5",Myself))
    SetGlobal("#GFAMLVL","GLOBAL",36)
    SetGlobal("#GFLVUP","GLOBAL",38)
    SetInterrupt(TRUE)
    Continue()
END

IF
  !GlobalsEqual("#GFAMLVL","#GPLALVL")
  GlobalLT("#GFAMLVL","GLOBAL",37)
  Global("#GFLVUP","GLOBAL",38)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetName(@400)
    ApplySpellRES("WTPFMLV0",Myself)
    ApplySpellRES("WTPFMLV3",Myself)
    ApplySpellRES("WTPFMLV5",Myself)
    Wait(1)
    DisplayStringNoName(Myself,@42)
    DisplayStringNoName(Myself,@45) // Thief points
    SetGlobal("#GFAMLVL","GLOBAL",37)
    SetGlobal("#GFLVUP","GLOBAL",39)
    SetInterrupt(TRUE)
    Continue()
END

IF
  !GlobalsEqual("#GFAMLVL","#GPLALVL")
  GlobalLT("#GFAMLVL","GLOBAL",38)
  Global("#GFLVUP","GLOBAL",39)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetName(@401)
    ApplySpellRES("WTPFMLV0",Myself)
    ApplySpellRES("WTPFMLV3",Myself)
    ApplySpellRES("WTPFMLV5",Myself)
    Wait(1)
    DisplayStringNoName(Myself,@42)
    DisplayStringNoName(Myself,@45) // Thief points
    ActionOverride(Player1,ReallyForceSpellRES("WTPFCon5",Myself))
    SetGlobal("#GFAMLVL","GLOBAL",38)
    SetGlobal("#GFLVUP","GLOBAL",40)
    SetInterrupt(TRUE)
    Continue()
END

IF
  !GlobalsEqual("#GFAMLVL","#GPLALVL")
  GlobalLT("#GFAMLVL","GLOBAL",39)
  Global("#GFLVUP","GLOBAL",40)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetName(@402)
    ApplySpellRES("WTPFMLV0",Myself)
    ApplySpellRES("WTPFMLV3",Myself)
    ApplySpellRES("WTPFMLV5",Myself)
    Wait(1)
    DisplayStringNoName(Myself,@42)
    DisplayStringNoName(Myself,@45) // Thief points
    SetGlobal("#GFAMLVL","GLOBAL",39)
    SetGlobal("#GFLVUP","GLOBAL",41)
    SetInterrupt(TRUE)
    Continue()
END

IF
  !GlobalsEqual("#GFAMLVL","#GPLALVL")
  GlobalLT("#GFAMLVL","GLOBAL",40)
  Global("#GFLVUP","GLOBAL",41)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetName(@403)
    ApplySpellRES("WTPFMLV0",Myself)
    ApplySpellRES("WTPFMLV3",Myself)
    ApplySpellRES("WTPFMLV5",Myself)
    Wait(1)
    DisplayStringNoName(Myself,@42)
    DisplayStringNoName(Myself,@45) // Thief points
    ActionOverride(Player1,ReallyForceSpellRES("WTPFCon5",Myself))
    SetGlobal("#GFAMLVL","GLOBAL",40)
    SetGlobal("#GFLVUP","GLOBAL",42)
    SetInterrupt(TRUE)
    Continue()
END

IF
  !GlobalsEqual("#GFAMLVL","#GPLALVL")
  GlobalLT("#GFAMLVL","GLOBAL",41)
  Global("#GFLVUP","GLOBAL",42)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetName(@404)
    ApplySpellRES("WTPFMLV0",Myself)
    ApplySpellRES("WTPFMLV3",Myself)
    ApplySpellRES("WTPFMLV5",Myself)
    Wait(1)
    DisplayStringNoName(Myself,@42)
    DisplayStringNoName(Myself,@45) // Thief points
    SetGlobal("#GFAMLVL","GLOBAL",41)
    SetGlobal("#GFLVUP","GLOBAL",43)
    SetInterrupt(TRUE)
    Continue()
END

IF
  !GlobalsEqual("#GFAMLVL","#GPLALVL")
  GlobalLT("#GFAMLVL","GLOBAL",42)
  Global("#GFLVUP","GLOBAL",43)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetName(@405)
    ApplySpellRES("WTPFMLV0",Myself)
    ApplySpellRES("WTPFMLV3",Myself)
    ApplySpellRES("WTPFMLV6",Myself)
    Wait(1)
    DisplayStringNoName(Myself,@42)
    DisplayStringNoName(Myself,@45) // Thief points
    ActionOverride(Player1,ReallyForceSpellRES("WTPFCon5",Myself))
    SetGlobal("#GFAMLVL","GLOBAL",42)
    SetGlobal("#GFLVUP","GLOBAL",44)
    SetInterrupt(TRUE)
    Continue()
END

IF
  !GlobalsEqual("#GFAMLVL","#GPLALVL")
  GlobalLT("#GFAMLVL","GLOBAL",43)
  Global("#GFLVUP","GLOBAL",44)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetName(@406)
    ApplySpellRES("WTPFMLV0",Myself)
    ApplySpellRES("WTPFMLV3",Myself)
    ApplySpellRES("WTPFMLV5",Myself)
    Wait(1)
    DisplayStringNoName(Myself,@42)
    DisplayStringNoName(Myself,@45) // Thief points
    SetGlobal("#GFAMLVL","GLOBAL",43)
    SetGlobal("#GFLVUP","GLOBAL",45)
    SetInterrupt(TRUE)
    Continue()
END

IF
  !GlobalsEqual("#GFAMLVL","#GPLALVL")
  GlobalLT("#GFAMLVL","GLOBAL",44)
  Global("#GFLVUP","GLOBAL",45)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetName(@407)
    ApplySpellRES("WTPFMLV0",Myself)
    ApplySpellRES("WTPFMLV3",Myself)
    ApplySpellRES("WTPFMLV5",Myself)
    Wait(1)
    DisplayStringNoName(Myself,@42)
    DisplayStringNoName(Myself,@45) // Thief points
    ActionOverride(Player1,ReallyForceSpellRES("WTPFCon5",Myself))
    SetGlobal("#GFAMLVL","GLOBAL",44)
    SetGlobal("#GFLVUP","GLOBAL",46)
    SetInterrupt(TRUE)
    Continue()
END

IF
  !GlobalsEqual("#GFAMLVL","#GPLALVL")
  GlobalLT("#GFAMLVL","GLOBAL",45)
  Global("#GFLVUP","GLOBAL",46)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetName(@408)
    ApplySpellRES("WTPFMLV0",Myself)
    ApplySpellRES("WTPFMLV3",Myself)
    ApplySpellRES("WTPFMLV5",Myself)
    Wait(1)
    DisplayStringNoName(Myself,@42)
    DisplayStringNoName(Myself,@45) // Thief points
    SetGlobal("#GFAMLVL","GLOBAL",45)
    SetGlobal("#GFLVUP","GLOBAL",47)
    SetInterrupt(TRUE)
    Continue()
END

IF
  !GlobalsEqual("#GFAMLVL","#GPLALVL")
  GlobalLT("#GFAMLVL","GLOBAL",46)
  Global("#GFLVUP","GLOBAL",47)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetName(@409)
    ApplySpellRES("WTPFMLV0",Myself)
    ApplySpellRES("WTPFMLV3",Myself)
    ApplySpellRES("WTPFMLV5",Myself)
    Wait(1)
    DisplayStringNoName(Myself,@42)
    DisplayStringNoName(Myself,@45) // Thief points
    ActionOverride(Player1,ReallyForceSpellRES("WTPFCon5",Myself))
    SetGlobal("#GFAMLVL","GLOBAL",46)
    SetGlobal("#GFLVUP","GLOBAL",48)
    SetInterrupt(TRUE)
    Continue()
END

IF
  !GlobalsEqual("#GFAMLVL","#GPLALVL")
  GlobalLT("#GFAMLVL","GLOBAL",47)
  Global("#GFLVUP","GLOBAL",48)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetName(@410)
    ApplySpellRES("WTPFMLV0",Myself)
    ApplySpellRES("WTPFMLV3",Myself)
    ApplySpellRES("WTPFMLV5",Myself)
    Wait(1)
    DisplayStringNoName(Myself,@42)
    DisplayStringNoName(Myself,@45) // Thief points
    SetGlobal("#GFAMLVL","GLOBAL",47)
    SetGlobal("#GFLVUP","GLOBAL",49)
    SetInterrupt(TRUE)
    Continue()
END

IF
  !GlobalsEqual("#GFAMLVL","#GPLALVL")
  GlobalLT("#GFAMLVL","GLOBAL",48)
  Global("#GFLVUP","GLOBAL",49)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetName(@411)
    ApplySpellRES("WTPFMLV0",Myself)
    ApplySpellRES("WTPFMLV3",Myself)
    ApplySpellRES("WTPFMLV5",Myself)
    Wait(1)
    DisplayStringNoName(Myself,@42)
    DisplayStringNoName(Myself,@45) // Thief points
    ActionOverride(Player1,ReallyForceSpellRES("WTPFCon5",Myself))
    SetGlobal("#GFAMLVL","GLOBAL",48)
    SetGlobal("#GFLVUP","GLOBAL",50)
    SetInterrupt(TRUE)
    Continue()
END

IF
  !GlobalsEqual("#GFAMLVL","#GPLALVL")
  GlobalLT("#GFAMLVL","GLOBAL",49)
  Global("#GFLVUP","GLOBAL",50)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetName(@412)
    ApplySpellRES("WTPFMLV0",Myself)
    ApplySpellRES("WTPFMLV3",Myself)
    ApplySpellRES("WTPFMLV6",Myself)
    Wait(1)
    DisplayStringNoName(Myself,@42)
    DisplayStringNoName(Myself,@45) // Thief points
    SetGlobal("#GFAMLVL","GLOBAL",49)
    SetGlobal("#GFLVUP","GLOBAL",100)
    SetInterrupt(TRUE)
    Continue()
END

IF
  !GlobalsEqual("#GFAMLVL","#GPLALVL")
  GlobalGT("#GFLVUP","GLOBAL",1)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    ActionOverride(Player1,MakeUnselectable(6))
    ActionOverride(Player2,MakeUnselectable(6))
    ActionOverride(Player3,MakeUnselectable(6))
    ActionOverride(Player4,MakeUnselectable(6))
    ActionOverride(Player5,MakeUnselectable(6))
    ActionOverride(Player6,MakeUnselectable(6))
    SetInterrupt(TRUE)
END

///////////////////
/// Name change ///
///////////////////

IF
  Global("#GNAMCHG","LOCALS",0)
  Global("#GEMPCHK","LOCALS",0)
  Global("#GFAMLVL","GLOBAL",0)
THEN
  RESPONSE #100
    SetName(@900)
    SetGlobal("#GNAMCHG","LOCALS",1)
END

IF
  Global("#GNAMCHG","LOCALS",0)
  Global("#GEMPCHK","LOCALS",0)
  Global("#GFAMLVL","GLOBAL",1)
THEN
  RESPONSE #100
    SetName(@901)
    SetGlobal("#GNAMCHG","LOCALS",1)
END

IF
  Global("#GNAMCHG","LOCALS",0)
  Global("#GEMPCHK","LOCALS",0)
  Global("#GFAMLVL","GLOBAL",2)
THEN
  RESPONSE #100
    SetName(@902)
    SetGlobal("#GNAMCHG","LOCALS",1)
END

IF
  Global("#GNAMCHG","LOCALS",0)
  Global("#GEMPCHK","LOCALS",0)
  Global("#GFAMLVL","GLOBAL",3)
THEN
  RESPONSE #100
    SetName(@903)
    SetGlobal("#GNAMCHG","LOCALS",1)
END

IF
  Global("#GNAMCHG","LOCALS",0)
  Global("#GEMPCHK","LOCALS",0)
  Global("#GFAMLVL","GLOBAL",4)
THEN
  RESPONSE #100
    SetName(@904)
    SetGlobal("#GNAMCHG","LOCALS",1)
END

IF
  Global("#GNAMCHG","LOCALS",0)
  Global("#GEMPCHK","LOCALS",0)
  Global("#GFAMLVL","GLOBAL",5)
THEN
  RESPONSE #100
    SetName(@905)
    SetGlobal("#GNAMCHG","LOCALS",1)
END

IF
  Global("#GNAMCHG","LOCALS",0)
  Global("#GEMPCHK","LOCALS",0)
  Global("#GFAMLVL","GLOBAL",6)
THEN
  RESPONSE #100
    SetName(@906)
    SetGlobal("#GNAMCHG","LOCALS",1)
END

IF
  Global("#GNAMCHG","LOCALS",0)
  Global("#GEMPCHK","LOCALS",0)
  Global("#GFAMLVL","GLOBAL",7)
THEN
  RESPONSE #100
    SetName(@907)
    SetGlobal("#GNAMCHG","LOCALS",1)
END

IF
  Global("#GNAMCHG","LOCALS",0)
  Global("#GEMPCHK","LOCALS",0)
  Global("#GFAMLVL","GLOBAL",8)
THEN
  RESPONSE #100
    SetName(@908)
    SetGlobal("#GNAMCHG","LOCALS",1)
END

IF
  Global("#GNAMCHG","LOCALS",0)
  Global("#GEMPCHK","LOCALS",0)
  Global("#GFAMLVL","GLOBAL",9)
THEN
  RESPONSE #100
    SetName(@909)
    SetGlobal("#GNAMCHG","LOCALS",1)
END

IF
  Global("#GNAMCHG","LOCALS",0)
  Global("#GEMPCHK","LOCALS",0)
  Global("#GFAMLVL","GLOBAL",10)
THEN
  RESPONSE #100
    SetName(@910)
    SetGlobal("#GNAMCHG","LOCALS",1)
END

IF
  Global("#GNAMCHG","LOCALS",0)
  Global("#GEMPCHK","LOCALS",0)
  Global("#GFAMLVL","GLOBAL",11)
THEN
  RESPONSE #100
    SetName(@911)
    SetGlobal("#GNAMCHG","LOCALS",1)
END

IF
  Global("#GNAMCHG","LOCALS",0)
  Global("#GEMPCHK","LOCALS",0)
  Global("#GFAMLVL","GLOBAL",12)
THEN
  RESPONSE #100
    SetName(@912)
    SetGlobal("#GNAMCHG","LOCALS",1)
END

IF
  Global("#GNAMCHG","LOCALS",0)
  Global("#GEMPCHK","LOCALS",0)
  Global("#GFAMLVL","GLOBAL",13)
THEN
  RESPONSE #100
    SetName(@913)
    SetGlobal("#GNAMCHG","LOCALS",1)
END

IF
  Global("#GNAMCHG","LOCALS",0)
  Global("#GEMPCHK","LOCALS",0)
  Global("#GFAMLVL","GLOBAL",14)
THEN
  RESPONSE #100
    SetName(@914)
    SetGlobal("#GNAMCHG","LOCALS",1)
END

IF
  Global("#GNAMCHG","LOCALS",0)
  Global("#GEMPCHK","LOCALS",0)
  Global("#GFAMLVL","GLOBAL",15)
THEN
  RESPONSE #100
    SetName(@915)
    SetGlobal("#GNAMCHG","LOCALS",1)
END

IF
  Global("#GNAMCHG","LOCALS",0)
  Global("#GEMPCHK","LOCALS",0)
  Global("#GFAMLVL","GLOBAL",16)
THEN
  RESPONSE #100
    SetName(@916)
    SetGlobal("#GNAMCHG","LOCALS",1)
END

IF
  Global("#GNAMCHG","LOCALS",0)
  Global("#GEMPCHK","LOCALS",0)
  Global("#GFAMLVL","GLOBAL",17)
THEN
  RESPONSE #100
    SetName(@917)
    SetGlobal("#GNAMCHG","LOCALS",1)
END

IF
  Global("#GNAMCHG","LOCALS",0)
  Global("#GEMPCHK","LOCALS",0)
  Global("#GFAMLVL","GLOBAL",18)
THEN
  RESPONSE #100
    SetName(@918)
    SetGlobal("#GNAMCHG","LOCALS",1)
END

IF
  Global("#GNAMCHG","LOCALS",0)
  Global("#GEMPCHK","LOCALS",0)
  Global("#GFAMLVL","GLOBAL",19)
THEN
  RESPONSE #100
    SetName(@919)
    SetGlobal("#GNAMCHG","LOCALS",1)
END

IF
  Global("#GNAMCHG","LOCALS",0)
  Global("#GEMPCHK","LOCALS",0)
  Global("#GFAMLVL","GLOBAL",20)
THEN
  RESPONSE #100
    SetName(@920)
    SetGlobal("#GNAMCHG","LOCALS",1)
END

IF
  Global("#GNAMCHG","LOCALS",0)
  Global("#GEMPCHK","LOCALS",0)
  Global("#GFAMLVL","GLOBAL",21)
THEN
  RESPONSE #100
    SetName(@921)
    SetGlobal("#GNAMCHG","LOCALS",1)
END

IF
  Global("#GNAMCHG","LOCALS",0)
  Global("#GEMPCHK","LOCALS",0)
  Global("#GFAMLVL","GLOBAL",22)
THEN
  RESPONSE #100
    SetName(@922)
    SetGlobal("#GNAMCHG","LOCALS",1)
END

IF
  Global("#GNAMCHG","LOCALS",0)
  Global("#GEMPCHK","LOCALS",0)
  Global("#GFAMLVL","GLOBAL",23)
THEN
  RESPONSE #100
    SetName(@923)
    SetGlobal("#GNAMCHG","LOCALS",1)
END

IF
  Global("#GNAMCHG","LOCALS",0)
  Global("#GEMPCHK","LOCALS",0)
  Global("#GFAMLVL","GLOBAL",24)
THEN
  RESPONSE #100
    SetName(@924)
    SetGlobal("#GNAMCHG","LOCALS",1)
END

IF
  Global("#GNAMCHG","LOCALS",0)
  Global("#GEMPCHK","LOCALS",0)
  Global("#GFAMLVL","GLOBAL",25)
THEN
  RESPONSE #100
    SetName(@925)
    SetGlobal("#GNAMCHG","LOCALS",1)
END

IF
  Global("#GNAMCHG","LOCALS",0)
  Global("#GEMPCHK","LOCALS",0)
  Global("#GFAMLVL","GLOBAL",26)
THEN
  RESPONSE #100
    SetName(@926)
    SetGlobal("#GNAMCHG","LOCALS",1)
END

IF
  Global("#GNAMCHG","LOCALS",0)
  Global("#GEMPCHK","LOCALS",0)
  Global("#GFAMLVL","GLOBAL",27)
THEN
  RESPONSE #100
    SetName(@927)
    SetGlobal("#GNAMCHG","LOCALS",1)
END

IF
  Global("#GNAMCHG","LOCALS",0)
  Global("#GEMPCHK","LOCALS",0)
  Global("#GFAMLVL","GLOBAL",28)
THEN
  RESPONSE #100
    SetName(@928)
    SetGlobal("#GNAMCHG","LOCALS",1)
END

IF
  Global("#GNAMCHG","LOCALS",0)
  Global("#GEMPCHK","LOCALS",0)
  Global("#GFAMLVL","GLOBAL",29)
THEN
  RESPONSE #100
    SetName(@929)
    SetGlobal("#GNAMCHG","LOCALS",1)
END

IF
  Global("#GNAMCHG","LOCALS",0)
  Global("#GEMPCHK","LOCALS",0)
  Global("#GFAMLVL","GLOBAL",30)
THEN
  RESPONSE #100
    SetName(@930)
    SetGlobal("#GNAMCHG","LOCALS",1)
END

IF
  Global("#GNAMCHG","LOCALS",0)
  Global("#GEMPCHK","LOCALS",0)
  Global("#GFAMLVL","GLOBAL",31)
THEN
  RESPONSE #100
    SetName(@931)
    SetGlobal("#GNAMCHG","LOCALS",1)
END

IF
  Global("#GNAMCHG","LOCALS",0)
  Global("#GEMPCHK","LOCALS",0)
  Global("#GFAMLVL","GLOBAL",32)
THEN
  RESPONSE #100
    SetName(@932)
    SetGlobal("#GNAMCHG","LOCALS",1)
END

IF
  Global("#GNAMCHG","LOCALS",0)
  Global("#GEMPCHK","LOCALS",0)
  Global("#GFAMLVL","GLOBAL",33)
THEN
  RESPONSE #100
    SetName(@933)
    SetGlobal("#GNAMCHG","LOCALS",1)
END

IF
  Global("#GNAMCHG","LOCALS",0)
  Global("#GEMPCHK","LOCALS",0)
  Global("#GFAMLVL","GLOBAL",34)
THEN
  RESPONSE #100
    SetName(@934)
    SetGlobal("#GNAMCHG","LOCALS",1)
END

IF
  Global("#GNAMCHG","LOCALS",0)
  Global("#GEMPCHK","LOCALS",0)
  Global("#GFAMLVL","GLOBAL",35)
THEN
  RESPONSE #100
    SetName(@935)
    SetGlobal("#GNAMCHG","LOCALS",1)
END

IF
  Global("#GNAMCHG","LOCALS",0)
  Global("#GEMPCHK","LOCALS",0)
  Global("#GFAMLVL","GLOBAL",36)
THEN
  RESPONSE #100
    SetName(@936)
    SetGlobal("#GNAMCHG","LOCALS",1)
END

IF
  Global("#GNAMCHG","LOCALS",0)
  Global("#GEMPCHK","LOCALS",0)
  Global("#GFAMLVL","GLOBAL",37)
THEN
  RESPONSE #100
    SetName(@937)
    SetGlobal("#GNAMCHG","LOCALS",1)
END

IF
  Global("#GNAMCHG","LOCALS",0)
  Global("#GEMPCHK","LOCALS",0)
  Global("#GFAMLVL","GLOBAL",38)
THEN
  RESPONSE #100
    SetName(@938)
    SetGlobal("#GNAMCHG","LOCALS",1)
END

IF
  Global("#GNAMCHG","LOCALS",0)
  Global("#GEMPCHK","LOCALS",0)
  Global("#GFAMLVL","GLOBAL",39)
THEN
  RESPONSE #100
    SetName(@939)
    SetGlobal("#GNAMCHG","LOCALS",1)
END

IF
  Global("#GNAMCHG","LOCALS",0)
  Global("#GEMPCHK","LOCALS",0)
  Global("#GFAMLVL","GLOBAL",40)
THEN
  RESPONSE #100
    SetName(@940)
    SetGlobal("#GNAMCHG","LOCALS",1)
END

IF
  Global("#GNAMCHG","LOCALS",0)
  Global("#GEMPCHK","LOCALS",0)
  Global("#GFAMLVL","GLOBAL",41)
THEN
  RESPONSE #100
    SetName(@941)
    SetGlobal("#GNAMCHG","LOCALS",1)
END

IF
  Global("#GNAMCHG","LOCALS",0)
  Global("#GEMPCHK","LOCALS",0)
  Global("#GFAMLVL","GLOBAL",42)
THEN
  RESPONSE #100
    SetName(@942)
    SetGlobal("#GNAMCHG","LOCALS",1)
END

IF
  Global("#GNAMCHG","LOCALS",0)
  Global("#GEMPCHK","LOCALS",0)
  Global("#GFAMLVL","GLOBAL",43)
THEN
  RESPONSE #100
    SetName(@943)
    SetGlobal("#GNAMCHG","LOCALS",1)
END

IF
  Global("#GNAMCHG","LOCALS",0)
  Global("#GEMPCHK","LOCALS",0)
  Global("#GFAMLVL","GLOBAL",44)
THEN
  RESPONSE #100
    SetName(@944)
    SetGlobal("#GNAMCHG","LOCALS",1)
END

IF
  Global("#GNAMCHG","LOCALS",0)
  Global("#GEMPCHK","LOCALS",0)
  Global("#GFAMLVL","GLOBAL",45)
THEN
  RESPONSE #100
    SetName(@945)
    SetGlobal("#GNAMCHG","LOCALS",1)
END

IF
  Global("#GNAMCHG","LOCALS",0)
  Global("#GEMPCHK","LOCALS",0)
  Global("#GFAMLVL","GLOBAL",46)
THEN
  RESPONSE #100
    SetName(@946)
    SetGlobal("#GNAMCHG","LOCALS",1)
END

IF
  Global("#GNAMCHG","LOCALS",0)
  Global("#GEMPCHK","LOCALS",0)
  Global("#GFAMLVL","GLOBAL",47)
THEN
  RESPONSE #100
    SetName(@947)
    SetGlobal("#GNAMCHG","LOCALS",1)
END

IF
  Global("#GNAMCHG","LOCALS",0)
  Global("#GEMPCHK","LOCALS",0)
  Global("#GFAMLVL","GLOBAL",48)
THEN
  RESPONSE #100
    SetName(@948)
    SetGlobal("#GNAMCHG","LOCALS",1)
END

IF
  Global("#GNAMCHG","LOCALS",0)
  Global("#GEMPCHK","LOCALS",0)
  Global("#GFAMLVL","GLOBAL",49)
THEN
  RESPONSE #100
    SetName(@949)
    SetGlobal("#GNAMCHG","LOCALS",1)
END

IF
  Global("#GNAMCHG","LOCALS",1)
  Global("#GEMPCHK","LOCALS",1)
  Global("#GFAMLVL","GLOBAL",0)
THEN
  RESPONSE #100
    SetName(@9)
    SetGlobal("#GNAMCHG","LOCALS",0)
END

IF
  Global("#GNAMCHG","LOCALS",1)
  Global("#GEMPCHK","LOCALS",1)
  Global("#GFAMLVL","GLOBAL",1)
THEN
  RESPONSE #100
    SetName(@364)
    SetGlobal("#GNAMCHG","LOCALS",0)
END

IF
  Global("#GNAMCHG","LOCALS",1)
  Global("#GEMPCHK","LOCALS",1)
  Global("#GFAMLVL","GLOBAL",2)
THEN
  RESPONSE #100
    SetName(@365)
    SetGlobal("#GNAMCHG","LOCALS",0)
END

IF
  Global("#GNAMCHG","LOCALS",1)
  Global("#GEMPCHK","LOCALS",1)
  Global("#GFAMLVL","GLOBAL",3)
THEN
  RESPONSE #100
    SetName(@366)
    SetGlobal("#GNAMCHG","LOCALS",0)
END

IF
  Global("#GNAMCHG","LOCALS",1)
  Global("#GEMPCHK","LOCALS",1)
  Global("#GFAMLVL","GLOBAL",4)
THEN
  RESPONSE #100
    SetName(@367)
    SetGlobal("#GNAMCHG","LOCALS",0)
END

IF
  Global("#GNAMCHG","LOCALS",1)
  Global("#GEMPCHK","LOCALS",1)
  Global("#GFAMLVL","GLOBAL",5)
THEN
  RESPONSE #100
    SetName(@368)
    SetGlobal("#GNAMCHG","LOCALS",0)
END

IF
  Global("#GNAMCHG","LOCALS",1)
  Global("#GEMPCHK","LOCALS",1)
  Global("#GFAMLVL","GLOBAL",6)
THEN
  RESPONSE #100
    SetName(@369)
    SetGlobal("#GNAMCHG","LOCALS",0)
END

IF
  Global("#GNAMCHG","LOCALS",1)
  Global("#GEMPCHK","LOCALS",1)
  Global("#GFAMLVL","GLOBAL",7)
THEN
  RESPONSE #100
    SetName(@370)
    SetGlobal("#GNAMCHG","LOCALS",0)
END

IF
  Global("#GNAMCHG","LOCALS",1)
  Global("#GEMPCHK","LOCALS",1)
  Global("#GFAMLVL","GLOBAL",8)
THEN
  RESPONSE #100
    SetName(@371)
    SetGlobal("#GNAMCHG","LOCALS",0)
END

IF
  Global("#GNAMCHG","LOCALS",1)
  Global("#GEMPCHK","LOCALS",1)
  Global("#GFAMLVL","GLOBAL",9)
THEN
  RESPONSE #100
    SetName(@372)
    SetGlobal("#GNAMCHG","LOCALS",0)
END

IF
  Global("#GNAMCHG","LOCALS",1)
  Global("#GEMPCHK","LOCALS",1)
  Global("#GFAMLVL","GLOBAL",10)
THEN
  RESPONSE #100
    SetName(@373)
    SetGlobal("#GNAMCHG","LOCALS",0)
END

IF
  Global("#GNAMCHG","LOCALS",1)
  Global("#GEMPCHK","LOCALS",1)
  Global("#GFAMLVL","GLOBAL",11)
THEN
  RESPONSE #100
    SetName(@374)
    SetGlobal("#GNAMCHG","LOCALS",0)
END

IF
  Global("#GNAMCHG","LOCALS",1)
  Global("#GEMPCHK","LOCALS",1)
  Global("#GFAMLVL","GLOBAL",12)
THEN
  RESPONSE #100
    SetName(@375)
    SetGlobal("#GNAMCHG","LOCALS",0)
END

IF
  Global("#GNAMCHG","LOCALS",1)
  Global("#GEMPCHK","LOCALS",1)
  Global("#GFAMLVL","GLOBAL",13)
THEN
  RESPONSE #100
    SetName(@376)
    SetGlobal("#GNAMCHG","LOCALS",0)
END

IF
  Global("#GNAMCHG","LOCALS",1)
  Global("#GEMPCHK","LOCALS",1)
  Global("#GFAMLVL","GLOBAL",14)
THEN
  RESPONSE #100
    SetName(@377)
    SetGlobal("#GNAMCHG","LOCALS",0)
END

IF
  Global("#GNAMCHG","LOCALS",1)
  Global("#GEMPCHK","LOCALS",1)
  Global("#GFAMLVL","GLOBAL",15)
THEN
  RESPONSE #100
    SetName(@378)
    SetGlobal("#GNAMCHG","LOCALS",0)
END

IF
  Global("#GNAMCHG","LOCALS",1)
  Global("#GEMPCHK","LOCALS",1)
  Global("#GFAMLVL","GLOBAL",16)
THEN
  RESPONSE #100
    SetName(@379)
    SetGlobal("#GNAMCHG","LOCALS",0)
END

IF
  Global("#GNAMCHG","LOCALS",1)
  Global("#GEMPCHK","LOCALS",1)
  Global("#GFAMLVL","GLOBAL",17)
THEN
  RESPONSE #100
    SetName(@380)
    SetGlobal("#GNAMCHG","LOCALS",0)
END

IF
  Global("#GNAMCHG","LOCALS",1)
  Global("#GEMPCHK","LOCALS",1)
  Global("#GFAMLVL","GLOBAL",18)
THEN
  RESPONSE #100
    SetName(@381)
    SetGlobal("#GNAMCHG","LOCALS",0)
END

IF
  Global("#GNAMCHG","LOCALS",1)
  Global("#GEMPCHK","LOCALS",1)
  Global("#GFAMLVL","GLOBAL",19)
THEN
  RESPONSE #100
    SetName(@382)
    SetGlobal("#GNAMCHG","LOCALS",0)
END

IF
  Global("#GNAMCHG","LOCALS",1)
  Global("#GEMPCHK","LOCALS",1)
  Global("#GFAMLVL","GLOBAL",20)
THEN
  RESPONSE #100
    SetName(@383)
    SetGlobal("#GNAMCHG","LOCALS",0)
END

IF
  Global("#GNAMCHG","LOCALS",1)
  Global("#GEMPCHK","LOCALS",1)
  Global("#GFAMLVL","GLOBAL",21)
THEN
  RESPONSE #100
    SetName(@384)
    SetGlobal("#GNAMCHG","LOCALS",0)
END

IF
  Global("#GNAMCHG","LOCALS",1)
  Global("#GEMPCHK","LOCALS",1)
  Global("#GFAMLVL","GLOBAL",22)
THEN
  RESPONSE #100
    SetName(@385)
    SetGlobal("#GNAMCHG","LOCALS",0)
END

IF
  Global("#GNAMCHG","LOCALS",1)
  Global("#GEMPCHK","LOCALS",1)
  Global("#GFAMLVL","GLOBAL",23)
THEN
  RESPONSE #100
    SetName(@386)
    SetGlobal("#GNAMCHG","LOCALS",0)
END

IF
  Global("#GNAMCHG","LOCALS",1)
  Global("#GEMPCHK","LOCALS",1)
  Global("#GFAMLVL","GLOBAL",24)
THEN
  RESPONSE #100
    SetName(@387)
    SetGlobal("#GNAMCHG","LOCALS",0)
END

IF
  Global("#GNAMCHG","LOCALS",1)
  Global("#GEMPCHK","LOCALS",1)
  Global("#GFAMLVL","GLOBAL",25)
THEN
  RESPONSE #100
    SetName(@388)
    SetGlobal("#GNAMCHG","LOCALS",0)
END

IF
  Global("#GNAMCHG","LOCALS",1)
  Global("#GEMPCHK","LOCALS",1)
  Global("#GFAMLVL","GLOBAL",26)
THEN
  RESPONSE #100
    SetName(@389)
    SetGlobal("#GNAMCHG","LOCALS",0)
END

IF
  Global("#GNAMCHG","LOCALS",1)
  Global("#GEMPCHK","LOCALS",1)
  Global("#GFAMLVL","GLOBAL",27)
THEN
  RESPONSE #100
    SetName(@390)
    SetGlobal("#GNAMCHG","LOCALS",0)
END

IF
  Global("#GNAMCHG","LOCALS",1)
  Global("#GEMPCHK","LOCALS",1)
  Global("#GFAMLVL","GLOBAL",28)
THEN
  RESPONSE #100
    SetName(@391)
    SetGlobal("#GNAMCHG","LOCALS",0)
END

IF
  Global("#GNAMCHG","LOCALS",1)
  Global("#GEMPCHK","LOCALS",1)
  Global("#GFAMLVL","GLOBAL",29)
THEN
  RESPONSE #100
    SetName(@392)
    SetGlobal("#GNAMCHG","LOCALS",0)
END

IF
  Global("#GNAMCHG","LOCALS",1)
  Global("#GEMPCHK","LOCALS",1)
  Global("#GFAMLVL","GLOBAL",30)
THEN
  RESPONSE #100
    SetName(@393)
    SetGlobal("#GNAMCHG","LOCALS",0)
END

IF
  Global("#GNAMCHG","LOCALS",1)
  Global("#GEMPCHK","LOCALS",1)
  Global("#GFAMLVL","GLOBAL",31)
THEN
  RESPONSE #100
    SetName(@394)
    SetGlobal("#GNAMCHG","LOCALS",0)
END

IF
  Global("#GNAMCHG","LOCALS",1)
  Global("#GEMPCHK","LOCALS",1)
  Global("#GFAMLVL","GLOBAL",32)
THEN
  RESPONSE #100
    SetName(@395)
    SetGlobal("#GNAMCHG","LOCALS",0)
END

IF
  Global("#GNAMCHG","LOCALS",1)
  Global("#GEMPCHK","LOCALS",1)
  Global("#GFAMLVL","GLOBAL",33)
THEN
  RESPONSE #100
    SetName(@396)
    SetGlobal("#GNAMCHG","LOCALS",0)
END

IF
  Global("#GNAMCHG","LOCALS",1)
  Global("#GEMPCHK","LOCALS",1)
  Global("#GFAMLVL","GLOBAL",34)
THEN
  RESPONSE #100
    SetName(@397)
    SetGlobal("#GNAMCHG","LOCALS",0)
END

IF
  Global("#GNAMCHG","LOCALS",1)
  Global("#GEMPCHK","LOCALS",1)
  Global("#GFAMLVL","GLOBAL",35)
THEN
  RESPONSE #100
    SetName(@398)
    SetGlobal("#GNAMCHG","LOCALS",0)
END

IF
  Global("#GNAMCHG","LOCALS",1)
  Global("#GEMPCHK","LOCALS",1)
  Global("#GFAMLVL","GLOBAL",36)
THEN
  RESPONSE #100
    SetName(@399)
    SetGlobal("#GNAMCHG","LOCALS",0)
END

IF
  Global("#GNAMCHG","LOCALS",1)
  Global("#GEMPCHK","LOCALS",1)
  Global("#GFAMLVL","GLOBAL",37)
THEN
  RESPONSE #100
    SetName(@400)
    SetGlobal("#GNAMCHG","LOCALS",0)
END

IF
  Global("#GNAMCHG","LOCALS",1)
  Global("#GEMPCHK","LOCALS",1)
  Global("#GFAMLVL","GLOBAL",38)
THEN
  RESPONSE #100
    SetName(@401)
    SetGlobal("#GNAMCHG","LOCALS",0)
END

IF
  Global("#GNAMCHG","LOCALS",1)
  Global("#GEMPCHK","LOCALS",1)
  Global("#GFAMLVL","GLOBAL",39)
THEN
  RESPONSE #100
    SetName(@402)
    SetGlobal("#GNAMCHG","LOCALS",0)
END

IF
  Global("#GNAMCHG","LOCALS",1)
  Global("#GEMPCHK","LOCALS",1)
  Global("#GFAMLVL","GLOBAL",40)
THEN
  RESPONSE #100
    SetName(@403)
    SetGlobal("#GNAMCHG","LOCALS",0)
END

IF
  Global("#GNAMCHG","LOCALS",1)
  Global("#GEMPCHK","LOCALS",1)
  Global("#GFAMLVL","GLOBAL",41)
THEN
  RESPONSE #100
    SetName(@404)
    SetGlobal("#GNAMCHG","LOCALS",0)
END

IF
  Global("#GNAMCHG","LOCALS",1)
  Global("#GEMPCHK","LOCALS",1)
  Global("#GFAMLVL","GLOBAL",42)
THEN
  RESPONSE #100
    SetName(@405)
    SetGlobal("#GNAMCHG","LOCALS",0)
END

IF
  Global("#GNAMCHG","LOCALS",1)
  Global("#GEMPCHK","LOCALS",1)
  Global("#GFAMLVL","GLOBAL",43)
THEN
  RESPONSE #100
    SetName(@406)
    SetGlobal("#GNAMCHG","LOCALS",0)
END

IF
  Global("#GNAMCHG","LOCALS",1)
  Global("#GEMPCHK","LOCALS",1)
  Global("#GFAMLVL","GLOBAL",44)
THEN
  RESPONSE #100
    SetName(@407)
    SetGlobal("#GNAMCHG","LOCALS",0)
END

IF
  Global("#GNAMCHG","LOCALS",1)
  Global("#GEMPCHK","LOCALS",1)
  Global("#GFAMLVL","GLOBAL",45)
THEN
  RESPONSE #100
    SetName(@408)
    SetGlobal("#GNAMCHG","LOCALS",0)
END

IF
  Global("#GNAMCHG","LOCALS",1)
  Global("#GEMPCHK","LOCALS",1)
  Global("#GFAMLVL","GLOBAL",46)
THEN
  RESPONSE #100
    SetName(@409)
    SetGlobal("#GNAMCHG","LOCALS",0)
END

IF
  Global("#GNAMCHG","LOCALS",1)
  Global("#GEMPCHK","LOCALS",1)
  Global("#GFAMLVL","GLOBAL",47)
THEN
  RESPONSE #100
    SetName(@410)
    SetGlobal("#GNAMCHG","LOCALS",0)
END

IF
  Global("#GNAMCHG","LOCALS",1)
  Global("#GEMPCHK","LOCALS",1)
  Global("#GFAMLVL","GLOBAL",48)
THEN
  RESPONSE #100
    SetName(@411)
    SetGlobal("#GNAMCHG","LOCALS",0)
END

IF
  Global("#GNAMCHG","LOCALS",1)
  Global("#GEMPCHK","LOCALS",1)
  Global("#GFAMLVL","GLOBAL",49)
THEN
  RESPONSE #100
    SetName(@412)
    SetGlobal("#GNAMCHG","LOCALS",0)
END

///////////////////////
///Skills reapply   ///
///////////////////////

IF
  Global("#GSKIRES","GLOBAL",1)
  Global("#GFAMLVL","GLOBAL",1)
THEN
  RESPONSE #100
    ApplySpellRES("WTPFMLVS",Myself)
    SetGlobal("#GSKIRES","GLOBAL",0)
END

IF
  Global("#GSKIRES","GLOBAL",1)
  Global("#GFAMLVL","GLOBAL",2)
THEN
  RESPONSE #100
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    SetGlobal("#GSKIRES","GLOBAL",0)
END

IF
  Global("#GSKIRES","GLOBAL",1)
  Global("#GFAMLVL","GLOBAL",3)
THEN
  RESPONSE #100
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    SetGlobal("#GSKIRES","GLOBAL",0)
END

IF
  Global("#GSKIRES","GLOBAL",1)
  Global("#GFAMLVL","GLOBAL",4)
THEN
  RESPONSE #100
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    SetGlobal("#GSKIRES","GLOBAL",0)
END

IF
  Global("#GSKIRES","GLOBAL",1)
  Global("#GFAMLVL","GLOBAL",5)
THEN
  RESPONSE #100
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    SetGlobal("#GSKIRES","GLOBAL",0)
END

IF
  Global("#GSKIRES","GLOBAL",1)
  Global("#GFAMLVL","GLOBAL",6)
THEN
  RESPONSE #100
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    SetGlobal("#GSKIRES","GLOBAL",0)
END

IF
  Global("#GSKIRES","GLOBAL",1)
  Global("#GFAMLVL","GLOBAL",7)
THEN
  RESPONSE #100
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVT",Myself)
    SetGlobal("#GSKIRES","GLOBAL",0)
END

IF
  Global("#GSKIRES","GLOBAL",1)
  Global("#GFAMLVL","GLOBAL",8)
THEN
  RESPONSE #100
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVT",Myself)
    SetGlobal("#GSKIRES","GLOBAL",0)
END

IF
  Global("#GSKIRES","GLOBAL",1)
  Global("#GFAMLVL","GLOBAL",9)
THEN
  RESPONSE #100
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVT",Myself)
    SetGlobal("#GSKIRES","GLOBAL",0)
END

IF
  Global("#GSKIRES","GLOBAL",1)
  Global("#GFAMLVL","GLOBAL",10)
THEN
  RESPONSE #100
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVT",Myself)
    SetGlobal("#GSKIRES","GLOBAL",0)
END

IF
  Global("#GSKIRES","GLOBAL",1)
  Global("#GFAMLVL","GLOBAL",11)
THEN
  RESPONSE #100
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVT",Myself)
    SetGlobal("#GSKIRES","GLOBAL",0)
END

IF
  Global("#GSKIRES","GLOBAL",1)
  Global("#GFAMLVL","GLOBAL",12)
THEN
  RESPONSE #100
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVT",Myself)
    SetGlobal("#GSKIRES","GLOBAL",0)
END

IF
  Global("#GSKIRES","GLOBAL",1)
  Global("#GFAMLVL","GLOBAL",13)
THEN
  RESPONSE #100
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVT",Myself)
    SetGlobal("#GSKIRES","GLOBAL",0)
END

IF
  Global("#GSKIRES","GLOBAL",1)
  Global("#GFAMLVL","GLOBAL",14)
THEN
  RESPONSE #100
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVT",Myself)
    ApplySpellRES("WTPFMLVT",Myself)
    SetGlobal("#GSKIRES","GLOBAL",0)
END

IF
  Global("#GSKIRES","GLOBAL",1)
  Global("#GFAMLVL","GLOBAL",15)
THEN
  RESPONSE #100
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVT",Myself)
    ApplySpellRES("WTPFMLVT",Myself)
    SetGlobal("#GSKIRES","GLOBAL",0)
END

IF
  Global("#GSKIRES","GLOBAL",1)
  Global("#GFAMLVL","GLOBAL",16)
THEN
  RESPONSE #100
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVT",Myself)
    ApplySpellRES("WTPFMLVT",Myself)
    SetGlobal("#GSKIRES","GLOBAL",0)
END

IF
  Global("#GSKIRES","GLOBAL",1)
  Global("#GFAMLVL","GLOBAL",17)
THEN
  RESPONSE #100
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVT",Myself)
    ApplySpellRES("WTPFMLVT",Myself)
    SetGlobal("#GSKIRES","GLOBAL",0)
END

IF
  Global("#GSKIRES","GLOBAL",1)
  Global("#GFAMLVL","GLOBAL",18)
THEN
  RESPONSE #100
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVT",Myself)
    ApplySpellRES("WTPFMLVT",Myself)
    SetGlobal("#GSKIRES","GLOBAL",0)
END

IF
  Global("#GSKIRES","GLOBAL",1)
  Global("#GFAMLVL","GLOBAL",19)
THEN
  RESPONSE #100
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVT",Myself)
    ApplySpellRES("WTPFMLVT",Myself)
    SetGlobal("#GSKIRES","GLOBAL",0)
END

IF
  Global("#GSKIRES","GLOBAL",1)
  Global("#GFAMLVL","GLOBAL",20)
THEN
  RESPONSE #100
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVT",Myself)
    ApplySpellRES("WTPFMLVT",Myself)
    SetGlobal("#GSKIRES","GLOBAL",0)
END

IF
  Global("#GSKIRES","GLOBAL",1)
  Global("#GFAMLVL","GLOBAL",21)
THEN
  RESPONSE #100
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVT",Myself)
    ApplySpellRES("WTPFMLVT",Myself)
    ApplySpellRES("WTPFMLVT",Myself)
    SetGlobal("#GSKIRES","GLOBAL",0)
END

IF
  Global("#GSKIRES","GLOBAL",1)
  Global("#GFAMLVL","GLOBAL",22)
THEN
  RESPONSE #100
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVT",Myself)
    ApplySpellRES("WTPFMLVT",Myself)
    ApplySpellRES("WTPFMLVT",Myself)
    SetGlobal("#GSKIRES","GLOBAL",0)
END

IF
  Global("#GSKIRES","GLOBAL",1)
  Global("#GFAMLVL","GLOBAL",23)
THEN
  RESPONSE #100
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVT",Myself)
    ApplySpellRES("WTPFMLVT",Myself)
    ApplySpellRES("WTPFMLVT",Myself)
    SetGlobal("#GSKIRES","GLOBAL",0)
END

IF
  Global("#GSKIRES","GLOBAL",1)
  Global("#GFAMLVL","GLOBAL",24)
THEN
  RESPONSE #100
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVT",Myself)
    ApplySpellRES("WTPFMLVT",Myself)
    ApplySpellRES("WTPFMLVT",Myself)
    SetGlobal("#GSKIRES","GLOBAL",0)
END

IF
  Global("#GSKIRES","GLOBAL",1)
  Global("#GFAMLVL","GLOBAL",25)
THEN
  RESPONSE #100
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVT",Myself)
    ApplySpellRES("WTPFMLVT",Myself)
    ApplySpellRES("WTPFMLVT",Myself)
    SetGlobal("#GSKIRES","GLOBAL",0)
END

IF
  Global("#GSKIRES","GLOBAL",1)
  Global("#GFAMLVL","GLOBAL",26)
THEN
  RESPONSE #100
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVT",Myself)
    ApplySpellRES("WTPFMLVT",Myself)
    ApplySpellRES("WTPFMLVT",Myself)
    SetGlobal("#GSKIRES","GLOBAL",0)
END

IF
  Global("#GSKIRES","GLOBAL",1)
  Global("#GFAMLVL","GLOBAL",27)
THEN
  RESPONSE #100
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVT",Myself)
    ApplySpellRES("WTPFMLVT",Myself)
    ApplySpellRES("WTPFMLVT",Myself)
    SetGlobal("#GSKIRES","GLOBAL",0)
END

IF
  Global("#GSKIRES","GLOBAL",1)
  Global("#GFAMLVL","GLOBAL",28)
THEN
  RESPONSE #100
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVT",Myself)
    ApplySpellRES("WTPFMLVT",Myself)
    ApplySpellRES("WTPFMLVT",Myself)
    ApplySpellRES("WTPFMLVT",Myself)
    SetGlobal("#GSKIRES","GLOBAL",0)
END

IF
  Global("#GSKIRES","GLOBAL",1)
  Global("#GFAMLVL","GLOBAL",29)
THEN
  RESPONSE #100
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVT",Myself)
    ApplySpellRES("WTPFMLVT",Myself)
    ApplySpellRES("WTPFMLVT",Myself)
    ApplySpellRES("WTPFMLVT",Myself)
    SetGlobal("#GSKIRES","GLOBAL",0)
END

IF
  Global("#GSKIRES","GLOBAL",1)
  Global("#GFAMLVL","GLOBAL",30)
THEN
  RESPONSE #100
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVT",Myself)
    ApplySpellRES("WTPFMLVT",Myself)
    ApplySpellRES("WTPFMLVT",Myself)
    ApplySpellRES("WTPFMLVT",Myself)
    SetGlobal("#GSKIRES","GLOBAL",0)
END

IF
  Global("#GSKIRES","GLOBAL",1)
  Global("#GFAMLVL","GLOBAL",31)
THEN
  RESPONSE #100
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVT",Myself)
    ApplySpellRES("WTPFMLVT",Myself)
    ApplySpellRES("WTPFMLVT",Myself)
    ApplySpellRES("WTPFMLVT",Myself)
    SetGlobal("#GSKIRES","GLOBAL",0)
END

IF
  Global("#GSKIRES","GLOBAL",1)
  Global("#GFAMLVL","GLOBAL",32)
THEN
  RESPONSE #100
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVT",Myself)
    ApplySpellRES("WTPFMLVT",Myself)
    ApplySpellRES("WTPFMLVT",Myself)
    ApplySpellRES("WTPFMLVT",Myself)
    SetGlobal("#GSKIRES","GLOBAL",0)
END

IF
  Global("#GSKIRES","GLOBAL",1)
  Global("#GFAMLVL","GLOBAL",33)
THEN
  RESPONSE #100
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVT",Myself)
    ApplySpellRES("WTPFMLVT",Myself)
    ApplySpellRES("WTPFMLVT",Myself)
    ApplySpellRES("WTPFMLVT",Myself)
    SetGlobal("#GSKIRES","GLOBAL",0)
END

IF
  Global("#GSKIRES","GLOBAL",1)
  Global("#GFAMLVL","GLOBAL",34)
THEN
  RESPONSE #100
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVT",Myself)
    ApplySpellRES("WTPFMLVT",Myself)
    ApplySpellRES("WTPFMLVT",Myself)
    ApplySpellRES("WTPFMLVT",Myself)
    SetGlobal("#GSKIRES","GLOBAL",0)
END

IF
  Global("#GSKIRES","GLOBAL",1)
  Global("#GFAMLVL","GLOBAL",35)
THEN
  RESPONSE #100
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVT",Myself)
    ApplySpellRES("WTPFMLVT",Myself)
    ApplySpellRES("WTPFMLVT",Myself)
    ApplySpellRES("WTPFMLVT",Myself)
    ApplySpellRES("WTPFMLVT",Myself)
    SetGlobal("#GSKIRES","GLOBAL",0)
END

IF
  Global("#GSKIRES","GLOBAL",1)
  Global("#GFAMLVL","GLOBAL",36)
THEN
  RESPONSE #100
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVT",Myself)
    ApplySpellRES("WTPFMLVT",Myself)
    ApplySpellRES("WTPFMLVT",Myself)
    ApplySpellRES("WTPFMLVT",Myself)
    ApplySpellRES("WTPFMLVT",Myself)
    SetGlobal("#GSKIRES","GLOBAL",0)
END

IF
  Global("#GSKIRES","GLOBAL",1)
  Global("#GFAMLVL","GLOBAL",37)
THEN
  RESPONSE #100
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVT",Myself)
    ApplySpellRES("WTPFMLVT",Myself)
    ApplySpellRES("WTPFMLVT",Myself)
    ApplySpellRES("WTPFMLVT",Myself)
    ApplySpellRES("WTPFMLVT",Myself)
    SetGlobal("#GSKIRES","GLOBAL",0)
END

IF
  Global("#GSKIRES","GLOBAL",1)
  Global("#GFAMLVL","GLOBAL",38)
THEN
  RESPONSE #100
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVT",Myself)
    ApplySpellRES("WTPFMLVT",Myself)
    ApplySpellRES("WTPFMLVT",Myself)
    ApplySpellRES("WTPFMLVT",Myself)
    ApplySpellRES("WTPFMLVT",Myself)
    SetGlobal("#GSKIRES","GLOBAL",0)
END

IF
  Global("#GSKIRES","GLOBAL",1)
  Global("#GFAMLVL","GLOBAL",39)
THEN
  RESPONSE #100
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVT",Myself)
    ApplySpellRES("WTPFMLVT",Myself)
    ApplySpellRES("WTPFMLVT",Myself)
    ApplySpellRES("WTPFMLVT",Myself)
    ApplySpellRES("WTPFMLVT",Myself)
    SetGlobal("#GSKIRES","GLOBAL",0)
END

IF
  Global("#GSKIRES","GLOBAL",1)
  Global("#GFAMLVL","GLOBAL",40)
THEN
  RESPONSE #100
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVT",Myself)
    ApplySpellRES("WTPFMLVT",Myself)
    ApplySpellRES("WTPFMLVT",Myself)
    ApplySpellRES("WTPFMLVT",Myself)
    ApplySpellRES("WTPFMLVT",Myself)
    SetGlobal("#GSKIRES","GLOBAL",0)
END

IF
  Global("#GSKIRES","GLOBAL",1)
  Global("#GFAMLVL","GLOBAL",41)
THEN
  RESPONSE #100
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVT",Myself)
    ApplySpellRES("WTPFMLVT",Myself)
    ApplySpellRES("WTPFMLVT",Myself)
    ApplySpellRES("WTPFMLVT",Myself)
    ApplySpellRES("WTPFMLVT",Myself)
    SetGlobal("#GSKIRES","GLOBAL",0)
END

IF
  Global("#GSKIRES","GLOBAL",1)
  Global("#GFAMLVL","GLOBAL",42)
THEN
  RESPONSE #100
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVT",Myself)
    ApplySpellRES("WTPFMLVT",Myself)
    ApplySpellRES("WTPFMLVT",Myself)
    ApplySpellRES("WTPFMLVT",Myself)
    ApplySpellRES("WTPFMLVT",Myself)
    ApplySpellRES("WTPFMLVT",Myself)
    SetGlobal("#GSKIRES","GLOBAL",0)
END

IF
  Global("#GSKIRES","GLOBAL",1)
  Global("#GFAMLVL","GLOBAL",43)
THEN
  RESPONSE #100
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVT",Myself)
    ApplySpellRES("WTPFMLVT",Myself)
    ApplySpellRES("WTPFMLVT",Myself)
    ApplySpellRES("WTPFMLVT",Myself)
    ApplySpellRES("WTPFMLVT",Myself)
    ApplySpellRES("WTPFMLVT",Myself)
    SetGlobal("#GSKIRES","GLOBAL",0)
END

IF
  Global("#GSKIRES","GLOBAL",1)
  Global("#GFAMLVL","GLOBAL",44)
THEN
  RESPONSE #100
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVT",Myself)
    ApplySpellRES("WTPFMLVT",Myself)
    ApplySpellRES("WTPFMLVT",Myself)
    ApplySpellRES("WTPFMLVT",Myself)
    ApplySpellRES("WTPFMLVT",Myself)
    ApplySpellRES("WTPFMLVT",Myself)
    SetGlobal("#GSKIRES","GLOBAL",0)
END

IF
  Global("#GSKIRES","GLOBAL",1)
  Global("#GFAMLVL","GLOBAL",45)
THEN
  RESPONSE #100
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVT",Myself)
    ApplySpellRES("WTPFMLVT",Myself)
    ApplySpellRES("WTPFMLVT",Myself)
    ApplySpellRES("WTPFMLVT",Myself)
    ApplySpellRES("WTPFMLVT",Myself)
    ApplySpellRES("WTPFMLVT",Myself)
    SetGlobal("#GSKIRES","GLOBAL",0)
END

IF
  Global("#GSKIRES","GLOBAL",1)
  Global("#GFAMLVL","GLOBAL",46)
THEN
  RESPONSE #100
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVT",Myself)
    ApplySpellRES("WTPFMLVT",Myself)
    ApplySpellRES("WTPFMLVT",Myself)
    ApplySpellRES("WTPFMLVT",Myself)
    ApplySpellRES("WTPFMLVT",Myself)
    ApplySpellRES("WTPFMLVT",Myself)
    SetGlobal("#GSKIRES","GLOBAL",0)
END

IF
  Global("#GSKIRES","GLOBAL",1)
  Global("#GFAMLVL","GLOBAL",47)
THEN
  RESPONSE #100
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVT",Myself)
    ApplySpellRES("WTPFMLVT",Myself)
    ApplySpellRES("WTPFMLVT",Myself)
    ApplySpellRES("WTPFMLVT",Myself)
    ApplySpellRES("WTPFMLVT",Myself)
    ApplySpellRES("WTPFMLVT",Myself)
    SetGlobal("#GSKIRES","GLOBAL",0)
END

IF
  Global("#GSKIRES","GLOBAL",1)
  Global("#GFAMLVL","GLOBAL",48)
THEN
  RESPONSE #100
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVT",Myself)
    ApplySpellRES("WTPFMLVT",Myself)
    ApplySpellRES("WTPFMLVT",Myself)
    ApplySpellRES("WTPFMLVT",Myself)
    ApplySpellRES("WTPFMLVT",Myself)
    ApplySpellRES("WTPFMLVT",Myself)
    SetGlobal("#GSKIRES","GLOBAL",0)
END

IF
  Global("#GSKIRES","GLOBAL",1)
  Global("#GFAMLVL","GLOBAL",49)
THEN
  RESPONSE #100
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVS",Myself)
    ApplySpellRES("WTPFMLVT",Myself)
    ApplySpellRES("WTPFMLVT",Myself)
    ApplySpellRES("WTPFMLVT",Myself)
    ApplySpellRES("WTPFMLVT",Myself)
    ApplySpellRES("WTPFMLVT",Myself)
    ApplySpellRES("WTPFMLVT",Myself)
    ApplySpellRES("WTPFMLVT",Myself)
    SetGlobal("#GSKIRES","GLOBAL",0)
END
