//////////////////////
///Familiar nags   ///
//////////////////////

IF
  Global("#GFAMGO","GLOBAL",0)
  Global("SPRITE_IS_DEADWTPCAT","GLOBAL",0)
  Global("SPRITE_IS_DEADWTPDMEPH","GLOBAL",0)
  Global("SPRITE_IS_DEADWTPFAIRY","GLOBAL",0)
  Global("SPRITE_IS_DEADWTPFERRE","GLOBAL",0)
  Global("SPRITE_IS_DEADWTPIMP","GLOBAL",0)
  Global("SPRITE_IS_DEADWTPSEUDO","GLOBAL",0)
  Global("SPRITE_IS_DEADWTPQUASI","GLOBAL",0)
  Global("SPRITE_IS_DEADWTPRABBI","GLOBAL",0)
  Global("SPRITE_IS_DEADWTPSPIDE","GLOBAL",0)
  OR(9)
    Allegiance("WTPseudo",FAMILIAR)
    Allegiance("WTPImp",FAMILIAR)
    Allegiance("WTPFerre",FAMILIAR)
    Allegiance("WTPCat",FAMILIAR)
    Allegiance("WTPRabbi",FAMILIAR)
    Allegiance("WTPDMeph",FAMILIAR)
    Allegiance("WTPFairy",FAMILIAR)
    Allegiance("WTPSpide",FAMILIAR)
    Allegiance("WTPQuasi",FAMILIAR)
THEN
  RESPONSE #100
    StartDialogueNoSet(%famsummoner%)
END

//////////////////////
///Familiar dies   ///
//////////////////////

////////////////////////////
///HP Bonus off		 ///
////////////////////////////

IF
  OR(2)
    Global("#GStartSpl","GLOBAL",0)
    HPGT(%famsummoner%,41)
  OR(2)
    Global("#GHPOFF","GLOBAL",1)
    Global("#GFAMGO","GLOBAL",3)
  OR(2)
    Global("#GFAMLVL","GLOBAL",49) // Familiar Lv 50
    Global("#GFAMLVL","GLOBAL",48) // Familiar Lv 49
THEN
  RESPONSE #100
    SetGlobal("#GHPCNT","LOCALS",43)
    Continue()
END

IF
  Global("#GStartSpl","GLOBAL",1)
  HPLT(%famsummoner%,42)
  OR(2)
    Global("#GHPOFF","GLOBAL",1)
    Global("#GFAMGO","GLOBAL",3)
  OR(2)
    Global("#GFAMLVL","GLOBAL",49) // Familiar Lv 50
    Global("#GFAMLVL","GLOBAL",48) // Familiar Lv 49
THEN
  RESPONSE #100
    SetGlobal("#GHPCNT","LOCALS",83)
    Continue()
END

IF
  OR(2)
    Global("#GStartSpl","GLOBAL",0)
    HPGT(%famsummoner%,40)
  OR(2)
    Global("#GHPOFF","GLOBAL",1)
    Global("#GFAMGO","GLOBAL",3)
  OR(2)
    Global("#GFAMLVL","GLOBAL",47) // Familiar Lv 48
    Global("#GFAMLVL","GLOBAL",46) // Familiar Lv 47
THEN
  RESPONSE #100
    SetGlobal("#GHPCNT","LOCALS",42)
    Continue()
END

IF
  Global("#GStartSpl","GLOBAL",1)
  HPLT(%famsummoner%,41)
  OR(2)
    Global("#GHPOFF","GLOBAL",1)
    Global("#GFAMGO","GLOBAL",3)
  OR(2)
    Global("#GFAMLVL","GLOBAL",47) // Familiar Lv 48
    Global("#GFAMLVL","GLOBAL",46) // Familiar Lv 47
THEN
  RESPONSE #100
    SetGlobal("#GHPCNT","LOCALS",82)
    Continue()
END

IF
  OR(2)
    Global("#GStartSpl","GLOBAL",0)
    HPGT(%famsummoner%,39)
  OR(2)
    Global("#GHPOFF","GLOBAL",1)
    Global("#GFAMGO","GLOBAL",3)
  OR(2)
    Global("#GFAMLVL","GLOBAL",45) // Familiar Lv 46
    Global("#GFAMLVL","GLOBAL",44) // Familiar Lv 45
THEN
  RESPONSE #100
    SetGlobal("#GHPCNT","LOCALS",41)
    Continue()
END

IF
  Global("#GStartSpl","GLOBAL",1)
  HPLT(%famsummoner%,40)
  OR(2)
    Global("#GHPOFF","GLOBAL",1)
    Global("#GFAMGO","GLOBAL",3)
  OR(2)
    Global("#GFAMLVL","GLOBAL",45) // Familiar Lv 46
    Global("#GFAMLVL","GLOBAL",44) // Familiar Lv 45
THEN
  RESPONSE #100
    SetGlobal("#GHPCNT","LOCALS",81)
    Continue()
END

IF
  OR(2)
    Global("#GStartSpl","GLOBAL",0)
    HPGT(%famsummoner%,38)
  OR(2)
    Global("#GHPOFF","GLOBAL",1)
    Global("#GFAMGO","GLOBAL",3)
  OR(2)
    Global("#GFAMLVL","GLOBAL",43) // Familiar Lv 44
    Global("#GFAMLVL","GLOBAL",42) // Familiar Lv 43
THEN
  RESPONSE #100
    SetGlobal("#GHPCNT","LOCALS",40)
    Continue()
END

IF
  Global("#GStartSpl","GLOBAL",1)
  HPLT(%famsummoner%,39)
  OR(2)
    Global("#GHPOFF","GLOBAL",1)
    Global("#GFAMGO","GLOBAL",3)
  OR(2)
    Global("#GFAMLVL","GLOBAL",43) // Familiar Lv 44
    Global("#GFAMLVL","GLOBAL",42) // Familiar Lv 43
THEN
  RESPONSE #100
    SetGlobal("#GHPCNT","LOCALS",80)
    Continue()
END

IF
  OR(2)
    Global("#GStartSpl","GLOBAL",0)
    HPGT(%famsummoner%,37)
  OR(2)
    Global("#GHPOFF","GLOBAL",1)
    Global("#GFAMGO","GLOBAL",3)
  OR(2)
    Global("#GFAMLVL","GLOBAL",41) // Familiar Lv 42
    Global("#GFAMLVL","GLOBAL",40) // Familiar Lv 41
THEN
  RESPONSE #100
    SetGlobal("#GHPCNT","LOCALS",39)
    Continue()
END

IF
  Global("#GStartSpl","GLOBAL",1)
  HPLT(%famsummoner%,38)
  OR(2)
    Global("#GHPOFF","GLOBAL",1)
    Global("#GFAMGO","GLOBAL",3)
  OR(2)
    Global("#GFAMLVL","GLOBAL",41) // Familiar Lv 42
    Global("#GFAMLVL","GLOBAL",40) // Familiar Lv 41
THEN
  RESPONSE #100
    SetGlobal("#GHPCNT","LOCALS",79)
    Continue()
END

IF
  OR(2)
    Global("#GStartSpl","GLOBAL",0)
    HPGT(%famsummoner%,36)
  OR(2)
    Global("#GHPOFF","GLOBAL",1)
    Global("#GFAMGO","GLOBAL",3)
  OR(2)
    Global("#GFAMLVL","GLOBAL",39) // Familiar Lv 40
    Global("#GFAMLVL","GLOBAL",38) // Familiar Lv 39
THEN
  RESPONSE #100
    SetGlobal("#GHPCNT","LOCALS",38)
    Continue()
END

IF
  Global("#GStartSpl","GLOBAL",1)
  HPLT(%famsummoner%,37)
  OR(2)
    Global("#GHPOFF","GLOBAL",1)
    Global("#GFAMGO","GLOBAL",3)
  OR(2)
    Global("#GFAMLVL","GLOBAL",39) // Familiar Lv 40
    Global("#GFAMLVL","GLOBAL",38) // Familiar Lv 39
THEN
  RESPONSE #100
    SetGlobal("#GHPCNT","LOCALS",78)
    Continue()
END

IF
  OR(2)
    Global("#GStartSpl","GLOBAL",0)
    HPGT(%famsummoner%,35)
  OR(2)
    Global("#GHPOFF","GLOBAL",1)
    Global("#GFAMGO","GLOBAL",3)
  OR(2)
    Global("#GFAMLVL","GLOBAL",37) // Familiar Lv 38
    Global("#GFAMLVL","GLOBAL",36) // Familiar Lv 37
THEN
  RESPONSE #100
    SetGlobal("#GHPCNT","LOCALS",37)
    Continue()
END

IF
  Global("#GStartSpl","GLOBAL",1)
  HPLT(%famsummoner%,36)
  OR(2)
    Global("#GHPOFF","GLOBAL",1)
    Global("#GFAMGO","GLOBAL",3)
  OR(2)
    Global("#GFAMLVL","GLOBAL",37) // Familiar Lv 38
    Global("#GFAMLVL","GLOBAL",36) // Familiar Lv 37
THEN
  RESPONSE #100
    SetGlobal("#GHPCNT","LOCALS",77)
    Continue()
END

IF
  OR(2)
    Global("#GStartSpl","GLOBAL",0)
    HPGT(%famsummoner%,34)
  OR(2)
    Global("#GHPOFF","GLOBAL",1)
    Global("#GFAMGO","GLOBAL",3)
  OR(2)
    Global("#GFAMLVL","GLOBAL",35) // Familiar Lv 36
    Global("#GFAMLVL","GLOBAL",34) // Familiar Lv 35
THEN
  RESPONSE #100
    SetGlobal("#GHPCNT","LOCALS",36)
    Continue()
END

IF
  Global("#GStartSpl","GLOBAL",1)
  HPLT(%famsummoner%,35)
  OR(2)
    Global("#GHPOFF","GLOBAL",1)
    Global("#GFAMGO","GLOBAL",3)
  OR(2)
    Global("#GFAMLVL","GLOBAL",35) // Familiar Lv 36
    Global("#GFAMLVL","GLOBAL",34) // Familiar Lv 35
THEN
  RESPONSE #100
    SetGlobal("#GHPCNT","LOCALS",76)
    Continue()
END

IF
  OR(2)
    Global("#GStartSpl","GLOBAL",0)
    HPGT(%famsummoner%,33)
  OR(2)
    Global("#GHPOFF","GLOBAL",1)
    Global("#GFAMGO","GLOBAL",3)
  OR(2)
    Global("#GFAMLVL","GLOBAL",33) // Familiar Lv 34
    Global("#GFAMLVL","GLOBAL",32) // Familiar Lv 33
THEN
  RESPONSE #100
    SetGlobal("#GHPCNT","LOCALS",35)
    Continue()
END

IF
  Global("#GStartSpl","GLOBAL",1)
  HPLT(%famsummoner%,34)
  OR(2)
    Global("#GHPOFF","GLOBAL",1)
    Global("#GFAMGO","GLOBAL",3)
  OR(2)
    Global("#GFAMLVL","GLOBAL",33) // Familiar Lv 34
    Global("#GFAMLVL","GLOBAL",32) // Familiar Lv 33
THEN
  RESPONSE #100
    SetGlobal("#GHPCNT","LOCALS",75)
    Continue()
END

IF
  OR(2)
    Global("#GStartSpl","GLOBAL",0)
    HPGT(%famsummoner%,32)
  OR(2)
    Global("#GHPOFF","GLOBAL",1)
    Global("#GFAMGO","GLOBAL",3)
  OR(2)
    Global("#GFAMLVL","GLOBAL",31) // Familiar Lv 32
    Global("#GFAMLVL","GLOBAL",30) // Familiar Lv 31
THEN
  RESPONSE #100
    SetGlobal("#GHPCNT","LOCALS",34)
    Continue()
END

IF
  Global("#GStartSpl","GLOBAL",1)
  HPLT(%famsummoner%,33)
  OR(2)
    Global("#GHPOFF","GLOBAL",1)
    Global("#GFAMGO","GLOBAL",3)
  OR(2)
    Global("#GFAMLVL","GLOBAL",31) // Familiar Lv 32
    Global("#GFAMLVL","GLOBAL",30) // Familiar Lv 31
THEN
  RESPONSE #100
    SetGlobal("#GHPCNT","LOCALS",74)
    Continue()
END

IF
  OR(2)
    Global("#GStartSpl","GLOBAL",0)
    HPGT(%famsummoner%,31)
  OR(2)
    Global("#GHPOFF","GLOBAL",1)
    Global("#GFAMGO","GLOBAL",3)
  OR(2)
    Global("#GFAMLVL","GLOBAL",29) // Familiar Lv 30
    Global("#GFAMLVL","GLOBAL",28) // Familiar Lv 29
THEN
  RESPONSE #100
    SetGlobal("#GHPCNT","LOCALS",33)
    Continue()
END

IF
  Global("#GStartSpl","GLOBAL",1)
  HPLT(%famsummoner%,32)
  OR(2)
    Global("#GHPOFF","GLOBAL",1)
    Global("#GFAMGO","GLOBAL",3)
  OR(2)
    Global("#GFAMLVL","GLOBAL",29) // Familiar Lv 30
    Global("#GFAMLVL","GLOBAL",28) // Familiar Lv 29
THEN
  RESPONSE #100
    SetGlobal("#GHPCNT","LOCALS",73)
    Continue()
END

IF
  OR(2)
    Global("#GStartSpl","GLOBAL",0)
    HPGT(%famsummoner%,30)
  OR(2)
    Global("#GHPOFF","GLOBAL",1)
    Global("#GFAMGO","GLOBAL",3)
  OR(2)
    Global("#GFAMLVL","GLOBAL",27) // Familiar Lv 28
    Global("#GFAMLVL","GLOBAL",26) // Familiar Lv 27
THEN
  RESPONSE #100
    SetGlobal("#GHPCNT","LOCALS",32)
    Continue()
END

IF
  Global("#GStartSpl","GLOBAL",1)
  HPLT(%famsummoner%,31)
  OR(2)
    Global("#GHPOFF","GLOBAL",1)
    Global("#GFAMGO","GLOBAL",3)
  OR(2)
    Global("#GFAMLVL","GLOBAL",27) // Familiar Lv 28
    Global("#GFAMLVL","GLOBAL",26) // Familiar Lv 27
THEN
  RESPONSE #100
    SetGlobal("#GHPCNT","LOCALS",72)
    Continue()
END

IF
  OR(2)
    Global("#GStartSpl","GLOBAL",0)
    HPGT(%famsummoner%,29)
  OR(2)
    Global("#GHPOFF","GLOBAL",1)
    Global("#GFAMGO","GLOBAL",3)
  OR(2)
    Global("#GFAMLVL","GLOBAL",25) // Familiar Lv 26
    Global("#GFAMLVL","GLOBAL",24) // Familiar Lv 25
THEN
  RESPONSE #100
    SetGlobal("#GHPCNT","LOCALS",31)
    Continue()
END

IF
  Global("#GStartSpl","GLOBAL",1)
  HPLT(%famsummoner%,30)
  OR(2)
    Global("#GHPOFF","GLOBAL",1)
    Global("#GFAMGO","GLOBAL",3)
  OR(2)
    Global("#GFAMLVL","GLOBAL",25) // Familiar Lv 26
    Global("#GFAMLVL","GLOBAL",24) // Familiar Lv 25
THEN
  RESPONSE #100
    SetGlobal("#GHPCNT","LOCALS",71)
    Continue()
END

IF
  OR(2)
    Global("#GStartSpl","GLOBAL",0)
    HPGT(%famsummoner%,28)
  OR(2)
    Global("#GHPOFF","GLOBAL",1)
    Global("#GFAMGO","GLOBAL",3)
  OR(2)
    Global("#GFAMLVL","GLOBAL",23) // Familiar Lv 24
    Global("#GFAMLVL","GLOBAL",22) // Familiar Lv 23
THEN
  RESPONSE #100
    SetGlobal("#GHPCNT","LOCALS",30)
    Continue()
END

IF
  Global("#GStartSpl","GLOBAL",1)
  HPLT(%famsummoner%,29)
  OR(2)
    Global("#GHPOFF","GLOBAL",1)
    Global("#GFAMGO","GLOBAL",3)
  OR(2)
    Global("#GFAMLVL","GLOBAL",23) // Familiar Lv 24
    Global("#GFAMLVL","GLOBAL",22) // Familiar Lv 23
THEN
  RESPONSE #100
    SetGlobal("#GHPCNT","LOCALS",70)
    Continue()
END

IF
  OR(2)
    Global("#GStartSpl","GLOBAL",0)
    HPGT(%famsummoner%,27)
  OR(2)
    Global("#GHPOFF","GLOBAL",1)
    Global("#GFAMGO","GLOBAL",3)
  OR(2)
    Global("#GFAMLVL","GLOBAL",21) // Familiar Lv 22
    Global("#GFAMLVL","GLOBAL",20) // Familiar Lv 21
THEN
  RESPONSE #100
    SetGlobal("#GHPCNT","LOCALS",29)
    Continue()
END

IF
  Global("#GStartSpl","GLOBAL",1)
  HPLT(%famsummoner%,28)
  OR(2)
    Global("#GHPOFF","GLOBAL",1)
    Global("#GFAMGO","GLOBAL",3)
  OR(2)
    Global("#GFAMLVL","GLOBAL",21) // Familiar Lv 22
    Global("#GFAMLVL","GLOBAL",20) // Familiar Lv 21
THEN
  RESPONSE #100
    SetGlobal("#GHPCNT","LOCALS",69)
    Continue()
END

IF
  OR(2)
    Global("#GStartSpl","GLOBAL",0)
    HPGT(%famsummoner%,26)
  OR(2)
    Global("#GHPOFF","GLOBAL",1)
    Global("#GFAMGO","GLOBAL",3)
  OR(2)
    Global("#GFAMLVL","GLOBAL",19) // Familiar Lv 20
    Global("#GFAMLVL","GLOBAL",18) // Familiar Lv 19
THEN
  RESPONSE #100
    SetGlobal("#GHPCNT","LOCALS",28)
    Continue()
END

IF
  Global("#GStartSpl","GLOBAL",1)
  HPLT(%famsummoner%,27)
  OR(2)
    Global("#GHPOFF","GLOBAL",1)
    Global("#GFAMGO","GLOBAL",3)
  OR(2)
    Global("#GFAMLVL","GLOBAL",19) // Familiar Lv 20
    Global("#GFAMLVL","GLOBAL",18) // Familiar Lv 19
THEN
  RESPONSE #100
    SetGlobal("#GHPCNT","LOCALS",68)
    Continue()
END

IF
  OR(2)
    Global("#GStartSpl","GLOBAL",0)
    HPGT(%famsummoner%,25)
  OR(2)
    Global("#GHPOFF","GLOBAL",1)
    Global("#GFAMGO","GLOBAL",3)
  Global("#GFAMLVL","GLOBAL",17) // Familiar Lv 18
THEN
  RESPONSE #100
    SetGlobal("#GHPCNT","LOCALS",27)
    Continue()
END

IF
  Global("#GStartSpl","GLOBAL",1)
  HPLT(%famsummoner%,26)
  OR(2)
    Global("#GHPOFF","GLOBAL",1)
    Global("#GFAMGO","GLOBAL",3)
  Global("#GFAMLVL","GLOBAL",17) // Familiar Lv 18
THEN
  RESPONSE #100
    SetGlobal("#GHPCNT","LOCALS",67)
    Continue()
END

IF
  OR(2)
    Global("#GStartSpl","GLOBAL",0)
    HPGT(%famsummoner%,24)
  OR(2)
    Global("#GHPOFF","GLOBAL",1)
    Global("#GFAMGO","GLOBAL",3)
  Global("#GFAMLVL","GLOBAL",16) // Familiar Lv 17
THEN
  RESPONSE #100
    SetGlobal("#GHPCNT","LOCALS",26)
    Continue()
END

IF
  Global("#GStartSpl","GLOBAL",1)
  HPLT(%famsummoner%,25)
  OR(2)
    Global("#GHPOFF","GLOBAL",1)
    Global("#GFAMGO","GLOBAL",3)
  Global("#GFAMLVL","GLOBAL",16) // Familiar Lv 17
THEN
  RESPONSE #100
    SetGlobal("#GHPCNT","LOCALS",66)
    Continue()
END

IF
  OR(2)
    Global("#GStartSpl","GLOBAL",0)
    HPGT(%famsummoner%,23)
  OR(2)
    Global("#GHPOFF","GLOBAL",1)
    Global("#GFAMGO","GLOBAL",3)
  Global("#GFAMLVL","GLOBAL",15) // Familiar Lv 16
THEN
  RESPONSE #100
    SetGlobal("#GHPCNT","LOCALS",25)
    Continue()
END

IF
  Global("#GStartSpl","GLOBAL",1)
  HPLT(%famsummoner%,24)
  OR(2)
    Global("#GHPOFF","GLOBAL",1)
    Global("#GFAMGO","GLOBAL",3)
  Global("#GFAMLVL","GLOBAL",15) // Familiar Lv 16
THEN
  RESPONSE #100
    SetGlobal("#GHPCNT","LOCALS",65)
    Continue()
END

IF
  OR(2)
    Global("#GStartSpl","GLOBAL",0)
    HPGT(%famsummoner%,22)
  OR(2)
    Global("#GHPOFF","GLOBAL",1)
    Global("#GFAMGO","GLOBAL",3)
  Global("#GFAMLVL","GLOBAL",14) // Familiar Lv 15
THEN
  RESPONSE #100
    SetGlobal("#GHPCNT","LOCALS",24)
    Continue()
END

IF
  Global("#GStartSpl","GLOBAL",1)
  HPLT(%famsummoner%,23)
  OR(2)
    Global("#GHPOFF","GLOBAL",1)
    Global("#GFAMGO","GLOBAL",3)
  Global("#GFAMLVL","GLOBAL",14) // Familiar Lv 15
THEN
  RESPONSE #100
    SetGlobal("#GHPCNT","LOCALS",64)
    Continue()
END

IF
  OR(2)
    Global("#GStartSpl","GLOBAL",0)
    HPGT(%famsummoner%,21)
  OR(2)
    Global("#GHPOFF","GLOBAL",1)
    Global("#GFAMGO","GLOBAL",3)
  Global("#GFAMLVL","GLOBAL",13) // Familiar Lv 14
THEN
  RESPONSE #100
    SetGlobal("#GHPCNT","LOCALS",23)
    Continue()
END

IF
  Global("#GStartSpl","GLOBAL",1)
  HPLT(%famsummoner%,22)
  OR(2)
    Global("#GHPOFF","GLOBAL",1)
    Global("#GFAMGO","GLOBAL",3)
  Global("#GFAMLVL","GLOBAL",13) // Familiar Lv 14
THEN
  RESPONSE #100
    SetGlobal("#GHPCNT","LOCALS",63)
    Continue()
END

IF
  OR(2)
    Global("#GStartSpl","GLOBAL",0)
    HPGT(%famsummoner%,20)
  OR(2)
    Global("#GHPOFF","GLOBAL",1)
    Global("#GFAMGO","GLOBAL",3)
  Global("#GFAMLVL","GLOBAL",12) // Familiar Lv 13
THEN
  RESPONSE #100
    SetGlobal("#GHPCNT","LOCALS",22)
    Continue()
END

IF
  Global("#GStartSpl","GLOBAL",1)
  HPLT(%famsummoner%,21)
  OR(2)
    Global("#GHPOFF","GLOBAL",1)
    Global("#GFAMGO","GLOBAL",3)
  Global("#GFAMLVL","GLOBAL",12) // Familiar Lv 13
THEN
  RESPONSE #100
    SetGlobal("#GHPCNT","LOCALS",62)
    Continue()
END

IF
  OR(2)
    Global("#GStartSpl","GLOBAL",0)
    HPGT(%famsummoner%,19)
  OR(2)
    Global("#GHPOFF","GLOBAL",1)
    Global("#GFAMGO","GLOBAL",3)
  Global("#GFAMLVL","GLOBAL",11) // Familiar Lv 12
THEN
  RESPONSE #100
    SetGlobal("#GHPCNT","LOCALS",21)
    Continue()
END

IF
  Global("#GStartSpl","GLOBAL",1)
  HPLT(%famsummoner%,20)
  OR(2)
    Global("#GHPOFF","GLOBAL",1)
    Global("#GFAMGO","GLOBAL",3)
  Global("#GFAMLVL","GLOBAL",11) // Familiar Lv 12
THEN
  RESPONSE #100
    SetGlobal("#GHPCNT","LOCALS",61)
    Continue()
END

IF
  OR(2)
    Global("#GStartSpl","GLOBAL",0)
    HPGT(%famsummoner%,18)
  OR(2)
    Global("#GHPOFF","GLOBAL",1)
    Global("#GFAMGO","GLOBAL",3)
  Global("#GFAMLVL","GLOBAL",10) // Familiar Lv 11
THEN
  RESPONSE #100
    SetGlobal("#GHPCNT","LOCALS",20)
    Continue()
END

IF
  Global("#GStartSpl","GLOBAL",1)
  HPLT(%famsummoner%,19)
  OR(2)
    Global("#GHPOFF","GLOBAL",1)
    Global("#GFAMGO","GLOBAL",3)
  Global("#GFAMLVL","GLOBAL",10) // Familiar Lv 11
THEN
  RESPONSE #100
    SetGlobal("#GHPCNT","LOCALS",60)
    Continue()
END

IF
  OR(2)
    Global("#GStartSpl","GLOBAL",0)
    HPGT(%famsummoner%,17)
  OR(2)
    Global("#GHPOFF","GLOBAL",1)
    Global("#GFAMGO","GLOBAL",3)
  Global("#GFAMLVL","GLOBAL",9) // Familiar Lv 10
THEN
  RESPONSE #100
    SetGlobal("#GHPCNT","LOCALS",19)
    Continue()
END

IF
  Global("#GStartSpl","GLOBAL",1)
  HPLT(%famsummoner%,18)
  OR(2)
    Global("#GHPOFF","GLOBAL",1)
    Global("#GFAMGO","GLOBAL",3)
  Global("#GFAMLVL","GLOBAL",9) // Familiar Lv 10
THEN
  RESPONSE #100
    SetGlobal("#GHPCNT","LOCALS",59)
    Continue()
END

IF
  OR(2)
    Global("#GStartSpl","GLOBAL",0)
    HPGT(%famsummoner%,16)
  OR(2)
    Global("#GHPOFF","GLOBAL",1)
    Global("#GFAMGO","GLOBAL",3)
  Global("#GFAMLVL","GLOBAL",8) // Familiar Lv 9
THEN
  RESPONSE #100
    SetGlobal("#GHPCNT","LOCALS",18)
    Continue()
END

IF
  Global("#GStartSpl","GLOBAL",1)
  HPLT(%famsummoner%,17)
  OR(2)
    Global("#GHPOFF","GLOBAL",1)
    Global("#GFAMGO","GLOBAL",3)
  Global("#GFAMLVL","GLOBAL",8) // Familiar Lv 9
THEN
  RESPONSE #100
    SetGlobal("#GHPCNT","LOCALS",58)
    Continue()
END

IF
  OR(2)
    Global("#GStartSpl","GLOBAL",0)
    HPGT(%famsummoner%,14)
  OR(2)
    Global("#GHPOFF","GLOBAL",1)
    Global("#GFAMGO","GLOBAL",3)
  Global("#GFAMLVL","GLOBAL",7) // Familiar Lv 8
THEN
  RESPONSE #100
    SetGlobal("#GHPCNT","LOCALS",16)
    Continue()
END

IF
  Global("#GStartSpl","GLOBAL",1)
  HPLT(%famsummoner%,15)
  OR(2)
    Global("#GHPOFF","GLOBAL",1)
    Global("#GFAMGO","GLOBAL",3)
  Global("#GFAMLVL","GLOBAL",7) // Familiar Lv 8
THEN
  RESPONSE #100
    SetGlobal("#GHPCNT","LOCALS",56)
    Continue()
END

IF
  OR(2)
    Global("#GStartSpl","GLOBAL",0)
    HPGT(%famsummoner%,12)
  OR(2)
    Global("#GHPOFF","GLOBAL",1)
    Global("#GFAMGO","GLOBAL",3)
  Global("#GFAMLVL","GLOBAL",6) // Familiar Lv 7
THEN
  RESPONSE #100
    SetGlobal("#GHPCNT","LOCALS",14)
    Continue()
END

IF
  Global("#GStartSpl","GLOBAL",1)
  HPLT(%famsummoner%,13)
  OR(2)
    Global("#GHPOFF","GLOBAL",1)
    Global("#GFAMGO","GLOBAL",3)
  Global("#GFAMLVL","GLOBAL",6) // Familiar Lv 7
THEN
  RESPONSE #100
    SetGlobal("#GHPCNT","LOCALS",54)
    Continue()
END

IF
  OR(2)
    Global("#GStartSpl","GLOBAL",0)
    HPGT(%famsummoner%,10)
  OR(2)
    Global("#GHPOFF","GLOBAL",1)
    Global("#GFAMGO","GLOBAL",3)
  Global("#GFAMLVL","GLOBAL",5) // Familiar Lv 6
THEN
  RESPONSE #100
    SetGlobal("#GHPCNT","LOCALS",12)
    Continue()
END

IF
  Global("#GStartSpl","GLOBAL",1)
  HPLT(%famsummoner%,11)
  OR(2)
    Global("#GHPOFF","GLOBAL",1)
    Global("#GFAMGO","GLOBAL",3)
  Global("#GFAMLVL","GLOBAL",5) // Familiar Lv 6
THEN
  RESPONSE #100
    SetGlobal("#GHPCNT","LOCALS",52)
    Continue()
END

IF
  OR(2)
    Global("#GStartSpl","GLOBAL",0)
    HPGT(%famsummoner%,8)
  OR(2)
    Global("#GHPOFF","GLOBAL",1)
    Global("#GFAMGO","GLOBAL",3)
  Global("#GFAMLVL","GLOBAL",4) // Familiar Lv 5
THEN
  RESPONSE #100
    SetGlobal("#GHPCNT","LOCALS",10)
    Continue()
END

IF
  Global("#GStartSpl","GLOBAL",1)
  HPLT(%famsummoner%,9)
  OR(2)
    Global("#GHPOFF","GLOBAL",1)
    Global("#GFAMGO","GLOBAL",3)
  Global("#GFAMLVL","GLOBAL",4) // Familiar Lv 5
THEN
  RESPONSE #100
    SetGlobal("#GHPCNT","LOCALS",50)
    Continue()
END

IF
  OR(2)
    Global("#GStartSpl","GLOBAL",0)
    HPGT(%famsummoner%,6)
  OR(2)
    Global("#GHPOFF","GLOBAL",1)
    Global("#GFAMGO","GLOBAL",3)
  Global("#GFAMLVL","GLOBAL",3) // Familiar Lv 4
THEN
  RESPONSE #100
    SetGlobal("#GHPCNT","LOCALS",8)
    Continue()
END

IF
  Global("#GStartSpl","GLOBAL",1)
  HPLT(%famsummoner%,7)
  OR(2)
    Global("#GHPOFF","GLOBAL",1)
    Global("#GFAMGO","GLOBAL",3)
  Global("#GFAMLVL","GLOBAL",3) // Familiar Lv 4
THEN
  RESPONSE #100
    SetGlobal("#GHPCNT","LOCALS",48)
    Continue()
END

IF
  OR(2)
    Global("#GStartSpl","GLOBAL",0)
    HPGT(%famsummoner%,4)
  OR(2)
    Global("#GHPOFF","GLOBAL",1)
    Global("#GFAMGO","GLOBAL",3)
  Global("#GFAMLVL","GLOBAL",2) // Familiar Lv 3
THEN
  RESPONSE #100
    SetGlobal("#GHPCNT","LOCALS",6)
    Continue()
END

IF
  Global("#GStartSpl","GLOBAL",1)
  HPLT(%famsummoner%,5)
  OR(2)
    Global("#GHPOFF","GLOBAL",1)
    Global("#GFAMGO","GLOBAL",3)
  Global("#GFAMLVL","GLOBAL",2) // Familiar Lv 3
THEN
  RESPONSE #100
    SetGlobal("#GHPCNT","LOCALS",46)
    Continue()
END

IF
  OR(2)
    Global("#GStartSpl","GLOBAL",0)
    HPGT(%famsummoner%,2)
  OR(2)
    Global("#GHPOFF","GLOBAL",1)
    Global("#GFAMGO","GLOBAL",3)
  Global("#GFAMLVL","GLOBAL",1) // Familiar Lv 2
THEN
  RESPONSE #100
    SetGlobal("#GHPCNT","LOCALS",4)
    Continue()
END

IF
  Global("#GStartSpl","GLOBAL",1)
  HPLT(%famsummoner%,3)
  OR(2)
    Global("#GHPOFF","GLOBAL",1)
    Global("#GFAMGO","GLOBAL",3)
  Global("#GFAMLVL","GLOBAL",1) // Familiar Lv 2
THEN
  RESPONSE #100
    SetGlobal("#GHPCNT","LOCALS",44)
    Continue()
END

IF
  GlobalGT("#GHPCNT","LOCALS",0)
  OR(2)
    Global("#GHPOFF","GLOBAL",1)
    Global("#GFAMGO","GLOBAL",3)
THEN
  RESPONSE #100
    SetGlobal("#GFAMLVL","GLOBAL",0)
    SetGlobal("#GFAMGO","GLOBAL",0)
    SetGlobal("#GHPOFF","GLOBAL",0)
    Continue()
END

IF
  Global("#GHPCNT","LOCALS",83)							// -41 MHP 1 CHP
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GHPCNT","LOCALS",0)
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONB",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCOND",Myself))
    ActionOverride(%famsummoner%,SetGlobal("#GWTPCOM","LOCALS",1))
    SetInterrupt(TRUE)
END

IF
  Global("#GHPCNT","LOCALS",82)							// -40 MHP 1 CHP
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GHPCNT","LOCALS",0)
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCOND",Myself))
    ActionOverride(%famsummoner%,SetGlobal("#GWTPCOM","LOCALS",1))
    SetInterrupt(TRUE)
END

IF
  Global("#GHPCNT","LOCALS",81)							// -39 MHP 1 CHP
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GHPCNT","LOCALS",0)
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONB",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCOND",Myself))
    ActionOverride(%famsummoner%,SetGlobal("#GWTPCOM","LOCALS",1))
    SetInterrupt(TRUE)
END

IF
  Global("#GHPCNT","LOCALS",80)							// -38 MHP 1 CHP
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GHPCNT","LOCALS",0)
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCOND",Myself))
    ActionOverride(%famsummoner%,SetGlobal("#GWTPCOM","LOCALS",1))
    SetInterrupt(TRUE)
END

IF
  Global("#GHPCNT","LOCALS",79)							// -37 MHP 1 CHP
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GHPCNT","LOCALS",0)
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONB",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCOND",Myself))
    ActionOverride(%famsummoner%,SetGlobal("#GWTPCOM","LOCALS",1))
    SetInterrupt(TRUE)
END

IF
  Global("#GHPCNT","LOCALS",78)							// -36 MHP 1 CHP
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GHPCNT","LOCALS",0)
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCOND",Myself))
    ActionOverride(%famsummoner%,SetGlobal("#GWTPCOM","LOCALS",1))
    SetInterrupt(TRUE)
END

IF
  Global("#GHPCNT","LOCALS",77)							// -35 MHP 1 CHP
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GHPCNT","LOCALS",0)
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONB",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCOND",Myself))
    ActionOverride(%famsummoner%,SetGlobal("#GWTPCOM","LOCALS",1))
    SetInterrupt(TRUE)
END

IF
  Global("#GHPCNT","LOCALS",76)							// -34 MHP 1 CHP
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GHPCNT","LOCALS",0)
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCOND",Myself))
    ActionOverride(%famsummoner%,SetGlobal("#GWTPCOM","LOCALS",1))
    SetInterrupt(TRUE)
END

IF
  Global("#GHPCNT","LOCALS",75)							// -33 MHP 1 CHP
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GHPCNT","LOCALS",0)
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONB",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCOND",Myself))
    ActionOverride(%famsummoner%,SetGlobal("#GWTPCOM","LOCALS",1))
    SetInterrupt(TRUE)
END

IF
  Global("#GHPCNT","LOCALS",74)							// -32 MHP 1 CHP
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GHPCNT","LOCALS",0)
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCOND",Myself))
    ActionOverride(%famsummoner%,SetGlobal("#GWTPCOM","LOCALS",1))
    SetInterrupt(TRUE)
END

IF
  Global("#GHPCNT","LOCALS",73)							// -31 MHP 1 CHP
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GHPCNT","LOCALS",0)
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONB",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCOND",Myself))
    ActionOverride(%famsummoner%,SetGlobal("#GWTPCOM","LOCALS",1))
    SetInterrupt(TRUE)
END

IF
  Global("#GHPCNT","LOCALS",72)							// -30 MHP 1 CHP
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GHPCNT","LOCALS",0)
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCOND",Myself))
    ActionOverride(%famsummoner%,SetGlobal("#GWTPCOM","LOCALS",1))
    SetInterrupt(TRUE)
END

IF
  Global("#GHPCNT","LOCALS",71)							// -29 MHP 1 CHP
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GHPCNT","LOCALS",0)
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFConB",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCOND",Myself))
    ActionOverride(%famsummoner%,SetGlobal("#GWTPCOM","LOCALS",1))
    SetInterrupt(TRUE)
END

IF
  Global("#GHPCNT","LOCALS",70)							// -28 MHP 1 CHP
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GHPCNT","LOCALS",0)
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCOND",Myself))
    ActionOverride(%famsummoner%,SetGlobal("#GWTPCOM","LOCALS",1))
    SetInterrupt(TRUE)
END

IF
  Global("#GHPCNT","LOCALS",69)							// -27 MHP 1 CHP
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GHPCNT","LOCALS",0)
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONB",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCOND",Myself))
    ActionOverride(%famsummoner%,SetGlobal("#GWTPCOM","LOCALS",1))
    SetInterrupt(TRUE)
END

IF
  Global("#GHPCNT","LOCALS",68)							// -26 MHP 1 CHP
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GHPCNT","LOCALS",0)
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCOND",Myself))
    ActionOverride(%famsummoner%,SetGlobal("#GWTPCOM","LOCALS",1))
    SetInterrupt(TRUE)
END

IF
  Global("#GHPCNT","LOCALS",67)							// -25 MHP 1 CHP
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GHPCNT","LOCALS",0)
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONB",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCOND",Myself))
    ActionOverride(%famsummoner%,SetGlobal("#GWTPCOM","LOCALS",1))
    SetInterrupt(TRUE)
END

IF
  Global("#GHPCNT","LOCALS",66)							// -24 MHP 1 CHP
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GHPCNT","LOCALS",0)
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCOND",Myself))
    ActionOverride(%famsummoner%,SetGlobal("#GWTPCOM","LOCALS",1))
    SetInterrupt(TRUE)
END

IF
  Global("#GHPCNT","LOCALS",65)							// -23 MHP 1 CHP
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GHPCNT","LOCALS",0)
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONB",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCOND",Myself))
    ActionOverride(%famsummoner%,SetGlobal("#GWTPCOM","LOCALS",1))
    SetInterrupt(TRUE)
END

IF
  Global("#GHPCNT","LOCALS",64)							// -22 MHP 1 CHP
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GHPCNT","LOCALS",0)
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCOND",Myself))
    ActionOverride(%famsummoner%,SetGlobal("#GWTPCOM","LOCALS",1))
    SetInterrupt(TRUE)
END

IF
  Global("#GHPCNT","LOCALS",63)							// -21 MHP 1 CHP
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GHPCNT","LOCALS",0)
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONB",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCOND",Myself))
    ActionOverride(%famsummoner%,SetGlobal("#GWTPCOM","LOCALS",1))
    SetInterrupt(TRUE)
END

IF
  Global("#GHPCNT","LOCALS",62)							// -20 MHP 1 CHP
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GHPCNT","LOCALS",0)
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCOND",Myself))
    ActionOverride(%famsummoner%,SetGlobal("#GWTPCOM","LOCALS",1))
    SetInterrupt(TRUE)
END

IF
  Global("#GHPCNT","LOCALS",61)							// -19 MHP 1 CHP
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GHPCNT","LOCALS",0)
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONB",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCOND",Myself))
    ActionOverride(%famsummoner%,SetGlobal("#GWTPCOM","LOCALS",1))
    SetInterrupt(TRUE)
END

IF
  Global("#GHPCNT","LOCALS",60)							// -18 MHP 1 CHP
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GHPCNT","LOCALS",0)
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCOND",Myself))
    ActionOverride(%famsummoner%,SetGlobal("#GWTPCOM","LOCALS",1))
    SetInterrupt(TRUE)
END

IF
  Global("#GHPCNT","LOCALS",59)							// -17 MHP 1 CHP
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GHPCNT","LOCALS",0)
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONB",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCOND",Myself))
    ActionOverride(%famsummoner%,SetGlobal("#GWTPCOM","LOCALS",1))
    SetInterrupt(TRUE)
END

IF
  Global("#GHPCNT","LOCALS",58)							// -16 MHP 1 CHP
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GHPCNT","LOCALS",0)
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCOND",Myself))
    ActionOverride(%famsummoner%,SetGlobal("#GWTPCOM","LOCALS",1))
    SetInterrupt(TRUE)
END

IF
  Global("#GHPCNT","LOCALS",56)							// -14 MHP 1 CHP
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GHPCNT","LOCALS",0)
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCOND",Myself))
    ActionOverride(%famsummoner%,SetGlobal("#GWTPCOM","LOCALS",1))
    SetInterrupt(TRUE)
END

IF
  Global("#GHPCNT","LOCALS",54)							// -12 MHP 1 CHP
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GHPCNT","LOCALS",0)
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCOND",Myself))
    ActionOverride(%famsummoner%,SetGlobal("#GWTPCOM","LOCALS",1))
    SetInterrupt(TRUE)
END

IF
  Global("#GHPCNT","LOCALS",52)							// -10 MHP 1 CHP
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GHPCNT","LOCALS",0)
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCOND",Myself))
    ActionOverride(%famsummoner%,SetGlobal("#GWTPCOM","LOCALS",1))
    SetInterrupt(TRUE)
END

IF
  Global("#GHPCNT","LOCALS",50)							// -8 MHP 1 CHP
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GHPCNT","LOCALS",0)
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCOND",Myself))
    ActionOverride(%famsummoner%,SetGlobal("#GWTPCOM","LOCALS",1))
    SetInterrupt(TRUE)
END

IF
  Global("#GHPCNT","LOCALS",48)							// -6 MHP 1 CHP
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GHPCNT","LOCALS",0)
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCOND",Myself))
    ActionOverride(%famsummoner%,SetGlobal("#GWTPCOM","LOCALS",1))
    SetInterrupt(TRUE)
END

IF
  Global("#GHPCNT","LOCALS",46)							// -4 MHP 1 CHP
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GHPCNT","LOCALS",0)
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCOND",Myself))
    ActionOverride(%famsummoner%,SetGlobal("#GWTPCOM","LOCALS",1))
    SetInterrupt(TRUE)
END

IF
  Global("#GHPCNT","LOCALS",44)							// -2 MHP 1 CHP
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GHPCNT","LOCALS",0)
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCONA",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCOND",Myself))
    ActionOverride(%famsummoner%,SetGlobal("#GWTPCOM","LOCALS",1))
    SetInterrupt(TRUE)
END

IF
  Global("#GHPCNT","LOCALS",43)							// -41 MHP -41 CHP
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GHPCNT","LOCALS",0)
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon7",Myself))
    SetInterrupt(TRUE)
END

IF
  Global("#GHPCNT","LOCALS",42)							// -40 MHP -40 CHP
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GHPCNT","LOCALS",0)
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    SetInterrupt(TRUE)
END

IF
  Global("#GHPCNT","LOCALS",41)							// -39 MHP -39 CHP
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GHPCNT","LOCALS",0)
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon7",Myself))
    SetInterrupt(TRUE)
END

IF
  Global("#GHPCNT","LOCALS",40)							// -38 MHP -38 CHP
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GHPCNT","LOCALS",0)
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    SetInterrupt(TRUE)
END

IF
  Global("#GHPCNT","LOCALS",39)							// -37 MHP -37 CHP
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GHPCNT","LOCALS",0)
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon7",Myself))
    SetInterrupt(TRUE)
END

IF
  Global("#GHPCNT","LOCALS",38)							// -36 MHP -36 CHP
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GHPCNT","LOCALS",0)
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    SetInterrupt(TRUE)
END

IF
  Global("#GHPCNT","LOCALS",37)							// -35 MHP -35 CHP
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GHPCNT","LOCALS",0)
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon7",Myself))
    SetInterrupt(TRUE)
END

IF
  Global("#GHPCNT","LOCALS",36)							// -34 MHP -34 CHP
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GHPCNT","LOCALS",0)
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    SetInterrupt(TRUE)
END

IF
  Global("#GHPCNT","LOCALS",35)							// -33 MHP -33 CHP
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GHPCNT","LOCALS",0)
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon7",Myself))
    SetInterrupt(TRUE)
END

IF
  Global("#GHPCNT","LOCALS",34)							// -32 MHP -32 CHP
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GHPCNT","LOCALS",0)
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    SetInterrupt(TRUE)
END

IF
  Global("#GHPCNT","LOCALS",33)							// -31 MHP -31 CHP
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GHPCNT","LOCALS",0)
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon7",Myself))
    SetInterrupt(TRUE)
END

IF
  Global("#GHPCNT","LOCALS",32)							// -30 MHP -30 CHP
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GHPCNT","LOCALS",0)
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    SetInterrupt(TRUE)
END

IF
  Global("#GHPCNT","LOCALS",31)							// -29 MHP -29 CHP
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GHPCNT","LOCALS",0)
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon7",Myself))
    SetInterrupt(TRUE)
END

IF
  Global("#GHPCNT","LOCALS",30)							// -28 MHP -28 CHP
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GHPCNT","LOCALS",0)
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    SetInterrupt(TRUE)
END

IF
  Global("#GHPCNT","LOCALS",29)							// -27 MHP -27 CHP
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GHPCNT","LOCALS",0)
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon7",Myself))
    SetInterrupt(TRUE)
END

IF
  Global("#GHPCNT","LOCALS",28)							// -26 MHP -26 CHP
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GHPCNT","LOCALS",0)
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    SetInterrupt(TRUE)
END

IF
  Global("#GHPCNT","LOCALS",27)							// -25 MHP -25 CHP
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GHPCNT","LOCALS",0)
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon7",Myself))
    SetInterrupt(TRUE)
END

IF
  Global("#GHPCNT","LOCALS",26)							// -24 MHP -24 CHP
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GHPCNT","LOCALS",0)
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    SetInterrupt(TRUE)
END

IF
  Global("#GHPCNT","LOCALS",25)							// -23 MHP -23 CHP
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GHPCNT","LOCALS",0)
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon7",Myself))
    SetInterrupt(TRUE)
END

IF
  Global("#GHPCNT","LOCALS",24)							// -22 MHP -22 CHP
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GHPCNT","LOCALS",0)
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    SetInterrupt(TRUE)
END

IF
  Global("#GHPCNT","LOCALS",23)							// -21 MHP -21 CHP
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GHPCNT","LOCALS",0)
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon7",Myself))
    SetInterrupt(TRUE)
END

IF
  Global("#GHPCNT","LOCALS",22)							// -20 MHP -20 CHP
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GHPCNT","LOCALS",0)
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    SetInterrupt(TRUE)
END

IF
  Global("#GHPCNT","LOCALS",21)							// -19 MHP -19 CHP
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GHPCNT","LOCALS",0)
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon7",Myself))
    SetInterrupt(TRUE)
END

IF
  Global("#GHPCNT","LOCALS",20)							// -18 MHP -18 CHP
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GHPCNT","LOCALS",0)
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    SetInterrupt(TRUE)
END

IF
  Global("#GHPCNT","LOCALS",19)							// -17 MHP -17 CHP
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GHPCNT","LOCALS",0)
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon7",Myself))
    SetInterrupt(TRUE)
END

IF
  Global("#GHPCNT","LOCALS",18)							// -16 MHP -16 CHP
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GHPCNT","LOCALS",0)
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    SetInterrupt(TRUE)
END

IF
  Global("#GHPCNT","LOCALS",16)							// -14 MHP -14 CHP
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GHPCNT","LOCALS",0)
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    SetInterrupt(TRUE)
END

IF
  Global("#GHPCNT","LOCALS",14)							// -12 MHP -12 CHP
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GHPCNT","LOCALS",0)
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    SetInterrupt(TRUE)
END

IF
  Global("#GHPCNT","LOCALS",12)							// -10 MHP -10 CHP
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GHPCNT","LOCALS",0)
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    SetInterrupt(TRUE)
END

IF
  Global("#GHPCNT","LOCALS",10)							// -8 MHP -8 CHP
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GHPCNT","LOCALS",0)
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    SetInterrupt(TRUE)
END

IF
  Global("#GHPCNT","LOCALS",8)							// -6 MHP -6 CHP
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GHPCNT","LOCALS",0)
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    SetInterrupt(TRUE)
END

IF
  Global("#GHPCNT","LOCALS",6)							// -4 MHP -4 CHP
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GHPCNT","LOCALS",0)
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    SetInterrupt(TRUE)
END

IF
  Global("#GHPCNT","LOCALS",4)							// -2 MHP -2 CHP
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("#GHPCNT","LOCALS",0)
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCon6",Myself))
    SetInterrupt(TRUE)
END

///////////////////////////////
///Level Drain Imp&Quasit   ///
///////////////////////////////

IF
  Global("#GBhaalHP1","GLOBAL",0)							// Compatibility check for GOooPD
  Global("#GNOLDR","GLOBAL",0)
  Global("#GIMP","GLOBAL",1)
THEN
  RESPONSE #100
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCo11",Myself))
    SetGlobal("#GIMP","GLOBAL",0)
END

IF
  Global("#GBhaalHP1","GLOBAL",0)							// Compatibility check for GOooPD
  Global("#GNOLDR","GLOBAL",0)
  Global("#GIMP","GLOBAL",2)
THEN
  RESPONSE #100
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCo12",Myself))
    SetGlobal("#GIMP","GLOBAL",0)
END

IF
  Global("#GBhaalHP1","GLOBAL",0)							// Compatibility check for GOooPD
  Global("#GNOLDR","GLOBAL",0)
  Global("#GIMP","GLOBAL",3)
THEN
  RESPONSE #100
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCo13",Myself))
    SetGlobal("#GIMP","GLOBAL",0)
END

IF
  Global("#GBhaalHP1","GLOBAL",0)							// Compatibility check for GOooPD
  Global("#GNOLDR","GLOBAL",0)
  Global("#GIMP","GLOBAL",4)
THEN
  RESPONSE #100
    ActionOverride(%famsummoner%,ReallyForceSpellRES("WTPFCo14",Myself))
    SetGlobal("#GIMP","GLOBAL",0)
END

/////////////////////////////////////////
///GOooPD CON adjustment              ///
/////////////////////////////////////////

IF
  Global("#GBhaalHP1","GLOBAL",0)	 						// Compatibility check for GOooPD
  TriggerOverride(%famsummoner%,Global("#GWTPCOM","LOCALS",1)) 				// Compatibility check for GOooPD
  Global("#GSHOCK","GLOBAL",1)
THEN
  RESPONSE #100
    ActionOverride(%famsummoner%,SetGlobal("#GWTPCOM","LOCALS",2))
END

IF
  TriggerOverride(%famsummoner%,Global("#GWTPCOM","LOCALS",1)) 				// Compatibility check for GOooPD
  Global("#GSHOCK","GLOBAL",0)
THEN
  RESPONSE #100
    ActionOverride(%famsummoner%,SetGlobal("#GWTPCOM","LOCALS",0))
END

/////////////////////////////////////////
///System Shock                       ///
/////////////////////////////////////////

IF
  Global("#GBhaalHP1","GLOBAL",2)							// Compatibility check for GOooPD
  Global("#GSHOCK","GLOBAL",1)
  Global("#GFAMGO","GLOBAL",0)
  Global("#GHPOFF","GLOBAL",0)
THEN
  RESPONSE #100
    ActionOverride(%famsummoner%,ApplySpellRES("WTPDESP1",Myself))
    ActionOverride(%famsummoner%,SetGlobal("#GWTPCOM","LOCALS",2))
    SetGlobal("#GSHOCK","GLOBAL",0)
END

IF
  Global("#GBhaalHP1","GLOBAL",0)							// Compatibility check for GOooPD
  Global("#GSHOCK","GLOBAL",1)
  CheckStat(%famsummoner%,1,CON)
  Global("#GFAMGO","GLOBAL",0)
  Global("#GHPOFF","GLOBAL",0)
THEN
  RESPONSE #75
    ActionOverride(%famsummoner%,ApplySpellRES("WTPDESP",Myself))
    SetGlobal("#GSHOCK","GLOBAL",0)
  RESPONSE #25
    ActionOverride(%famsummoner%,ApplySpellRES("WTPDESP1",Myself))
    SetGlobal("#GSHOCK","GLOBAL",0)
END

IF
  Global("#GBhaalHP1","GLOBAL",0)							// Compatibility check for GOooPD
  Global("#GSHOCK","GLOBAL",1)
  CheckStat(%famsummoner%,2,CON)
  Global("#GFAMGO","GLOBAL",0)
  Global("#GHPOFF","GLOBAL",0)
THEN
  RESPONSE #70
    ActionOverride(%famsummoner%,ApplySpellRES("WTPDESP",Myself))
    SetGlobal("#GSHOCK","GLOBAL",0)
  RESPONSE #30
    ActionOverride(%famsummoner%,ApplySpellRES("WTPDESP1",Myself))
    SetGlobal("#GSHOCK","GLOBAL",0)
END

IF
  Global("#GBhaalHP1","GLOBAL",0)							// Compatibility check for GOooPD
  Global("#GSHOCK","GLOBAL",1)
  CheckStat(%famsummoner%,3,CON)
  Global("#GFAMGO","GLOBAL",0)
  Global("#GHPOFF","GLOBAL",0)
THEN
  RESPONSE #65
    ActionOverride(%famsummoner%,ApplySpellRES("WTPDESP",Myself))
    SetGlobal("#GSHOCK","GLOBAL",0)
  RESPONSE #35
    ActionOverride(%famsummoner%,ApplySpellRES("WTPDESP1",Myself))
    SetGlobal("#GSHOCK","GLOBAL",0)
END

IF
  Global("#GBhaalHP1","GLOBAL",0)							// Compatibility check for GOooPD
  Global("#GSHOCK","GLOBAL",1)
  CheckStat(%famsummoner%,4,CON)
  Global("#GFAMGO","GLOBAL",0)
  Global("#GHPOFF","GLOBAL",0)
THEN
  RESPONSE #60
    ActionOverride(%famsummoner%,ApplySpellRES("WTPDESP",Myself))
    SetGlobal("#GSHOCK","GLOBAL",0)
  RESPONSE #40
    ActionOverride(%famsummoner%,ApplySpellRES("WTPDESP1",Myself))
    SetGlobal("#GSHOCK","GLOBAL",0)
END

IF
  Global("#GBhaalHP1","GLOBAL",0)							// Compatibility check for GOooPD
  Global("#GSHOCK","GLOBAL",1)
  CheckStat(%famsummoner%,5,CON)
  Global("#GFAMGO","GLOBAL",0)
  Global("#GHPOFF","GLOBAL",0)
THEN
  RESPONSE #55
    ActionOverride(%famsummoner%,ApplySpellRES("WTPDESP",Myself))
    SetGlobal("#GSHOCK","GLOBAL",0)
  RESPONSE #45
    ActionOverride(%famsummoner%,ApplySpellRES("WTPDESP1",Myself))
    SetGlobal("#GSHOCK","GLOBAL",0)
END

IF
  Global("#GBhaalHP1","GLOBAL",0)							// Compatibility check for GOooPD
  Global("#GSHOCK","GLOBAL",1)
  CheckStat(%famsummoner%,6,CON)
  Global("#GFAMGO","GLOBAL",0)
  Global("#GHPOFF","GLOBAL",0)
THEN
  RESPONSE #50
    ActionOverride(%famsummoner%,ApplySpellRES("WTPDESP",Myself))
    SetGlobal("#GSHOCK","GLOBAL",0)
  RESPONSE #50
    ActionOverride(%famsummoner%,ApplySpellRES("WTPDESP1",Myself))
    SetGlobal("#GSHOCK","GLOBAL",0)
END

IF
  Global("#GBhaalHP1","GLOBAL",0)							// Compatibility check for GOooPD
  Global("#GSHOCK","GLOBAL",1)
  CheckStat(%famsummoner%,7,CON)
  Global("#GFAMGO","GLOBAL",0)
  Global("#GHPOFF","GLOBAL",0)
THEN
  RESPONSE #45
    ActionOverride(%famsummoner%,ApplySpellRES("WTPDESP",Myself))
    SetGlobal("#GSHOCK","GLOBAL",0)
  RESPONSE #55
    ActionOverride(%famsummoner%,ApplySpellRES("WTPDESP1",Myself))
    SetGlobal("#GSHOCK","GLOBAL",0)
END

IF
  Global("#GBhaalHP1","GLOBAL",0)							// Compatibility check for GOooPD
  Global("#GSHOCK","GLOBAL",1)
  CheckStat(%famsummoner%,8,CON)
  Global("#GFAMGO","GLOBAL",0)
  Global("#GHPOFF","GLOBAL",0)
THEN
  RESPONSE #40
    ActionOverride(%famsummoner%,ApplySpellRES("WTPDESP",Myself))
    SetGlobal("#GSHOCK","GLOBAL",0)
  RESPONSE #60
    ActionOverride(%famsummoner%,ApplySpellRES("WTPDESP1",Myself))
    SetGlobal("#GSHOCK","GLOBAL",0)
END

IF
  Global("#GBhaalHP1","GLOBAL",0)							// Compatibility check for GOooPD
  Global("#GSHOCK","GLOBAL",1)
  CheckStat(%famsummoner%,9,CON)
  Global("#GFAMGO","GLOBAL",0)
  Global("#GHPOFF","GLOBAL",0)
THEN
  RESPONSE #35
    ActionOverride(%famsummoner%,ApplySpellRES("WTPDESP",Myself))
    SetGlobal("#GSHOCK","GLOBAL",0)
  RESPONSE #65
    ActionOverride(%famsummoner%,ApplySpellRES("WTPDESP1",Myself))
    SetGlobal("#GSHOCK","GLOBAL",0)
END

IF
  Global("#GBhaalHP1","GLOBAL",0)							// Compatibility check for GOooPD
  Global("#GSHOCK","GLOBAL",1)
  CheckStat(%famsummoner%,10,CON)
  Global("#GFAMGO","GLOBAL",0)
  Global("#GHPOFF","GLOBAL",0)
THEN
  RESPONSE #30
    ActionOverride(%famsummoner%,ApplySpellRES("WTPDESP",Myself))
    SetGlobal("#GSHOCK","GLOBAL",0)
  RESPONSE #70
    ActionOverride(%famsummoner%,ApplySpellRES("WTPDESP1",Myself))
    SetGlobal("#GSHOCK","GLOBAL",0)
END

IF
  Global("#GBhaalHP1","GLOBAL",0)							// Compatibility check for GOooPD
  Global("#GSHOCK","GLOBAL",1)
  CheckStat(%famsummoner%,11,CON)
  Global("#GFAMGO","GLOBAL",0)
  Global("#GHPOFF","GLOBAL",0)
THEN
  RESPONSE #25
    ActionOverride(%famsummoner%,ApplySpellRES("WTPDESP",Myself))
    SetGlobal("#GSHOCK","GLOBAL",0)
  RESPONSE #75
    ActionOverride(%famsummoner%,ApplySpellRES("WTPDESP1",Myself))
    SetGlobal("#GSHOCK","GLOBAL",0)
END

IF
  Global("#GBhaalHP1","GLOBAL",0)							// Compatibility check for GOooPD
  Global("#GSHOCK","GLOBAL",1)
  CheckStat(%famsummoner%,12,CON)
  Global("#GFAMGO","GLOBAL",0)
  Global("#GHPOFF","GLOBAL",0)
THEN
  RESPONSE #20
    ActionOverride(%famsummoner%,ApplySpellRES("WTPDESP",Myself))
    SetGlobal("#GSHOCK","GLOBAL",0)
  RESPONSE #80
    ActionOverride(%famsummoner%,ApplySpellRES("WTPDESP1",Myself))
    SetGlobal("#GSHOCK","GLOBAL",0)
END

IF
  Global("#GBhaalHP1","GLOBAL",0)							// Compatibility check for GOooPD
  Global("#GSHOCK","GLOBAL",1)
  CheckStat(%famsummoner%,13,CON)
  Global("#GFAMGO","GLOBAL",0)
  Global("#GHPOFF","GLOBAL",0)
THEN
  RESPONSE #15
    ActionOverride(%famsummoner%,ApplySpellRES("WTPDESP",Myself))
    SetGlobal("#GSHOCK","GLOBAL",0)
  RESPONSE #85
    ActionOverride(%famsummoner%,ApplySpellRES("WTPDESP1",Myself))
    SetGlobal("#GSHOCK","GLOBAL",0)
END

IF
  Global("#GBhaalHP1","GLOBAL",0)							// Compatibility check for GOooPD
  Global("#GSHOCK","GLOBAL",1)
  CheckStat(%famsummoner%,14,CON)
  Global("#GFAMGO","GLOBAL",0)
  Global("#GHPOFF","GLOBAL",0)
THEN
  RESPONSE #12
    ActionOverride(%famsummoner%,ApplySpellRES("WTPDESP",Myself))
    SetGlobal("#GSHOCK","GLOBAL",0)
  RESPONSE #88
    ActionOverride(%famsummoner%,ApplySpellRES("WTPDESP1",Myself))
    SetGlobal("#GSHOCK","GLOBAL",0)
END

IF
  Global("#GBhaalHP1","GLOBAL",0)							// Compatibility check for GOooPD
  Global("#GSHOCK","GLOBAL",1)
  CheckStat(%famsummoner%,15,CON)
  Global("#GFAMGO","GLOBAL",0)
  Global("#GHPOFF","GLOBAL",0)
THEN
  RESPONSE #10
    ActionOverride(%famsummoner%,ApplySpellRES("WTPDESP",Myself))
    SetGlobal("#GSHOCK","GLOBAL",0)
  RESPONSE #90
    ActionOverride(%famsummoner%,ApplySpellRES("WTPDESP1",Myself))
    SetGlobal("#GSHOCK","GLOBAL",0)
END

IF
  Global("#GBhaalHP1","GLOBAL",0)							// Compatibility check for GOooPD
  Global("#GSHOCK","GLOBAL",1)
  CheckStat(%famsummoner%,16,CON)
  Global("#GFAMGO","GLOBAL",0)
  Global("#GHPOFF","GLOBAL",0)
THEN
  RESPONSE #5
    ActionOverride(%famsummoner%,ApplySpellRES("WTPDESP",Myself))
    SetGlobal("#GSHOCK","GLOBAL",0)
  RESPONSE #95
    ActionOverride(%famsummoner%,ApplySpellRES("WTPDESP1",Myself))
    SetGlobal("#GSHOCK","GLOBAL",0)
END

IF
  Global("#GBhaalHP1","GLOBAL",0)							// Compatibility check for GOooPD
  Global("#GSHOCK","GLOBAL",1)
  CheckStat(%famsummoner%,17,CON)
  Global("#GFAMGO","GLOBAL",0)
  Global("#GHPOFF","GLOBAL",0)
THEN
  RESPONSE #3
    ActionOverride(%famsummoner%,ApplySpellRES("WTPDESP",Myself))
    SetGlobal("#GSHOCK","GLOBAL",0)
  RESPONSE #97
    ActionOverride(%famsummoner%,ApplySpellRES("WTPDESP1",Myself))
    SetGlobal("#GSHOCK","GLOBAL",0)
END

IF
  Global("#GBhaalHP1","GLOBAL",0)							// Compatibility check for GOooPD
  Global("#GSHOCK","GLOBAL",1)
  CheckStatGT(%famsummoner%,17,CON)
  Global("#GFAMGO","GLOBAL",0)
  Global("#GHPOFF","GLOBAL",0)
THEN
  RESPONSE #1
    ActionOverride(%famsummoner%,ApplySpellRES("WTPDESP",Myself))
    SetGlobal("#GSHOCK","GLOBAL",0)
  RESPONSE #99
    ActionOverride(%famsummoner%,ApplySpellRES("WTPDESP1",Myself))
    SetGlobal("#GSHOCK","GLOBAL",0)
END

IF
  Global("#GStartSpl","GLOBAL",0) 						// Compatibility check for GOooPD
  HPLT(%famsummoner%,1)
THEN
  RESPONSE #100
    Kill(%famsummoner%)
END

IF
  Global("#GSHOCK","GLOBAL",0)
  Global("#GHPOFF","GLOBAL",0)
  Global("#GFAMGO","GLOBAL",0)
  Global("#GBhaalHP1","GLOBAL",0)							// Compatibility check for GOooPD
THEN
  RESPONSE #100
    DestroySelf()
END
